### ISSUE TITLE
Cocina mapping error: key not found nil (contibutor roleTerm)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1161]
```
druid:pd967mn2579 error. key not found: nil
app/services/cocina/to_fedora/descriptive/contributor.rb:33:in `fetch'
```

**Comment by jcoyne** [comment]
This is on an APO that has blank template metadata:

<img width="478" alt="Screen Shot 2020-10-15 at 3 09 40 PM" src="https://user-images.githubusercontent.com/92044/96180706-74409580-0ef8-11eb-83a4-1d27807d5d41.png">

**Comment by jcoyne** [comment]
@arcadiafalcone has specified:

> `roleTerm` should be ignored if `namePart` doesn't have a value (unless `etal`, a sibling tag to `roleTerm` is present, which is an edge case)

**Comment by ndushay** [comment]
Name with et. al. from https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/6a10e6bddaabfdd0b6ca21794e7aa2077595b713/mods_cocina_mappings/mods_to_cocina_name.txt#L498-L519:

```
13. Name with et al.
<name type="personal">
  <namePart>Frydman, Judith</namePart>
</name>
<name>
  <etal/>
</name>
{
  "contributor": [
    {
      "name": [
        {
          "value": "Frydman, Judith"
        }
      ],
      "type": "person"
    },
    {
      "type": "unspecified others"
    }
  ]
}
```
