### ISSUE TITLE
Cocina mapping support recordChangeDate

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1186]
See druid:hk131vq7662 on stage.

See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/88

The mapping was added in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/97

```
  <recordInfo>
    <recordCreationDate encoding="marc">810724</recordCreationDate>
    <recordChangeDate encoding="iso8601">20130318214853.0</recordChangeDate>
  </recordInfo>
```

**Comment by ndushay** [comment]
This appears to be done??

![image](https://user-images.githubusercontent.com/96775/101656519-a6054280-39f7-11eb-955b-7c86840eb76b.png)
