### ISSUE TITLE
bin/validate-cocina-roundtrip: for failures, display diff, not full xml

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1203]
use https://github.com/mbklein/equivalent-xml gem to show differences between expected and actual xml.

not sure if we should add an option to allow ignoring mods version???

**Comment by mjgiarlo** [comment]
We believe this to be a difficult and time-consuming problem to solve. (See [abandoned, outdated equivalent-xml PR attempt](https://github.com/mbklein/equivalent-xml/pull/6).) We are backlogging this as a result. Would be nice but not worth the time or effort at this point.

**Comment by ndushay** [comment]
I'm closing this ticket;  @justinlittman has addressed this.
