### ISSUE TITLE
Cascade of issues when refreshing metadata after attaching catkey to collection record

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/dor-services-app#1227]
Following slack conversation yesterday about catkey: 4082833. I added the catkey to the collection object and attempted to refresh descMetadata on that object which led to a cascade of errors in common-accessioning. I think I grabbed all the honeybadger errors - see below (all apply to https://argo.stanford.edu/view/druid:df380nz3912):

* https://app.honeybadger.io/projects/50568/faults/68611110
* https://app.honeybadger.io/projects/52894/faults/61164909
* https://app.honeybadger.io/projects/52894/faults/63819738
* https://app.honeybadger.io/projects/52894/faults/63620512
* https://app.honeybadger.io/projects/52894/faults/62544871
* https://app.honeybadger.io/projects/52894/faults/60744324

I can work around this, but thought I would provide this in case it's any help in your current work.

**Comment by justinlittman** [comment]
@blalbrit Can you verify that this has been resolved?

**Comment by andrewjbtw** [comment]
I've refreshed the metadata for catkey 4082833 on stage and am now not seeing anything in honeybadger to indicate a problem.

For the general case of refreshing/importing Symphony metadata failures and what to show when that happens in Argo, I've written up a separate issue:
https://github.com/sul-dlss/argo/issues/2303

**Comment by andrewjbtw** [comment]
The marc2mods and mods-to-Cocina mappings have been updated, as has how we handle errors/invalid data. I'm going to close this in favor of opening a new issue if a catkey import fails in the future.
