### ISSUE TITLE
cocina mapping error: key not found: "life dates"

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1234]
seen on stage.
```
druid:fw124bx4247 error. key not found: "life dates"
```

See Cocina model in https://argo-stage.stanford.edu/view/druid:fw124bx4247. Any structured values including the type `'life dates'` is not mapping. Fix `ToFedora` mapping in dor-services-app.

**Comment by aaron-collier** [comment]
Just capturing that this is going to require updating https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/to_fedora/descriptive/title.rb#L69 to handle input like:

```
  "title": [
    {
      "structuredValue": [
        {
          "value": "Saint-Saëns",
          "type": "surname"
        },
        {
          "value": "Camille",
          "type": "forename"
        },
        {
          "value": "1835-1921",
          "type": "life dates"
        },
        {
          "value": "Princesse jaune. Vocal score",
          "type": "title"
        }
      ],
      "type": "uniform"
    }
  ]
```

Where the types are `surname` and `forename`, not just `person` to indicate that a name/namePart block is required.

**Comment by ndushay** [comment]
@aaron-collier is it possible this is done now?  I ran across code that seemed to be doing this today.

If so, perhaps there is an example that Arcadia needs to add to the mappings in cocina-descriptive-metadata?   See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/102 as an example (?)

**Comment by aaron-collier** [comment]
Not yet, no. The example in the spec does not round trip. I have the code ready however and should have it in a clean PR in the morning.
