### ISSUE TITLE
In validate-cocina-roundtrip separate "Missing Title Error" into a count apart from other errors

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1254]
The "Missing Title" error is generally an error with the data itself, not something we can/should fix, so we should account for it separately.

**Comment by ndushay** [comment]
@jcoyne is this still desired?  As in, alert to honeybadger with a particular error title or something?

**Comment by jcoyne** [comment]
No, just in the report that validate-cocina-roundtrip generates at the end of its run.

**Comment by ndushay** [comment]
@jcoyne if JLitt is writing a new round trip validator ... is this still useful?

**Comment by jcoyne** [comment]
@ndushay too early to tell, I haven't seen the new validator yet.

**Comment by justinlittman** [comment]
Done.
