### ISSUE TITLE
mapping validation cache of druids should filter out Part objects (depends on #1259)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1262]
Maybe `has_model_ssim:-"info:fedora/afmodel:Part"` ?

so:
```
druid:pj147kx9285 error. Cocina::Mapper::MissingTitle
```

should not show up.

**Comment by ndushay** [comment]
`fq:-has_model_ssim:"info:fedora/afmodel:Part"` is the query.  I put this info in a comment in #1259:  https://github.com/sul-dlss/dor-services-app/pull/1259/files#r513554321 .   I also slacked JLitt.

I'm gonna mark this closed.

**Comment by ndushay** [comment]
(also did a quick doublecheck to see if the query only trapped ETD parts, and that seemed to be correct.
