### ISSUE TITLE
when showing an item that has a descriptive conversion error, return an explanation

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1284]
Return a 422 (or something else?) with a JSON-API formatted error, and above all, avoid returning a generic 500 error with no explanation

This will show a more helpful message in the workflow service.

**Comment by jmartin-sul** [comment]
the dor-services-app honeybadger error that i believe corresponds with the argo error noted in #2290:  https://app.honeybadger.io/projects/50568/faults/69242449/0f5a40f2-1a02-11eb-9d57-9efdd9af2de3

    KeyError: key not found: nil

    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive/subject.rb:88 :in `fetch`

    86           case node.name
    87           when 'name'
    88             attrs[:type] = Contributor::ROLES.fetch(node[:type])
    89             Contributor.name_parts(node, add_default_type: true).first.merge(attrs)
    90           when 'titleInfo'

    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive/subject.rb:88 :in `simple_item`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive/subject.rb:38 :in `block in build`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive/subject.rb:28 :in `map`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive/subject.rb:28 :in `build`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive/subject.rb:20 :in `build`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive.rb:44 :in `block in add_descriptive_elements`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive.rb:43 :in `each`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive.rb:43 :in `add_descriptive_elements`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive.rb:35 :in `props`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive.rb:26 :in `props`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/dro.rb:30 :in `block in props`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/dro.rb:28 :in `tap`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/dro.rb:28 :in `props`
    [PROJECT_ROOT]/app/services/cocina/from_fedora/dro.rb:10 :in `props`
    [PROJECT_ROOT]/app/services/cocina/mapper.rb:35 :in `build`
    [PROJECT_ROOT]/app/services/cocina/mapper.rb:22 :in `build`
    [PROJECT_ROOT]/app/controllers/objects_controller.rb:47 :in `show`
