### ISSUE TITLE
mapping validation error:  (contributor) ./mods:role/mods:roleTerm[@type="code"] is missing required authority attribute

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1290]
NOTE:  Arcadia says below (https://github.com/sul-dlss/dor-services-app/issues/1290#issuecomment-718997876):

> If there's a valueURI without an authority attribute, that's valid and doesn't need to be reported. If the value is three letters, let it pass without the authority attribute and report it as an error. If the value is not three letters, something unpredictable is wrong with the data and it should fail.

Two actions needed by engineer:

1. the mapping code is modified per Arcadia's instructions, and if requested, sends Honeybadger a notification (see https://github.com/sul-dlss/dor-services-app/pull/1282/files# for an example notification)
2. assign this ticket back to Arcadia once the error handling is added to the code and she'll follow through with data remediation.

**Do not have PR close this ticket -- mention the ticket # but don't use github magic words in PR description**

------ original ticket below -----

JLitt's most recent run of validator (from fedora to cocina mappings) for 325K random prod objects:

```
Error: ./mods:role/mods:roleTerm[@type="code"] is missing required authority attribute (19 errors)
druid:cr391gq7466
druid:ds919sg5985
druid:jq959xy6710
druid:nf676xt4970
druid:jn867nx7451
druid:nc018xn7579
druid:tr882hg3507
druid:tr870pd7774
druid:zc221rc0493
druid:ds846xd1044
druid:fw863hr6225
druid:bs056js0016
druid:rx675br5706
druid:mw965fm4175
druid:sb590rq6970
druid:fj037zf2211
druid:ck132wb6800
druid:my683pp9971
druid:jm834bv7649
```

It's possible the mapping needed for this error is related to the missing mappings in #1251

**Comment by arcadiafalcone** [comment]
If there's a valueURI without an authority attribute, that's valid and doesn't need to be reported. If the value is three letters, let it pass without the authority attribute and report it as an error. If the value is not three letters, something unpredictable is wrong with the data and it should fail.
