### ISSUE TITLE
mapping validation error: key not found: "Topic" 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1291]
NOTE:  Arcadia says below (https://github.com/sul-dlss/dor-services-app/issues/1291#issuecomment-718999688):

> For "Topic", normalize to lower case and report as an error. For "topic", that is invalid MODS and should fail.

Two actions needed by engineer:

1. the mapping code is modified per Arcadia's instructions, and if requested, sends Honeybadger a notification (see https://github.com/sul-dlss/dor-services-app/pull/1282/files# for an example notification)
2. assign this ticket back to Arcadia once the error handling is added to the code and she'll follow through with data remediation.

**Do not have PR close this ticket -- mention the ticket # but don't use github magic words in PR description**

------ original ticket below -----

from JLitt's most recent run of validator (from fedora to cocina mappings) for 325K random prod objects:

```
Error: key not found: "Topic" (11 errors)
druid:xv661kx4223
druid:qr684zq1130
druid:xy743kk5793
druid:yw448qd5583
druid:ky082np9069
druid:gf424bq2099
druid:rd235fv8920
druid:fz099qm8777
druid:bq782pp3515
druid:jx066kr2212
druid:qt282gh9166
```

The following is different and is ticketed as #1306

```
Error: key not found: "topic" (1 errors)
druid:kd333yz5798
```

**Comment by arcadiafalcone** [comment]
For "Topic", normalize to lower case and report as an error. For "topic", that is invalid MODS and should fail.

**Comment by ndushay** [comment]
Note further:

```xml
<subject authority=“topic” authorityURI=“http://id.loc.gov/authorities/subjects” valueURI=“http://id.loc.gov/authorities/subjects/sh85028356”>
          <Topic>College students</Topic>
</subject>
```

Should also be notifying honeybadger for authority attribute on subject.  Code currently creates this happily:

```
        {
          "value": 'College students',
          "type": 'topic',
          "uri": 'http://id.loc.gov/authorities/subjects/sh85028356',
          "source": {
            "code": 'topic',
            "uri": 'http://id.loc.gov/authorities/subjects'
          }
        }
```

**Comment by ndushay** [comment]
code greased for thes by PR #1308
