### ISSUE TITLE
mapping validation error: key not found: "primary"

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1292]
NOTE:  Arcadia says below (https://github.com/sul-dlss/dor-services-app/issues/1292#issuecomment-719002741):

> ignore the invalid type attribute and report the error.

Two actions needed by engineer:

1. the mapping code is modified per Arcadia's instructions, and if requested, sends Honeybadger a notification (see https://github.com/sul-dlss/dor-services-app/pull/1282/files# for an example notification)
2. assign this ticket back to Arcadia once the error handling is added to the code and she'll follow through with data remediation.

**Do not have PR close this ticket -- mention the ticket # but don't use github magic words in PR description**

------ original ticket below -----

from JLitt's most recent run of validator (from fedora to cocina mappings) for 325K random prod objects:

```
Error: key not found: "primary" (3 errors)
druid:rw667tg8009
druid:md049mq5771
druid:wq793rc8271
```

~~This *may* have to do with "primary" belonging on "language" element rather than "languageTerm" element.  See https://github.com/sul-dlss/dor-services-app/issues/1090#issuecomment-715532802 and sul-dlss-labs/cocina-descriptive-metadata/issues/99~~

**Comment by arcadiafalcone** [comment]
This isn't connected to the language issue, but rather an invalid name type. To handle, ignore the invalid type attribute and report the error.

**Comment by ndushay** [comment]
Examples: druid:rw667tg8009, druid:md049mq5771, druid:wq793rc8271, druid:sd836bn3355, druid:tj585kp4051, druid:bj241ch3330

**Comment by ndushay** [comment]
code greased for thes by PR #1309
