### ISSUE TITLE
mapping validation error: key not found: "naf"

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1293]
NOTE:  Arcadia says (https://github.com/sul-dlss/dor-services-app/issues/1292#issuecomment-719002741):

> ignore the invalid type attribute and report the error.

Two actions needed by engineer:

1. the mapping code is modified per Arcadia's instructions, and if requested, sends Honeybadger a notification (see https://github.com/sul-dlss/dor-services-app/pull/1282/files# for an example notification)
2. assign this ticket back to Arcadia once the error handling is added to the code and she'll follow through with data remediation.

**Do not have PR close this ticket -- mention the ticket # but don't use github magic words in PR description**

------ original ticket below -----

from JLitt's most recent run of validator (from fedora to cocina mappings) for 325K random prod objects:

```
Error: key not found: "naf" (1 errors)
druid:pw260mt1867
```

**Comment by arcadiafalcone** [comment]
This is the same problem as in #1292.

**Comment by ndushay** [comment]
code greased for thes by PR #1309
