### ISSUE TITLE
mapping error:  bad value for subject authority attribute

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1307]
While working on #1291 and #1306, I realized this `<subject>` has a bad value for authority:

```xml
<subject authority=“topic” authorityURI=“http://id.loc.gov/authorities/subjects” valueURI=“http://id.loc.gov/authorities/subjects/sh85028356”>
          <Topic>College students</Topic>
</subject>
```

What the code does now is happily produce:

```
        {
          "value": 'College students',
          "type": 'topic',
          "uri": 'http://id.loc.gov/authorities/subjects/sh85028356',
          "source": {
            "code": 'topic',
            "uri": 'http://id.loc.gov/authorities/subjects'
          }
        }
```

What it should do:
- [ ] Honeybadger.notify that subject element has an unrecognized authority
- [ ] Leave `source.code` nil in the cocina model:

```
        {
          "value": 'College students',
          "type": 'topic',
          "uri": 'http://id.loc.gov/authorities/subjects/sh85028356',
          "source": {
            "uri": 'http://id.loc.gov/authorities/subjects'
          }
        }
```

**Comment by ndushay** [comment]
List(s) of acceptable authorities can be derived from below, per Arcadia:

- authority lists mentioned in mapping preamble (sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_subject.txt#L1)
> Note: Subjects with LCSH/NAF authorities are tricky in MODS (and MARC) because there may be a URI for the combined subject string, each individual term, or both. Also, the official MODS documentation says to use authority="lcsh" at the subject level, even when the individual terms have authority="naf": 'If the subject string is formulated according to the Library of Congress Subject Headings (or LC Name Authority File), the value of the authority attribute is "lcsh." A subject thesaurus that does not include names but has an implied authority for names uses the designation for that thesaurus (i.e., "lcsh" means LCSH plus NAF).'[1] This results in apparent inconsistencies, such as pairing authorityURI="http://id.loc.gov/authorities/subjects/" with valueURI="http://id.loc.gov/authorities/names/123", where the authorityURI namespace does not actually include the valueURI. The MODS>COCINA mapping does not represent this conflict, but it is possible to regenerate it from the retained data when mapping COCINA>MODS if desired.
- https://www.itsmarc.com/crs/mergedProjects/sorcecod/sorcecod/subject_heading_and_term_source_codes.htm

**Comment by arcadiafalcone** [comment]
Code lists for subject authorities

Subject codes: https://id.loc.gov/vocabulary/subjectSchemes.html
Classification codes: https://id.loc.gov/vocabulary/classSchemes.html
Genre codes: https://id.loc.gov/vocabulary/genreFormSchemes.html
Name-title codes: https://id.loc.gov/vocabulary/nameTitleSchemes.html
Cartographic codes: http://www.loc.gov/standards/sourcelist/cartographic-data.html
Occupation codes: http://www.loc.gov/standards/sourcelist/occupation.html
Country codes: http://www.loc.gov/standards/sourcelist/country.html
Geographic codes: http://www.loc.gov/standards/sourcelist/geographic-area.html
