### ISSUE TITLE
FromFedora mapping error: #/components/schemas/Source/properties/code does not allow null values

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1310]
```
Error: #/components/schemas/Source/properties/code does not allow null values (3 errors)
```

Examples: druid:dz692fn7184, druid:qw833gg0782, druid:jb294tg1139

**Comment by arcadiafalcone** [comment]
Can you determine which code was missing? All three of these records look OK to me.

**Comment by peetucket** [comment]
Looking at druid:dz692fn7184, this appears the be two nils for the ORCID identifiers:

```
    :identifier=>
     [{:value=>"https://orcid.org/0000-0002-6186-3761",
       :type=>"URI",
       :source=>{:code=>nil}}]},
```

Removing the `source` block in those cases allows validation to pass.  So let me try that in the mapping.

**Comment by peetucket** [comment]
jb294tg1139 seems to be the same issue with the ORCID identifier.

qw833gg0782 passes validation for me
