### ISSUE TITLE
FromFedora mapping error: #/components/schemas/DescriptiveStructuredValue does not allow null values

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1312]
```
Error: #/components/schemas/DescriptiveStructuredValue does not allow null values (2 errors)
```

Examples: druid:bm056hv8204, druid:pp689kh8248

**Comment by arcadiafalcone** [comment]
Looks to be a blank namePart type="date" element. Both records are generated by the current MARC2MODS XSLT so I'll take a look there. For error handling, drop the empty element and report the error.
