### ISSUE TITLE
FromFedora mapping error: key not found: "personal" 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1314]
```
Error: key not found: "personal" (1 errors)
```
Examples: druid:sm835nh3655

**Comment by arcadiafalcone** [comment]
For processing, treat it as if the type attribute is on the name element instead of namePart, and report the error.

**Comment by peetucket** [comment]
@arcadiafalcone Question about this one... I have a PR #1322 to report this type of error and to ignore the invalid type on the namePart node, but I believe that recognizing that this type is actually valid at the parent name node and adding it there is not quite as straightforward.  Just trying to assess cost/benefit ratio of allowing the mapping to proceed and alerting on the data issue vs trying to fix in the mapping itself at the same time.

**Comment by peetucket** [comment]
Justin merged my PR (I should have put in Draft until my question was resolved, sorry).  Perhaps we can open a new ticket if we want to do more work on this.
