### ISSUE TITLE
contributor mappings FromFedora and ToFedora used by h2

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1375]
See sul-dlss-labs/cocina-descriptive-metadata/pull/125/files

and

https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/h2_cocina_mappings/h2_to_cocina_contributor.txt

sul-dlss/happy-heron/issues/240 is in progress so h2 will put the right stuff in the cocina-model sent, ultimately, to DSA.

**Comment by jcoyne** [comment]
I'm unsure what needs to happen in DSA for this. https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/125 is a change to h2_cocina_mappings which shouldn't require any DSA modifications.

**Comment by ndushay** [comment]
Maybe nothing but I want to take a careful look.  It'll be splendid if we already have all the mappings we need for H2.

**Comment by ndushay** [comment]
So I'm down to 3 failing tests from the h2 cocina mappings.  ...
