### ISSUE TITLE
mappings for subjects for h2 -- to and from fedora

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1376]
See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/120/files

**Comment by jcoyne** [comment]
@ndushay I'm not clear on what needs to be done here.  I don't believe that anything in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/tree/master/h2_cocina_mappings should need special handling in DSA as they should have been covered by the spec in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/tree/master/mods_cocina_mappings.

**Comment by ndushay** [comment]
Mostly, i was just creating the ticket "just in case" -- I didn't confirm that work was required.  if you've checked and you're confident, that's fine w me.  Closing this - re-open if needed.
