### ISSUE TITLE
event mapping - originInfo dateOther  ensure correct mapping in from_fedora and to_fedora

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1379]
Ensure mappings for new examples from Arcadia https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/110 are mapped for from_fedora and to_fedora.

**Comment by jmartin-sul** [comment]
the from_fedora half:  https://github.com/sul-dlss/dor-services-app/issues/1426

and is this the to_fedora half?  https://github.com/sul-dlss/dor-services-app/issues/1408

**Comment by jmartin-sul** [comment]
i think https://github.com/sul-dlss/dor-services-app/issues/1426 overlaps with this issue, but is not exactly the same.  not actively working on this at the moment, so unassigning myself and putting back in the ready column.

**Comment by peetucket** [comment]
It appears this  the (5c) addition is already covered - confirmed that the tests cover it.  Will look at (5b)

```
5c. dateOther with eventType
<originInfo eventType="acquisition">
  <dateOther keyDate="yes" encoding="w3cdtf">1970-11-23</dateOther>
</originInfo>
{
  "event": [
    {
      "type": "acquisition",
      "date": [
        {
          "value": "1970-11-23",
          "status": "primary",
          "encoding": {
            "code": "w3cdtf"
          }
        }
      ]
    }
  ]
}
```

**Comment by peetucket** [comment]
Actually, (5c) seems to be covered in from_fedora but possibly not in to_fedora .  Investigating and writing a test for that.

**Comment by peetucket** [comment]
I think (5b) is covered in the from_fedora mapping, as shown in this test:

https://github.com/sul-dlss/dor-services-app/blob/master/spec/services/cocina/from_fedora/descriptive/event_spec.rb#L117-L151

It throws an HB alert if any <dateOther> element is missing the 'eventType', so more generalized than (5b) (and also not a fatal error, which I'm not sure what would mean).
