### ISSUE TITLE
MARC2MODS XSLT: map missing Chinese title in multiple language titles

### ISSUE THREAD

**Issue by cebraj** [sul-dlss/dor-services-app#1424]
Content owner noticed that some records in Argo are missing the title in Chinese characters. The translated and/or transliterated titles are there, but the Chinese title didn't get mapped from the MARC data.

Examples:
https://purl.stanford.edu/bj690cs7374

https://purl.stanford.edu/jx406zm7857

https://purl.stanford.edu/kd709kf2800

This one mapped ok:
https://purl.stanford.edu/bc988yx5529

**Comment by andrewjbtw** [comment]
I'm not sure why those titles weren't mapped initially, but I just tried refreshing the metadata on argo-stage using all three catkeys from the non-working examples and the mappings included the Chinese titles. Have you tried refreshing these items? They should work in production if they're working in stage.

**Comment by cebraj** [comment]
@andrewjbtw that worked in production! Thanks for looking into it. It is odd that it didn't map initially.

**Comment by cebraj** [comment]
Sounds like it may have been due to the old MODS 3.6 mapping. Closing ticket!
