### ISSUE TITLE
from_fedora: originInfo eventType attr and dateOther element mapped to cocina incorrectly

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#1426]
This file https://github.com/sul-dlss/infrastructure-integration-test/blob/master/spec/fixtures/filled_template.xlsx

when deposited creates errors like this:
```
https://app.honeybadger.io/projects/50568/faults/69404271
```

```
Data Error: originInfo/dateOther missing eventType
```

**Comment by jmartin-sul** [comment]
see also: https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/127/files

**Comment by mjgiarlo** [comment]
moved to In Progres

**Comment by jmartin-sul** [comment]
i think the desired mapping has been clarified by https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/127/files and the specific error ticketed here fixed by https://github.com/sul-dlss/dor-services-app/pull/1427/files, so closing this issue.

**Comment by jmartin-sul** [comment]
i think https://github.com/sul-dlss/dor-services-app/issues/1379 overlaps with this, but is not exactly the same, so leaving that open.
