### ISSUE TITLE
Map xml:space

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1450]
See `Title with xml:space="preserve"`.

https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_titleInfo.txt#L524

**Comment by jcoyne** [comment]
I don't think this ticket has enough details to be actionable.

**Comment by arcadiafalcone** [comment]
It's not something we intentionally add to our metadata - I suspect it's mostly coming out of the MARC2MODS transform. In any case we currently ignore it in our display systems. I think it's fine not to map this attribute.

**Comment by justinlittman** [comment]
Closing in favor of https://github.com/sul-dlss/dor-services-app/issues/1557
