### ISSUE TITLE
geo metadata: mis-capitalized type generates warning, gets normalized (was: ...generates invalid cocina)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dor-services-app#1464]
_**EDIT**_: title and description updated to reflect added normalization, remaining data remediation work.

`<dc:type>Image</dc:type>` is expected, but actual value in tag is all lower case, for example:

```xml
  <extension displayLabel="geo">
    <rdf:RDF xmlns:gml="http://www.opengis.net/gml/3.2/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:gmd="http://www.isotc211.org/2005/gmd">
      <rdf:Description rdf:about="https://purl.stanford.edu/bc959wt3333">
        <dc:format>image/jpeg</dc:format>
        <dc:type>image</dc:type>
        <gmd:centerPoint>
          <gml:Point gml:id="ID">
            <gml:pos>31.201435 29.909773</gml:pos>
          </gml:Point>
        </gmd:centerPoint>
      </rdf:Description>
    </rdf:RDF>
  </extension>
```

because of this, some items with the above data problem ~won't version~ generate normalization warnings when cocina is produced from MODS (e.g. when displaying in argo or closing an open version).   for examples of objects that ran into versioning issues before the mapping code was made more tolerant, see e.g. this search result:

https://argo.stanford.edu/catalog?apo_id=druid%3Afp165nz4391&f%5Bnonhydrus_collection_title_ssim%5D%5B%5D=The+Cantor+Arts+Center%C2%A0collection+of+ancient%C2%A0coins%2C+circa+5th+century+BCE+-+15th+century+CE&search_field=text

We should fix the remaining `<dc:type>image</dc:type>` occurrences to be `<dc:type>Image</dc:type>`

**Comment by jmartin-sul** [comment]
from [slack conversation](https://stanfordlib.slack.com/archives/C0EAZ09QF/p1605904981167400?thread_ts=1605893982.167000&cid=C0EAZ09QF):

@jmartin-sul 💬 
> 1. should our code do that comparison case-insensitively?  i.e., should it treat `<dc:type>image</dc:type>` like it does `<dc:type>Image</dc:type>`?  if so, warn on bad case, or just ignore?
> 2. should the prod data be cleaned up to normalize case?
> 3. is it safe to assume that the simpler format (e.g. <dc:format>image/jpeg</dc:format> instead of e.g. `<dc:format>application/x-esri-shapefile; format=Shapefile</dc:format>`) will always correspond to `<dc:type>Image</dc:type>`, or should we be building this cocina JSON based on parsing the `dc:format` value (looking for the `;` delimiter) without checking for `<dc:type>Image</dc:type>` ?

to which @arcadiafalcone 💬 
> 1. it's ok to compare case-insensitively, but do report the error
> 2. yes, it would be good to normalize to `Image`
> 3. i can't say for certain that assumption would always be true, so looking for the delimiter would be more reliable

**Comment by jmartin-sul** [comment]
seems like prod data should be remediated before this is closed?  or at least, a new ticket filed for remediation?

**Comment by jmartin-sul** [comment]
see also https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_geo_extension.txt

**Comment by ndushay** [comment]
What is left to be done on this ticket?

**Comment by jmartin-sul** [comment]
> What is left to be done on this ticket? If data remediation only, could it be assigned to Arcadia or Andrew and moved out of the ready column for sprint 3?

yeah, just data remediation, afaik.  @arcadiafalcone or @andrewjbtw, could we assign this to one of you as suggested by @ndushay?

**Comment by mjgiarlo** [comment]
@justinlittman Is this something you worked/are working on? It's still in our in progress column. Not sure what to do with it, given what @jmartin-sul said above.
