### ISSUE TITLE
Mapping error: PURL mistakenly has primary display usage

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1518]
PURL should only have `usage="primary display"` when there is no other `<url>` with `usage="primary display"` .

See, for example, druid:cy979mw6316.

This is wrong:
```
<location>
  <physicalLocation>Stanford University Libraries</physicalLocation>
  <url usage="primary display">http://infoweb.newsbank.com/?db=SERIAL</url>
  <url>http://web.lexis-nexis.com/congcomp/form/cong/s_pubadvanced.html?srcboxes=SSMaps&amp;srcboxes=SerialSet</url>
  <url>http://purl.access.gpo.gov/GPO/LPS839</url>
  <url usage="primary display">http://purl.stanford.edu/cy979mw6316</url>
</location>
```

**Comment by peetucket** [comment]
Problem is here (I think):  https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/mods_normalizer.rb#L136-L142

We need to search for a "primary display" designation across the entire MODs document, and not just the current `mods:location` node ...
