### ISSUE TITLE
ensure we have the latest MARC21slimUtils.xsl

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#154]
PR #152 switches to using a local version of MARC21slimUtils.xsl rather than one from http://www.loc.gov/standards/marcxml/xslt/MARC21slimUtils.xsl (which is sometimes unavail).  We need to check (once loc's is once again avail) that we have the latest greatest from http://www.loc.gov/standards/marcxml/xslt/MARC21slimUtils.xsl

**Comment by arcadiafalcone** [comment]
Updated in 2020.
