### ISSUE TITLE
Additional originInfo type normalization

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1593]
For druid:dr315bc3798:
```
Original node:
<relatedItem type="otherFormat">
  <originInfo>
    <publisher>Northwestern University Library</publisher>
  </originInfo>
  <identifier type="local">(DLC) 2006257206</identifier>
  <identifier type="local">(OCoLC)54441844</identifier>
</relatedItem>
Best guess roundtripped node:
<relatedItem type="otherFormat">
  <originInfo eventType="publication">
    <publisher>Northwestern University Library</publisher>
  </originInfo>
  <identifier type="local">(DLC) 2006257206</identifier>
  <identifier type="local">(OCoLC)54441844</identifier>
</relatedItem>
```

Need to determine why the evenType is publication and add to normalization.

**Comment by ndushay** [comment]
eventType is determined from the flavor of date field - see https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/from_fedora/descriptive/event.rb#L61-L76. -- it is the first argument passed to `build_event` https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/from_fedora/descriptive/event.rb#L168

Some weeks back, I added normalization in the roundtripping to allow for eventType to be added to mods with roundtrip.   Ihttps://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/mods_normalizer.rb#L108.   I imagine this is just a matter of putting the same code in relatedItem.

**Comment by ndushay** [comment]
closing in favor of #1671
