### ISSUE TITLE
Mapping error:  originInfo/dateOther missing eventType

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1617]
Blocked by PR #1616

Data error: [DATA ERROR] originInfo/dateOther missing eventType (202 errors)  (out of 100,000)

Examples: druid:qy796rh6653, druid:dm508mt8359, druid:rj629pm3328, druid:dk301qh7944, druid:wx268gw1165, druid:hh096tc4794, druid:pc581xv5441, druid:gd951np7323, druid:sw328xt2844, druid:hy547jf7656

**Comment by ndushay** [comment]
Arcadia - not sure what the correct thing is to do in this case ... possibly ... just fix the data?   Maybe you already have this in your queue via Honeybadger??   If there's coding for us to do, please write a mapping spec and then put this into the ready column.

**Comment by arcadiafalcone** [comment]
This is in my remediation queue - no mapping needed (unless it's breaking something).
