### ISSUE TITLE
mapping error (originInfo but really anything):  handle a parallelValue when script is missing

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1619]
Arcadia mapped some originInfo examples for us in examples 43A, B, C:  https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_originInfo.txt#L1475 

From earlier to-cocina errors:

Error: #/components/schemas/Standard/properties/code does not allow null values (316 errors)
Examples: druid:zj576wq3325, druid:hn285fy7937, druid:bh212vz9239, druid:mb692mj9654, druid:tt582sd2713, druid:jc234ns7884, druid:hk834br2244, druid:rq359py4413, druid:yq997xw9085, druid:ns423hv2461

**Comment by ndushay** [comment]
@arcadiafalcone after you figure out what we should do, please unassign yourself and move to ready column.

**Comment by arcadiafalcone** [comment]
Mappings in https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/218.

**Comment by justinlittman** [comment]
Looks like these examples are handled.
