### ISSUE TITLE
mapping:  (originInfo) with script attribute but no altRepGroup

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#1683]
from sul-dlss-labs/cocina-descriptive-metadata/issues/221:

https://argo.stanford.edu/view/druid:pk167yq6876 _had_ but one originInfo element:

```xml
 <originInfo script="Latn">
    <place>
      <placeTerm type="code" authority="marccountry">ja</placeTerm>
    </place>
    <dateIssued encoding="marc" point="start">1915</dateIssued>
    <dateIssued encoding="marc" point="end">1942</dateIssued>
    <issuance>monographic</issuance>
  </originInfo>
```

it roundtrips like this (no script attribute):

```xml
  <originInfo eventType="publication">
    <dateIssued point="start" encoding="marc">1915</dateIssued>
    <dateIssued point="end" encoding="marc">1942</dateIssued>
    <place>
      <placeTerm type="code" authority="marccountry">ja</placeTerm>
    </place>
    <issuance>monographic</issuance>
  </originInfo>
```

per Arcadia here:  https://github.com/sul-dlss-labs/cocina-descriptive-metadata/issues/221#issuecomment-742786001

>Script should stay even in the absence of altRepGroup.

Arcadia also says:
> I've refreshed that record and the script went away ...

Note that ruling probably applies to all MODS top-level elements, not just `<originInfo>`  (right, @arcadiafalcone ?) ... but if it's too hard to do this for everything, I would suggest making separate tickets as needed.

**Comment by arcadiafalcone** [comment]
Yes, it applies to any instance of the script attribute.
