### ISSUE TITLE
Map titleInfo authority

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1756]
For druid:wq027ng0617:

```
Original node:
<titleInfo authority="Corpus Christi College">
  <title>Cambridge, Corpus Christi College, MS 410: Walter of Oddington OSB, De speculatione musicae. Johannes de Muris, Libellus cantus mensurabilis (recensio minor). A Short Treatise on the Rule of Discant</title>
</titleInfo>
Best guess roundtripped node:
<titleInfo>
  <title>Cambridge, Corpus Christi College, MS 410: Walter of Oddington OSB, De speculatione musicae. Johannes de Muris, Libellus cantus mensurabilis (recensio minor). A Short Treatise on the Rule of Discant</title>
</titleInfo>
```

**Comment by jcoyne** [comment]
I believe this is a valid use of the authority attribute.

> When recording authoritative titles, the authority attribute may be used whenever the type attribute is set to "uniform" and/or "abbreviated". Authority codes for "uniform" may be taken from the Name and Title Authority Source Codes; authority codes for "abbreviated" may be taken from the code list for Abbreviated Title Source Codes, both maintained by the Library of Congress. The authority attribute should not be used with titles having a type attribute of "translated" or "alternative" since these title types would not be represented in an authority file. If implementers need to link a name to a uniform title MODS provides the nameTitleGroup attribute, although this is not often applied in practice. 


https://www.loc.gov/standards/mods/userguide/titleinfo.html

**Comment by jcoyne** [comment]
@arcadiafalcone what do you think?

**Comment by arcadiafalcone** [comment]
I'm going to call this one valid, because a) the MODS guidelines don't say that the authority value _must_ be a code and b) Parker is a unique case and I don't expect non-code authorities to appear more generally. So it should be added to the list of valid authority values.
