### ISSUE TITLE
Change strategy for reporting data errors

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1817]
As described in https://github.com/sul-dlss/argo/issues/2356, raising an error for data errors is problematic.

**Comment by justinlittman** [comment]
The strategy:
1. Add an abstraction (DataErrorNotifier) around reporting data errors. The initial implementation will notify via Honeybadger.
2. Stop intentionally raising for from fedora mapping errors. Currently, this includes a missing title and sourceId.
3. Remove all of the code that handled those errors (e.g., in controllers).

In a separate ticket, I'd suggest that:
1. Missing title and sourceId get added to the existing Cocina validator.
2. For `show`, validation should not be applied.
3. For `create`, validation should not allow any errors.
4. For `update`, validation should not allow any new errors.

Also, @andrewjbtw should be warned that these changes may have unforeseen consequences.

**Comment by ndushay** [comment]
My initial guess is that we do need validation for show because some of our data is created/manipulated outside of Argo and users will need to be able to get specific errors via Argo in some cases (e.g. via Goobi).   If the real errors can get surfaced to the users as appropriate for their context, then of course that would be preferable ... but we have a lot of contexts.

Also, when creating and updating in batches ... how do we indicate which records had errors and the specifics?

**Comment by justinlittman** [comment]
Yes, agree with your comments about needing to provide appropriate handling / feedback in the various contexts, including when performing batch operations. However, this is at the API level and making sure that errors are not raised in inappropriate contexts. The current problem is exactly that: users cannot fixed the descMetadata for an item because when Argo calls `show` to get the Cocina representation for the item to check permissions, an error is raised.

As we role out Cocina, there is going to be more work to make sure that in all of the contexts in which users can submit / update items, validation errors are correctly reported.

**Comment by andrewjbtw** [comment]
> Also - what is the motivation for not raising for missing title or missing sourceid?

I'm not sure what not raising an error means in this context, but the current situation prevents anyone from fixing a title or sourceid from within Argo. You have to go to Fedora directly.
