### ISSUE TITLE
Undefined method 'empty?' for nil:NilClass

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#1875]
Error: undefined method `empty?' for nil:NilClass (9 errors)
druid:tr674df8094
druid:fc870hd0726
druid:ms018nh8114
druid:bc123mv3855
druid:tr306ww8912
druid:wh196nz4605
druid:zn201fm5255
druid:rg537qv0539
druid:cj588dp9662

**Comment by jcoyne** [comment]
I've indexed these you can find them in argo: https://argo.stanford.edu/catalog?f%5Bdata_quality_ssim%5D%5B%5D=Cocina+conversion+failed&search_field=text
