### ISSUE TITLE
Undefined method '[]' for nil:NilClass

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#1876]
Error: undefined method `[]' for nil:NilClass (3 errors)
druid:hr644fn6354
druid:ky585kf9485
druid:vb930ys4873

**Comment by jcoyne** [comment]
I believe these may be fixed via #1871. @arcadiafalcone can you confirm?

**Comment by justinlittman** [comment]
Confirmed.
