### ISSUE TITLE
[dor-services-app/stage] ArgumentError: Source ID must follow the format 'namespace:value', not 'foo'

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#193]
## Backtrace

    line 19 of [PROJECT_ROOT]/app/controllers/objects_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/44150027)

This should be a 422 error, not a 500

**Comment by justinlittman** [comment]
Catch ArgumentError and return as 422.
