### ISSUE TITLE
Implement mapping for place - text and code for different places - Version B

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1976]
See "Place - text and code for different places - Version B" in `spec/services/cocina/mapping/descriptive/mods/origin_info_place_spec.rb`.

**Comment by ndushay** [comment]
@arcadiafalcone how are we supposed to know from the MODS only that the text and code don't match?

```xml
          <originInfo eventType="publication">
            <place>
              <placeTerm type="code" authority="marccountry" authorityURI="http://id.loc.gov/authorities/names/"
                valueURI="http://id.loc.gov/authorities/names/n50046557">cau</placeTerm>
              <placeTerm type="text" authority="marccountry" authorityURI="http://id.loc.gov/authorities/names/"
                valueURI="http://id.loc.gov/authorities/names/n50046557">Stanford (Calif.)</placeTerm>
            </place>
          </originInfo>
 ```

**Comment by arcadiafalcone** [comment]
If the `authority` is `marccountry` and the `authorityURI`/`valueURI` does not begin with `http://id.loc.gov/vocabulary/countries`, then it's a mismatch. All codes are 2 or 3 characters and should be lowercase, so the one matching that pattern goes with `authority`, and the other one gets the URIs that don't begin with the above string. If none of the values match that pattern, map it as if they were `parallelValue` and warn 'Mismatch between placeTerm code and text.' Also warn 'Unknown authority code in placeTerm' if the value is not `marccountry`.

**Comment by ndushay** [comment]
@arcadia:   mapping this as you specified is ... hard.   This isn't even the correct psuedocode logic, and it's already awful:

```
          # group placeTerm elements that share @authority and/or @authorityURI
          #   for each group:
          #     if @authority is marccountry
          #       warn if @authorityURI is present and doesn't start properly
          #       if @type is code
          #         if it is 2 or 3 chars
          #           make it lowercase (?warn if not?)
          #           cocina.source.code is set to @authority (marccountry)
          #           cocina.source.authority is set to @quthorityURI if it starts properly
          #           cocina[:code] = code value
          #         else if another placeterm (NOT type code, i.e. @type missing or text) is 2-3 letters
          #           ?warn type is wrong if find one?
          #           treat it as if it is @type code
          #         else nothing matches the pattern (2-3 chars)
          #           warn 'Mismatch between placeTerm and code and text'
          #           map with other values (type text, type missing) as parallel value
          #       if @type is text
          #         if @valueURI is present and starts properly
          #           cocina[:text] = text value
          #           cocina[:uri] = @valueURI
          #         elsif @valueURI is present and doesn't start properly
          #           warn @valueURI is present and doesn't start properly
          #           SEPARATE location from CODE LOCATION
          #           cocina[:text] = text value
          #           cocina[:uri] = @valueURI? or left blank?
          #           cocina.source.authority = @authorityURI? or left blank?
          #         else
          #           (@valueURI isn't present, but @authorityURI is present?
          #
          #     else # authority is NOT marccountry
          #       warn 'Unknown authority code in placeTerm' if @authority is not marccountry
          #
          #  for each NOT in group
          #    do something
```

So what I'm wondering is ... how many of these records do we have, and would it be okay to warn or error on them and not have perfect cocina?

This is from a replayable spreadsheet, so ... if they were to error ... would that be sufficient?

bleah bleah bleah

**Comment by arcadiafalcone** [comment]
I just realized I introduced some unnecessary complexity in the version above - here is a (I hope) streamlined version.

If `authority` is `marccountry`, `iso3166`, or `marcgac`, or if there is no `placeTerm type="text"` in the `place` element, it goes with the `placeTerm` with `type="code"`. Else it goes with `placeTerm type="text"`.

If `authorityURI` contains `id.loc.gov/vocabularies`, or if there is no `type="text"`, it goes with `type="code"`. Else it goes with `type="text"`.

If `valueURI` contains `id.loc.gov/vocabularies`, or if there is no `type="text"`, it goes with `type="code"`. Else it goes with `type="text"`.

If all three authority attributes apply to the same `placeTerm`, treat them as a `parallelValue` if both `text` and `code` are present.

Warn if the `code` value receives no authority attributes and is not a `parallelValue` with `text`.

Warn if the value of `authority` is not any of the following:
- in CARTOGRAPHIC_CODES
- in COUNTRY_CODES
- in GEOGRAPHIC_CODES
- naf
- wikidata

If it's possible to run this logic against some sample records so that I can confirm the output is as expected, that would be helpful.

**Comment by ndushay** [comment]
Not implemented:

Warn if the `code` value receives no authority attributes and is not a `parallelValue` with `text`.

Warn if the value of `authority` is not any of the following:
- in CARTOGRAPHIC_CODES
- in COUNTRY_CODES
- in GEOGRAPHIC_CODES
- naf
- wikidata

**Comment by ndushay** [comment]
asking Arcadia for more help in examining output.

**Comment by ndushay** [comment]
@justinlittman if you're still seeking tickets, This one shouldn't crash with what I'm doing ... much.

**Comment by justinlittman** [comment]
Rather than implement this insane mapping, going to try a report and remediate approach. Per @arcadiafalcone, the report should be for:
> any place which has a placeTerm type=code and placeTerm type=text where authority is present and authorityURI or valueURI contains id.loc.gov/authorities
