### ISSUE TITLE
Implement mapping for transliterated name with parts (name as structuredValue) test

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1988]
See "Transliterated name with parts (name as structuredValue)" in `spec/services/cocina/mapping/descriptive/mods/name_spec.rb`.

Note that example may need some changes.

**Comment by justinlittman** [comment]
@arcadiafalcone Can this be implemented? It has note "# This example is for reference only - doesn't need to be mapped.  Splitting the name isn't implemented."

See https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/name_spec.rb#L1050

**Comment by arcadiafalcone** [comment]
Correct, it doesn't need to be implemented.
