### ISSUE TITLE
Implement mapping for event as contributor test

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1991]
See "Event as contributor" in `spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb`.

**Comment by ndushay** [comment]
@arcadia - this is implemented already -- is it correct?   See https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb#L500   (and yes, that was me messing with your example data)

**Comment by arcadiafalcone** [comment]
That is correct - closing this ticket.
