### ISSUE TITLE
Implement mapping for event release date: 2022-01-01 test

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#1995]
See "Release date: 2022-01-01" in `spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb`.  (line 151, last one)

**Comment by ndushay** [comment]
@arcadiafalcone https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb#L150   uses `eventType="release"` but our enumerated event types do not, at this time, include "release"

Should "release" be added?

Also double checking that "appliesTo" is completely ignoring for cocina -> MODS mapping purposes.

**Comment by arcadiafalcone** [comment]
Yes, add release. `appliesTo` is ignored except when it's with a `language` property.

**Comment by ndushay** [comment]
@arcadiafalcone I'm assuming when mapping from cocina, event type `release` gets `dateIssued` element for date in cocina.
