### ISSUE TITLE
Normalize capitalization of MODS elements and attributes

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2035]
See druid:kd767cw2079 - `name` has `valueuri`

**Comment by justinlittman** [comment]
This is tricky. Do we know how common this is? Does if affect all elements/attributes? Could this be handled through data remediation (instead of normalization)? Perhaps we could create a report to detect?

**Comment by arcadiafalcone** [comment]
If we could create a report and do a bulk remediation that would be preferable. It may be localized to this one collection.

**Comment by justinlittman** [comment]
Is it all elements/attributes? Or do you have a specific list to check?

**Comment by arcadiafalcone** [comment]
Best to check everything. I can probably compile a complete list if needed.

**Comment by arcadiafalcone** [comment]
Looking at this again for an example, I suspect that we updated the elements and not the attributes. So if checking/updating the attributes only is easier that would probably be sufficient.
