### ISSUE TITLE
mapping for placeTerm - when authority is 'marcountry' not 'marccountry'

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2080]
This is to address one of the new roundtrip errors while implementing a fix for #1976.

https://argo-prod-02.stanford.edu/view/vx956gk6224 has 

```xml
  <originInfo displayLabel="Place of creation" eventType="production">
    <place>
      <placeTerm type="code" authority="marcountry" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n50046557">cau</placeTerm>
      <placeTerm type="text" authority="marcountry" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n50046557">Stanford (Calif.)</placeTerm>
    </place>
...
```

Note `marcountry` as authority instead of `marccountry`.

For now the plan is to 
1. normalize to 'marccountry' and 
2. to warn (can we notify as part of normalization??)

But in a perfect world, we'd do something like this, per Arcadia:

1. if authority isn't one of blessed 3, then look at authorityURI
2.  if authorityURI is http://id.loc.gov/authorities/names (with trailing slash) then the place code stands alone (no attribs) in cocina and 
3. should error (or warn??) and
4. AND the authority attrib becomes 'naf' and goes with text

To get this in the event:

```ruby
              location: [
                {
                  code: 'cau'
                },
                {
                  value: 'Stanford (Calif.)',
                  uri: 'http://id.loc.gov/authorities/names/n50046557',
                  source: {
                    code: 'naf',
                    uri: 'http://id.loc.gov/authorities/names/'
                  }
                }
              ],
```

**Comment by ndushay** [comment]
@arcadiafalcone can you please re-confirm that this is an appropriate plan (at least for now):

1. normalize to 'marccountry' and
2. warn ( if we can notify as part of normalization)

**Comment by arcadiafalcone** [comment]
Yes, that works.
