### ISSUE TITLE
Implement descriptive standard with authority

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2088]
See "Description standard with authority" in https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb

**Comment by justinlittman** [comment]
@arcadiafalcone Does the code come from `authority` (https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb#L21) or the text (https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb#L193)?

**Comment by arcadiafalcone** [comment]
It should come from the text value. https://github.com/sul-dlss/dor-services-app/blob/195f3d06ca642ce50a73b13ae26ce292f8ce141e/spec/services/cocina/mapping/descriptive/mods/record_info_spec.rb#L21 should be
```
<descriptionStandard authorityURI="http://id.loc.gov/vocabulary/descriptionConventions/" 
valueURI="http://id.loc.gov/vocabulary/descriptionConventions/dacs">dacs</descriptionStandard>
```
