### ISSUE TITLE
Implement xlink mappings for name and alternativeName

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2102]
See https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/name_spec.rb

**Comment by justinlittman** [comment]
@arcadiafalcone Should structuredValues have status=primary? They don't elsewhere. https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/name_spec.rb#L1541

And if so, when should it have status=primary?

**Comment by arcadiafalcone** [comment]
I think I'm going to have to add a property for cases like this and physical description where a set of values are grouped together but order doesn't matter as it usually does in structuredValue.
