### ISSUE TITLE
Implement handling of blank subject/cartographics/coordinates node

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2113]
See #2112 . Entire subject stanza should be dropped if no subelement has value; drop only the empty coordinates element if other subelements of subject/cartographics have value.

**Comment by justinlittman** [comment]
Already done: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/mods_normalizers/subject_normalizer.rb#L165-L201
