### ISSUE TITLE
Report on dateOther usage

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2125]
Select: records that contain a dateOther element

Output: item druid, APO druid, collection druid, catkey

It would also be helpful if I could get a zip file of the MODS records themselves.

**Comment by ndushay** [comment]
Arcadia says:

>  if eventType and dateOther{@type} could be in the report that would be great - i was going to pull them from the mods

> basically i'm trying to answer 1) what records have dateOther without type? 2) what kind of type values does dateOther have? and 3) how does dateOther type relate to eventType when both are present?

**Comment by ndushay** [comment]
Justin has implemented said report (not with zip file of druids, but probably could make that happen if necessary.)

**Comment by arcadiafalcone** [comment]
If the data is in the report then I don't need the records (at least not yet). Do I run the report myself once I get back my access to sdr-deploy?

**Comment by justinlittman** [comment]
I'm running it now. In the future, if it would be helpful, we can create a tool to extract MODS records and zip.
