### ISSUE TITLE
Update H2 event mappings to fit with new specs

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2129]

**Comment by mjgiarlo** [comment]
Hi, @arcadiafalcone! Is this in progress?

**Comment by arcadiafalcone** [comment]
The MODS `originInfo` specs are still in flux, but I ran through the H2 mappings and they shouldn't be affected by the parts of the spec that are still uncertain (those are more about MODS>COCINA than COCINA>MODS). Closing ticket.

**Comment by mjgiarlo** [comment]
@arcadiafalcone OK, thank you!
