### ISSUE TITLE
Develop testing strategy for round tripping Fedora-Cocina for all datastreams

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2148]
When making changes to objects using the Cocina API, we need to ensure that these changes do not modify data in Fedora that was not meant to be modified. For example, a change to the source id or catkey should not result in a change to object rights. We need to develop a strategy for catching these issues before they affect items in production.

Examples of unintentional changes that have caught people by surprise:

These issues have been resolved:

- Setting rights stripped out the file role attribute in contentMetadata, which turned off content search for OCR: https://github.com/sul-dlss/argo/issues/2262
- Updates to media items that went through the Cocina API had the "thumb" attribute added to resources, rendering items unviewable: https://github.com/sul-dlss/argo/issues/2373
- Changing rights on media items converted resource types from video or audio to file, rendering the items unviewable on the purl: https://github.com/sul-dlss/argo/issues/2261

This issue is active:

- File-level rights are being stripped from objects when updates are made via Cocina https://github.com/sul-dlss/argo/issues/2382 

The testing strategy developed for descriptive metadata mapping may be useful here, but we may need another approach for non-descriptive metadata. The issues I've seen so far seem to be concentrated around rights and content metadata.

**Comment by ndushay** [comment]
I have created tickets:
- #2700 get results of roundtripping the cache of our actual production Fedora data - assigned to JLitt
- #2701 rightsMetadata roundtripping - more better unit tests - assigned to me
- #2703 identityMetadata roundtripping - more better unit tests
- #2704 administrativeMetadata roundtripping - more better unit tests - assigned to me because i started in and have a PR up for part of it

What we need from @andrewjbtw:
- priority order of which data we should focus on first (also requested in #2700).   It can be the fedora unit of a datastream or the cocina unit of a cocina-model.

**Comment by andrewjbtw** [comment]
Since descMetadata, adminMetadata and maybe embargoMetadata (?) are already being addressed, my priority order is:

- rightsMetadata (biggest impact on what people see, risk of exposing wrong levels of access)
- RELS-EXT (maintain object relationships)
- contentMetadata (problems can result in objects being unviewable)
- defaultObjectRights
- identityMetadata
- roleMetadata (probably easiest to fix)

The new approach to versionMetadata is different enough that it doesn't seem like a good candidate for this type of testing. We need to be able to show lifecycle and version names for previous versions, but Cocina is just storing the current version, as far as I know.

**Comment by ndushay** [comment]
Still need tix for mapping code roundtrip tests for:

- RELS-EXT
- embargoMetadata (?)
- defaultObjectRights
- roleMetadata

**Comment by justinlittman** [comment]
Now that I'm thinking about it, is there a reason that we need to test each of these separately and can't test together using `validate-cocina-roundtrip`? The more tricky ones benefit from individual testing, but perhaps it is not necessary for the rest.

**Comment by justinlittman** [comment]
Or perhaps we want to test by type, e.g., test DROs, APOs, and collections separately, but test all datastreams?

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/dor-services-app/pull/2785 adds caching of some missing datastreams.

**Comment by ndushay** [comment]
We wanted to be able to check a single datastream separately so it wouldn't take forever to get new info ... ok w me if they are grouped ...

**Comment by justinlittman** [comment]
This is addressed by `validate-cocina-roundtrip`. If this proves inadequate, we can re-visit.
