### ISSUE TITLE
Bulk remediation of invalid MODS authority value

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2201]
Replace all instances of
`authority="lcnaf"`
with
`authority="naf"

Expected record count is around 57K.

**Comment by justinlittman** [comment]
Since this is adjusted in the mapping, is there a reason to remediate the MODS?

**Comment by arcadiafalcone** [comment]
It's preferable for the MODS to be valid, especially while it's still our data of record.

**Comment by arcadiafalcone** [comment]
[lcnaf_druids.txt](https://github.com/sul-dlss/dor-services-app/files/5998192/lcnaf_druids.txt)
