### ISSUE TITLE
Missing type=translated

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2266]
From druid:cd673rq3538

```
Original node:
<titleInfo type="translated" altRepGroup="05">
  <title>T&#x14D; "so" niman-gosenbun no ichizu</title>
</titleInfo>
Best guess roundtripped node:
<titleInfo altRepGroup="2">
  <title>Tō "so" niman-gosenbun no ichizu</title>
</titleInfo>
```

**Comment by justinlittman** [comment]
@arcadiafalcone This requires a spec, please. (I'm unclear on the mapping.)

**Comment by arcadiafalcone** [comment]
This particular example is due to a data error in the MARC (now remediated), but I've added the mapping for an unstructured translated title.

**Comment by justinlittman** [comment]
FYI @arcadiafalcone I'm fairly sure I saw other cases of this.
