### ISSUE TITLE
Map parallel identifiers

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2267]
For example, https://argo.stanford.edu/view/druid:cf645zr8941:
```
<identifier altRepGroup="09">(DLC) 99115020</identifier>
    <identifier altRepGroup="09">(OCoLC)8735405</identifier>
```

**Comment by arcadiafalcone** [comment]
I think this will be fixed by refreshing from source with the current MARC2MODS XSLT (which I can't do myself because it's a Project Phoenix item).

**Comment by arcadiafalcone** [comment]
Confirmed fixed by refresh.
