### ISSUE TITLE
Handle MODS version mismatches

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2366]
For some items (e.g., druid:hj975yc6595, druid:hp978sk7611), the version in the MODS element does not match the version in the mods:recordInfo/mods:recordOrigin.

Our current normalization does not change the version if there is a value in the mods:recordInfo/mods:recordOrigin, leading to a roundtrip mapping error.

How should this be handled?

**Comment by arcadiafalcone** [comment]
Treat the version in the mods element as the correct one and report the mismatch for remediation.
