### ISSUE TITLE
Migrate events datastream events into events service

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2394]
When we decouple from Fedora, we need to bring the event history in the Events datastream into the Events service. As far as I know, the Events service currently only shows data recorded after the Events service was launched.

We've received user feedback that the Events datastream is useful in showing who has interacted with an object in the past in case any questions come up about it.

**Comment by andrewjbtw** [comment]
I'm not sure if this is the right repo for this ticket but I don't know where the SDR Events service lives.

**Comment by peetucket** [comment]
Note: Hydrus v1 is using this datastream, so it may not make sense to not port this data over until we are really done with H1.

**Comment by justinlittman** [comment]
@andrewjbtw Do you want all events or just the open/close events? Is there documentation on the events datastream?

**Comment by andrewjbtw** [comment]
There's a Chimera page here: https://consul.stanford.edu/display/chimera/Event+history+and+the+events+datastream

For migration purposes, I'd just like open and close, with the identifying information of who did what so we can see that in Argo. It's been useful when needing to ask someone about a past edit.

I believe the remaining events data is application-specific - Hydrus tracked user edits using this - and I think it's safe to not migrate that. If needed, the XML will be in the Moab.

**Comment by justinlittman** [comment]
Action for this ticket: Write a EventsMigrationService. Given a Fedora object, for each open and close event in the EventMetadataDS, it will create ActiveRecord Events (using the EventFactory) for events that do not already exist.

**Comment by justinlittman** [comment]
All the code for this is in place -- event migration happens as necessary for an individual item. Bulk event migration will occur as part of the bulk object migration.
