### ISSUE TITLE
dor-services-app prod config has some cruft

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dor-services-app#24]
- it has a solr.yml file which points to a dev instance
  - but i'm pretty sure solr.yml is a blacklight thing, and that's not a blacklight app, so it probably doesn't make a practical difference?
- it has configuration in config/environments/production.rb for gsearch.url, which is no longer useful (and which still points to the old argo 2 solr collection).

solrizer.url is correct, so neither of the above things should make a practical difference, but it'd be good to clean them up, so as to lessen confusion and detritus.

**Comment by jcoyne** [comment]
solr.yml is an activeFedora concern, so it is necessary. gsearch is no longer present.
