### ISSUE TITLE
[discussion] embargo behavior change for cocina

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#2414]
Currently when an embargo is released, we keep the embargoMetadata and add a status that says "released"  as we convert to cocina, we have an opportunity to change this behavior.  We must undertake this now as it is required to decouple dor_indexing_app from Fedora.

I propose that instead of setting "released" we remove the embargo altogether. I believe this is simpler and it matches what other community software is doing in the same domain: https://github.com/samvera/hydra-head/blob/98e4c991b539a89e7755a7a2c7bfda7b0f270776/hydra-access-controls/app/models/hydra/access_controls/embargo.rb#L18-L26

If we are required mirror the existing behavior we would need to add a new field to the Embargo schema: https://github.com/sul-dlss/cocina-models/blob/9334bed182573d89d13ff1351be15d03ac479131/openapi.yml#L792-L816

**Comment by aaron-collier** [comment]
we need to make sure we add an entry to the events when this happens.

To Determine: do we need to facet this in argo?

**Comment by andrewjbtw** [comment]
I've discussed this with the main embargo-facet-in-Argo stakeholders (Amy, Cathy, Hannah) and we can go ahead with indexing embargo data only from currently-embargoed objects. We do not need to preserve the ability to facet on already-released embargo dates. 

We do still need to be able to look up embargo history on individual objects, but as I understand this the Events and version history will show what happened previously. An embargo release creates a version with the name "embargo released" and that behavior should continue.

I think (and have gotten feedback along these lines) that it would still be useful to be able to create reports that can pull from embargo release history, so I will file an issue for that as an enhancement. But it is not a requirement for leaving Fedora.
