### ISSUE TITLE
For media content type, map image content as resource type image

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2444]
In discussion of https://github.com/sul-dlss/argo/issues/2431 I learned that for the media content type, we are doing the following mapping for resource types:

If resource contains audio --> set resource type = audio
If resource contains video --> set resource type = video
If resource is anything else --> set resource type = file

We need to add an inference that

If resource consists only of image content --> set resource type = image

Many media content types contain the following:

- video resource (video files + optionally a thumbnail image)
- audio resource (audio files + optionally a thumbnail image)
- image resource (only image files, usually a photograph of original physical media)

The current inference in our mapping is setting those image resources to the resource type of file. The result of this is that the images disappear from the sul-embed viewer. They need to be image resources so that they can continue to be displayed.

**Comment by ndushay** [comment]
specifically showing a record that should be something else, and what exactly should be diff ... is it in the contentMetadata??  somewhere else?

**Comment by andrewjbtw** [comment]
Example in stage: https://argo-stage.stanford.edu/view/druid:xn130pw5787

This media item has a video resource and an image resource. The image resource should have contentMetadata like this, with resource type="image":

```xml
<resource id="xn130pw5787_2" sequence="2" type="image">
    <label>Image file</label>
    <file id="xn130pw5787_Kokaji-Kiri_Dance_Front_Score_thumb.jp2" mimetype="image/jp2" size="700498" publish="yes" shelve="yes" preserve="yes">
      <checksum type="sha1">abe820afb7b9421a9befa018391b445f26e6b843</checksum>
      <checksum type="md5">cdc9eba55b80abf398f63787654cc229</checksum>
      <imageData height="720" width="1280"/>
    </file>
  </resource>
```
If it goes through Cocina, it comes out like this, with resource type="file"

```xml
  <resource id="xn130pw5787_2" sequence="2" type="file">
    <label>Image file</label>
    <file id="xn130pw5787_Kokaji-Kiri_Dance_Front_Score_thumb.jp2" mimetype="image/jp2" size="700498" publish="yes" shelve="yes" preserve="yes"><checksum type="sha1">abe820afb7b9421a9befa018391b445f26e6b843</checksum><checksum type="md5">cdc9eba55b80abf398f63787654cc229</checksum>
      <imageData height="720" width="1280"/>
</file>
  </resource>

When resource type is image, you can see the image file in the viewer (a menu pops up when you click the three dots):

<img width="1180" alt="Screen Shot 2021-03-10 at 4 25 34 PM" src="https://user-images.githubusercontent.com/8975583/110717147-5c2a2500-81bd-11eb-906b-7c58a304a8b1.png">

When resource type if file, you don't see the image content at all:

<img width="1180" alt="Screen Shot 2021-03-10 at 4 24 57 PM" src="https://user-images.githubusercontent.com/8975583/110717189-6fd58b80-81bd-11eb-8fea-7bb723e525fa.png">

**Comment by andrewjbtw** [comment]
I don't understand why my screenshots aren't displaying. Until I can fix it, here are links to the uploaded images.

[Resource type: image](https://user-images.githubusercontent.com/8975583/110717147-5c2a2500-81bd-11eb-906b-7c58a304a8b1.png "media player showing image content is available")

[Resource type: file](https://user-images.githubusercontent.com/8975583/110717189-6fd58b80-81bd-11eb-8fea-7bb723e525fa.png "media player showing no image content")

**Comment by ndushay** [comment]
Word is that we'll have to store this info, not infer it, so this ticket needs a rewrites
