### ISSUE TITLE
mapping: edtf date ranges should go into cocina like other date ranges

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2459]
they can be normalized back into edtf dates on the transform out;  it will make our code easier.

There are some `xit` and `FIXME` comments about this in the originInfo event mapping code and specs.

beware:  keyDate problems into and out of cocina

**Comment by arcadiafalcone** [comment]
EDTF dates should also stay the same type - currently they're changing to dateOther (see wf395pf7684).

**Comment by ndushay** [comment]
see also #2292
