### ISSUE TITLE
Filter out Hydrus from update_legacy_metadata date experiment

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2478]
See https://github.com/sul-dlss/dor-services-app/blob/c450ab7ff178e6b1687d194cba48ec55345b408f/app/services/legacy_metadata_service.rb#L17

Do not send an HB alert if this is a Hydrus object (based on the project tag)

**Comment by ndushay** [comment]
does this mean we want to say "if this dsa request came from Hydrus, don't output to HB" ?   Or does it mean "if this object is in a certain APO, then don't output to HB" or what?

**Comment by justinlittman** [comment]
Per @andrewjbtw, anything with a `Project : Hydrus` tag.

**Comment by peetucket** [comment]
> does this mean we want to say "if this dsa request came from Hydrus, don't output to HB" ? Or does it mean "if this object is in a certain APO, then don't output to HB" or what?

I had the same question -- confirmed it is "filter out", so don't go to HB if a hydrus object.  I picked this up and updated the ticket title to  make it more clear.
