### ISSUE TITLE
MODS validation fails when only subelement of originInfo is frequency

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2482]
druid:cf732ms2329

**Comment by justinlittman** [comment]
The problem is an empty originInfo:
```
<originInfo altRepGroup="06"/>
```

**Comment by arcadiafalcone** [comment]
@justinlittman Can you confirm? The validation error message is `MODS error: 83:0: ERROR: Element '{http://www.loc.gov/mods/v3}originInfo': Missing child element(s). Expected is one of ( {http://www.loc.gov/mods/v3}place, {http://www.loc.gov/mods/v3}publisher, {http://www.loc.gov/mods/v3}dateIssued, {http://www.loc.gov/mods/v3}dateCreated, {http://www.loc.gov/mods/v3}dateCaptured, {http://www.loc.gov/mods/v3}dateValid, {http://www.loc.gov/mods/v3}dateModified, {http://www.loc.gov/mods/v3}copyrightDate, {http://www.loc.gov/mods/v3}dateOther, {http://www.loc.gov/mods/v3}edition ). ` The list doesn't include `frequency` or `issuance`.
