### ISSUE TITLE
Batch remediation for languageTerm missing type

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2484]
Find: `<languageTerm authority="iso639-2b">eng</languageTerm>` anywhere in record
Replace with: `<languageTerm type="code" authority="iso639-2b" authorityURI="http://id.loc.gov/vocabulary/iso639-2" valueURI="http://id.loc.gov/vocabulary/iso639-2/eng">eng</languageTerm>`

**Comment by jcoyne** [comment]
@arcadiafalcone does it make sense to fix this stylesheet too so we don't introduce more bad data?

https://github.com/sul-dlss/was_robot_suite/blob/62d930157859925d06aa3253f45ac46bc48dcb8c/template/wasSeedPreassembly/descMetadata.xslt#L32

**Comment by arcadiafalcone** [comment]
Yes, that would be good.
