### ISSUE TITLE
When calling barcode -> catkey lookup, we get a 500 if no results are returned

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#251]
This code https://github.com/sul-dlss/dor-services-app/blob/master/app/controllers/marcxml_controller.rb#L20-L22 ends up throwing an exception from the `MarcxmlResource.find_by` call (on the model) if no result is found.  This ends up generating a 500 response.  It would make more sense to not throw an exception and instead return something like a 204 with a blank body.

**Comment by jcoyne** [comment]
204 = "No Content"

**Comment by ndushay** [comment]
where is this code called???  I couldn't find it.

**Comment by jcoyne** [comment]
It will be used by the google books import project
