### ISSUE TITLE
Implement updated name subject mappings

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2524]
To spin up on mapping tickets, Naomi or JLitt. can help w context that might be necessary.

See #2523

**Comment by jermnelson** [comment]
@aaron-collier and @arcadiafalcone, I created a new test `spec/services/cocina/from_fedora/descriptive/subject_spec.rb` and trying out the various combinations of MODS XML to Cocina to see if they match up to the specs in `https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb`. So far the current code looks like it is implementing the name-subjects correctly; is there something I'm missing (happy to put up a PR with these tests)?

Thanks!

**Comment by arcadiafalcone** [comment]
@jermnelson It looks like subject/name/description got taken care of as a side-along to subject/name/affiliation in #2613, so this one should be fine.
