### ISSUE TITLE
Implement mappings for multiscript titles converted from MARC

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2528]
See #2527 (PR that added xit specs)  (and also #2468 - issue for parallel titles)

To spin up on mapping tickets, Naomi or JLitt. can help w context that might be necessary.

Arcadia says:

> 2528 is when a record has multiple titleInfo elements with the same altRepGroup and different/no types (specifically the output generated when mapping from marc), and in theory represents the situation where the record includes the title in original script transcribed from the resource and in translation/transliteration created by the cataloger.
>
> 2468 is when all titleInfo elements with the same altRepGroup have type="translated". it represents the situation where multiple titles in different scripts/languages are transcribed directly from the resource by the cataloger - i.e., the resource itself has titles in multiple scripts/languages on itself and all are considered of equal importance.
>
> some (but not all) of the titles included in 2528 should actually be 2468 titles, but it's nontrivial to determine that from the marc via the xslt so the mods doesn't treat them that way. so they're linked intellectually but not necessarily in the way they're implemented.

**Comment by peetucket** [comment]
@arcadiafalcone : a couple quick questions as I start to work on this.

I an "un"-xited your spec in #2527, and noticed the following failures that need to be corrected:

```
           {
              parallelValue: [
                {
                  value: "Dang dai Taiwan wen xue xuan yi <2002->",
                  type: "translated"
                },
                {
                  value: "當代台灣文學選譯 <2002->",
                  type: "alternative"
                }
              ],
              type: "parallel"
            },
```

Should instead be:

```
           {
              parallelValue: [
                {
                  value: "Dang dai Taiwan wen xue xuan yi <2002->",
                  type: "translated"
                },
                {
                  value: "當代台灣文學選譯 <2002->",
                  type: "alternative"
                }
              ]
            }
```

Does that seem right?


It also looks like the tests are showing the PURL being expected in the Cocina:

```
   purl: "http://purl.stanford.edu/cp165bv2167",
          access: {
            digitalRepository: [
              {
                value: "Stanford Digital Repository"
              }
            ]
          }
```
and then the inverse in MODs was in expected but not received:

```
  <location>\n
       <url usage=\"primary display\">http://purl.stanford.edu/cp165bv2167</url>\n
    </location>\n
```
It's not clear to me if we just need to update the expected Cocina to include PURL, or if that's a problem somewhere in the mapping.  Do you happen to know?

**Comment by arcadiafalcone** [comment]
1. That is correct. (But I'm not seeing the `type: 'parallel'` in #2527).
2. That was my mistake - I used `let` to indicate the druid that an example was adapted from rather than putting it in a comment. I'll double check and make sure those are all fixed.

**Comment by peetucket** [comment]
1. Ok, so the mapping code not add that that extraneous `type: 'parallel'` (in other words, we currently create it in cocina, but we don't want it, according to the spec)?
2. I'll update the expectation to include the PURL.

**Comment by ndushay** [comment]
oh right - when the druid is explicitly included in the code, it creates a purl.  you can instead make it a comment "# based on oo000oo0000" and the purl will go away.

**Comment by arcadiafalcone** [comment]
1. Yes, `type: 'parallel'` should not be added in that case.
2. What Naomi just said ;)
