### ISSUE TITLE
Add an endpoint for setting the license of an object

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dor-services-app#2537]
This will be required to allow this to be added to the argo interface as well as a bulk action.

**Comment by jcoyne** [comment]
Is there a reason the Cocina update is insufficient for this?

**Comment by justinlittman** [comment]
Yes, is our model "retrieve the cocina, update the cocina, post back the updated cocina" or create separate convenience endpoints for each sort of update?

**Comment by aaron-collier** [comment]
No, cocina update is right, I was down the wrong path...
