### ISSUE TITLE
Add an endpoint to unpublish an object.

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dor-services-app#2538]
We have a "publish" action in Argo but not an unpublish action. The only way to unpublish seems to be to set rights to "dark" and then run the publish action, which is both counterintuitive and potentially risky because "dark" rights carry additional settings changes.

This is a problem when things are published accidentally as it's difficult to undo that action.

We could mitigate this problem by preventing publish in circumstances where it clearly should be prohibited, such as when an item is registered (see #2384).

**Comment by jcoyne** [comment]
Is "unpublish" different than "publish"?

**Comment by jermnelson** [comment]
@andrewjbtw and @aaron-collier, just a clarifying question on this ticket. Is the intent to have a **Unpublish** button in Argo that would make a call through the dor services client to this endpoint that would then remove the item from PURL but keep the object's rights in intact? Thanks!

**Comment by andrewjbtw** [comment]
Yes, this would solely remove the purl but change nothing else. There's a related ticket with Astrid's design, but the UI part is expecting we'd enable this in the new overall Argo design, not with an additional blue button right now: https://github.com/sul-dlss/argo/issues/2411

**Comment by jermnelson** [comment]
> Yes, this would solely remove the purl but change nothing else. There's a related ticket with Astrid's design, but the UI part is expecting we'd enable this in the new overall Argo design, not with an additional blue button right now: [sul-dlss/argo#2411](https://github.com/sul-dlss/argo/issues/2411)

Thanks @andrewjbtw that helps!
