### ISSUE TITLE
Create report of license codes and labels in the defaultObjectRights of APOs

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#2546]
Create a unique count of each code & label combination.

If there are a small number of outliers, we may just need to fix them.   If there are no odd licence/label combinations, we probably don't need to extend the cocina-model to support a license label (as we can just look it up in SPDX).

**Comment by mjgiarlo** [comment]
`defaultObjectRights` ?

**Comment by jcoyne** [comment]
Yes. I'll amend the title.

**Comment by peetucket** [comment]
@andrewjbtw I believe it is possible that some objects have overiden the default license provided by the APO in the individual object's rightsMetadata -- but am not sure this happens.  If it does, I thinks means would we need to actually inspect every single object to see what the extent of the licenses in use are ...

**Comment by peetucket** [comment]
Here is the report from APOs in JSON form.  It shows all of the possible values found in all 1239 APOs, along with the number for each. 

The APO splits the selections into two XML elements: Creative Common (shown below in CC) and Open Data Commons (shown below in OD).  It then includes a human label and a machine label.  I just enumerated each option and counted.

```
{
  "cc": {
    "human": {
      "": 71,
      "CC BY-NC-ND Attribution-NonCommercial-NoDerivs": 40,
      "Attribution 3.0 Unported": 6,
      "Public Domain Mark 1.0": 10,
      "CC BY-SA Attribution Share Alike": 18,
      "CC BY-NC Attribution-NonCommercial": 146,
      "CC BY-NC-SA Attribution-NonCommercial-ShareAlike": 46,
      "Attribution Non-Commercial 3.0 Unported": 14,
      "CC BY Attribution": 60,
      "CC-BY SA 4.0": 1,
      "CC BY-ND Attribution-NoDerivs": 6,
      "Attribution No Derivatives 3.0 Unported": 1,
      "Attribution-ShareAlike 4.0 International 4.0": 1,
      "Attribution Non-Commercial, No Derivatives 3.0 Unported": 5,
      "Attribution Non-Commercial, No Derivatives 4.0 Unported": 3,
      "Attribution Share Alike 3.0 Unported": 4,
      "Attribution Non-Commercial Share Alike 3.0 Unported": 5,
      "Attribution Non-commercial, No Derivatives 3.0 Unported": 1,
      "This work is licensed under a Creative Commons Attribution 3.0 Unported License": 1
    },
    "machine": {
      "": 68,
      "by-nc-nd": 49,
      "by": 67,
      "pdm": 10,
      "by-sa": 23,
      "by-nc": 160,
      "by-nc-sa": 52,
      "by-nd": 7
    }
  },
  "od": {
    "human": {
      "": 13,
      "ODC-By Attribution License": 11,
      "PDDL Public Domain Dedication and License": 5,
      "ODC Public Domain Dedication and Licence": 1,
      "Open Data Commons Attribution License 1.0": 1,
      "ODC-ODbl Open Database License": 2,
      "Open Data Commons Open Database License 1.0": 1
    },
    "machine": {
      "": 13,
      "odc-by": 12,
      "pddl": 6,
      "odc-odbl": 3
    }
  }
}
```

**Comment by peetucket** [comment]
Simple script used to run the report (starting with a .csv file with all of the APO druids as pulled from the report view in Argo):

```
# bundle exec rails runner -e production tmp/apo_report.rb

require 'csv'
require 'json'

input_file = 'tmp/apo_druids.csv'
output_file = 'tmp/license_report.json'

licenses={cc:{human:Hash.new(0),machine:Hash.new(0)},od:{human:Hash.new(0),machine:Hash.new(0)}}

rows = CSV.parse(File.read(input_file), headers: true)
num_rows = rows.size

puts "Input file #{input_file} : #{num_rows} found"

rows.each_with_index do |row, i|
  druid = "druid:#{row['druid']}"
  puts "#{i+1} of #{num_rows} : #{druid}"
  apo = Dor.find(druid)
  apo.defaultObjectRights.creative_commons.each { |lic| licenses[:cc][:machine][lic] += 1 }
  apo.defaultObjectRights.creative_commons_human.each { |lic| licenses[:cc][:human][lic] += 1 }
  apo.defaultObjectRights.open_data_commons.each { |lic| licenses[:od][:machine][lic] += 1 }
  apo.defaultObjectRights.open_data_commons_human.each { |lic| licenses[:od][:human][lic] += 1 }
end

File.open(output_file, 'w') { |f| f.write(JSON.pretty_generate(licenses)) }
puts "Output written to #{output_file}"

```

**Comment by peetucket** [comment]
[apo_druids.csv.zip](https://github.com/sul-dlss/dor-services-app/files/6167268/apo_druids.csv.zip)

**Comment by andrewjbtw** [comment]
I think you're right that we have to look out for all of the rights statements on objects. Definitely possible that someone edited them directly, especially if the APO defaults needed to be overridden since there's no other way to do that.

**Comment by peetucket** [comment]
We can use solr to inspect the machine readable codes since we index the machine readable license code in the object rightsMetadata  (as shown here https://github.com/sul-dlss/dor_indexing_app/blob/main/app/indexers/rights_metadata_datastream_indexer.rb#L70).

Argo will give us the values in this facet for just items: https://argo.stanford.edu/catalog?all=true&f%5BobjectType_ssim%5D%5B%5D=item

All results here:

![Screen Shot 2021-03-18 at 4 06 46 PM](https://user-images.githubusercontent.com/47137/111709441-d897b600-8804-11eb-8387-bc30c6386568.png)

**Comment by peetucket** [comment]
Scanning the lists of item codes shows these are the only two licenses that are in the item facet that don't exist in any of the APOs:

- by-nc-i (681 items)
- cc0 (1 item)

**Comment by peetucket** [comment]
The item's objectRights datastream also has the human readable form, but that isn't indexed, so I'm not sure there is an easy way to enumerate without looking at each object in Fedora (verrry slow).  But I think the idea is that we can just store a machine code, from which we can derive the human readable form as needed (i.e. to send to PURL if we need to).

**Comment by peetucket** [comment]
Here is some summary analysis:

```
Current H2 Licenses:

'CC0-1.0' => 'CC0-1.0',
'CC-BY-4.0' => 'CC-BY-4.0 Attribution International',
'CC-BY-SA-4.0' => 'CC-BY-SA-4.0 Attribution-Share Alike International',
'CC-BY-ND-4.0' => 'CC-BY-ND-4.0 Attribution-No Derivatives International',
'CC-BY-NC-4.0' => 'CC-BY-NC-4.0 Attribution-NonCommercial International',
'CC-BY-NC-SA-4.0' => 'CC-BY-NC-SA-4.0 Attribution-NonCommercial-Share Alike International',
'CC-BY-NC-ND-4.0' => 'CC-BY-NC-ND-4.0 Attribution-NonCommercial-No Derivatives',
'PDDL-1.0' => 'PDDL-1.0 Public Domain Dedication and License',
'ODC-By-1.0' => 'ODC-By-1.0 Attribution License',
'ODbL-1.0' => 'ODbL-1.0 Open Database License',
'AGPL-3.0-only' => 'AGPL-3.0-only GNU Affero General Public License',
'Apache-2.0' => 'Apache-2.0',
'BSD-2-Clause' => 'BSD-2-Clause "Simplified" License',
'BSD-3-Clause' => 'BSD-3-Clause "New" or "Revised" License',
'CDDL-1.1' => 'CDDL-1.1 Common Development and Distribution License',
'EPL-2.0' => 'EPL-2.0 Eclipse Public License',
'GPL-3.0-only' => 'GPL-3.0-only GNU General Public License',
'ISC' => 'ISC License',
'LGPL-3.0-only' => 'LGPL-3.0-only Lesser GNU Public License',
'MIT' => 'MIT License',
'MPL-2.0' => 'MPL-2.0 Mozilla Public License',
'none' => 'No License'
```

Current Argo selectable Licenses:

```
'by' => 'Attribution 3.0 Unported',
'by-sa' => 'Attribution Share Alike 3.0 Unported',
'by-nd' => 'Attribution No Derivatives 3.0 Unported',
'by-nc' => 'Attribution Non-Commercial 3.0 Unported',
'by-nc-sa' => 'Attribution Non-Commercial Share Alike 3.0 Unported',
'by-nc-nd' => 'Attribution Non-Commercial, No Derivatives 3.0 Unported',
'pdm' => 'Public Domain Mark 1.0',
'pddl' => 'Open Data Commons Public Domain Dedication and License 1.0',
'odc-by' => 'Open Data Commons Attribution License 1.0',
'odc-odbl' => 'Open Data Commons Open Database License 1.0'
```

Licenses currently in SDR objects from above report and suggested analog to H2 licenses:

```
'by-nc-nd'  ===> 'cc-by-nc-nd-4.0'
'by-nc-sa'  ===> 'cc-by-nc-sa-4.0'
'pdm'  ===> 'pddl-1.0' ? 
'by' ===> 'cc-by-4.0'
'by-nc' ===> 'cc-by-nc-4.0'
'by-sa' ===> 'cc-by-sa-4.0'
'none' ===> 'none'
'by-nc-i' ===> 'cc-by-nc-4.0' ?
'odc-by' ===> 'obc-by-1.0'
'pddl' ===> 'pddl-1.0'
'odc-odbl' ===> 'odbl-1.0'
'by-nd' ===> cc-by-nd-4.0'
'cc0' ===> 1 bad object in SDR needs a new license?
```

So it appears that nearly all licenses currently in SDR object have an possible analgous mapping to new H2 licenses (though the original CC licenses are version 3 and the newly selectable ones are version 4, and I assume we want to preserve the originally actually selected license).  I am not sure about the current license codes of 'BY-NC-I', 'PDM' and 'CC0'.

**Comment by jcoyne** [comment]
The versions of the CC licenses in SDR are all 3.0 licenses: https://github.com/sul-dlss/dor-services/blob/main/lib/dor/services/creative_commons_license_service.rb#L12-L28

**Comment by andrewjbtw** [comment]
The versions entered in the XML directly aren't limited to the list in the SDR menu/code. This APO has been edited to use a 4.0 version in the defaultObjectRights and I think all the items under that APO have the same 4.0 version: https://argo.stanford.edu/view/druid:sr199zw3981

**Comment by andrewjbtw** [comment]
`cc0` is in https://argo.stanford.edu/view/druid:qk286xn8411 where it has the URI: https://creativecommons.org/publicdomain/zero/1.0/ In the object history, you can see that the depositor specifically requested this license, which must have been directly entered into the rightsMetadata XML. It must correspond to H2: `'CC0-1.0' => 'CC0-1.0'`

`by-nc-i` appears to be the same as `cc-by-nc-4.0` and Google suggests that `by-nc-i` might be an abbreviation only Stanford has used for it, as a search led me to: https://github.com/sul-dlss/dor-services/issues/316 You can see in example druids that a 4.0 license has been written out into the rightsMetadata XML here too: https://argo.stanford.edu/view/druid:qk740gj0996

For PDM, maybe H2 should add that for consistency. I don't know the difference between PDM and PDDL but since one is Creative Commons and the other is Open Data Commons, maybe we shouldn't mix the two. But there also could be a good reason not to use PDM at all.

**Comment by jcoyne** [comment]
@andrewjbtw while there are outliers that use 4.0, the ones that don't have URIs, and just have a code should be interpreted at 3.0 versions, because that is what is displayed in Argo when you select the license. It is problematic to just "upgrade" licenses from one version to another.

**Comment by jcoyne** [comment]
@andrewjbtw additionally, I don't see that the code that sets licenses respects "whatever you have in the xml", so any time that code is accessed, I'll probably overwrite or error because those licenses are not something the code is aware of.

**Comment by andrewjbtw** [comment]
Right, I don't think licenses should be upgraded by default. I do think the licenses that are valid in the real world need to be retained even if they're not valid in the SDR world because SDR never got updated. We should not overwrite the 4.0 licenses, for example.

**Comment by amyehodge** [comment]
Agree with @jcoyne on this point "It is problematic to just "upgrade" licenses from one version to another."

And with @andrewjbtw that we want to keep the 4.0 licenses so they are available in the future. We have users who have requested these.

My understanding is that [CC PDM](https://creativecommons.org/share-your-work/public-domain/pdm/) and [ODC-PDDL](https://opendatacommons.org/licenses/pddl/1-0/) are not the same and should not be mixed.

**Comment by peetucket** [comment]
Calling this report ticket closed.  Follow on work should already be ticketed elsewhere.
