### ISSUE TITLE
Question: what data point should the Cocina object-level label field map from Fedora?

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2567]
The Cocina object-level "label" field is currently mapped from the Fedora object label. The Fedora object label is essentially never updated after an object is created. It's set at registration from the registration form "label" field and I don't think any part of the system ever modifies it afterwards. It doesn't seem like useful data to keep, migrate, or map.

I'm not clear what purpose the Cocina object-level label field is meant to serve, but it would be better if it were set from a field that actually gets updated in a user interface. The two candidates fields that are most similar to the Fedora object label are:

- identityMetadata objectLabel
- MODS title

The identityMetadata objectLabel can only be updated by editing the identityMetadata XML. However, this field is published to the Purl and some functions in the Access realm rely on the data here. So even if we don't use this field for the Cocina label, we need to store this data so that it can be made available to the Purl.

The MODS title is the field that people are most likely to be editing when they change a title. However, titles can be quite complex to parse (parallel title, etc.) and might overcomplicate the goal of having a Cocina object-level label field, whatever that goal might be.

One more consideration: in every use case I know of, the identityMetadata objectLabel field and the MODS title are expected to match. This is very clear in the Access sphere when someone has changed a MODS title and the change displays in some places (where Access is using the MODS title) but not in other places (where Access is using the identityMetadata). 

We could potentially solve two problems if:

- the Cocina object-level label was a simplified mapping from the MODS title (maybe a pre-defined subset of MODS title data?)
- the Cocina object-level label is what got published to the Purl

That way, a change to MODS title would update in both places.

Alternatively, the Access systems could use MODS title everywhere and identityMetadata objectLabel nowhere, but I haven't been able to make headway in that direction.

**Comment by jcoyne** [comment]
MODS title is not something we can easily use everywhere, because some titles are rather complicated, with subtitles, possibly translated to different languages.  It's much nicer to have a simplified label that we store separately.  We could use the IdentityMetadata#objectLabel as the source though, that would be no big deal.

**Comment by ndushay** [comment]
I think the code current IS mapping the objectLabel from identityMetadata for cocina label

**Comment by justinlittman** [comment]
@ndushay is correct: Cocina label comes from objectLabel (https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/from_fedora/dro.rb#L60) which is identity objectLabel (https://github.com/sul-dlss/dor-services/blob/c2c7eeb84cfae6e84a7b636f2e08159838cfe699/lib/dor/models/abstract.rb#L79-L83).

Closing, unless @andrewjbtw believes that there is additional work for this ticket.

**Comment by andrewjbtw** [comment]
The question was about should. There are a number of problems with using the identityMetadata objectLabel, discussed above. If we choose to use it, we have to make other changes. I'd been hoping this could be resolved with Access-side work but that doesn't look like it will happen in the timeframe we have.

**Comment by andrewjbtw** [comment]
And now I'm going to close it again, after talking to @jcoyne . I think we're going to end up making the label editable, rather than trying to map it in from the MODS title.
