### ISSUE TITLE
Add registrationWF to the seeded workflows

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#257]
Otherwise we can't register objects in argo.

**Comment by ndushay** [comment]
Naive question:  If the workflows are in https://github.com/sul-dlss/workflow-server-rails/tree/master/config/workflows, then why does dor-services-app need them to be in Fedora?

**Comment by ndushay** [comment]
Blocking virtual-merge testing ...

**Comment by ndushay** [comment]
druid:sh219xb1690

**Comment by ndushay** [comment]
Manually added it to stage using rails console.

**Comment by justinlittman** [comment]
@ndushay Can you add how to manually add via rails console to the README?

**Comment by ndushay** [comment]
uh ... i just did what was in the code at the rails console ... 

1.  go to WF object in prod
2.  get foxml for WF object in prod
3.  save raw foxml to file
4.  scp foxml file to stage box (where other WF objects live)
5.  execute the appropriate part of ruby code for the rake task that adds seeds via the rails console.

Do you think we'll be doing this often enough to warrant adding it to the README?  It seemed pretty one-offy to me ...

A regular object (not a WF object) would be out of sync with workflows and so on, so it wouldn't be the right thing for other types of objects, I don't think.

**Comment by justinlittman** [comment]
It's OK. Can add later if need arises.
