### ISSUE TITLE
H2 mapping: Is include in citation still necessary?

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2572]
See https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/h2/contributor_h2_spec.rb#L42-L47

**Comment by arcadiafalcone** [comment]
Yes. If we're going to be ultimately mapping to DataCite and want that to be backwards compatible with H2 data created before that point, we need to have the distinction, as DataCite separates agents into creators and additional contributors in a way that MODS doesn't. (Also it may be used in generating the preferred citation.)
