### ISSUE TITLE
Unable to create a new collection

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2598]
**Describe the bug**
I get a 500 error trying to create a collection from the "Create collection" button on an APO: https://argo-stage.stanford.edu/view/druid:bb973ms0268

Argo error: https://app.honeybadger.io/projects/49894/faults/78554731
Dor services app error: https://app.honeybadger.io/projects/50568/faults/78554730

**User Impact**
It's not possible to create new collections.

**Expected behavior**
A collection should have been created.

**Comment by jcoyne** [comment]
The problem is occurring when it is updating the APO to add the new collection to the APO.
