### ISSUE TITLE
Allow `AdministrativeTags#project` to return multiple entries

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor-services-app#2615]
Currently, `AdministrativeTags#project` assumes the object has no more than one tag, which is not the case in DOR. This method is only used in the `FromFedora` mappers in DSA and it not exposed anywhere else. So the current code is producing incomplete Cocina representations. Changing this has the following costs:

* Patch, re-generate, and cut new release of cocina-models: https://github.com/sul-dlss/cocina-models/blob/main/openapi.yml#L186-L189
  * Once done, update sdr-api and dor-services-app openapi specs too, and bump and cut new releases of sdr-client and dor-services-client
  * If we wanted to make this less likely to break everything, we could consider allowing `partOfProject` to be a string and an array of strings as long as we update code across the portfolio to handle this appropriate. Not currently sure whether that's more work than ripping off the adhesive bandage.
* Change dor-services-app
  * `FromFedora` mapper: https://github.com/sul-dlss/dor-services-app/blob/03e161698e2c10c0d59f94f42f82a8f19a432e4b/app/services/cocina/from_fedora/administrative.rb#L23
  * `ObjectCreator`: https://github.com/sul-dlss/dor-services-app/blob/06b6a1fbca0cd01c3efb468abb349449f477e82b/app/services/cocina/object_creator.rb#L139-L146
  * `ObjectUpdater`: https://github.com/sul-dlss/dor-services-app/blob/2c00ae43b866f1ca07d241fb15ae42d0e89a7ab5/app/services/cocina/object_updater.rb#L184
  * Consider how to deal with multiple projects given we're currently using the project as a means to route RabbitMQ messages: https://github.com/sul-dlss/dor-services-app/blob/03e161698e2c10c0d59f94f42f82a8f19a432e4b/app/services/notifications/object_created.rb#L36
* Change google-books
  * A single change to config to return the tags as an array should be sufficient: https://github.com/sul-dlss/google-books/blob/80f90a59ffdf89e8edb73922918b9142d130a0f8/app/services/request_generator.rb#L72
* Change dor_indexing_app
  * Fix identifiable indexer: https://github.com/sul-dlss/dor_indexing_app/blob/f626c62941c738f4c6fa7b523033f23870cb05cc/app/indexers/identifiable_indexer.rb#L100
* Change hydrus
  * https://github.com/sul-dlss/hydrus/blob/9d5b20086c8ca3c6c59b6f4167196f64c96881cc/app/models/hydrus/generic_object.rb#L313
* Change H2
  * Per google-books above, change config to return tag(s) as an array
    * https://github.com/sul-dlss/happy-heron/blob/3c5156cefc8257fb9f72b28868f24596edf0bde3/app/services/collection_generator.rb#L41
    * https://github.com/sul-dlss/happy-heron/blob/f3a1b9be55ce94d7185cea9c6081476944a95139/app/services/request_generator.rb#L37
  * Per DSA above, we may need to revisit the RabbitMQ routing key: https://github.com/sul-dlss/happy-heron/blob/fc4e956234970acc1c1ffdb683745c41440efcf1/lib/tasks/rabbitmq.rake#L24
* Change Argo
  * Tweak registration form: https://github.com/sul-dlss/argo/blob/05e9cf2f2948839604b6e331c612eda15ffdf3cb/app/forms/registration_form.rb#L42
  * Tweak registration CSV converter: https://github.com/sul-dlss/argo/blob/ba9a94a1f24e302ad2472da7110afc3e7b2a1354/app/services/registration_csv_converter.rb#L56

**Comment by andrewjbtw** [comment]
Possibly worth asking as well: should this tag be in the Cocina model?

**Comment by mjgiarlo** [comment]
@andrewjbtw Worth asking, for sure.

**Comment by andrewjbtw** [comment]
Do we do this now? Or some other solution that covers the same goal? We definitely handle multiple Project tags now.
