### ISSUE TITLE
Do not insert opaque identifiers into publicly readable resource labels

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2625]
Some content is deposited into SDR without resource labels in the contentMetadata. When this happens, we are mapping the opaque identifier assigned to the resource into the Cocina resource label field in structural metadata. We should not publish these identifiers to the Purl in the label field.

Example: https://argo.stanford.edu/view/druid:bb254jh9333

The contentMetadata for that item has no resource label:

```xml
<contentMetadata objectId="bb254jh9333" type="file">
  <resource id="bb254jh9333_1" sequence="1" type="file">
    <file id="Capacity-Building-With-Small-Groups.pdf" preserve="yes" publish="yes" shelve="yes" mimetype="application/pdf" size="184671">
      <checksum type="md5">966b9444933cfd2fd65d2dc849425f1e</checksum>
      <checksum type="sha1">e7c294ed847bad09d70f01d88418eb83507ea706</checksum>
    </file>
  </resource>
</contentMetadata>
```

The Cocina JSON does have a label:

```json
{"structural": {
        "contains": [
           {
                "type": "http://cocina.sul.stanford.edu/models/resources/file.jsonld",
                "externalIdentifier": "http://cocina.sul.stanford.edu/fileSet/3a924bc7-c983-46bb-b812-d63b23be5f26",
                "label": "http://cocina.sul.stanford.edu/fileSet/3a924bc7-c983-46bb-b812-d63b23be5f26",
                "version": 2,
           }]}}
```

If that opaque label gets published to the contentMetadata on the Purl, it will be displayed alongside the object in the access environments. Currently, the display for that item has no label because we are not mapping the label from Cocina back into the contentMetadata:

<img width="464" alt="Screen Shot 2021-03-30 at 9 39 24 AM" src="https://user-images.githubusercontent.com/8975583/113024644-d81fe900-913b-11eb-88de-693eeea78104.png">

An item with a label looks like this:
<img width="464" alt="Screen Shot 2021-03-30 at 9 40 11 AM" src="https://user-images.githubusercontent.com/8975583/113024767-f8e83e80-913b-11eb-9bfe-2534374a912e.png">

It's preferable to leave the label field blank than to insert the Cocina identifier. 

I thought that labels were required in contentMetadata but clearly that's not the case. Unless we start inserting labels into all contentMetadata that hasn't had labels, we might need to make label optional in Cocina too if it's being required.

**Comment by peetucket** [comment]
This appears to be the part of the FromFedora mapping that adds the external identifier in place of the label if the label doesn't exist:

https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/from_fedora/file_sets.rb#L18-L20

This is done deliberately, so want to be sure it won't cause other problems if we just leave it as blank.

It looks like the label attribute is not optional, trying to sort out if a blank string will violate this constraint: https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/file_set.rb#L29

**Comment by peetucket** [comment]
Naomi had suggested just scrubbing the label when publishing if needed (i.e.  from contentMetadata that is generated for PURL: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_xml_service.rb#L78)

But the implementation above looks like PURL XML is still generated from the datastream from Fedora, which means resources without labels should still end up with no label on PURL.  

This doesn't mean this won't be a problem in the future, but I'm not sure how it's happening now.  @andrewjbtw do you have another example object? Public XML for the object above doesn't have a label in the resource : https://purl.stanford.edu/bb254jh9333.xml

**Comment by peetucket** [comment]
Ahh, ok, so the label is showing in Argo on this object: https://argo.stanford.edu/view/druid:bb254jh9333 

Maybe that is coming from Cocina.

**Comment by peetucket** [comment]
Yes, the label showing in the "Contents" section in Argo is definitely coming from Cocina, though it is not being sent to PURL (at least not now):

https://github.com/sul-dlss/argo/blob/main/app/components/contents/structural_component.html.erb#L2
https://github.com/sul-dlss/argo/blob/main/app/components/contents/resource_component.rb#L22

So:

(1) If our primary concern is display in Argo, it would be easy to suppress display of the label when it is that URI form
(2) When we start generating public XML from cocina, we'd want to filter it there too to prevent it from going to PURL

OR

We need to stop generating it in cocina entirely, though this may require relaxing the constraints and marking it as optional.

**Comment by andrewjbtw** [comment]
I think I understand why the resource label was required in Cocina: it seemed like it was required for all objects in contentMetadata so they already had them. But that turns out not to be true.

The only use of this label that I know of is for display. Depending on the viewer it shows up as:

- a label in a file listing (as in the examples above)
- a caption on an image (showing in the viewer superimposed on the image when the controls are displayed)
- the text of a download link (like "Download Page 1")

I don't see a reason for this label to be unique and if we have thousands of objects that already do not have labels (and apparently we do), I think we should make it optional rather than try to guess at what to call them.

Since we have the externalIdentifier as a separate field, we should be able to use that for management purposes.

**Comment by peetucket** [comment]
Ok, will work on just leaving label off in cocina when it doesn't exist in contentMetadta. I think this should take care of all of the display issues.
