### ISSUE TITLE
Sidekiq UI won't display (dor-services-app and sdr-api)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2638]
from https://app.honeybadger.io/projects/50568/faults/78615180

We get this error info

![image](https://user-images.githubusercontent.com/96775/113345074-cc245a80-92e6-11eb-8513-87bad1d49a24.png)

But it seems like we should be ok?

```
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  mount Sidekiq::Web => '/queues'
...
```

from https://github.com/mperham/sidekiq/blob/master/Changes.md

" Numerous people have hit "Forbidden" errors and struggled with Sidekiq's Web UI session requirement. If you have code in your initializer for Web sessions, it's quite possible it will need to be removed. "

**Comment by jcoyne** [comment]
Take a look at https://github.com/mperham/sidekiq/issues/4850#issuecomment-805964129

**Comment by mjgiarlo** [comment]
See the [updated Sidekiq documentation](https://github.com/mperham/sidekiq/wiki/Monitoring#rails-api-application-session-configuration) on how to render the UI in an API-only application.

**Comment by mjgiarlo** [comment]
@jcoyne @ndushay should this be a high-ish priority FR issue, given how it can be useful to see the UI? If so, we should get this on Vivian's radar.

**Comment by ndushay** [comment]
It's on the production priorities board and I will bring it to her attention at the handoff meeting.

**Comment by andrewjbtw** [comment]
I also endorse this as a priority. The sidekiq UI is useful for understanding what's going on with the non-resque workflow steps, among other things.
