### ISSUE TITLE
Repeated edits to an APO create a lot of XML nodes

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2644]
**Describe the bug**
Repeatedly updating an APO (using https://github.com/sul-dlss/argo/pull/2529) is adding a lot of XML nodes to the administrativeMetadata. 

The administrativeMetadata for https://argo-qa.stanford.edu/view/druid:vr838wn4827 looks like this after many rounds of changed:

```xml
<?xml version="1.0"?>
<administrativeMetadata>
  <dissemination>
    
  </dissemination>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination/>
  <registration/>
  <dissemination>
    <workflow id=""/>
  </dissemination>
  <registration>
    <workflow id="accessionWF"/>
    <workflow id="goobiWF"/>
    <workflow id="registrationWF"/>
    <collection id="druid:ns375cy3379"/>
  </registration>
</administrativeMetadata>
```

**User Impact**
It's kind of a mess but doesn't seem to hurt functionality.

**Comment by jcoyne** [comment]
This involves fixing this todo: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/apo_rights.rb#L15

**Comment by ndushay** [comment]
See https://github.com/sul-dlss/dor-services-app/pull/2677/files#r612116570 -- it may be there's a more appropriate solution to ensure that there is always exactly one dissemination node, which may be empty ...    just not MORE than one.  Diddot for registration nodes
