### ISSUE TITLE
Mapping error: undefined method `merge' for nil:NilClass

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2652]
For druid:nh904dj7473

```
Error: undefined method `merge' for nil:NilClass

Backtrace:
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:53:in `rescue in build'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:39:in `build'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:28:in `build'
bin/validate-cocina-roundtrip:90:in `validate_druid'
bin/validate-cocina-roundtrip:163:in `block in <main>'
```

**Comment by justinlittman** [comment]
The problem is that the CC license ('by-nc-i') is unrecognized: https://github.com/sul-dlss/dor-services/blob/main/lib/dor/services/creative_commons_license_service.rb

**Comment by justinlittman** [comment]
The problem is that the license ('by-nc-i') is unrecognized: https://github.com/sul-dlss/dor-services/blob/main/lib/dor/services/creative_commons_license_service.rb

**Comment by jcoyne** [comment]
by-nc-i is not a cc license. I think they may have used this to mean BY-NC-4.0 ?

**Comment by justinlittman** [comment]
There are 682 items that have the incorrect cc license: https://argo-prod-02.stanford.edu/catalog?all=true&f%5Buse_license_machine_ssi%5D%5B%5D=by-nc-i

To fix:
```
item.rightsMetadata.creative_commons = 'by-nc'
item.rightsMetadata.creative_commons.uri = "https://creativecommons.org/licenses/by-nc/4.0/"
item.save!
```

**Comment by justinlittman** [comment]
Remediation complete.

![image](https://user-images.githubusercontent.com/588335/113925145-aac8e000-97b8-11eb-9f38-16760330bb98.png)
