### ISSUE TITLE
Add ability to set the embargo date for an object

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dor-services-app#2672]
Currently, we can only update an existing embargo which has been set in the datastreams by either hydrus or hydra_etc, we need to be able to set the embargo date of an object through argo in order to remove the need to edit the datastreams.

This should expose an endpoint that will be used through dor-services-client.

**Comment by andrewjbtw** [comment]
We also need to be able to set the rights to be assigned post embargo. The use cases for setting embargo via Argo come primarily from University Archives and Special Collections content, where items can go to Stanford-only or other restricted rights settings when the embargo is lifted. 

This is a recent embargo ticket where one druid went to World and the other to Stanford: https://jirasul.stanford.edu/jira/browse/SDRO-386

**Comment by ndushay** [comment]
@andrewjbtw I may split the second part ("set the rights assigned post embargo") into a separate ticket, if that's ok.

**Comment by ndushay** [comment]
Andrew says "I think ETD embargoes always release to world, but Hydrus may allow you to release to Stanford." -- basically, we've not heretofore had a way to set the rights on release to something in particular. (?)

**Comment by ndushay** [comment]
created ticket for settings rights upon embargo release (2691)

**Comment by ndushay** [comment]
note that Andrew views this work as being tied to 2691.

**Comment by jcoyne** [comment]
Why do we need an endpoint for this? This is part of the object update endpoint.

**Comment by ndushay** [comment]
to add a NEW embargo in Argo.  We can't do that now.

**Comment by jcoyne** [comment]
But we can if we use the update endpoint, right?

**Comment by justinlittman** [comment]
Agree that this shouldn't require a new endpoint. Moving out of ready column to prevent someone from working.

**Comment by ndushay** [comment]
since DSA update endpoint can be used, this is no longer needed.
