### ISSUE TITLE
cocina embargo data not getting to purl.xml  

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2682]
https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/embargo_h2_spec.rb has some lines commented out because the embargo information is NOT getting to the purl.xml when we have native cocina data (or maybe just h2?   but I'm guessing cocina).

The correct info *is* present for hydrus items and is proven by https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/embargo_hydrus_spec.rb.

The problem *may* be related to fedora having the embargo info in both the embargo datastream AND in the rights metadata, while cocina only has this information as part of the access model.

In any case, this needs to be fixed.  You will know you have fixed it when you can uncomment the h2 integration spec lines and the spec passes.

**Comment by ndushay** [comment]
This may benefit from creating roundtrip mapping specs for access data.

**Comment by jcoyne** [comment]
I think this is already fixed but it hasn't been deployed yet.

**Comment by ndushay** [comment]
I'll run the temporary integration test and check.

**Comment by ndushay** [comment]
I will NOW buy, with #2690 added to #2676, that this is addressed.  Because the main branch now passes the hydrus and h2 integration tests that check for this.
