### ISSUE TITLE
Error: undefined method `gsub' for nil:NilClass 

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2695]
On round trip validation for druid:bn222zb9473

**Comment by mjgiarlo** [comment]
@arcadiafalcone This appears to be caused by:

```xml
  <subject>
    <topic>Balkan War</topic>
  </subject>
  <classification authority="ddc" edition="">949.6</classification>
```

The empty `classification@edition` value, specifically. How do you think we should proceed: code changes or data remediation? (Not sure how common data like this is.) If the former, do you know offhand if we have this mapping covered in the specs?

**Comment by arcadiafalcone** [comment]
I don't think it's in the specs, but I can add it. In general empty attributes can be dropped (and I think normalization already removes some of them).

**Comment by mjgiarlo** [comment]
@arcadiafalcone ok, thanks!
