### ISSUE TITLE
Implement updated uniform title mappings

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2699]
https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/name_spec.rb#L909

See #3600 (was #2698)

**Comment by arcadiafalcone** [comment]
Examples: bf818dg3045, zc962tn0888

**Comment by arcadiafalcone** [comment]
The role on the second instance of the name is getting dropped in the Cocina>MODS direction, and should be retained.

**Comment by ndushay** [comment]
There is a problem with the spec as written, in that the roundtrip MODs would NOT be expressed as the same Cocina -- there is no longer a way to know how much of the contributor should be associated with the title, and how much of it should be only associated with the top level contributor.  @arcadiafalcone and I spoke about this and she is pondering how to address it.

**Comment by ndushay** [comment]
#### rf385xq8725

![image](https://user-images.githubusercontent.com/96775/160704695-bf10a6ab-2d97-4556-8327-0eec229c7580.png)

**Comment by ndushay** [comment]
From Arcadia: 

> Could you try something and see its impact on the error rate? Add `status: 'primary'` to the Cocina generated by MODS `<name type="corporate" nameTitleGroup="N">`.

**Comment by ndushay** [comment]
It clearly helps, and it is also clearly insufficient.

![image](https://user-images.githubusercontent.com/96775/160726619-09362638-e5fb-43ea-bcf6-76296a0b5aa9.png)

**Comment by ndushay** [comment]
Still implementing, but progress!

### name-title-groups-2 branch (incomplete implementation)

```
Status (n=500000; not using Missing for success/different/error stats):
  Success:   495460 (99.173%)
  Different: 4073 (0.815%)
  Mapping error:     58 (0.012%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     409 (0.082%)
  Bad cache:     0 (0.0%)
  Validate error:     0 (0.0%)
```

### main branch

```
```

**Comment by arcadiafalcone** [comment]
Normalize specs as needed to follow these rules:
MODS name usage="primary" > Cocina contributor with status: primary, always
MODS name usage="primary" > Cocina name with status: primary, if MODS name has altRepGroup and other name with matching altRepGroup is present
