### ISSUE TITLE
allow real data roundtrip validation of each type of metadata, separately

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2700]
Per meeting today captured (somewhat) in https://docs.google.com/document/d/19NSubyerKKh5pjwkFrzBsUtHFZAlIla91C7h8jwiTnI/edit#:

When we run roundtrip validation on every production fedora object in our cache on sdr-deploy, but only for descriptiveMetadata, it takes ~ 3 hours (or used to).

It would be useful to be able to run roundtrip validation on different types of metadata in our cache singly -- partly to keep processing time down, and partly so we can look at the results independently.

If we're looking at it from the standpoint of fedora datastreams:
- **rightsMetadata.xml**  <-- definitely the priority!
- **embargoMetadata.xml** (only on objects with embargoed content)
- identityMetadata.xml
- RELS-EXT
- roleMetadata.xml (APO and Agreements only)
- defaultObjectRights (APO only)
- administrativeMetadata.xml (APO only)
- contentMetadata
- technicalMetadata

@andrewjbtw should we care about ordering^^, besides doing rights first?  and did I miss any datastreams that show up in some cases ... that we should care about?

Do we care about:
- hydrusProperties (shudder) - hydrus collections and agreements only, perhaps?

We can safely ignore:
- ~~provenanceMetadata~~
- ~~versionMetadata~~
- ~~events~~
- ~~DC~~

---- 
Note that once this is done and we get info like:
- timings on how long it takes to run each one
- current roundtrip error count / percentage success ...
- ???
We may want to set up crons to run specific jobs on a regular basis.  Good to confer with whomever would be responsible for cleaning up / ticketing problems for each type of metadata roundtripping errors.

**Comment by jcoyne** [comment]
@ndushay versionMetadata doesn't get round tripped, as it's external to the cocina, which is the representation for only a single version.

**Comment by ndushay** [comment]
Thanks @jcoyne - that's helpful!

**Comment by ndushay** [comment]
Note that we also want to ensure that agreement objects roundtrip properly.  These are a flavor of DRO in cocina ... but they map to particular "object type" in Fedora (Argo).

**Comment by andrewjbtw** [comment]
@ndushay we shouldn't be doing anything to affect hydrusProperties. Those govern some parts of the hydrus interface and that datastream should go away when hydrus does.

**Comment by ndushay** [comment]
I have made the following tickets for actual data roundtrip validations:

#2777 - for RELS-EXT 
#2779 - for contentMetadata.xml
#2780 - for (APO) defaultObjectRights.xml 
#2784 - for (APO) adminMetadata.xml 
#2783 - for roleMetadata.xml
#2781 - for identityMetadata.xml
#2782 - for embargoMetadata.xml
