### ISSUE TITLE
Fedora rights / Cocina access mappings - symmetrical (unit-ish) specs set up

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2701]
somewhat akin to what we do for MODS mapping roundtrip tests, write rspec shared_examples and a few starter tests to check symmetry of rightsMetadata.xml (fedora) / access (cocina model) mapping code (to and from fedora):

- fedora (A) to cocina (B)
- cocina (B) to roundtrip fedora (C) where C and A should match, or C is explicitly specified as different per approved normalizations (e.g. don't care about useless vestigial attributes in the XML).
- roundtrip fedora (C) to roundtrip cocina (D) where D and B should match.

rightsMetadata.xml is the Fedora datastream, but it may be that the cocina-model access object https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/access.rb gets info from additional places, such as embargoMetadata.xml.

embargoMetadata.xml is also represented in cocina-model access object!

Note that the mappings may be different for APO vs collection vs item, and in other dimensions as well.

This ticket is not to get ALL of the wrinkles in specs;  it's to set up a pattern that can be used for additional rights <--> access specs, as needed.

See https://github.com/sul-dlss/cocina-models/issues/236 for some good examples of problems

**Comment by ndushay** [comment]
tagging @mjgiarlo and @andrewjbtw as they may already have some ideas of 
- what sorts of wrinkles we should eventually test for (which can/will/should be written up as separate tickets, once this one is done) AND 
- what sorts of unimportant differences in roundtripped rightsMetadata.xml and cocina access are okay and should be accommodated with normalization code and/or tolerant specs ...

**Comment by ndushay** [comment]
See https://github.com/sul-dlss/cocina-models/issues/236 for some examples.

**Comment by ndushay** [comment]
Shore up tests after major cocina access rewrite

**Comment by ndushay** [comment]
### Problems/Bugs with IdentityMetadata.xml <--> Cocina::Identification Mapping code

Make issues for each of these?
- [ ] accessCondition element in rightsMetadata  should error/notify?   (https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/access/dro_access_spec.rb#L396)


### Normalizations needed for IdentityMetadata.xml <--> Cocina::Identification Mapping code

- [ ] originating incomplete rights become complete, e.g. https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/access/dro_access_spec.rb#L626
- [ ] issue #2797 - license data changes from 
```xml
            <rightsMetadata>
              <use>
                <human type="openDataCommons">Open Data Commons Attribution License 1.0</human>
                <machine type="openDataCommons">odc-by</machine>
              </use>
            </rightsMetadata>
```

to 

```
              <use>
                <license>http://opendatacommons.org/licenses/by/1.0/</license>
              </use>
```

**Comment by ndushay** [comment]
aside from above, need to adjust shared examples to account for normalization code.

**Comment by ndushay** [comment]
Only remaining thing on this ticket:

there is an accessCondition element in rightsMetadata for bk689jd2364.  What should happen? (https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/access/dro_access_spec.rb#L436) tagging @andrewjbtw

**Comment by andrewjbtw** [comment]
For bk689jd2364 the accessCondition was a license code. I remediated it to be the correct format. When there's an accessCondition element, I think someone will have to investigate. There's no guarantee that will always be a license code that someone entered.

**Comment by ndushay** [comment]
closing this as rightsNormalization has been coded and built into mapping specs, and remaining work is ticketed.
