### ISSUE TITLE
APO roleMetadata.xml needs normalization code

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2708]
PR  #2677 has an xit-ed spec on line 421 that needs:

### copes with empty <name> elements in roleMetadata

for an APO, `roleMetadata.xml` might contain

```xml
          <roleMetadata>
            <role type="hydrus-collection-manager">
              <person>
                <identifier type="sunetid">dhartwig</identifier>
                <name/>
              </person>
              <person>
                <identifier type="sunetid">jschne</identifier>
                <name/>
              </person>
            </role>
```

The empty name elements are meaningless, and we should have "normalization" code, such as we do for MODS/descriptive, to ignore this difference when comparing roundtripped Fedora xml (fedora -> cocina -> roundtripped fedora).

The normalization could/should be executed by bin/(validate-cocina-roundtrip) scripts as appropriate and it should also be executed by spec/services/cocina/mapping/administrative/apo_administrative_spec.rb so the specs compare the actual roundtripped Fedora roleMetadata.xml to the roleMetadata.xml that is normalized by executing said normalization code.

### copes with roles specified by sunetid in roleMetadata

for an APO, `roleMetadata.xml`  might contain

```xml
          <roleMetadata>
            <role type="hydrus-collection-manager">
              <person>
                <identifier type="sunetid">dhartwig</identifier>
                <name/>
              </person>
              <person>
                <identifier type="sunetid">jschne</identifier>
                <name/>
              </person>
            </role>
```

@andrewjbtw  - DO we need to support person/sunetid as a means of indicating who is allowed access, or are we only using LDAP groups now?

if we DO need to support it, 

The normalization could/should be executed by bin/(validate-cocina-roundtrip) scripts as appropriate and it should also be executed by spec/services/cocina/mapping/administrative/apo_administrative_spec.rb so the specs compare the actual roundtripped Fedora roleMetadata.xml to the roleMetadata.xml that is normalized by executing said normalization code.

**Comment by andrewjbtw** [comment]
We have to support sunetid as long as Hydrus exists, at least. That's a peculiar class of roleMetadata, where it's on non-APO objects.

For APOs, I'm not sure. I think that needs data analysis to see what sunets are actually authorized. The Argo form doesn't support entering sunets. Those were typed in when the datastream was editable.

**Comment by ndushay** [comment]
@andrewjbtw so which objects besides APOs get `roleMetadata.xml`

**Comment by andrewjbtw** [comment]
Hydrus-managed items. Hydrus collections don't appear to have roleMetadata.

**Comment by justinlittman** [comment]
closing in favor of #3126
