### ISSUE TITLE
Implement extent unit mapping

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2731]
https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/physical_description_spec.rb#L535

See #2730

**Comment by arcadiafalcone** [comment]
Relevant test is "Extent with unit and note sibling" in physical_description_spec.

**Comment by lwrubel** [comment]
@arcadiafalcone: we've added logic for handling a single sibling note element when there is an extent with a unit attribute in physicalDescription. Does that fully cover the scenario or might there be times when there are multiple notes (or anything else to consider)?

**Comment by arcadiafalcone** [comment]
@lwrubel It's possible for `<extent>` to be repeated with different units, such as for an archival collection containing both analog and digital content, so it would be good to account for that use case.

**Comment by lwrubel** [comment]
Thanks, @arcadiafalcone. Would you happen to be able to point me to an example druid that has multiple extent elements?

**Comment by arcadiafalcone** [comment]
@lwrubel Druid for you: bh920np8004
