### ISSUE TITLE
Implement subject/name with additional subelements and subject/name without name type (Cocina>MODS)

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2733]
* https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb#L736

Note that the below is the first of 3 specs that are related to each other, and not entirely related to the above.

* https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb#L1142

See #2732

**Comment by arcadiafalcone** [comment]
Cocina>MODS only.

**Comment by lwrubel** [comment]
Parking some questions here for Arcadia for when we talk through them:
- The subject metadata in this example has a parallelValue nested inside a structuredValue. I'd like to make sure I understand the characteristics of this record that mean that kind of mapping is used. I see that parallelValue is used for multiple representations of the same information--I think this is something other than different languages though. 
- Should we anticipate records with further level of nesting? Or multiple parallelValues?
- Have we handled parallelValues in other mapping so far? Wondering if there are approaches we could re-use.

**Comment by lwrubel** [comment]
@arcadiafalcone is there an example druid for this spec: https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb#L1142

**Comment by lwrubel** [comment]
I think the spec at [L1142](https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb#L1142) (and possibly the others below) will be easier to implement once #2794 is addressed since the warning mentioned in that issue is currently getting triggered.

**Comment by lwrubel** [comment]
@arcadiafalcone in the spec for [Name subject without name type and subdivisions](https://github.com/sul-dlss/dor-services-app/blob/6927d139578a7f99ed5e20b0ea7666dcb8c3d33a/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb#L1204), I see that in the expected cocina there is a form alongside subject, duplicating the genre in the subject. What in the MODS should cause that additional form element to be created?

**Comment by arcadiafalcone** [comment]
The form element is generated when the MODS has a subject with a genre subdivision. The genre remains part of the subject and also goes into form.

**Comment by lwrubel** [comment]
Thanks, @arcadiafalcone. I'm trying to understand how this is example is different from (Name-title subject with additional terms including genre subdivision, authority for set)[https://github.com/sul-dlss/dor-services-app/blob/6927d139578a7f99ed5e20b0ea7666dcb8c3d33a/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb#L581] and (Name-title subject with additional terms including genre subdivision, authority for terms)[https://github.com/sul-dlss/dor-services-app/blob/6927d139578a7f99ed5e20b0ea7666dcb8c3d33a/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb#L629]? It may be I am not understanding subdivisions in these examples.

**Comment by arcadiafalcone** [comment]
Thanks for bringing this to my attention - I dug through the issue history and realized that while we had started out mapping subject/genre to form, we later changed the mappings to not do that. The mapping at https://github.com/sul-dlss/dor-services-app/blob/6927d139578a7f99ed5e20b0ea7666dcb8c3d33a/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb#L1204 must have been missed when that change was made. To bring that mapping spec into line with current practice, you can delete the `:roundtrip_mods` stanza and remove the `form` element from the `:cocina`.

**Comment by lwrubel** [comment]
Thanks, @arcadiafalcone, that helped me move forward and that change (with the others in the second half of this issue) is now merged.
