### ISSUE TITLE
Implement mapping for name with multiple roles

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2738]
See #2737

**Comment by jcoyne** [comment]
@arcadiafalcone is it correct that this "primary" usage never makes it into the cocina model? https://github.com/sul-dlss/dor-services-app/pull/2737/files#diff-e2d8e22538aea0f6f69ac7fdea08c8e2e063905a52c29ace935a28c425f239b3R296

**Comment by arcadiafalcone** [comment]
No, `usage: 'primary'` should be present twice, once as a sibling of the first `name` and once as a sibling of `parallelContributor`.

**Comment by arcadiafalcone** [comment]
Appears to be working.
