### ISSUE TITLE
Review COCINA mappings for H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/dor-services-app#2742]
Creating this ticket as requested by Arcadia in an email thread, which is recreated below.

_______________________________
From Arcadia:
Thanks for sharing this feedback. The format terms provided in H2 are mapped to additional terms from shared controlled vocabularies with the intent of improving discovery, as other resources in SearchWorks use terms from these same vocabularies. In creating these mappings we made some assumptions about the types of resources likely to be associated with particular H2 formats which I am happy to revisit and revise as needed. Amy, if you create a ticket to review the mappings and assign it to me I can go through them with an eye towards interrogating some of those assumptions more strictly.

_______________________________
Hi Arcadia,
 
We got the feedback below from Leah Strauss, a SERG staff member who is doing some beta testing on H2 for us.
 
Her notes below refer to this PURL: https://sul-purl-stage.stanford.edu/gq687jh4538 and concern the mappings of the item types and subtypes to typeOfResource and Genre terms.
 
I’d appreciate if you could review this to see if there is anything amiss in the mappings to the MODS (or possibly more likely, the COCINA mappings) that needs to be ticketed.
 
Thanks,
 
~ Amy

_______________________________

Amy and Hannah:
 
Just a couple of notes about the process after receiving the automatic reply from SDR about my deposit. 
 
1. The resource type seems to have defaulted to include "software, multimedia" - maybe because I ticked the button for "data?"  (My text report includes sociological - ethnographic data in tabular format.  So I suppose it can be construed as a "dataset.")
 
TYPE OF RESOURCE
Text

Software, multimedia

2. Some of the resulting genre descriptive terms are, unfortunately not apt. Technical manuals (and possibly datasets, data set) doesn't  apply.  How would I, as a depositor, be able to correct this - or whom would I notify to request a change be made?  Would it make sense to include this in the automated email response to the depositor?
 
Here is the genre list:
Text
Report
Data
Documentation
Ethnography
Reports
Data sets
Dataset
Technical manuals
Ethnographies3.

**Comment by arcadiafalcone** [comment]
Moved to https://github.com/sul-dlss/happy-heron/issues/1392.
