### ISSUE TITLE
Mapping to cocina drops html tags from use and reproduction statement

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2752]
For example, for druid:pp562fx0548's rights metadata DS:

```
-  <use>
-    <human type="useAndReproduction">Property rights reside with the repository. Literary rights reside with the creators of the documents or their heirs. To obtain permission to publish or reproduce, please contact the Special Collections Public Services Librarian at <a href="mailto:speccollref@stanford.edu">speccollref@stanford.edu</a>.</human>
-  </use>
```

is mapped to:
```
{
  "useAndReproductionStatement": "Property rights reside with the repository. Literary rights reside with the creators of the documents or their heirs. To obtain permission to publish or reproduce, please contact the Special Collections Public Services Librarian at speccollref@stanford.edu."
}

```

**Comment by justinlittman** [comment]
@andrewjbtw Should the HTML be retained or dropped?

Note that it is currently being normalized out, so if retaining then this normalization must be removed. See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/normalizers/rights_normalizer.rb#L65

**Comment by jcoyne** [comment]
I'd prefer we normalize this out because we don't want to say that the users of this data need to understand html.  Since anyone at stanford can create SDR content that is displayed on PURL, we should not permit html from the data to be displayed on the page (or `<h1 style="font-color:pink">I could cause problems</h1>`).

**Comment by andrewjbtw** [comment]
I'm tagging @arcadiafalcone because I'm not sure what the current policy is on encoding tags in MODS. I think we have a rule that can make links without using html tags, possibly an automatic conversion of email address or URLs based on structure.

**Comment by arcadiafalcone** [comment]
We have done selected stripping of html tags at the display stage, but recently determined to allow italics tags in data (see https://github.com/sul-dlss/mods_display/issues/77 and https://github.com/sul-dlss/exhibits/issues/1981).

We do convert URLs (I think only in certain fields) and emails to clickable links at display -- see e.g. tv381bm6115, which doesn't have the html in the source data but does add the tags for display. Possibly this happens here: https://github.com/sul-dlss/mods_display/blob/9ef99027580da98148a9db69ca914071a2c5b78d/app/helpers/mods_display/record_helper.rb#L76.

**Comment by justinlittman** [comment]
Unless I hear otherwise, we will continue to remove html tags from the use and reproduction statement.
