### ISSUE TITLE
file-level externalIdentifier gets new unique id every time a change is made even if the file is never changed

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2768]
I noticed this when cycling through rights settings. The file-level `externalIdentifier` gets repeatedly changed each time the rights are changed, even though no change is being made to the files. 

**To reproduce**

1. Go to https://argo-stage.stanford.edu/view/druid:zy016kn1469

2. Look at the structural metadata for the files:

```json
{
              "type": "http://cocina.sul.stanford.edu/models/file.jsonld",
              "externalIdentifier": "http://cocina.sul.stanford.edu/file/fb85ee0e-15d1-4eee-8b30-8fe867c8a285",
              "label": "placeholder.jp2",
              "filename": "placeholder.jp2",
...
}
```

3. Change the rights for the object
4. Look again at the structural metadata:

```json
 {
              "type": "http://cocina.sul.stanford.edu/models/file.jsonld",
              "externalIdentifier": "http://cocina.sul.stanford.edu/file/5320fe7d-abf7-40d6-ab38-8f3e464eb5bb",
              "label": "placeholder.jp2",
              "filename": "placeholder.jp2",
...
}
```
5. See that the `externalIdentifier` started as 
`http://cocina.sul.stanford.edu/file/fb85ee0e-15d1-4eee-8b30-8fe867c8a285`
and is now
`http://cocina.sul.stanford.edu/file/5320fe7d-abf7-40d6-ab38-8f3e464eb5bb`

I'm not sure what the purpose of this identifier is but it seems like it should be stable across versions.

**Comment by andrewjbtw** [comment]
Or is this happening because we're not persisting cocina yet?

**Comment by justinlittman** [comment]
You're exactly right -- it is happening because we are not persisting cocina yet. Once we do, the identifier will be stable.
