### ISSUE TITLE
roundtrip of roleMetadata.xml in our actual data

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2783]
outgrowth of #2148

Andrew would like to be able to see roundtrip validations (like we do for descriptiveMetadata and rightsMetadata) for roleMetadata.xml for our Fedora objects.

Not sure objects other than APOs have roleMetadata, but our data is probably dirty, so 🤷‍♀️  (e.g. maybe agreements???  collections????)

See #2751 for how this was done for rightsMetadata.   Also, ensure roleMetadata is in our cache on sdr-deploy (see #2749) so we can test against it.

<hr>
Note that once this is done and we get info like:

- timings on how long it takes to run each one
- current roundtrip error count / percentage success ...
- ???

then we may want to set up crons to run specific jobs on a regular basis. Good to confer with whomever would be responsible for cleaning up / ticketing problems for each type of metadata roundtripping errors.

**Comment by justinlittman** [comment]
`validate-cocina-roundtrip` currently roundtrips role metadata, so I don't think any further action is necessary.
