### ISSUE TITLE
Don't warn for missing name type when name value not present

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2794]

**Comment by justinlittman** [comment]
@arcadiafalcone Can you point to an HB alert or spec for this? (It isn't clear which warning you would like removed.)

**Comment by arcadiafalcone** [comment]
@justinlittman 

"Missing or empty name type attribute" notification in https://github.com/sul-dlss/dor-services-app/blob/2fd1b684b00612a1be969f2166b40e876b1a71f5/app/services/cocina/from_fedora/descriptive/contributor.rb and https://github.com/sul-dlss/dor-services-app/blob/a0b852540c0d9333ccbbfe92b0d72ab850a7e4dd/spec/services/cocina/mapping/descriptive/mods/name_spec.rb

"Subject contains a <name> element without a type attribute" notification in https://github.com/sul-dlss/dor-services-app/blob/2ac9d78e999eb9a738a8c887d0b6e2f0ce726730/spec/services/cocina/from_fedora/descriptive/subject_name_spec.rb and https://github.com/sul-dlss/dor-services-app/blob/e4083babdc0962525ae2eb265bcdc0a66832c516/app/services/cocina/from_fedora/descriptive/subject.rb
