### ISSUE TITLE
Remove geoData in content metadata in normalization

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#2802]
For druid:cc377hs8114:

```
Original XML for contentMetadata:
<?xml version="1.0"?>
<contentMetadata objectId="cc377hs8114" type="geo">
  <resource id="cc377hs8114_1" sequence="1" type="object">
    <label>Data</label>
    <file preserve="yes" shelve="yes" publish="yes" id="data.zip" mimetype="application/zip" size="1216894" role="master">
      <geoData>
        <rdf:Description xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:about="http://purl.stanford.edu/cc377hs8114">
          <dc:format xmlns:dc="http://purl.org/dc/elements/1.1/">application/x-esri-shapefile; format=Shapefile</dc:format>
          <dc:type xmlns:dc="http://purl.org/dc/elements/1.1/">Dataset#LineString</dc:type>
          <gml:boundedBy xmlns:gml="http://www.opengis.net/gml/3.2/">
            <gml:Envelope gml:srsName="EPSG:4326">
              <gml:lowerCorner>2.591614 4.547012</gml:lowerCorner>
              <gml:upperCorner>13.628449 13.74575</gml:upperCorner>
            </gml:Envelope>
          </gml:boundedBy>
          <dc:coverage xmlns:dc="http://purl.org/dc/elements/1.1/" rdf:resource="" dc:language="eng" dc:title="Nigeria"/>
        </rdf:Description>
      </geoData>
      <checksum type="sha1">ae052966c362af7bcfec55a9ac2f2c4fdef21738</checksum>
      <checksum type="md5">3e620e897533e7aee47a8b2f3dec7523</checksum>
    </file>
    <file preserve="no" shelve="yes" publish="yes" id="data_EPSG_4326.zip" mimetype="application/zip" size="1216232" role="derivative">
      <geoData srsName="EPSG:4326"/>
      <checksum type="sha1">ea57ad73eab8b51f848ef53be73a2f9e6a63b2ca</checksum>
      <checksum type="md5">6917a0345c5fc5d24c213994fcaadd44</checksum>
    </file>
  </resource>
  <resource id="cc377hs8114_2" sequence="2" type="preview">
    <label>Preview</label>
    <file preserve="yes" shelve="yes" publish="yes" id="preview.jpg" mimetype="image/jpeg" size="5954" role="master">
      <checksum type="sha1">69054c3a2f650fcc70e30f5cf5d96372b715b34c</checksum>
      <checksum type="md5">e2df985a2be01d7e685d3c485ac76873</checksum>
      <imageData width="200" height="133"/>
    </file>
  </resource>
</contentMetadata>
```

```
Roundtripped XML for contentMetadata:
<?xml version="1.0"?>
<contentMetadata objectId="druid:cc377hs8114" type="geo">
  <resource id="http://cocina.sul.stanford.edu/fileSet/0dcbdd52-73c1-4f7f-8a68-9a0aa7092e6d" sequence="1" type="object">
    <label>Data</label>
    <file id="data.zip" mimetype="application/zip" size="1216894" publish="yes" shelve="yes" preserve="yes" role="master">
      <checksum type="sha1">ae052966c362af7bcfec55a9ac2f2c4fdef21738</checksum>
      <checksum type="md5">3e620e897533e7aee47a8b2f3dec7523</checksum>
    </file>
    <file id="data_EPSG_4326.zip" mimetype="application/zip" size="1216232" publish="yes" shelve="yes" preserve="no" role="derivative">
      <checksum type="sha1">ea57ad73eab8b51f848ef53be73a2f9e6a63b2ca</checksum>
      <checksum type="md5">6917a0345c5fc5d24c213994fcaadd44</checksum>
    </file>
  </resource>
  <resource id="http://cocina.sul.stanford.edu/fileSet/94c8d5e8-af35-4c09-86e4-e8379c7d47d1" sequence="2" type="preview">
    <label>Preview</label>
    <file id="preview.jpg" mimetype="image/jpeg" size="5954" publish="yes" shelve="yes" preserve="yes" role="master">
      <checksum type="sha1">69054c3a2f650fcc70e30f5cf5d96372b715b34c</checksum>
      <checksum type="md5">e2df985a2be01d7e685d3c485ac76873</checksum>
      <imageData height="133" width="200"/>
    </file>
  </resource>
</contentMetadata>
```

Per discussion below, when geoData is mapped from cocina to MODS, use that same geoData in the content metadata.

**Comment by justinlittman** [comment]
Revisit this after https://github.com/sul-dlss/dor-services-app/issues/3113

**Comment by jcoyne** [comment]
This is created in:
https://github.com/sul-dlss/gis-robot-suite/blob/6d0802f2d68b1613339303dd8fb41c2d082153dc/lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb#L84

**Comment by justinlittman** [comment]
@andrewjbtw Does this geoData need to be modeled in cocina? If so, can it be stored as a text chunk?

**Comment by jcoyne** [comment]
Why do we collect this data?  I'm pretty sure it isn't presented anywhere.

**Comment by andrewjbtw** [comment]
I know nothing about geoData and its place in the model.

**Comment by justinlittman** [comment]
Oh, it is just duplicated from the MODS: https://github.com/sul-dlss/gis-robot-suite/blob/6d0802f2d68b1613339303dd8fb41c2d082153dc/lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb#L146

**Comment by justinlittman** [comment]
That leaves 2 approaches:
1. If the geoData in content metadata is redundant and not used, then it can be dropped from content metadata. This means that (1) when mapping from fedora to cocina, it would be mapped from the MODS to cocina, but not content metadata to cocina; (2) when mapping from cocina to fedora, it would be mapped from cocina to MODS, but not to content metadata; and (3) when roundtripping, it would be removed from content metadata as part of normalization.
2. If the geoData in content metadata is necessary, then it can be copied mapped both to MODS and content metadata. This means that (1) when mapping from fedora to cocina, it would be mapped from the MODS to cocina (the copy in content metadata would be ignored); (2) when mapping from cocina to fedora, it would be mapped from cocina to MODS and content metadata (using the same mapping).

**Comment by andrewjbtw** [comment]
Now that I'm not heading out the door for winter closure, and actually thinking about it more clearly, I still don't know how geometadata is used ultimately, but I would expect it to be used in sul-embed and in Earthworks. I think the Access team would be in the best position to answer. It's possible things have been implemented in a way that both the MODS and the contentMetadata representations are used but by different systems.

**Comment by justinlittman** [comment]
OK, then I would suggest the more conservative approach 2.

**Comment by ndushay** [comment]
use mapping from desc metadata for content metadata

**Comment by aaron-collier** [comment]
Complicating this issue, https://argo.stanford.edu/view/druid:bb008zm4587 includes the geoData in the `descMetadata` but does not include it at the content metadata file level as we see in the druid referenced above.

Can we determine if maintaining the data at the file level makes sense for roundtripping?

**Comment by ndushay** [comment]
Further - can we determine what is actually needed by downstream consumers?   Earthworks ... and any others?

**Comment by justinlittman** [comment]
Further complication: https://argo.stanford.edu/view/druid:bb033gt0615, which has different geoMetadata in multiple files in the content metadata.

**Comment by justinlittman** [comment]
Per Kim:
```
In short, no we don't use the geoData elements anymore. These elements were created during a time when we could not control how coordinates were structured within MODS metadata (descMetadata). In order to create valid bounding boxes for EarthWorks objects, Darren added these elements to structure the metadata. I'm not sure why the geoData elements appear in the contentMetadata stream.

We used to use the gisDiscoveryWF to create GeoBlacklight metadata from MODS and those geoData elements were used to generate the coordinates. However, since we started using the releaseWF for EarthWorks, I believe this metadata is mapped from the subject/coordinates element, and not the geoData.

We have an XSLT that creates the MODS from the ISO19139.
https://github.com/sul-dlss/gis-robot-suite/blob/main/lib/xslt/iso2mods.xsl
```

Action for this ticket: Remove geo data in content metadata in normalization.
