### ISSUE TITLE
Data Validation: Source_id is required when registering

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#281]
When I register and don't submit a source_id it should return a 400 bad request.

Additionally source_id must be unique (within its namespace)

**Comment by andrewjbtw** [comment]
@jcoyne will investigate

**Comment by jcoyne** [comment]
Blocked by https://github.com/sul-dlss/dor-services-app/issues/852

**Comment by jcoyne** [comment]
Fixed by #879
