### ISSUE TITLE
Handle <accessCondition> in identityMetadata

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2831]
This is an obsolete element and human intervention is needed to know what to do with it.

We have examples of throwing bad data notifications for MODS mapping errors;   not sure if this is the first one for non-MODS ... perhaps consult with Andrew and/or Arcadia to see if there is a particular tag, format or starting string to be used in Honeybadger, and confirm it should be a notification (and not an error)

**Comment by justinlittman** [comment]
Initial action for this ticket is to write a report looking for <accessCondition> in identity metadata.

**Comment by edsu** [comment]
@ndushay @justinlittman does it make sense that the report I added would yield no results running over the full list of druids in `/opt/app/deploy/dor-services-app/druids.txt` on `sdr-deploy`?

**Comment by ndushay** [comment]
@andrewjbtw @arcadiafalcone do you know of any existing records with accessCondition in the identitMetadata?   I no longer recall the context in which I wrote this ticket.

**Comment by edsu** [comment]
Could it be that [accessCondition](https://www.loc.gov/standards/mods/userguide/accesscondition.html) is in the MODS descriptive metadata?

**Comment by justinlittman** [comment]
I believe that we already handle accessCondition in MODS.

If Ed didn't find any records and Arcadia and Andrew aren't aware of any examples, then we can close this ticket. If there is a problem, it will appear in roundtrip testing.

**Comment by andrewjbtw** [comment]
accessCondition is most likely to appear in either MODS, in rightsMetadata, or in the defaultObjectRights. It shouldn't be in rightsMetadata or defaultObjectRights, so will have to be remediated in those places, but I wouldn't expect it to be in identityMetadata. So I think this can be closed.

**Comment by edsu** [comment]
Thanks for the quick feedback. I will close this ticket and remove my branch.
