### ISSUE TITLE
identityMetadata mapping report: dissertationId  

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2832]
should otherId of type disssertationId be retained in identityMetadata in cocina when there is a separate sourceID that is not a dissertationId ?

Many example specs of records with dissertationIds in https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/identification/dro_identity_spec.rb but I think they may all be examples WITHOUT sourceId, so we would want to add another spec for a record that DOES have a sourceId as well as an otherId of type dissertationId.

**Comment by justinlittman** [comment]
@ndushay Are there any examples of this?

**Comment by ndushay** [comment]
I think we want a report for this.

**Comment by justinlittman** [comment]
Can you describe the criteria for the report? (I'm not clear what a "separate sourceID that is not a dissertationId" is.)

**Comment by ndushay** [comment]
Look at  https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/identification/dro_identity_spec.rb#L655;  that is an "otherId" with type dissertationId.   And see if there are records with them that have a "sourceId" that is not of type "dissertationId" 

That is what I'm talking about, AFAICR.

**Comment by justinlittman** [comment]
Some more context: Currently, for a dissertation, the sourceId is the dissertation id (from the registrar). However, there may be some legacy dissertations where the sourceId is not the dissertation id.

For the report, please identify items where there is an otherId with name="dissertationId", but the sourceId does not have name="dissertationId".

Once this report is complete, @andrewjbtw can determine how/if to remediate/address. It is essential that the dissertation id be retained in mapping.

```
<sourceId source="googlebooks">stanford_36105010362304</sourceId>
```

```
<otherId name="dissertationid">0000000296</otherId>
```

**Comment by lwrubel** [comment]
Some older dissertations may have no sourceId at all:

```
<?xml version="1.0"?>
<identityMetadata>
  <objectId>druid:bb132pr2055</objectId>
  <objectType>item</objectType>
  <objectLabel/>
  <objectCreator>DOR</objectCreator>
  <citationTitle/>
  <citationCreator/>
  <otherId name="dissertationid">0000004039</otherId>
  <otherId name="catkey">11347509</otherId>
  <otherId name="uuid">a1494258-2fa5-11e5-9247-0050569b52d5</otherId>
  <agreementId>druid:ct692vv3660</agreementId>
  <objectAdminClass>ETDs</objectAdminClass>
  <tag>ETD : Dissertation</tag>
  <tag>Remediated By : 4.21.2</tag>
  <release to="Searchworks" what="self" when="2016-11-22T19:17:57Z" who="blalbrit">true</release>
  <release to="Searchworks" what="self" when="2016-11-22T21:30:52Z" who="blalbrit">true</release>
  <release to="Searchworks" what="self" when="2016-11-22T23:26:06Z" who="blalbrit">true</release>
  <release to="Searchworks" what="self" when="2017-02-07T06:24:21Z" who="blalbrit">true</release>
</identityMetadata>
```

Are those to be included in this report, or only those that have a sourceId to begin with?

**Comment by justinlittman** [comment]
If there is no sourceId it should not be included in the report. (In that case, we treat the otherId[@name="dissertationid"] as the sourceId.)

Also, sourceId's have a "source" attribute, not a "name" attribute.

**Comment by lwrubel** [comment]
Thanks, looking again at current ETDs, I see that the sourceId's source attribute has a value of "dissertation" rather than "dissertationId". For [example](https://argo.stanford.edu/view/druid:bd412rv0997): `<sourceId source="dissertation">0000008745</sourceId>`. 

So I'm creating the report to look for those records with `<otherId name="dissertationid">`, and that have a `sourceId[@source]` that has a value that's not "dissertation" (rather than "dissertationId". Let me know if I'm misunderstanding something, since the thread talks about source="dissertationId".

**Comment by lwrubel** [comment]
One record was found: https://argo.stanford.edu/view/druid:wn922bm5946

druid,apo,catkey,message
druid:wn922bm5946,druid:bx911tp9024,13333114,v

**Comment by justinlittman** [comment]
I've remediated that one item.
