### ISSUE TITLE
object has 2 catkeys in identityMetadata.xml

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2833]
if a Fedora item has 2 catkeys in identityMetadata.xml - what should the code do? (zw844wz5427 - it's an old ETD)

This is also an xit-ed spec  in https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/identification/dro_identity_spec.rb#L590  so we can ensure our code does the appropriate thing.

**Comment by jcoyne** [comment]
I wonder if this is a rare enough case that it wouldn't be worth writing code to handle this.

**Comment by andrewjbtw** [comment]
I'm checking with metadata on this one. It's probably only supposed to have one catkey.

**Comment by andrewjbtw** [comment]
If this is the only item with two catkeys and it's really supposed to have one, maybe we should limit the field to one and notify if something has more than one. If there's an identified need for multi-catkey support we could revisit.

**Comment by justinlittman** [comment]
Initial action for this ticket: Write a report looking for 2 catkeys in identity metadata.

```
<otherId name="catkey">8652337</otherId>
```

**Comment by edsu** [comment]
There's no need to also look in [<descMd>](https://consul.stanford.edu/display/chimera/Identity+metadata+--+the+identityMetadata+datastream) too right?

**Comment by edsu** [comment]
I ran my report on sdr-deploy using `/opt/app/deploy/dor-services-app/druids.txt` and it found 3,496 identity datastreams with more than one catkey. They are attached here. I spot checked 5 of them in Argo and noticed that the catkey values were the same. 

[identity-multi_catkeys.csv](https://github.com/sul-dlss/dor-services-app/files/7916672/identity-multi_catkeys.csv)

**Comment by justinlittman** [comment]
@edsu Can you modify to look for cases in which the catkey values were different?

**Comment by justinlittman** [comment]
Based on what you have found so far, will want to write a test for multiple identical catkeys.

**Comment by edsu** [comment]
I adapted the report to look for multiple catkeys where the catkeys are different. It found 670 when run against the full list of druids. 

[identity-multi_catkeys.csv](https://github.com/sul-dlss/dor-services-app/files/7925601/identity-multi_catkeys.csv)

Does writing a test mean adding to `spec/services/cocina/normalizers/identity_normalizer_spec.rb` to ensure that multiple identical catkeys are flattened? And then modifying the normalizer?

What should happen in cases where there are different catkeys?

**Comment by edsu** [comment]
In ec44fe2379c5b21facaea7adcdc423a2ac401c4b I added a test and a small change to the identity normalizer to flatten duplicate catkeys.

**Comment by justinlittman** [comment]
Normalizer change and test looks good.

**Comment by edsu** [comment]
Do we need to worry about multiple catkeys with different values as part of this issue?

**Comment by arcadiafalcone** [comment]
There are definitely some cases where having two catkeys is intentional - I'll investigate further.

**Comment by edsu** [comment]
Ok, so I'll ignore the different catkeys, thanks @arcadiafalcone!

**Comment by justinlittman** [comment]
@arcadiafalcone So is the correct action to retain both catkeys in the same order?

The cocina would look like:
```
identification: {
            sourceId: 'dissertationid:0000000296',
            catalogLinks: [
              {
                catalog: 'symphony',
                catalogRecordId: "12345"
              },
              {
                catalog: 'symphony',
                catalogRecordId: "67890"
              }
            ]
          }
```

**Comment by arcadiafalcone** [comment]
Yes, retain both in the same order.
