### ISSUE TITLE
Accept barcode prefix 245 (for Lane Medical Library books) and correctly index

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2851]
Books from the Lane Medical Library use the barcode prefix "245". This is not yet on our validation list, so adding this barcode to an object triggers a validation failure.

See: https://app.honeybadger.io/projects/50568/faults/78631512/01F62WYBJX9TM9B93J0X0XHGKA?page=0

Example druid: https://argo.stanford.edu/view/druid:wc042cz6208 (I've removed the barcode line for now)

**Comment by peetucket** [comment]
reopening...still need to bump cocina-model gem and do deploys.

**Comment by peetucket** [comment]
@andrewjbtw : the validation has been updated to accept lane barcodes and deployed to qa and stage...is there an easy way to validate this before deploying to production?

**Comment by andrewjbtw** [comment]
@peetucket I added a Lane barcode to this item on stage https://argo-stage.stanford.edu/view/druid:bc229sx2775 Something is wrong because even though the Cocina model seems ok (no validation error), the show page display is missing a bunch of indexed data (the actual title isn't there) and it's not showing the right number of blue buttons. If you switch the barcode to a Green one, the display goes back to normal.

**Comment by peetucket** [comment]
Ok, i'll reopen.  I'm not sure what's going on, maybe there is some attempt to look up metadata using that barcode that is failing because we can't get metadata from Lane.  This might be causing an issue with indexing?

**Comment by andrewjbtw** [comment]
That could be it. There's a SW record for the book, but it doesn't appear to have the barcode in it: https://searchworks.stanford.edu/view/10906003 I guess the digitization lab must have gotten it from the physical volume. It does make me wonder what data is being checked via checking the barcode since the description is tied to the catkey.

**Comment by peetucket** [comment]
The cocina model view in argo seems ok at quick glance, but the solr document view certainly doesn't look complete: https://argo-stage.stanford.edu/view/druid:bc229sx2775.json

I don't see any exceptions in HB though.

**Comment by peetucket** [comment]
The problem with indexing may have been due to mismatch in cocina-models.  I re-deployed the indexing app and re-indexed and the title is there now.  https://argo-stage.stanford.edu/view/druid:bc229sx2775

**Comment by peetucket** [comment]
I think this may have been fixed by the updates to cocina-models in dor-indexing-app and other apps.  I will re-close unless it turns out to be a problem.
