### ISSUE TITLE
Implement updated type mappings for H2 in DSA and in H2

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2869]
- [x] DSA spec (Arcadia) - See PR #2847 
- [x] DSA roundtrips per spec - See PR #2967
- [x] H2 spec in sync (Arcadia) - See PR https://github.com/sul-dlss/happy-heron/pull/1864
- [x] H2 produces correct cocina - See PR https://github.com/sul-dlss/happy-heron/pull/1869
- [ ] roundtrip tested w Amy & Arcadia (H2 does deposit, Argo metadata in sync w H2, no HB errors)

**Comment by ndushay** [comment]
closing this as Amy and Arcadia have signed off on the testing.
