### ISSUE TITLE
Do not add human/machine tags to public XML rightsMetadata for CC 4.0 URLs

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#2880]
For backwards compatibility, we are publishing CC 3.0 and ODC licenses to Purl with the legacy human/machine tags in the rightsMetadata. Doing this means the Purl retains its previous display for these licenses, including a badge, link, and license description.

For previously unsupported CC 4.0 licenses, we do not want this behavior, as the legacy behavior is only capable of displaying the 3.0 badge/text/description. Instead, we should not publish human/machine nodes for these items. This will result in the new and correct license descriptions being published to the Purl (in the MODS).

**Comment by jcoyne** [comment]
@andrewjbtw do you think we still need to continue adding the legacy human/machine tags for the 3.0 and ODC licenses too, or can we remove all of them?

**Comment by andrewjbtw** [comment]
I think we'd be ok with leaving them alone at publish. So if they exist, publish doesn't strip them out. But if they don't exist, publish doesn't add them. I'm going to re-raise the question of removing them entirely (from Fedora) for the license check-in meeting on July 7.

**Comment by mjgiarlo** [comment]
The decision we wrote up in our notes from last week leaves this a bit vague. We said:

> We do not need machine/human license use statements for licenses other than CC3 & ODC.

There are two ways to read this:

1. Do not add machine/human license use statements to rights metadata for licenses other than CC3 & ODC.
    * In which case, #2881 is A-OK.
2. Retain machine/human license use statements in rights metadata only for CC3 & ODC licenses.
    * In which case, #2881 is less in keeping with the decision. (It's not clear to me how far down the road of retaining current behavior w/r/t CC3/ODC licenses the `original.clone` line gets us...)

**Comment by andrewjbtw** [comment]
As we discussed in the meeting, there isn't consistency in the existing data. Adding or removing human/machine statements during publish is a significant change that makes the connection between the public XML and the stored data less transparent.

These statements have been stored in Fedora and past practice has been to publish whatever is in Fedora. If the statements are both missing and necessary, then they should be remediated in Fedora for the relevant object.

It doesn't sound like the final form of the license metadata has been settled. I'm not clear at this point which apps still need the backwards compatibility if:

- purl can read from the public MODS
- Earthworks can read from the public MODS
- sul-embed can read from the public MODS
- we have agreed upon display text for the all licenses in the public MODS

But as long as we're maintaining backwards compatibility we're running a system with multiple tiers of license displays:

- ODC and CC 3.0 licenses will never display the new text
- non-ODC and non-CC 3.0 licenses will display the new and approved text

This does not seem like a sustainable situation. So if we're going to meet in a few weeks to reassess then I'd prefer to take the path of least change for now, and that path is to not insert or remove anything from rightsMetadata when an item is published.

**Comment by mjgiarlo** [comment]
Agree the current situation is not optimal or sustainable for the medium- or long-term. The path of least change approach makes sense to me until we have time to work on a more consistent, more sustainable solution.

I don't fully grok how merging #2881 is less change. I guess what I'm wondering in @jcoyne's direction is, does `Publish::RightsMetadata` act on the Fedora representation that comes out of the `ToFedora` side? If not, I think the `original.clone` line will pass along CC3 / ODC licenses in rightsMD. If it does, won't this code make sure that CC3 / ODC licenses never make it into rightsMD in public XML? https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/license.rb#L16-L25 And, in that case, is this still the path of least change?

Appreciate the opportunity to talk this through here before moving forward. No matter what we do with #2881, we'll have a chance to iterate and improve in relatively short order, so I'm not *too* fussed either way. If this does have unanticipated side effects on Access systems in the interim, I also want to be sure y'all are open to making a subsequent reversion. I don't expect that will happen but... it does on occasion. 😅 Thanks, gents.

**Comment by andrewjbtw** [comment]
I think the missing context is that I'm asking for a change to be reverted. The behavior right now, with tags being inserted on publish, is new to this week.

**Comment by andrewjbtw** [comment]
For example, last week this object, which doesn't have human/machine tags, displayed the CC 4.0 text: https://sul-purl-stage.stanford.edu/wp959th7839 

Also last week, this object, also a CC 4.0 but with human and machine tags, displayed the CC 3.0 info: https://sul-purl-stage.stanford.edu/bp606ft7703

This week, after republish, both objects display the 3.0 info because the tags were inserted into the first one. I can't speak to what it looks like in the code but that's the behavior I think we should avoid for now.

**Comment by mjgiarlo** [comment]
@andrewjbtw OK. What is confusing me about #2881 is it looks like it's reverting changes from two months ago. Is this the recent bit you'd like reverted? https://github.com/sul-dlss/dor-services-app/commit/8bc8548622f71089fc27d491e808eff0c622553d#diff-0ed48b798fa20414a18eb7b8404ebe6e8c90d0db2cd011039039c98dc2104a1e That's from nine days ago.

**Comment by andrewjbtw** [comment]
In fact, https://sul-purl-stage.stanford.edu/bp606ft7703.xml has two separate human and machine tag sets, presumably one from Fedora and the other from publish. Again, I don't know where this is happening in the code, but it should not be happening.

**Comment by mjgiarlo** [comment]
@andrewjbtw So for those examples, it is definitely surprising to see CC4 stuff in rightsMD. That is why PURL is showing CC3. It looks like https://argo-stage.stanford.edu/view/druid:bp606ft7703 is one of the objects needing data remediation, since there's CC4 data in the CC3 section of the rightsMD. https://argo-stage.stanford.edu/view/druid:wp959th7839 looks fine on the Argo side, so it does look like the `add_license` method needs to change such that it *only* lets CC3 and ODC stuff into rightsMD. Maybe removing CC4 licenses from the hash would be a sufficient change. @andrewjbtw @jcoyne if it's helpful for us to put our heads together tomorrow, lmk.

**Comment by andrewjbtw** [comment]
My plan for druids like bp606ft7703 based on [this Slack conversation](https://app.slack.com/client/T044BUE0A/CSXTVRBEU/thread/CSXTVRBEU-1623344323.011900) has been to remove the human/machine statements from Fedora for the 4.0 items that have them, so they will look like wp959th7839 in Fedora after remediation. The fixture exists to represent what some of the prod data looks like.

These items have the data in the rightsMD in Fedora in prod because people entered it there manually (or got it inserted via editing the APO defaultObjectRights manually) following the pattern for CC 3. They had no way at the time of knowing how the license model would look in the future.

**Comment by mjgiarlo** [comment]
@andrewjbtw Sounds good to me!
