### ISSUE TITLE
Create an HTTP endpoint that updates Datacite DOI metadata

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#2912]
This should kick off a background job that handles the communication with Datacite.  This should be a sidekiq job because we want to make this resilient from Datacite being temporarily offline.  This endpoint will be called by the robots.  This will not have a callback to update the workflow.  If there is a failure, it should log in HB, but then rely on the sidekiq mechanism to retry as necessary.

**Comment by ndushay** [comment]
@jcoyne is there code that does this already somewhere?

**Comment by ndushay** [comment]
@arcadiafalcone can you let me know where you are in the mapping process, and where I should look for what you have so far?  (I can set up the plumbing and a partial mapping now.)

**Comment by arcadiafalcone** [comment]
Mappings in progress are here: https://github.com/sul-dlss/dor-services-app/tree/desc-spec-datacite/spec/services/cocina/mapping/descriptive/h2_datacite

I'm currently revamping contributor and event based on a conversation with Amy, but the others should be mostly stable.

**Comment by jcoyne** [comment]
@arcadiafalcone the datacite API that I'm looking at is in JSON, but it looks like you're making XML. https://support.datacite.org/reference/dois-2#post_dois

**Comment by arcadiafalcone** [comment]
XML is what we use in the current workflow and the format of DataCite's example records, but I can switch it to JSON.

**Comment by arcadiafalcone** [comment]
Though it looks like the metadata post API does take XML: https://support.datacite.org/reference/metadata#create-metadata-record-2.

**Comment by jcoyne** [comment]
I think we'd prefer to work with JSON if it's the same to you.

**Comment by jcoyne** [comment]
> Though it looks like the metadata post API does take XML: https://support.datacite.org/reference/metadata#create-metadata-record-2.

that's the MDS API, but we are not using that API.

**Comment by arcadiafalcone** [comment]
OK. I'll finish up the event spec first and then start translating the specs to JSON.

**Comment by ndushay** [comment]
noting that I will now work on a placeholder endpoint in DSA as the first part of this ticket.

**Comment by ndushay** [comment]
https://github.com/sul-dlss/dor-services-app/pull/2920 provides the mappings;  I will now implement them.

**Comment by ndushay** [comment]
Arcadia says:
> the required attributes are title, creator, identifier with identifierType, publisher, publication year, and resourceType with resourceTypeGeneral

- [ ] So if all of those aren’t populated after mappings, then there should be an HB error

> it shouldn't happen with h2 data, but yes - it would not be valid against the datacite metadata schema

**Comment by jcoyne** [comment]
I believe that schema is only enforced for the Datacite MDS API, but we aren't using that API.

**Comment by arcadiafalcone** [comment]
It would still be good to know if we are generating invalid data.

**Comment by ndushay** [comment]
I'm declaring this ticket done;  I will create a ticket indicating the hardcoded DataCite type mappings I did will need to be corrected.   I'm sure there are other mapping changes on the way once @arcadiafalcone is back at work, but those can be ticketed separately.
