### ISSUE TITLE
Implement multiple subject mapping - in DSA and H2

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#2961]
- [x] DSA spec (Arcadia) - See PR #2959
- [x] DSA roundtrips per spec - See PR #2968
- [x] H2 spec in sync (Arcadia) - See PR https://github.com/sul-dlss/happy-heron/pull/1868
- [x] H2 produces correct cocina - See PR https://github.com/sul-dlss/happy-heron/pull/1870
- [x] roundtrip tested w Amy & Arcadia (H2 does deposit, Argo metadata in sync w H2, no HB errors)

**Comment by ndushay** [comment]
closing this as Amy and Arcadia have signed off on the testing.
