### ISSUE TITLE
Implement roundtrippable event mappings in DSA and H2

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2963]
- [x] DSA spec (Arcadia) - see PR #2965 and #2969
- [x] DSA roundtrips per spec
- [x] H2 spec in sync (Arcadia) - PR https://github.com/sul-dlss/happy-heron/pull/1868
- [x] H2 produces correct cocina - See PR https://github.com/sul-dlss/happy-heron/pull/1870
- [x] roundtrip tested w Amy & Arcadia (H2 does deposit, Argo metadata in sync w H2, no HB errors)

**Comment by jcoyne** [comment]
I'm concerned that it may be impossible to implement https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/h2/event_h2_spec.rb#L426-L498  as MODS doesn't have enough data to distinguish a cited publisher from an uncited publisher

**Comment by ndushay** [comment]
Closing this as @jcoyne's concern was address (with an updated spec?) and Amy and Arcadia have signed off on the testing.
