### ISSUE TITLE
Implement roundtrippable form mappings in DSA and H2

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#2964]
- [x] DSA spec **Ask @arcadiafalcone ** ?? in PR  #2847 from May???
- [x] DSA roundtrips per spec
- [x] H2 spec in sync (Arcadia) - see PR sul-dlss/happy-heron/pull/1864
- [x] H2 produces correct cocina -- see PR https://github.com/sul-dlss/happy-heron/pull/1870
- [x] roundtrip tested w Amy & Arcadia (H2 does deposit, Argo metadata in sync w H2, no HB errors)

**Comment by arcadiafalcone** [comment]
I think https://github.com/sul-dlss/dor-services-app/pull/2847 was redone somewhere at some point because the existing form spec is correct.

**Comment by ndushay** [comment]
tested by Amy and Arcadia.
