### ISSUE TITLE
datacite implement distributor (optional field)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#2997]
If a contributor has a publisher role then it should be sent to datacite as a distributor:

```json
            "contributors:" [
              {
                "name": "Stanford University Press",
                "nameType": "Organizational",
                "contributorType": "Distributor"
              }
            ]
```

**Comment by justinlittman** [comment]
@jcoyne Can you say more? In the example above, the contributorType is "Distributor". Is this the only contributorType? Where should it go in the DataCite attributes and what should it look like?

**Comment by jcoyne** [comment]
@justinlittman I think you already implemented this: https://github.com/sul-dlss/dor-services-app/blob/664af8482efdfab58875186a08370a26b1bc4c63/spec/services/cocina/mapping/descriptive/h2_datacite/contributor_h2_datacite_spec.rb#L1461-L1471
