### ISSUE TITLE
Upgrade to ruby 2.2.x

### ISSUE THREAD

**Issue by wmene** [sul-dlss/dor-services-app#3]
@darrenleeweber the dor-services gem has already been updated to 2.1, so now this webservice needs to be updated

**Comment by atz** [comment]
Ruby 2.2 is target now.

**Comment by darrenleeweber** [comment]
Not sure why I'm tagged in this issue - I've never worked on this app.

**Comment by tingulfsen** [comment]
I officially became the owner of this app after Willy left. @atz what was the reason for revisiting this at this time? Updating dor-services?

**Comment by atz** [comment]
@tingulfsen Right.

**Comment by drh-stanford** [comment]
deployed on 2.2.x (see https://github.com/sul-dlss/dor-services-app/pull/27)
