### ISSUE TITLE
MARC2MODS XSLT: Map 340 and 344 subfields to physicalDescription notes

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3006]
Requested by Kevin Kishimoto.

**Comment by kevkishi** [comment]
Hi.
Please convert MARC 340 and 344 subfields to MODS <physicalDescription><note> fields.

Examples:
https://searchworks.stanford.edu/view/13613674 = https://purl.stanford.edu/vd156zb5829

https://searchworks.stanford.edu/view/10197351 = https://purl.stanford.edu/df799sq3079

https://searchworks.stanford.edu/view/11814836 = https://purl.stanford.edu/cn545yt6379

https://searchworks.stanford.edu/view/11953574 = https://purl.stanford.edu/yc408ms8686

Possible default display labels (from MARC standard):
- 340$a Material base and configuration
- 340$b Dimensions
- 340$c Materials applied to surface
- 340$d Information recording technique
- 340$i Technical specifications of medium
- 340$j Generation
- 344$a Type of recording
- 344$b Recording medium
- 344$c Playing speed
- 344$d Groove characteristic
- 344$e Track configuration
- 344$f Tape configuration
- 344$g Configuration of playback channels
- 344$h Special playback characteristics

OR just general Display Label for entire MARC field (like Searchworks):

- 340 = Medium
- 344 = Sound

Thanks
