### ISSUE TITLE
Implement datacite mapping for admin metadata

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3008]
```
spec/services/cocina/mapping/descriptive/h2_datacite/admin_metadata_h2_datacite_spec.rb:    xit 'not implemented' do
```

**Comment by justinlittman** [comment]
I don't understand what is supposed to be tested here. It seems that testing that nothing happens. And the spec as written doesn't indicate what is supposed to be invoked to verify that nothing happens?
