### ISSUE TITLE
Implement mapping for subject/name with affiliation (Cocina>MODS)

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3039]
https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/subject_name_spec.rb#L191

See #2580 . Previously addressed in #2613 but test is still xit-ed and roundtrip error still occurring (druid:bg593yv1090).

**Comment by arcadiafalcone** [comment]
No longer an issue.

**Comment by lwrubel** [comment]
Keep an eye on whether this may overlap with the work in this draft PR https://github.com/sul-dlss/dor-services-app/pull/3287. Hoping to move that out of draft for review today.
