### ISSUE TITLE
Remediate contentMetadata file with deliver attribute

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3070]
This must be changed to the currently used "publish" attribute.  This was already done for Project Phoenix:
https://github.com/sul-dlss/dor-services-app/issues/2630#issuecomment-878526085

**Comment by justinlittman** [comment]
Is there an example druid with this? Can this be handled by mapping/normalization instead of remediation?

**Comment by jcoyne** [comment]
We don't know if any of this case exists. It needs investigation.

**Comment by justinlittman** [comment]
First step then is to write a report to look for this.

**Comment by lwrubel** [comment]
Report contains 4,433 druids with file elements with deliver attributes:

[content-file-deliver.csv](https://github.com/sul-dlss/dor-services-app/files/7928006/content-file-deliver.csv)

**Comment by justinlittman** [comment]
Action for this ticket:
* When mapping from Fedora to Cocina, if `publish` attribute is not present, try `deliver` attribute.
* When normalizing content metadata, change `deliver` attribute to `publish` attribute if `deliver` is present, but `publish` is not.
* Add a test to https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/structural/dro_structural_spec.rb that tests both of the above.
