### ISSUE TITLE
Report of all MODS where the "version" attribute is missing

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3081]
Invalid MODS in descMetadata datastreams are causing issues for the maps team working on the David Rumsey collection. When they try to update records with invalid MODS, they are prevented from saving their edits. The most common problem is the lack of a `version` attribute in the root element. 

For example: https://argo.stanford.edu/view/druid:dj414px7657
```xml
<mods xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.loc.gov/mods/v3" xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-5.xsd">
```

The correct MODS should start like this:
```xml
<mods xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.loc.gov/mods/v3" xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-5.xsd" version="3.5">
```

I can fix these by updating the datastream but I have no easy way to tell what is or is not valid. I would like a report of all druids where the MODS is missing the `version` attribute. It seems to be a problem with items from 4-5 years ago that have not been updated since.

**Comment by aaron-collier** [comment]
@andrewjbtw Here is the report that was produced. 103K druids! I spot checked a few, and it includes the druid from above, so I assume it's correct. Happy to work further on this if you think there is an issue.

[desc-mods-missing-version.csv](https://github.com/sul-dlss/dor-services-app/files/7689076/desc-mods-missing-version.csv)

**Comment by andrewjbtw** [comment]
That number doesn't completely surprise me since there was probably a bug for a while that resulted in every descMetadata getting updated without the attribute. Since the system didn't validate anything, it probably didn't cause any noticeable problems. But now that we validate, records won't save when they're edited from Argo unless the attribute is added.

I don't think there's a current issue and any record updated via the spreadsheet upload gets this problem fixed. Probably none of the 103k druids have been updated for years.
