### ISSUE TITLE
Shelve web archive files without using the stacks attribute of content metadata

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3082]
The shelving service currently looks to see if there is a stacks attribute in the content metadata:
https://github.com/sul-dlss/dor-services-app/blob/main/app/services/shelving_service.rb#L53-L60

This is only use by web-archive files:
https://github.com/sul-dlss/was_robot_suite/blob/b0ae8bb3f9e3dc85e76be02f8ffecf32e18c2ed0/template/wasCrawlPreassembly/contentMetadata_dark.xslt#L8

Currently the best know way to identify objects like this is to see if the wasCrawlPreassemblyWF workflow is present.

If this condition is met, then shelf to `/web-archiving-stacks/data/collections/<collection_id>`, where collection_id is the unnamespaced druid of the (first) collection.

**Comment by justinlittman** [comment]
This seems like a very tenuous way to identify web archive crawls. Should they have their own type instead of object?

**Comment by jcoyne** [comment]
I think that would be ideal, but this is the approach @andrewjbtw identified.

**Comment by andrewjbtw** [comment]
We could and probably should create a web archive crawl type of object as a new type and then follow that type through the system, but finding existing objects of that type will need a technique like checking the web archive workflow.
