### ISSUE TITLE
Normalize content metadata invalid and/or deprecated resource attributes

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3084]
For example: https://argo.stanford.edu/view/druid:zn580kw6428 uses resource attributes that are no longer valid. Instead, this druid should get a valid resource type.

**Comment by justinlittman** [comment]
I'm not clear that the action on this ticket is. @andrewjbtw Can you clarify "resource attributes that are no longer valid" and "get a valid resource type"?

**Comment by jcoyne** [comment]
This means `  <resource objectId="druid:zn580kw6428" data="content" id="content">` the `data` and `id` are non-normative

**Comment by justinlittman** [comment]
Action to be taken for this ticket: Remove data and id attributes as part of content metadata normalization.
