### ISSUE TITLE
Normalize <location> element in the contentMetadata

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3085]
For example, https://argo.stanford.edu/view/druid:tt395zz8686 uses a `<location>` element for each file in the object. The location URL is a Stacks URL that

1. does not need to be stored in the contentMetadata (though it might have been required at some point in the past)
2. should not apply to the TIFF file, which is not supposed to be public (shelve is no, so it's not on Stacks)

```
<?xml version="1.0"?>
<contentMetadata type="file" objectId="druid:tt395zz8686">
  <resource objectId="druid:tt395zz8686" id="content" type="file">
    <label>Using xSearch for Accelerating Research-Review of Deep Web Technologies Federated Search Service</label>
    <file preserve="yes" deliver="yes" size="4333001" mimetype="application/pdf" id="xSearch_Review_Charleston_Advisor.pdf" shelve="yes" publish="yes">
      <location type="url">https://stacks.stanford.edu/file/druid:tt395zz8686/xSearch_Review_Charleston_Advisor.pdf</location>
      ...
```

Action for this ticket: Remove `<location type="url">` during content metadata normalization.

**Comment by justinlittman** [comment]
@andrewjbtw Do we need to actually remediate the data? Alternatively, can we (1) not map it to cocina and (2) remove it in roundtrip normalization?

**Comment by andrewjbtw** [comment]
We can try the mapping approach first. I'm not familiar enough with the data to know how consistently it will map.
