### ISSUE TITLE
Contributor affiliation note should be sibling of name

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3088]
Currently maps to child of name.

bb227wj5837

**Comment by arcadiafalcone** [comment]
See also "Name with multiple affiliations" in name_spec for mapping.

**Comment by justinlittman** [comment]
@arcadiafalcone Is this correct?
![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/dfcd7213-ac13-483a-82d2-27527045ee53)

**Comment by arcadiafalcone** [comment]
Yes, that's right.

**Comment by justinlittman** [comment]
OK, then I think this is resolved.
