### ISSUE TITLE
Report on MODS titles

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3092]
I would like a list of object druids (with APO druids) that fit the criteria that a) titleInfo has the attribute type="translated" and b) titleInfo has the attribute "transliteration" with any value. Include titleInfo at any level of the hierarchy (inside subject and relatedItem for example).

**Comment by jcoyne** [comment]
@arcadiafalcone I'm not finding any items that fit this criteria.  Do you know of any that should be found so that I can test that I've done this correctly?

**Comment by arcadiafalcone** [comment]
I was unclear - it's records that fit either a or b, not both a and b.

**Comment by jcoyne** [comment]
@arcadiafalcone that sounds good. Are there any records that you know will be in this report so I can test?

**Comment by arcadiafalcone** [comment]
One with transliteration: dv443xj0944
One with translated: zn746hz1696

**Comment by jcoyne** [comment]
@arcadiafalcone Is this complete now? Can this be closed?
