### ISSUE TITLE
tag editing fails on items with administrative tags that include a slash

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3093]
See https://app.honeybadger.io/projects/49894/faults/82034832

The druid is https://argo.stanford.edu/view/xd594pn7815 and one of the tags is `Project : ARS0022 speech : 1/4" audio tape`

**Comment by andrewjbtw** [comment]
From @jcoyne on Slack https://stanfordlib.slack.com/archives/C09M7P91R/p1638391766322400
>I suspect this is because the webserver for DSA is missing this bit of config:
AllowEncodedSlashes NoDecode

**Comment by jcoyne** [comment]
This change should help us to verify that this is the correct change: https://github.com/sul-dlss/puppet/pull/7291

**Comment by jcoyne** [comment]
This is the change for prod that should fix the issue: https://github.com/sul-dlss/puppet/pull/7296

**Comment by jcoyne** [comment]
fixed by the puppet changes.
