### ISSUE TITLE
  Rewrite PublicDescMetadataService to take a cocina item as its input 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3098]
https://github.com/sul-dlss/dor-services-app/blob/338601d512a866359a57ed2566323f471b571140/app/services/publish/public_desc_metadata_service.rb#L5

Rewrite the PublicDescMetadataService (which creates XML for exporting to purl/stacks) so that it doesn't rely on the XML datastreams and instead takes only the cocina model as its input.

As part of this:
* Generate the MODS using ToFedora::Descriptive
* Get the DOI (https://github.com/sul-dlss/dor-services-app/blob/338601d512a866359a57ed2566323f471b571140/app/services/publish/public_desc_metadata_service.rb#L49-L58) from Cocina model.
* Retrieve related collections from CocinaObjectStore.

**Comment by justinlittman** [comment]
This should be one of the last that is cocina-ized, as it depends on the desc metadata mapping.

**Comment by justinlittman** [comment]
- [ ] https://github.com/sul-dlss/dor-services-app/issues/3328
- [ ] https://github.com/sul-dlss/dor-services-app/issues/3329
- [ ] https://github.com/sul-dlss/dor-services-app/issues/3330
- [ ] https://github.com/sul-dlss/dor-services-app/issues/3334
- [ ] https://github.com/sul-dlss/dor-services-app/issues/3335
- [ ] https://github.com/sul-dlss/dor-services-app/issues/3098
