### ISSUE TITLE
Determine what missing objects are (and why they're missing)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3106]
![image](https://user-images.githubusercontent.com/588335/145638174-c368606f-72ad-43b6-ab81-59541911e569.png)

**Comment by justinlittman** [comment]
Missing indicates that it is not in the cache. I tested adding one of these missing druids to the cache and then it was no longer missing.

We should re-visit this after the cache regeneration is complete. Missing should be 0.

**Comment by jcoyne** [comment]
Can we change the label of that to "Missing from the cache"?

**Comment by justinlittman** [comment]
Yup. https://github.com/sul-dlss/dor-services-app/pull/3116

**Comment by justinlittman** [comment]
Missing is improved, so closing.
