### ISSUE TITLE
Normalize content metadata resource nodes with objectIds

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3118]
For example druid:ch697pb5703 has content metadata:
```
<?xml version="1.0"?>
<contentMetadata type="file" objectId="druid:ch697pb5703">
  <resource type="main-original" id="main">
    <label>Body of dissertation (as submitted)</label>
    <file shelve="yes" size="893629" publish="no" mimetype="application/pdf" preserve="yes" id="Jihee Kim Dissertation.pdf">
      <checksum type="md5">b44cd77b31716c951921473ff0a59b35</checksum>
      <checksum type="sha1">3edf5947c9fed80130d35539be55fe76011f43f3</checksum>
    </file>
  </resource>
  <resource type="main-augmented" objectId="druid:nh907tk5835" id="main">
    <label>Body of dissertation</label>
    <file shelve="yes" size="987995" publish="yes" mimetype="application/pdf" preserve="yes" id="Jihee Kim Dissertation-augmented.pdf">
      <checksum type="md5">fc3ebe4e566cdf7538d116a96698a96c</checksum>
      <checksum type="sha1">7a2d12dbbbdee88fe75b7aecd2dffc4566fca86b</checksum>
    </file>
  </resource>
</contentMetadata>
```

Note the objectId attribute on the resource node: `<resource objectId="druid:nh907tk5835">`. This attribute is not currently mapped / normalized. Should it be?

**Comment by andrewjbtw** [comment]
I think this is one of the questions that comes down to whether the access systems use the property.

**Comment by andrewjbtw** [comment]
Looking at it more closely, this might be a legacy of the old build-an-object-from-part-objects approach to ETDs. The resource "objectID" in the example is a druid that no longer exists and probably was a "part" object. That leads me to think it's likely we can normalize it out. 

But there could be other usages of "objectID" in the resource that are different than this.

**Comment by justinlittman** [comment]
Initial action for this ticket: Write a report to identify examples of resource nodes with objectId.

**Comment by lwrubel** [comment]
Attaching a report with 10,572 druids: 

[content-resource-objectid.csv](https://github.com/sul-dlss/dor-services-app/files/7898441/content-resource-objectid.csv)

**Comment by justinlittman** [comment]
Looks like EEMS includes an objectId which is the item's druid. For example, https://argo-prod-01.stanford.edu/view/druid:ms397jj9336:
```
<contentMetadata type="file" objectId="druid:ms397jj9336">
  <resource objectId="druid:ms397jj9336" data="content" id="content" type="file">
    <label>The Geometry of Exponential Families</label>
    <file preserve="yes" shelve="yes" deliver="yes" size="707152" mimetype="application/pdf" id="EFS NSF 89.pdf" publish="yes">
      <checksum type="md5">23ba96380af420e596feea6937ba8e2a</checksum>
      <checksum type="sha1">e23c84d180db795b9096f69b0f912adf4dc5011d</checksum>
    </file>
  </resource>
</contentMetadata>
```

**Comment by justinlittman** [comment]
All of the items in the report are EEMS or ETDS.

Action for this ticket: Remove objectId attributes from resource nodes as part of content metadata normalization.

**Comment by andrewjbtw** [comment]
There may be cases where there's a resource `objectId` but no resource `id`. In that case, a resource `id` may need to be created. I had to create one for an object I remediated in the past few weeks, but I don't remember which object. It was definitely from EEMS.
