### ISSUE TITLE
Normalize content metadata file node with format

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3119]
For druid:dv189xy6708:
```
<file mimetype="image/jp2" preserve="yes" format="JPEG2000" size="3305920" shelve="yes" id="M1090_S15_B01_F08_0073.jp2" publish="yes">
```

The format attribute is not mapped/normalized. It should be removed in normalization.

**Comment by andrewjbtw** [comment]
I don't believe it's used in the access systems. New items just have a mimetype. So we can probably normalize "format" out.
