### ISSUE TITLE
Normalize content metadata stacks attribute

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3121]
For druid:qn429kb8104:
```
<contentMetadata type="file" stacks="/web-archiving-stacks/data/collections/mm553tf6423" id="druid:qn429kb8104">
```

This attribute should be removed in normalization.

**Comment by jcoyne** [comment]
Is this the same as #3082?

**Comment by justinlittman** [comment]
Related, #3082 is about the functionality driven by the stacks attribute; this is about the mapping/normalization.

**Comment by jcoyne** [comment]
I'm suggesting that if 3082 is completed, then we can normalize this out.
