### ISSUE TITLE
Normalize content metadata reading order node

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3128]
For druid:dc266nc2219:

```
Normalized original XML for contentMetadata:
<?xml version="1.0" encoding="UTF-8"?>
<contentMetadata type="book"/>
```

```
Normalized roundtripped XML for contentMetadata:
<?xml version="1.0" encoding="UTF-8"?>
<contentMetadata objectId="druid:dc266nc2219" type="book">
  <bookData readingOrder="ltr"/>
</contentMetadata>
```

The logic for book data mapping may depend on administrative tags, making normalizing the original XML problematic. Therefore, normalize by adding `<bookData readingOrder="ltr"/>` when type=book and no <bookData> exists.

**Comment by jcoyne** [comment]
I believe this is because we are going from an implied order to an explicit order

**Comment by lwrubel** [comment]
There's a [previous normalization step](https://github.com/sul-dlss/dor-services-app/pull/2810/commits/b9e1b0da0651f630ab8ad11800d34301e96d54ca) to not add a readingOrder when the contentMetadata lacks a resource node. This would be in conflict with that. Should that normalization be removed as part of this new normalization, or is there other logic to add to the case of when a resource is lacking?

**Comment by lwrubel** [comment]
@jcoyne: should cocina be adding a hasMemberOrders > viewingDirection to all books if it does not currently exist? This normalization seems to assume it does, but I don't see that in the cocina ([example](https://argo.stanford.edu/view/druid:hp308wm0436)), and the validation success rate is going down.

[Branch with the normalization code](https://github.com/sul-dlss/dor-services-app/compare/t3128-normalize-readingorder?expand=1).

**Comment by justinlittman** [comment]
In Cocina, a book should always have a hasMemberOrders > viewingDirection.
In Fedora, a book should always have a contentMetadata > bookData.

Thus:
* When mapping from Fedora to Cocina, hasMemberOrders > viewingDirection should be added for a book if it does not already exist in the mapping.
* When normalizing contentMetadata, if a book if missing contentMetadata > bookData, it should be added.
