### ISSUE TITLE
Implement new models for versions

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3139]
Whenever a change is made to a DRO, collection, or AdminPolicy record a record should be kept of changed Cocina fields.

This should be based on https://github.com/sul-dlss/dor-services-app/pull/2413. See code related to use of hairtrigger gem.

When the DRO, collection, or AdminPolicy record is deleted, the version records should also be deleted.

Depends on #3138

**Comment by jcoyne** [comment]
@justinlittman is this fixed by #3311 ?

**Comment by justinlittman** [comment]
No. This is for versions that capture changes in the cocina, not SDR object versions.

**Comment by jcoyne** [comment]
@justinlittman @andrewjbtw I wonder if the update events in the current event log is sufficient to satisfy this use case.

 ![Screen Shot 2022-02-10 at 10.26.43 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/f3c28d6d-9c8b-4867-b4ac-aaa92b678019)

**Comment by justinlittman** [comment]
This won't handle cases in which we perform DDL directly without instantiating the object. Will we ever do this? Maybe -- it is one of the possible approaches for the evolution of Cocina and is a big advantage of having the JSON in Postgres.

**Comment by justinlittman** [comment]
Per @andrewjbtw , the primary use case for this is to be able to view user-initiated changes. The current approach using events satisfies that use case, so closing this ticket.
