### ISSUE TITLE
MARC2MODS XSLT - fix physicalLocation/repository mapping

### ISSUE THREAD

**Issue by cebraj** [sul-dlss/dor-services-app#314]
Currently, the holding repository information seems to be mapping to the physicalLocation field instead of the repository field.

In MODS, physicalLocation should indicate the storage/box information, not the repository name.

Example record: https://purl.stanford.edu/sz810hh0474

**Comment by arcadiafalcone** [comment]
Repository data is not from the MARC2MODS transformation, but appears to have been added when modifying the collection record to describe an individual item in that collection.
