### ISSUE TITLE
Report to find APOs without agreement ids

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3142]
Agreement ids are in the `RELS-EXT` as `referencesAgreement`, e.g.,
```
<?xml version="1.0"?>
<rdf:RDF xmlns:fedora-model="info:fedora/fedora-system:def/model#" xmlns:hydra="http://projecthydra.org/ns/relations#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="info:fedora/druid:bb540gx2176">
    <hydra:isGovernedBy rdf:resource="info:fedora/druid:zw306xn5593"/>
    <hydra:referencesAgreement rdf:resource="info:fedora/druid:mc322hh4254"/>
    <fedora-model:hasModel rdf:resource="info:fedora/afmodel:Hydrus_AdminPolicyObject"/>
  </rdf:Description>
</rdf:RDF>
```

In theory, any agreements missing agreement ids will be remediated to allow https://github.com/sul-dlss/cocina-models/issues/259 to proceed.

**Comment by andrewjbtw** [comment]
I'll take a look at them. They are probably decommissioned Hydrus-origin APOs. I can just insert an agreement ID.

**Comment by andrewjbtw** [comment]
These all turned out to be broken objects that had never made it to accessioned states and were not used in any way, so I purged them.
