### ISSUE TITLE
Map file nodes missing mimeType and size (contentMetadata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3155]
For example:
```
<contentMetadata objectId="druid:hv992ry2431" type="book">
          <resource id="ck831vq4558_1" sequence="1" type="file">
            <file id="sul-logo.png" publish="yes" preserve="yes" shelve="yes"/>
          </resource>
        </contentMetadata>
```

Currently, when mapping to Cocina, `size` is set to 0 and `mimeType` is omitted.

And when roundtripping:
```
<contentMetadata objectId="druid:hv992ry2431" type="book">
        <resource id="ck831vq4558_1" sequence="1" type="file">
          <file id="sul-logo.png" mimetype="" size="0" publish="yes" preserve="yes" shelve="yes"/>
        </resource>
      </contentMetadata>
```

Is this correct? Should size be set to 0? On roundtrip, should mimeType be set to "" or omitted?

**Comment by andrewjbtw** [comment]
Both pieces of data should be entered and they should be correct.

**Comment by justinlittman** [comment]
Initial action for this ticket: Write a report looking for files missing mimetype or size attributes.

**Comment by andrewjbtw** [comment]
Could the API not be generating this data? The assemblyWF creates it for accessions that take that path.

**Comment by justinlittman** [comment]
There are definitely contentMD with blank mimetypes. For example:
```
<file id="mj877zq3306-0.img" preserve="yes" publish="no" shelve="no" mimetype="" size="0">
      <checksum type="md5">d41d8cd98f00b204e9800998ecf8427e</checksum>
      <checksum type="sha1">da39a3ee5e6b4b0d3255bfef95601890afd80709</checksum>
    </file>
```

Here are some druids:
* druid:mj877zq3306
* druid:dm803vv6779
* druid:hc450rn7460
* druid:kb912xn9744
* druid:tf282kb3650
* druid:dc193dy4457
* druid:xb030zs8555
* druid:fs834ks2521

**Comment by justinlittman** [comment]
There are definitely contentMD with 0 size. Here are some druids:
* druid:pc378bg7455
* druid:bt451cx2607
* druid:mj877zq3306
* druid:my944rx1869
* druid:nr115fk4324

**Comment by jcoyne** [comment]
for the files in the first list, I think this was because it was unable to determine a file type. I wonder if we can replace a blank mime-type with `application/octet-stream`.

**Comment by jcoyne** [comment]
I don't think the 0 size is missing. They actually have files that are 0 bytes.

**Comment by justinlittman** [comment]
I have verified that there are no <file> missing mimetypes.

**Comment by justinlittman** [comment]
I have verified that there are no missing sizes.

I would propose that the only action that is necessary is to change a blank mime type to `application/octet-stream`. Is this acceptable @andrewjbtw ?

**Comment by andrewjbtw** [comment]
I think so. I'd actually thought that's what we were doing by default if something didn't map to a more specific mimetype, which probably lots of the more unusual software and data files don't do.

**Comment by justinlittman** [comment]
Action for this ticket:
* When mapping, to cocina if mimetype is blank change to "application/octet-stream".
* When normalizing, change a blank mimetype to "application/octet-stream".

**Comment by justinlittman** [comment]
Oh wait, there is a note in the code that indicates that files from Goobi and Hydrus don't have mimetype until they hit exif-collect in the assemblyWF. Given that, new action for this ticket:
* When mapping to cocina, if mimetype is blank omit it (mimetype is optional).
* When normalizing, remove a blank mimetype.
