### ISSUE TITLE
Delete cleaner.rake

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3157]
Rewrite https://github.com/sul-dlss/dor-services-app/blob/main/lib/tasks/cleaner.rake to use Cocina rather than Fedora.

**Comment by jcoyne** [comment]
I'd say this can be a low priority as I don't think we've used this script for 3 years.

**Comment by peetucket** [comment]
Looks like two defined rake tasks in that file:

1. `delete_all_objects` -- would the equivalent be to nuke cocina out of Postgres and then ensure solr gets updated?
2. `seed` - do we have cocina APO fixtures to load into Postgres and then index?

**Comment by jcoyne** [comment]
My proposal is that we remove this script. @andrewjbtw do you agree?

**Comment by andrewjbtw** [comment]
I would like to clear out stage and QA at some point and start over fresh but we don't necessarily need to update this script to do so rather than come up with something new. I don't really have an opinion about these rake tasks.

**Comment by justinlittman** [comment]
Action for this ticket: delete `cleaner.rake`.
