### ISSUE TITLE
Determine fate of bin/refresh-metadata

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3158]
Should [bin/refresh-metadata](https://github.com/sul-dlss/dor-services-app/blob/main/bin/refresh-metadata) be deleted or updated for Cocina?

**Comment by andrewjbtw** [comment]
I've never used this. Does it operate behind the scenes as part of the "Refresh descriptive metadata" function? If not, I'd check with @arcadiafalcone . If it's a standalone script that no one uses then it can be deleted.

**Comment by arcadiafalcone** [comment]
@justinlittman Am I understanding correctly that this script refreshes records in the cache based on a list of druids?

**Comment by justinlittman** [comment]
No @arcadiafalcone, it calls the [RefreshMetadataAction](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/refresh_metadata_action.rb), which:
```
# Look into identityMetadata for compliant ids and use them to fetch
# descriptive metadata from Symphony.  Put the fetched value in the descMetadata
```

The cache is not involved.

**Comment by arcadiafalcone** [comment]
@justinlittman I think this is useful to keep at least until the "refresh metadata" synchronous bulk update in Argo gets ported over to an asynchronous bulk action.
