### ISSUE TITLE
Delete remediation scripts

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3159]
Can the following be deleted @arcadiafalcone ?
* https://github.com/sul-dlss/dor-services-app/blob/main/bin/remediate-languageTerm
* https://github.com/sul-dlss/dor-services-app/blob/main/bin/remediate-naf
* https://github.com/sul-dlss/dor-services-app/blob/main/bin/remediate-stanford-placeTerm

**Comment by arcadiafalcone** [comment]
@justinlittman Yes, OK to delete.

**Comment by justinlittman** [comment]
Action for this ticket: delete the aforementioned scripts.
