### ISSUE TITLE
Prefer Authorization header over X-Auth

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor-services-app#320]
When token-based authentication was added to dor-services-app, we still supported HTTP Basic (credential-based) authentication, and thus defined an unconventional header (`X-Auth`) to flag token-based connections. Now that dor-services-app and all of its clients have switched to token-based authentication, and dor-services-client no longer supports HTTP Basic authentication, we should consider whether to keep using the `X-Auth` header (advantage: less work; disadvantage: unconventional) or to switch to the `Authorization` header (advantage: conventional/least surprise; disadvantage: have to touch a lot of codebases and coordinate deployments).

**Comment by mjgiarlo** [comment]
@jcoyne recommends that we allow both headers in the interim.

We plan to discuss this issue and come up with a plan at our @sul-dlss/infrastructure-team development meeting on Tuesday, August 20th.

**Comment by justinlittman** [comment]
Per Infra Dev Meeting (8/20/19), should prefer Authorization header over X-Auth header.
