### ISSUE TITLE
Normalize objectCreator (identityMedata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3213]
Currenty, when mapping from Cocina from Fedora, `<objectCreator>` is always added with value "DOR" to identity metadata. However, in some cases, the original identity metadata does not contain `<objectCreator>`, e.g., https://argo-prod-01.stanford.edu/view/druid:nb871dz1060.

Is this always adding an `<objectCreator>` correct?

If so, it will also need to be added in normalization when missing.

**Comment by andrewjbtw** [comment]
Do any of our systems use `<objectCreator>`? I think the field may have been created in anticipation of different systems creating SDR objects, but ultimately the value seems to have always been DOR, unless it wasn't recorded at all. If we don't have any systems that use the value, I don't see a need to have `objectCreator` at all and it can be normalized out. It doesn't look like it's in Cocina.

**Comment by justinlittman** [comment]
Not clear whether any of our systems use it; however, there are many references to it, e.g., in fixture: https://github.com/search?p=4&q=org%3Asul-dlss+objectCreator&type=Code

Therefore, I think the safest course of action is to continue to always add it with value "DOR".

Action for this ticket: For identity metadata normalization, add `<objectCreator>` with value "DOR" if it does not exist.

**Comment by andrewjbtw** [comment]
It certainly doesn't seem to cause a problem to add it.
