### ISSUE TITLE
Map multiple catkeys

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3221]
See #2833 for context

Some objects have multiple catkeys in identity metadata, e.g., druid:bb593hn2771:
```
<?xml version="1.0"?>
<identityMetadata>
  <objectId>druid:bb593hn2771</objectId>
  <otherId name="dissertationid">0000000256</otherId>
  <otherId name="catkey">8652439</otherId>
  <otherId name="uuid">a2dbe1e0-6328-11e1-a761-022c4a816c60</otherId>
  <otherId name="catkey">12303491</otherId>
</identityMetadata>
```

Both catkeys should be retained when mapping to cocina in the original order:
```
identification: {
            sourceId: 'dissertationid:0000000296',
            catalogLinks: [
              {
                catalog: 'symphony',
                catalogRecordId: "12345"
              },
              {
                catalog: 'symphony',
                catalogRecordId: "67890"
              }
            ]
          }
```

As part of this ticket, please complete the ["with ETD with 2 catkeys" test](https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/identification/dro_identity_spec.rb#L638), which will probably need some changes.

**Comment by edsu** [comment]
Is `with objectAdminClass (EEMS) and same catkey twice, no collection` worth doing too as part of this?

**Comment by justinlittman** [comment]
I don't think so. That spec is about 2 collections, not 2 catkeys.
