### ISSUE TITLE
Move DruidTools::Druid#mkdir to dor-services-app

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#326]
`dor-services-app/app/services/workspace_service.rb` has the only usage in all the sul-dlss code. It's also used in the specs in this repo.

**Comment by ndushay** [comment]
@jcoyne is this done?  If so, please close.

**Comment by jcoyne** [comment]
Not able to do it at this time because `DruidTools::Druid#path` uses mkdir.  That method is used all over the place. https://github.com/sul-dlss/druid-tools/blob/77cefae78856bde35c6493da04114a64691a41b9/lib/druid_tools/druid.rb#L94
