### ISSUE TITLE
Change file / fileset external identifier strategy

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3275]
Currently, when mapping from fedora to cocina, external identifiers for files and filesets are generated with a UUID: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/id_generator.rb#L29

This is problematic for 2 reasons:
* Since the identifiers aren't persisted, a new external identifier is generated each time a mapping is performed.
* Virtual objects that reference files have no means of referencing those files in a stable way.

Therefore:
* Change external identifiers for filesets to be: `http://cocina.sul.stanford.edu/fileSet/<druid without prefix>/<resourceId>`
* Change external identifiers for files to be: `http://cocina.sul.stanford.edu/file/<druid without prefix>/<resourceId>/<fileId>`.
* Enforce this external identifier structure in cocina model so that new/updated virtual objects can map to fedora. (After migration, this enforcement can be relaxed).

**Comment by jcoyne** [comment]
I would prefer we persist the UUID and can load that resource/file knowing the UUID alone, and we don't need to know the object to which it belongs.

**Comment by justinlittman** [comment]
Given new strategy for virtual objects (virtual objects are composed of other objects, not resources or files), this is not necessary so closing.

**Comment by mjgiarlo** [comment]
We now believe this is required in order to have deterministic and consistent resource identifiers, which is particularly important for virtual objects. 

Blocks #3177, #3331, #3379

**Comment by ndushay** [comment]
is this PR also relevant to  https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/normalizers/content_metadata_normalizer.rb#L62-L66 ?   Were there 2 of these PRs?  'Cause I thought in #dlss-infrastructure channel you were closing a PR on a similar topic without merging??

**Comment by mjgiarlo** [comment]
This is the PR you suggested earlier today which I attempted and walked away from when it was clear it would take more time than I thought I could afford: https://github.com/sul-dlss/dor-services-app/pull/3575

**Comment by ndushay** [comment]
all I meant was ... if we're being deterministic, then is it the case that we don't need contentMetadata roundtrip normalization?  `normalize_roundtrip` only.   If it isn't the case that it is easy to tell, might there be a comment update for that method?
