### ISSUE TITLE
Publish the created_at/updated_at to RabbitMQ

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3297]
In https://github.com/sul-dlss/dor-services-app/blob/main/app/services/notifications/object_created.rb and https://github.com/sul-dlss/dor-services-app/blob/main/app/services/notifications/object_updated.rb, in addition to the model, add the created at and updated at metadata. 

Here's where we set that metadata on an API request: https://github.com/sul-dlss/dor-services-app/blob/759941e7527c528518a6dc5289c551999b433868/app/controllers/objects_controller.rb#L78-L79

 This change will enable dor_indexing_app to run indexing without having to call back to DSA to get the model.

**Comment by aaron-collier** [comment]
@jcoyne in the objects_controller I see that we're getting that data from the Dor::Item. I do not see this mapped into the cocina model. Should this be mapped or we just publish the current time?

**Comment by jcoyne** [comment]
@aaron-collier this is stored in the table that contains the cocina model, but is not in the model itself.

**Comment by justinlittman** [comment]
Can this be abstracted behind `CocinaObjectStore` to isolate the Fedora bits?

**Comment by aaron-collier** [comment]
@justinlittman yeah - that's the idea that @jcoyne mentioned after standup, starting down that path now.
