### ISSUE TITLE
Map / normalize / remediate non-numeric imageData (content metadata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3323]
For example druid:ft996xy0052:
```
<contentMetadata objectId="ft996xy0052" type="file">
  <resource id="ft996xy0052_3" sequence="3" type="file">
    <label>File 3</label>
    <file id="12220080_labyrinth_trace.svg" preserve="yes" shelve="yes" publish="yes" size="13543" mimetype="image/svg+xml">
      <checksum type="md5">f4d7c7316e50b026d922e7450b1ec11a</checksum>
      <checksum type="sha1">09ad00510e0acd8882c202a19ef5f1a9111ae19f</checksum>
      <imageData width="27.544308mm" height="29.510118mm"/>
    </file>
  </resource>
</contentMetadata>
```

Currently, this is converted to an integer.

Should this be mapped, normalized, or remediated?

**Comment by andrewjbtw** [comment]
I'm not really sure what to do here. We can't display SVG in the viewer and this item has content type of file so the `imageData` is not serving any function in the example druid. 

Probably `imageData` should always be pixels but it really comes down to what the Access side code expects. These values would have come from the assemblyWF so if we need it to always produce pixels we'd need to change what happens there.

**Comment by justinlittman** [comment]
Initial action for this ticket: Write a report that find all heights and widths that are non-numers (e.g., "27" and "27.544308" is OK, but "27.544308mm" is not).

**Comment by jcoyne** [comment]
@andrewjbtw PURL converts the height and width to integers and it only uses it on resources where`type="image"`

**Comment by edsu** [comment]
Attached is a report of `<imageData>` elements that have a non-numeric `height` or `width` using `sdr-deploy:/opt/app/deploy/dor-services-app/druids.txt`.

It looks like there are 25 that use `mm` but a significant portion seem to be cases where the height and/or width are set to the empty string? For example [druid:nr142mk4735](https://argo.stanford.edu/view/druid:nr142mk4735).

[image-dimensions.csv](https://github.com/sul-dlss/dor-services-app/files/8048464/image-dimensions.csv)

**Comment by justinlittman** [comment]
`mm` is valid SVG: https://www.w3.org/TR/SVGMobile12/types.html#DataTypeLength

My proposal is to add an optional `height_unit` and `width_unit` to [Presentation](https://github.com/sul-dlss/cocina-models/blob/main/openapi.yml#L1347).

**Comment by jcoyne** [comment]
Svg are not supposed in the access systems, they are not "type=image", so maybe they don't need image data.

**Comment by justinlittman** [comment]
The decision was to:
* Not map imageData for svg.
* Map/normalize imageData height and width to integers.

**Comment by justinlittman** [comment]
Closing in favor of #3540, #3541, #3542
