### ISSUE TITLE
Rewrite identity metadata in PublicXmlService to map from a cocina item

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3328]
Currently, identity metadata that is including in the public XML is derived from a Fedora object. It should be re-written to derive it from a Cocina object. The public XML should remain unchanged.

See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_xml_service.rb#L24

refs #3098

**Comment by peetucket** [comment]
Note; I'm noticing that the `ReleaseTags#create` method only appears to be called in one place, which is in a spec: https://github.com/sul-dlss/dor-services-app/blob/main/spec/requests/show_object_spec.rb#L72

If true, would it make sense to get rid of this method and adjust the test to mock the data in some way?

**Comment by justinlittman** [comment]
I defer to your judgement @peetucket .
