### ISSUE TITLE
Rewrite relationships metadata in PublicXmlService to map from a cocina item

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3334]
Currently, relationships metadata that is including in the public XML is derived from a Fedora object. It should be re-written to derive it from a Cocina object. The public XML should remain unchanged unless you can determine that Access/PURL is only using a subset of that XML.

See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_xml_service.rb#L27

refs https://github.com/sul-dlss/dor-services-app/issues/3098

**Comment by jmartin-sul** [comment]
i think this got picked off by @jcoyne in the course of working on another ticket last week, closing, of course reopen if that was in error
