### ISSUE TITLE
identityMetadata existing objectLabel should be kept

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#3336]
Many ~~APO~~ objects already have an ```<objectLabel>``` in `identityMetadata`; this should not be changed when mapping (please confirm @andrewjbtw)

Note #3320 is related;  this ticket is for ~~APOs~~ objects with `identityMetadata` that already have an existing objectLabel.   

(@andrewjbtw, @justinlittman  - does the original objectLabel disappear for Collections, Agreements, Items?)

examples: bb329pr4129, zy568yz3838

```xml
Original XML for identityMetadata:
 <?xml version="1.0"?>
 <identityMetadata>
    <objectId>druid:bb329pr4129</objectId>
    <objectCreator>DOR</objectCreator>
    <objectLabel>Hydrus</objectLabel>
    <objectType>adminPolicy</objectType>
 </identityMetadata>
 

Roundtripped XML for identityMetadata:
<?xml version="1.0"?>
 <identityMetadata>
   <objectId>druid:bb329pr4129</objectId>
   <objectCreator>DOR</objectCreator>
   <objectType>adminPolicy</objectType>
   <objectLabel>Intial Hydrus APO title</objectLabel>
</identityMetadata>
 ```

See  https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/identity.rb#L40-L44  and https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/object_creator.rb#L89.

**Comment by ndushay** [comment]
@andrewjbtw should this apply to collection and DROs also?  (See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/object_creator.rb, which calls  https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/identity.rb#L40-L44)

**Comment by andrewjbtw** [comment]
Yes, if there's already an `objectLabel` in the identityMetadata for any object type we should keep it.

**Comment by justinlittman** [comment]
Hold on. In Cocina there is only a single label. What is the significance of an objectLabel that is different than the label?

(cc @jcoyne)

**Comment by ndushay** [comment]
when there is no `objectLabel`, the code can get a value from the fedora object level label, or it can get it from ??descriptiveMetadata?? .  That's how we seemed to have coded it.  I think in cocina we just have "label" but perhaps we have it in multiple sub-objects that make a single cocina DRO, APO, collection object?

**Comment by justinlittman** [comment]
Other than DRO, AdminPolicy, and Collections only Files and FileSets have labels.

**Comment by andrewjbtw** [comment]
The Cocina object-level label should be mapped from the identityMetadata `<objectLabel>` (if there is one) or somewhere else if there isn't. It should not be mapped from the Fedora object label except as a last resort.

The identityMetadata <objectLabel>, as published to the public XML, is parsed by some Access systems for display. The value really should match the descMetadata title but that title field can be quite complex and it's not clear what Access side changes are needed to take the new field. I've been unable to get traction on this issue, which pre-dates me working at SUL. 

It might be better to walk through what's going on with this field via zoom rather than write it all out in issues. I don't know why Cocina has a label at all, except for backwards compatibility with the Fedora model and the public XML. Maybe there's a use case I'm missing.

**Comment by ndushay** [comment]
Trying to take notes from Andrew at standup

- cocina top level "label" field 
    - what is the use?
    - it is mapped from top level Fedora object label;  we shouldn't use this.
- `objectLabel` in `<identityMetadata>`
    - we _should_ use:  `objectLabel` in `<identityMetadata>` -- this is used in public_xml from PURL.  
        - when this isn't populated, it should be populated.  (from ??)
        - consumers SHOULD use the MODS title, but they won't
        - this should therefore be the MODS title (?) - perhaps just on "publish" ?
 - is there even a value for any cocina labe?

**Comment by ndushay** [comment]
There is an APO in argo with "Belkan-Knopp" in the identityMetadata that becomes "Knopp-Belkan" ... and the only place the latter was, was in the fedora object top level label.   But I can't find the record now.

**Comment by justinlittman** [comment]
Action for this ticket: Change FromFedora mapping for [APO](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/from_fedora/apo.rb#L23) and [Collection](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/from_fedora/collection.rb#L23) to prefer objectLabel like ([DRO](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/from_fedora/dro.rb#L60)).

**Comment by ndushay** [comment]
Please make sure to test this with the druids mentioned above and with druids.apo.txt and druids.collections.txt

**Comment by aaron-collier** [comment]
Should we have a "source of truth" for `druids.txt` `druids.apo.txt` and `druids.collections.txt`? The 2 later I was unaware of before today.

**Comment by ndushay** [comment]
This link is in the bookmarks in #dlss-infrastructure. https://docs.google.com/document/d/18gAZlMNcnKGYoegw34kBvqx2TLjaQEZelC_C_Myp2h8

**Comment by aaron-collier** [comment]
Thank you, I was unaware of that.
