### ISSUE TITLE
ConstituentService should also check objects for (not) dark or citation_only

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#334]
~~requires sul-dlss/dor-rights-auth#40 (new release of dor-rights-auth with `dark?` and `citation_only?` methods)~~

both the parent and the child objects should be
- open for modification
- not dark 
- not citation_only (ditto)

**Comment by jmartin-sul** [comment]
sul-dlss/dor-rights-auth#40 is done (released v1.4.0 to rubygems)

**Comment by mjgiarlo** [comment]
@jmartin-sul 	given your work on sul-dlss/dor-rights-auth#40, are you inclined to take this issue on next?

**Comment by ndushay** [comment]
@mjgiarlo i would rather John did the analysis on permissons in argo (https://github.com/sul-dlss/argo/issues/1478)  for workflows before his vacation.

**Comment by jmartin-sul** [comment]
@mjgiarlo and @ndushay, will investigate this as my next task.  will leave notes with whatever i find, and whatever possible next steps might be if it needs to be handed off.

**Comment by ndushay** [comment]
@jmartin-sul I'd rather have you investigate the argo permissions, if you're willing.

**Comment by jmartin-sul** [comment]
@ndushay said
> I'd rather have you investigate the argo permissions, if you're willing.

yup, planning to, i just wrote my initial note as if it was on that ticket, my mistake.

**Comment by jmartin-sul** [comment]
breadcrumbs for whoever does pick this up:

for some examples of how to use the new methods for determining "dark" and "citation only" status, see:
* https://github.com/sul-dlss/argo/issues/1464#issuecomment-520615876 and https://github.com/sul-dlss/argo/issues/1464#issuecomment-520616793 ... **except** that now there _are_ `#dark?` and `#citation_only?` convenience methods:
  * https://github.com/sul-dlss/dor-rights-auth/pull/38/files
  * https://github.com/sul-dlss/dor-rights-auth/pull/41/files

but basically, if you have a `Dor` object `obj`, you could do:
```ruby
obj.dra_object.dark?
obj.dra_object.citation_only?
```

the `dra_object` method will instantiate the `Dor::RightsAuth` object such that the `#dark?` and `#citation_only?` methods work (and if you instantiate the DRA object incorrectly, `#dark?` and `#citation_only?` should raise a hopefully helpful error).

see https://github.com/sul-dlss/dor-services/blob/0c85ae8135e21a0c654cab470bb8dd8504208f87/lib/dor/datastreams/rights_metadata_ds.rb#L75-L77

also, you'll need to use dor-rights-auth v1.4.0 or higher:  https://github.com/sul-dlss/dor-rights-auth/releases/tag/v1.4.0
