### ISSUE TITLE
APOs possibly needing attention for clean roundtripping

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#3344]
If there is a way to clean these up manually, they are the only 3 APOs with roleMetadata problems not otherwise already addressed or ticketed.

### roleMetadata of kz136vz0351
empty, and yet not.
```xml
<roleMetadata>
  <role type="dor-apo-manager"/>
</roleMetadata>
```
Is this effectively empty?  Should our code normalize it out (drop it)?  Is it a problem for an APO to have missing `roleMetadata`?  

### roleMetadata of mk653jf7735, tw357qz5418
empty `dor-apo-manager` role

```xml
<roleMetadata>
  <role type="hydrus-collection-manager">
    <person>
      <identifier type="sunetid">jschne</identifier>
      <name/>
    </person>
  </role>
  <role type="dor-apo-manager">
  </role>
</roleMetadata>
```

**Comment by peetucket** [comment]
Action: Andrew will remediate.

**Comment by andrewjbtw** [comment]
I've added workgroup roles to all three APOs in this ticket, which I think means they will now roundtrip and the ticket can be closed.

**Comment by ndushay** [comment]
I'll test these APOs right now.

**Comment by ndushay** [comment]
all are happy - closing this ticket.
