### ISSUE TITLE
APO empty administrative metadata

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#3345]
@andrewjbtw @justinlittman - are the following things true?
- it is ok for an APO to have empty `administrativeMetadata`
- `administrativeMetadata` should be empty rather than missing
- in the example below, there is no real information so it is equivalent to empty

How do we define empty administrativeMetadata? 

examples:  bb329pr4129, bg492mf5264, gj997gr2148 (affects 49 APOs)

```xml
Original XML for administrativeMetadata:
<administrativeMetadata>
  <dissemination>
    <workflow id=""/>
  </dissemination>
</administrativeMetadata>

Normalized original XML for administrativeMetadata:
<administrativeMetadata>
  <dissemination>
    <workflow id=""/>
  </dissemination>
</administrativeMetadata>

Roundtripped XML for administrativeMetadata:
<administrativeMetadata/>
```

**Comment by justinlittman** [comment]
Action for this ticket: Remove empty dissemination in normalization:
```
<dissemination>
    <workflow id=""/>
  </dissemination>
```

**Comment by justinlittman** [comment]
Please make sure to test this with the druids mentioned above and with `druids.apo.txt`.
