### ISSUE TITLE
releaseWF is hitting an error at update-marc / update_marc_record

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3346]
Items running the releaseWF are hitting an error at the `update-marc` step. There are currently 17 items in an error state at this step, apparently all from today:
https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=releaseWF%3Aupdate-marc%3Aerror

This corresponds to a few HB issues:
https://app.honeybadger.io/projects/52894/faults/61783946
https://app.honeybadger.io/projects/50568/faults/83911967
https://app.honeybadger.io/projects/50568/faults/83916162

**Impact**

This is likely preventing items from being released or unreleased where the release process involves updates to the MARC record. It's also preventing the releaseWF from completing.

**Comment by aaron-collier** [comment]
Looking at the first couple druids I see in HB they are collection objects so they don't have the `identification` node in cocina.
