### ISSUE TITLE
APO records with nested administrativeMetadata elements need remediation

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#3356]
The following 15 APO druids all have `<administrativeMetadata>` elements nested inside `<administrativeMetadata>` , such as

```xml
<administrativeMetadata>
  <descMetadata>
    <format>MODS</format>
    <source>DOR</source>
  </descMetadata>
  <administrativeMetadata>
    <registration>
      <workflow id="registrationWF"/>
      <collection id="druid:zm916ww7449"/>
    </registration>
  </administrativeMetadata>
</administrativeMetadata>
```

@andrewjbtw @justinlittman I assume this is bad data and worth correcting, rather than writing normalization ... but either way.

- [x] druid:bt419zy3596.txt
- [x] druid:bz466cq3451.txt
- [x] druid:dn218mt2501.txt
- [x] druid:gc003rg6636.txt
- [x]  druid:gn965yg6021.txt
- [ ] druid:gz830zp4734.txt
- [x] druid:hd578bc5236.txt
- [x] druid:hv695nb1898.txt
- [x] druid:jz175zc6377.txt
- [x] druid:kq265wn4855.txt
- [x] druid:kz136vz0351.txt
- [x] druid:qh637kf2429.txt
- [x] druid:sb559ym0369.txt
- [x] druid:sm977cq5975.txt
- [x] druid:zk257mf5837.txt

**Comment by justinlittman** [comment]
@andrewjbtw Can you remediate druid:gz830zp4734?

**Comment by andrewjbtw** [comment]
I'm not sure what needs to be done for gz830zp4734. Maybe someone already fixed it?

**Comment by justinlittman** [comment]
It roundtrips now, so good to go.
