### ISSUE TITLE
APO administrativeMetadata objectId attribute should be normalized out

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#3360]
```xml
<administrativeMetadata objectId="druid:cg616xd9084">
...
</administrativeMetadata>
```

Remove objectId in normalization for administrativeMetadata.

occurrences in APOs: 40

examples: bj961cc4982, fp733rq3615

Please make sure to test this with the druids mentioned above and with druids.apo.txt.

**Comment by ndushay** [comment]
@andrewjbtw - 

- is there ever a need to have the object's druid as an objectId attribute at the top level of _any_ datastream?  It seems like its only utility would be if the datastream got separated from its object.  ("Help!  I'm an orphan datastream!")

@justinlittman 
- in terms of roundtripping, should we always remove, or always add if missing?  https://github.com/sul-dlss/dor-services-app/issues/3127

**Comment by andrewjbtw** [comment]
I would defer to whatever the code does with the druid in the top of a datastream. There's no user-facing requirement as far as I know.
