### ISSUE TITLE
856 output from releaseWF is showing the #<> syntax instead of a catkey in certain subfields

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3369]
There are a couple of situations where the 856 generated from the releaseWF should list catkeys in one or more subfields:

- when an item is part of a collection that has a catkey, a subfield will list the collection and the collection's catkey (if it has one, and if it has been released)
- when an item is part of a virtual object that has a catkey, a subfield will list the virtual object druid and that object's catkey (if it has one, and if it has been released)

In tonight's list of releases, instead of a catkey the 856 is including some ruby-specific output in the `xset` subfield:
```
12132784	bg260bf4357	.856. 41|uhttps://purl.stanford.edu/bg260bf4357|xSDR-PURL|xitem|xfile:bg260bf4357%2Fbg260bf4357_01.jp2|xcollection:qw878nc9115:9102342:Stanford University publications and ephemera collection, 1885-2011|xset:qw878nc9115:#<Cocina::Models::CatalogLink:0x00007fc76d3b4e30>:Stanford University publications and ephemera collection, 1885-2011|xlabel:Volume 3, number 1, 1997|xrights:world
```
The value following `xset:qw878nc9115` should be the catkey associated with qw878nc9115. I'm not sure what to call the syntax of `#<Cocina::Models::CatalogLink:0x00007fc76d3b4e30>` but it looks like that's what's getting output in place of a catkey whenever the `xset` subfield is being generated. Multiple records released today have this issue.

**Impact**

It's not clear yet. The data hasn't been pulled into the MARC record yet, so we won't know until tomorrow.

**Additional information**

The subfield that starts with `xcollection` has the correct catkey. I'm not sure why both `xcollection` and `xset` are getting the same collection+catkey info, but I suspect they play different roles in how SW renders the data. 

Looking through other 856s, I think the data is supposed to look like this:

```
4767563	cr201ws3781	.856. 41|uhttp://purl.stanford.edu/cr201ws3781|xSDR-PURL|xitem|xfile:cr201ws3781%2FParkin_1899_00043.jp2|xcollection:wn972rs0795::Stanford Geological Survey|xset:dv390rr1685:4767563:Notes on the geology of the Palo Alto sheet
```

Additional debugging note: it's possible to view the 856s generated each day by connecting to `dor_services_prod` and looking in the `/sdrpurl_transfer` directory. An archive of releases is located at `/sdrpurl`.

**Comment by justinlittman** [comment]
cc @aaron-collier
