### ISSUE TITLE
Remediate geo metadata objects

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3395]
Some objects (e.g., druid:vp514gs0717, druid:zn779hf4325) have geo metadata, but are not content geo content type. However, our current code only maps geo metadata when geo content type: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/from_fedora/dro.rb#L72

Action:

- write a report to identify other objects that look like this (appear to be geo but are not marked as geo).
- this is any object that has geoMetadata datastream but is not the geo content type

Remdiation: switch them to geo content type

**Comment by jcoyne** [comment]
I disagree. I think these objects just have the wrong content type. They are in the geo dataset collection and went through the geo workflows. These objects just need remediation.

**Comment by justinlittman** [comment]
This was @andrewjbtw's call.

**Comment by peetucket** [comment]
Action for this ticket: 
- write a report to identify other objects that look like this (appear to be geo but are not marked as geo).
- this is any object that has geoMetadata datastream but is not the geo content type

Remdiation: switch them to geo content type

**Comment by andrewjbtw** [comment]
I looked at some geo objects and I think what happens in the geo workflows is that at some point the content type is actually changed from file to geo. There are no registered objects with content type geo, which leads me to believe they're registered as "file" first and not as geo. So updating these to geo is probably what was supposed to happen but they stalled somewhere in the geo workflows and didn't hit that point.

**Comment by justinlittman** [comment]
So the correct action would be to map geo metadata regardless of type (not remediate), right @andrewjbtw?

**Comment by jcoyne** [comment]
I think allowing geo metadata on non geo items makes the data less useful and makes our systems more complicated. Why have object types if they do not convey anything useful? The generate content metadata in gisAssemblyWF already generates as type 'geo', so these  looks like bad data to me, not how it's typically done.

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/dor-services-app/pull/3433 follows the approach that we've been using for other non-fatal data errors: perform the mapping, but HB notify so that it can be remediated.

**Comment by justinlittman** [comment]
@andrewjbtw Let's go with remediation and see if problem re-appears in testing.

**Comment by andrewjbtw** [comment]
So the remediation is to make the content type geo? Is it just these two or have I lost track of a related report?

**Comment by justinlittman** [comment]
This should do it: https://argo-prod-01.stanford.edu/catalog?f%5Bcontent_type_ssim%5D%5B%5D=file&f%5Bis_governed_by_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Abz466cq3451

**Comment by andrewjbtw** [comment]
Well, that didn't go well: https://app.honeybadger.io/projects/50568/faults/78631512

That's what I got when trying to bulk change content type to geo. Most of those druids now won't render a show page in Argo.

**Comment by andrewjbtw** [comment]
I see now. That was not a good list of druids to use because many of those don't have a geoMetadata datastream. It might take some time get them back to content type file and start over with an accurate list.

**Comment by jcoyne** [comment]
One way to do that is to use the items that have been through generate-geo-metadata

**Comment by andrewjbtw** [comment]
So the state we want is "content type=geo" if and only if a geoMetadata datastream is present. It looks like if it's geo without the datastream it's an error and if it's non-geo with the datastream it's also an error.

**Comment by andrewjbtw** [comment]
The bigger remediation now might be undoing what I did above. That bulk content type change must have fixed the ones that needed the change and broken the ones that didn't.

**Comment by justinlittman** [comment]
If it makes the remediation easier, we can temporarily relax the requirement that geo must have a geoMetadata stream.

**Comment by andrewjbtw** [comment]
That may be more trouble than it's worth. But this does raise an issue: if someone accidentally changes a content type to geo on something without the datastream, they'll have no way of correcting the issue.

**Comment by jcoyne** [comment]
The good thing about Cocina is that it wouldn't let you make that change

**Comment by justinlittman** [comment]
Yet it did.

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/dor-services-app/pull/3483 should prevent this by not allowing Fedora items to be saved when they cannot be mapped to cocina.

**Comment by jcoyne** [comment]
> Yet it did.

Because we didn't put the restriction in cocina-models...which we should have done.

**Comment by ndushay** [comment]
Is there an action remaining with this ticket?  Is the title still accurate?

**Comment by andrewjbtw** [comment]
I don't understand the current state of this issue anymore. I think all the items that were "geo" but didn't have a geoMetadata datastream are not being called "file" and all items that do have a geoMetadata datastream but were called "file" are now called "geo". I don't have enough knowledge of the geo content type to know if this means everything is correct.

There are no objects in the "Cocina conversion failed" list so everything must be valid - pending anything in the indexing backlog.

**Comment by justinlittman** [comment]
I think this is done, so closing for now.
