### ISSUE TITLE
Add missing <access type="discover"> during embargo metadata normalization

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3396]
For druid:bm722zk9642:
```
Normalized original XML for embargoMetadata:
<?xml version="1.0" encoding="UTF-8"?>
<embargoMetadata>
  <status>embargoed</status>
  <releaseDate>2022-06-08T07:00:00Z</releaseDate>
  <releaseAccess>
    <access type="read">
      <machine>
        <world/>
      </machine>
    </access>
  </releaseAccess>
</embargoMetadata>


Normalized roundtripped XML for embargoMetadata:
<?xml version="1.0" encoding="UTF-8"?>
<embargoMetadata>
  <status>embargoed</status>
  <releaseDate>2022-06-08T07:00:00Z</releaseDate>
  <releaseAccess>
    <access type="discover">
      <machine>
        <world/>
      </machine>
    </access>
    <access type="read">
      <machine>
        <world/>
      </machine>
    </access>
  </releaseAccess>
</embargoMetadata>
```

If there is a:
```
 <access type="read">
      <machine>
        <world/>
      </machine>
    </access>
```

but no:
```
    <access type="discover">
      <machine>
        <world/>
      </machine>
    </access>
```
add it.

**Comment by ndushay** [comment]
@justinlittman FYI, I just found this problem in about 180 ETDs, e.g. bb645cz8933

and this appears to be how we create the embargos now:  https://github.com/sul-dlss/hydra_etd/blob/main/app/services/create_embargo.rb#L12

I'm not sure if 
- this is limited to ETDs
- the cocina embargo information is complete enough
    - will changes be needed in hydra_etd code creating new ETDs with embargos?
- the original fedora `embargoMetadata.xml` is complete enough
    - will data remediation be needed?

**Comment by justinlittman** [comment]
The cocina is complete, so is there a problem?
![image](https://user-images.githubusercontent.com/588335/153961791-f10069f0-230a-41c2-996b-ee817f70d6fc.png)

Isn't all that is needed normalization?

**Comment by ndushay** [comment]
it could be that all we need is normalization, yes.  I had that in the ticket I almost created that would have duplicated this one.
