### ISSUE TITLE
Normalize duplicate sourceId (identity metadata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3401]
From druid:ht121fv8052:
```
Normalized original XML for identityMetadata:
<?xml version="1.0" encoding="UTF-8"?>
<identityMetadata>
  <objectId>druid:ht121fv8052</objectId>
  <objectCreator>DOR</objectCreator>
  <sourceId source="sul">M1141_B9_1:1</sourceId>
  <objectLabel>People's Computer Company</objectLabel>
  <objectType>item</objectType>
  <sourceId source="sul">M1141_B9_1:1</sourceId>
  <otherId name="catkey">404268</otherId>
  <release to="Searchworks" what="self" when="2019-06-26T21:38:24Z" who="cebraj">true</release>
</identityMetadata>


Roundtripped XML for identityMetadata:
<?xml version="1.0"?>
<identityMetadata>
  <sourceId source="sul">M1141_B9_1:1</sourceId>
  <objectId>druid:ht121fv8052</objectId>
  <objectCreator>DOR</objectCreator>
  <objectType>item</objectType>
  <objectLabel>People's Computer Company</objectLabel>
  <release who="cebraj" what="self" to="Searchworks" when="2019-06-26T21:38:24Z">true</release>
  <otherId name="catkey">404268</otherId>
</identityMetadata>
```

Remove duplicate sourceIds in normalization.

**Comment by andrewjbtw** [comment]
The source id is effectively "sul:M1141_B9_1:1", which is how users enter it. So the whole value should be retained. You'll find a lot of different prefixes in the source ids and all should be retained. I don't know why the XML representation separates the prefix as an attribute and then treats what follows the prefix as the value. The prefix was envisioned to be a namespace (or like a namespace). Nothing actually treats it that way as far as I know.

Also the example above has two colons, which is fun. I don't know if that's supposed to be considered valid or not. But the prefix should always be what comes before the first colon.

**Comment by justinlittman** [comment]
Duh. The problem is that there are duplicate source ids.
