### ISSUE TITLE
Map non-integer imageData (content metadata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3405]
Currently, in Cocina, the height and width must be integers. If a non-integer is found, it is converted to an integer. However, for svgs, the height and width are not integers. For example, druid:zy084wg9064:
```
<resource id="zy084wg9064_4" sequence="4" type="file">
    <label>File 4</label>
    <file id="xb572rf0120_compass.svg" preserve="yes" shelve="yes" publish="yes" size="12593" mimetype="image/svg+xml">
      <checksum type="md5">4bb2ca76473e1cf9508edf74aeee1039</checksum>
      <checksum type="sha1">c77b11447e4426bad6381794c7c5bca03597d832</checksum>
      <imageData width="54.432" height="109.008"/>
    </file>
  </resource>
```

Mapping should be changed so that all numbers (including floats) are retained as is when mapping.

**Comment by justinlittman** [comment]
Depends on https://github.com/sul-dlss/cocina-models/issues/306

**Comment by jcoyne** [comment]
@justinlittman the access team is just casting these values to integers anyway, are we sure this is necessary?
