### ISSUE TITLE
H2 object labels

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3408]
Some H2 objects, e.g., druid:bb328jb5128 and druid:wg608dc4783 have "Hydrus" as identityMetadata objectLabel even though the Fedora item has a descriptive label.

Currently, when mapping to Cocina, "Hydrus" is used as the label, since objectLabel trumps Fedora item label. This should be changed so that Fedora item label trumps objectLabel when objectLabel="Hydrus".

**Comment by andrewjbtw** [comment]
Strange. I would have expected the opposite to happen. These are both quite recent objects too. Both of these were Hydrus-registered and then H2-deposited and I suspect that has something to do with it.

**Comment by jcoyne** [comment]
This sounds more like a remediation task than a mapping task

**Comment by justinlittman** [comment]
Mapping is faster, easier, and more accurate than remediation. And by mapping it correctly, it will be remediated when we migrate to Cocina. (This approach is used widely for other problems as well.)

**Comment by jcoyne** [comment]
Can we verify that this only applies to items registered in Hydrus and deposited by H2?  It's possible that H2 is doing something wrong, so mapping won't be sufficient if we keep making bad data.

**Comment by justinlittman** [comment]
#3431 fixes the underlying problem that was causing this -- updates were not updating objectLabel.

**Comment by justinlittman** [comment]
With @jcoyne label refactoring, these now map correctly. Win!
