### ISSUE TITLE
Add relationship type when missing (content metadata)

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3409]
Some virtual objects are missing the type attribute for `<relationship>`. For example, druid:ty497dw3030:
```
<resource sequence="1" id="ty497dw3030_1">
    <externalFile objectId="druid:fn851rw5684" resourceId="fn851rw5684_1" fileId="PC0170_s3_Oregon_State_2008-08-28_154120_0001.jp2" mimetype="image/jp2"/>
    <relationship objectId="druid:fn851rw5684"/>
  </resource>
```

As part of normalization, the type attribute should be added when missing:
```
<resource sequence="1" id="ty497dw3030_1">
    <externalFile objectId="druid:fn851rw5684" resourceId="fn851rw5684_1" fileId="PC0170_s3_Oregon_State_2008-08-28_154120_0001.jp2" mimetype="image/jp2"/>
    <relationship objectId="druid:fn851rw5684" type="alsoAvailableAs"/>
  </resource>
```

**Comment by jcoyne** [comment]
@andrewjbtw The relationship node is not used in PURL and seems duplicative now that the externalFile node has the same data.  Can we just get rid of the relationship node?

**Comment by justinlittman** [comment]
Either way you have to normalize, so please proceed with this ticket as written.

**Comment by lwrubel** [comment]
Do you happen to have another druid with this behavior? Might help me create a local cache since I'm still getting bad cache errors with the druid:ty497dw3030.
