### ISSUE TITLE
Do a bulk reindex of virtual objects

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3417]
Upon completion of sul-dlss/dor-services-app#3419 and https://github.com/sul-dlss/dor_indexing_app/issues/743, perform a bulk reindex of virtual objects using Argo.

**Comment by justinlittman** [comment]
Please make sure that https://github.com/sul-dlss/dor_indexing_app/issues/743 is deployed to production and verify that `has_constituents_ssim` is present after reindex.

**Comment by jcoyne** [comment]
@justinlittman it was deployed on Friday last week.

**Comment by mjgiarlo** [comment]
All 4,693 virtual objects in prod have been reindexed successfully and `has_constituents_ssim` is now present in the index.
