### ISSUE TITLE
When updating updating legacy datastreams, map to cocina before saving

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3426]
Currently, datastreams that are updated via the [update_legacy_metadata](https://github.com/sul-dlss/dor-services-app/blob/10a11083f9075dea17a30ac14bc8e688da3de872/app/controllers/metadata_controller.rb#L26) and [mods update](https://github.com/sul-dlss/dor-services-app/blob/main/app/controllers/mods_controller.rb#L11) endpoints save the Fedora item before mapping the item to Cocina. This allows users to create Fedora items that cannot map to Cocina.

Instead, map the updated Fedora item to cocina before saving it.

**Comment by jcoyne** [comment]
It is possible that an item which is already invalid, can not be made valid by editing only one datastream, thus this validation may prevent progress toward correctness.

**Comment by justinlittman** [comment]
If the item is already invalid then with the current DSA/Argo code the user cannot fix it so this doesn't make anything worse. In that case, the correction will have to be performed from the Rails console.
