### ISSUE TITLE
ETD wz924gg6479 identityMetadata.xml is missing the objectId

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#3441]
@andrewjbtw @caaster 

currently, Fedora has this for `identityMetadata` for https://argo.stanford.edu/view/wz924gg6479

```xml
<identityMetadata>
  <otherId name="dissertationid">0000001785</otherId>
</identityMetadata>
```

identityMetadata would roundtrip cleanly fedora/cocina/fedora if an objectId and objectType were added:

```xml
<identityMetadata>
  <otherId name="dissertationid">0000001785</otherId>
  <objectId>druid:wz924gg6479</objectId
  <objectType>item</objectType>
</identityMetadata>
```

**Comment by justinlittman** [comment]
Let's just remediate this single item.

**Comment by andrewjbtw** [comment]
I see this particular druid is a known outlier for many reasons so I'm just going to fix the identityMetadata and walk away:
https://github.com/sul-dlss/hydra_etd/search?q=wz924gg6479&type=issues

**Comment by andrewjbtw** [comment]
I added the missing fields, including `objectLabel` just for good measure.
