### ISSUE TITLE
ImageData report - when <file> has <imageData> element, has mimeType of jp2, and imageData is missing height or width info

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3446]
Create 2 reports:
* Items that have `<imageData>` nodes for a `<file>` that is the child of a `<resource [@type != "image"]>`.
* Items that have `<file>` that do not have `<imageData>` or the `width` or `height` attributes for the `<imageData>` are blank and is the child of a `<resource [@type = "image"]>`.

```
<?xml version="1.0"?>
<contentMetadata objectId="bb000kg4251" type="image">
  <resource id="bb000kg4251_1" sequence="1" type="image">
    <label>Image 1</label>
    <file id="bb000kg4251.jpg" mimetype="image/jpeg" size="1347965" preserve="yes" publish="no" shelve="no">
      <checksum type="md5">abf0fd6d318bab3a5daf1b3e545ca8ac</checksum>
      <checksum type="sha1">eb68cd8ece6be6570e14358ecae66f3ac3026d21</checksum>
      <imageData width="3184" height="2205"/>
    </file>
    <file id="bb000kg4251.jp2" mimetype="image/jp2" size="1333879" preserve="no" publish="yes" shelve="yes">
      <checksum type="md5">7f682a6acaecb00ec23dc5b15e61ee87</checksum>
      <checksum type="sha1">8356f16250042158e8d91ef4f86646a7d58aae0b</checksum>
      <imageData width="3184" height="2205"/>
    </file>
  </resource>
</contentMetadata>
```

**Comment by ndushay** [comment]
Report 1:   

Items that have `<imageData>` nodes for a `<file>` that is the child of a `<resource [@type != "image"]>`.
there are 396108  of these;  I suspect we want to say resource is not of type "image" OR "book"

Here's a sample
```
druid,apo,catkey,message
druid:hp308wm0436,,,
druid:yv388sd4099,,,
druid:bb645rx2234,,,
druid:wb540fw6515,,,
druid:fg928zc5860,,,
druid:rs145hp9367,,,
druid:dy225qm6521,,,
druid:st351yk8376,,,
druid:xh343kg4239,,,
```

**Comment by jcoyne** [comment]
@ndushay wouldn't it be "image" or "page"?

**Comment by ndushay** [comment]
### Report 2:   (still to come)

Items that have `<file>` that do not have `<imageData>` or the `width` or `height` attributes for the `<imageData>` are blank and is the child of a `<resource [@type = "image"]>`.

There are of these.

```
```

**Comment by ndushay** [comment]
> @ndushay wouldn't it be "image" or "page"?

not at the resource level.  Maybe at the file level, dunno.

**Comment by ndushay** [comment]
@andrewjbtw I guess we use "preview" instead of "thumb" ??

**Comment by andrewjbtw** [comment]
Please do not automatically change resource type based on file type. I'm not sure there's any value in even reporting supposed mismatches.

**Comment by andrewjbtw** [comment]
Also, we should allow `<imageData>` on image files in non-image resources. We will potentially break the ability to change content type if we strip this data out. Parts of our existing structural metadata model are a mess and I don't think it's possible to fix that with remediation.

**Comment by ndushay** [comment]
@justinlittman @andrewjbtw Is it still useful to find cases where an `<imageData>` element exists but there is not complete information for height and width attributes?

**Comment by ndushay** [comment]
Andrew notes that users deposit jp2 images that don't get imageData from accessioning path;  this is ok.

**Comment by ndushay** [comment]
ACTION:  report on incomplete <imageData> stuff

**Comment by ndushay** [comment]
### Report on image/jp2 files with imageData missing height or width info

There are none. Or my report is wrong (but I'm confident it is NOT).

**Comment by ndushay** [comment]
I'm declaring this done.
