### ISSUE TITLE
Stop writing unnecessary datastreams to exported bag

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3465]
The only files that should be written are for:
* contentMetadata
* workflow
* versionMetadata
* cocina.json

These files are written by PreservationMetadataExtractor and invoked by SdrIngestService.

**Comment by ndushay** [comment]
if "DatastreamExtractor" is only used in this context, the bag is for preservation.  "ExtractForPreservation" ? 

Another question:  are we preserving as XML or as JSON?   If we choose the latter ... how do we relate old preserved versions to new ones?   If we choose the former ... don't we lose information with the xform (as one always loses information with an xform).

**Comment by justinlittman** [comment]
It has already been renamed to `PreservationMetadataExtractor` so renaming not necessary.

We are storing cocina.json as JSON and version, workflow, and content metadata as XML. So the completeness of the cocina representation and the backwards compatability of the XML representation where necessary.

**Comment by justinlittman** [comment]
FYI @andrewjbtw moving this to Ready.

**Comment by andrewjbtw** [comment]
This means that if the roundtrip isn't correct yet, the cocina saved is missing the lost data?

**Comment by justinlittman** [comment]
That is correct. However, there is only a single outstanding mapping ticket (on the fringes of desc metadata).
