### ISSUE TITLE
raise error if retrieval of marc data from Symphony fails or is incomplete

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#348]
part of uber ticket sul-dlss/common-accessioning#188

We want dor-services-app to raise an error when it gets no response or an incomplete response from Symphony for a metadata lookup for a catkey.

This could happen in SymphonyReader or in MarcxmlResource or in CatalogHandler ... wherever it makes sense, as long as we surface the error as a proper HTTP error code, with info in the message.  Sending the error to honeybadger would be good also.

Our criteria are actually expressed in terms of Mods, but perhaps @arcadiafalcone  or someone could help express them in terms of Marc (you should have ?? a leader, these fixed fields, a 245, and at least one other field ??)

from Andrew, via slack:
> with catkey, there should be title + at least one other field

per Ben, we sometimes get no response from Symphony, and we sometimes end up with incomplete desc metadata.  See https://github.com/sul-dlss/common-accessioning/issues/372 for an example of incomplete mods output.   Unclear whether the marc was incomplete, or just the mods ...

SO:
- [ ] at LEAST one of the following (preferably all)
  - [x] error raised if symphony response is wrong length #358
  - [ ] make sure error is raised if we don't get marc meeting minimal requirements back from Symphony (leader, 008, 245a -- see comment below)
  - [ ] make sure error is raised if marcxml doesn't meet minimal requirements (leader, 008, 245a -- see comment below)
  - [ ] make sure error is raised if marc_to_mods xsl xform doesn't have title and at least one other field
- [ ] send any flavors of these errors to Honeybadger PR #373
- [x] make sure dor-services-app returns HTTP error response with appropriate message for client (e.g. xxx was unable to fetch complete metadata from Catalog for catkey 1234, or marcxml for catkey 1234 is missing 245a, or whatever)

I believe the dor-services-client has recently been updated to surface any error messages it gets from dor-services-app ReST calls, which in turn should bubble up in argo / workflows.

<hr />

Some spelunking breadcrumbs, which you are welcome to ignore:

argo
- app/assets/register.js calls
- Dor::ObjectsController.create

which calls

dor-services-client
- Dor::Services::Client::Objects.register

which calls

dor-services-app
- objects_controller.create calls
- RegistrationService.create_from_request calls
- RegistrationService.register_object calls
- RefreshMetadataAction.run calls
- MetadataService calls
- CatalogHandler calls 
- MarcxmlResource calls
- SymphonyReader

**Comment by jcoyne** [comment]
I think SymphonyReader already raises a `JSON::ParserError` if there is no response or an incomplete response: https://github.com/sul-dlss/dor-services-app/blob/master/app/models/symphony_reader.rb#L40

Do you think we should be validating that response has `fields/bib` (https://github.com/sul-dlss/dor-services-app/blob/master/app/models/symphony_reader.rb#L44)?

**Comment by ndushay** [comment]
If SymphonyReader raises an exception, it isn't making it back to the client, and it isn't going to honeybadger.  

We also have empirical evidence that incomplete or missing mods happens. 

Perhaps https://github.com/sul-dlss/dor-services-app/blob/master/app/models/symphony_reader.rb#L44 should raise an error if these requirements are not met: 

- leader https://www.loc.gov/marc/bibliographic/nlr/nlrleaddirect.html
- ? directory ? https://www.loc.gov/marc/bibliographic/nlr/nlrleaddirect.html
- 008
- 245 subfield a https://www.loc.gov/marc/bibliographic/nlr/nlr2xx.html

certainly the mods should be checked for "title plus one other field" per Andrew.

**Comment by ndushay** [comment]
possible data point from Andrew's testing:

From dor-services-app logs on stage:

```
I, [2019-08-26T10:55:52.151648 #85943]  INFO -- : [6d159892-cfea-47ac-94d8-54e3bf57ded9]   Parameters: {"object_type"=>"item", "admin_policy"=>"druid:zv774fm6469", "rights"=>"default", "other_id"=>"symphony:3240876", "tag"=>["Process : Content Type : Book (ltr)", "Registered By : bergeraj"], "source_id"=>"without-label", "label"=>":auto", "object"=>{"object_type"=>"item", "admin_policy"=>"druid:zv774fm6469", "rights"=>"default", "other_id"=>"symphony:3240876", "tag"=>["Process : Content Type : Book (ltr)", "Registered By : bergeraj"], "source_id"=>"without-label", "label"=>":auto"}}
I, [2019-08-26T10:55:52.153227 #85943]  INFO -- : [6d159892-cfea-47ac-94d8-54e3bf57ded9] <ActionController::Parameters {"object_type"=>"item", "admin_policy"=>"druid:zv774fm6469", "rights"=>"default", "other_id"=>"symphony:3240876", "tag"=>["Process : Content Type : Book (ltr)", "Registered By : bergeraj"], "source_id"=>"without-label", "label"=>":auto", "controller"=>"objects", "action"=>"create", "object"=>{"object_type"=>"item", "admin_policy"=>"druid:zv774fm6469", "rights"=>"default", "other_id"=>"symphony:3240876", "tag"=>["Process : Content Type : Book (ltr)", "Registered By : bergeraj"], "source_id"=>"without-label", "label"=>":auto"}} permitted: false>
I, [2019-08-26T10:55:52.634427 #85943]  INFO -- : [6d159892-cfea-47ac-94d8-54e3bf57ded9] Completed 422 Unprocessable Entity in 483ms (Views: 0.3ms)
```

**Comment by ndushay** [comment]
Note:  we do get back the length of the JSON Symphony is sending us via Content-Length header in the response.

Returned headers:
```
HTTP/1.1 200 
Date: Fri, 30 Aug 2019 00:02:56 GMT
Server: Apache/2.4.6 ()
Strict-Transport-Security: max-age=31536000; includeSubDomains
Access-Control-Allow-Origin: *
Content-Type: application/json
Content-Length: 1960
Via: 1.1 symphony-webservices-dev.stanford.edu
```

but at this moment, I'm not gonna rewrite the SymphonyReader  so it checks header.

**Comment by ndushay** [comment]
@andrewjbtw confirming that we're ok with the following:
- [x] checking metadata requests from Symphony for their length, throwing an error if the number of bytes we received doesn't match the length in the HTTP header from Symphony
- [ ] surfacing said error with somewhat useful message in Registration results and in refresh metadata button from item view
- [x] checking that descriptiveMetadata has a MODS title field

And we no longer are prioritizing:
- [ ] checking for minimal required fields in marc received from symphony
- [ ] checking for minimal required fields in marcxml derived from marc received from symphony
- [ ] checking for mods title + "something else" in mods derived from marcxml derived from ...

**Comment by ndushay** [comment]
@andrewjbtw can this be closed?   Can we assume we're good if we get the right number of bytes from Symphony?

**Comment by ndushay** [comment]
Rewording:  I am closing this, given PR #380 that addresses Symphony error responses, and PR #392 that addresses timeouts for Symphony requests.

**Comment by andrewjbtw** [comment]
I see you've already closed this -- was just coming here to agree that you can close it.
