### ISSUE TITLE
SymphonyReader should check response status codes from Symphony

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#350]
Looking at some logs on dor-services-stage, I found:

```
I, [2019-08-26T13:21:30.769614 #85943]  INFO -- : [64314fd4-8949-43f0-a15e-71ed312fd98e] Started POST "/v1/objects/druid:bb151dz4290/refresh_metadata" for 171.67.23.30 at 2019-08-26 13:21:30 -0700
I, [2019-08-26T13:21:30.770224 #85943]  INFO -- : [64314fd4-8949-43f0-a15e-71ed312fd98e] Processing by MetadataRefreshController#refresh as */*
I, [2019-08-26T13:21:30.770265 #85943]  INFO -- : [64314fd4-8949-43f0-a15e-71ed312fd98e]   Parameters: {"id"=>"druid:bb151dz4290"}
I, [2019-08-26T13:21:30.838717 #85943]  INFO -- : [64314fd4-8949-43f0-a15e-71ed312fd98e] Completed 204 No Content in 68ms
```

It's possible I'm misinterpreting the rails logs;  is this saying that `refresh_metadata` in THIS app returned a 204 to the client?   I'm thinking it probably should return a 4xx or 5xx if refresh_metadata has no content, no?

I think this is coming from, ultimately, https://github.com/sul-dlss/dor-services-app/blob/master/app/models/symphony_reader.rb#L40 ???

I dunno if we should do a retry to Symphony , but after 1-2 retries, if still not content, it should be raised all the way up as 4xx vs 5xx, with error info from Symphony avail in dor-services-app HTTP response.

related to #348

**Comment by jcoyne** [comment]
You are misinterpreting it.  It is saying 204 - everything is okay -- I have refreshed the metadata and have nothing else to tell you.  This is the correct behavior.

**Comment by ndushay** [comment]
So refresh_metadata updates the descMetadataDS with results from symphony.  Per info from Ben, apparently this step sometimes doesn't successfully update the descMetadata ... do we surface non-success in the HTTP response?

**Comment by jcoyne** [comment]
If any errors are raised, then they will be a 500 status.  I think the only thing we need to be concerned about is symphony returning a 2xx code, with syntactically valid JSON, but that doesn't have the fields we need.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 	
> If any errors are raised, then they will be a 500 status. I think the only thing we need to be concerned about is symphony returning a 2xx code, with syntactically valid JSON, but that doesn't have the fields we need.

I'm hearing that in order for folks to pick this issue up, we need to know what are "the fields we need." Who knows that? cc: @ndushay

**Comment by ndushay** [comment]
I'm gonna say this is a dup of #348.

I just checked if:
- Symphony API adheres to HTTP response codes (probably - I certainly got a 400 from my browser)
- Faraday raises when we want it to (probably:  https://github.com/lostisland/faraday/blob/master/spec/faraday/response/raise_error_spec.rb)

We need to be sure we surface any errors raised by faraday at https://github.com/sul-dlss/dor-services-app/blob/master/app/models/symphony_reader.rb#L40, but I believe that is covered by #348.
