### ISSUE TITLE
Restore support for multiple project tags

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3545]
Cocina treats the "Project" tag specially and differently than all other administrative tags and only allows objects to have one Project tag. Last fall, when we launched H2, we learned that items that have multiple Project tags fail certain actions, such as the releaseWF, as described in https://github.com/sul-dlss/dor-services-app/issues/3004 .

It has long been common Argo practice, dating back years and pre-dating Cocina, to assign multiple Project tags in Argo when multiple tags are appropriate to the projects being managed. We should restore the ability to use multiple Project tags. 

Because Project tags are used in 3 different ways, this may be a challenge. There's a long discussion of the issue in #3004 

The 3 usages are:

- as a tag in Argo for purely in-Argo uses (gathering things under a tag in the tag facet)
- as a tag with special meaning for Goobi: goobi-notify uses Project tags to connect druids to Goobi Projects
- as a tag that indicates a message route: messages to H2 about accesioning progress rely on the "Project : H2" tag

One proposal from our earlier discussion is to split things up:

- one usage becomes a normal tag
- one usage is purely message routing

I think it would be least disruptive to users, who have been working around this issue for a few months, to make "Project" a normal tag and rename the message routing usage. But this will need some additional discussion.

**Comment by andrewjbtw** [comment]
From Justin C - will be easier to solve when we persist Cocina in Cocina datastore. Fedora has no place to hold routing information because tags are not in Fedora. 

Routing via rabbit requires a single key (currently a Project tag serves this purpose), but users want to make use of multiple Project tags.

**Comment by jcoyne** [comment]
@andrewjbtw I believe this is now complete. Can you test and let us know?

**Comment by andrewjbtw** [comment]
Looks good to me.
