### ISSUE TITLE
Determine readingOrder roundtrip problems

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3563]
Determine what is causing the readingOrder mapping problems for the following:
* druid:hy320vs1433
* druid:rv963gj5282
* druid:tp243qs6455
* druid:rx931qd1265
* druid:yy645nz4200
* druid:mg574qq3204
* druid:zd213tg4578
* druid:hb678bg7762

For example:
```
Druid: druid:hy320vs1433

Difference found for contentMetadata
Diff for contentMetadata:
 <?xml version="1.0" encoding="UTF-8"?>
 <contentMetadata objectId="druid:hy320vs1433" type="book">
+  <bookData readingOrder="ltr"/>
```

**Comment by jcoyne** [comment]
@justinlittman am I doing this right?

```
bin/validate-cocina-roundtrip -d druid:hy320vs1433
...
Status (n=1; not using Missing for success/different/error stats):
  Success:   1 (100.0%)
  Different: 0 (0.0%)
  Mapping error:     0 (0.0%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     0 (0.0%)
  Bad cache:     0 (0.0%)
  Validate error:     0 (0.0%)
```

**Comment by jcoyne** [comment]
In rv963gj5282 the difference appears to be whether the `<bookData>` node comes as the first child or last child of `contentMetadata`.   The source contentMetadata (https://argo.stanford.edu/view/rv963gj5282) does not have `<bookData>` so perhaps this is an artifact of where the normalizer inserts it.

**Comment by jcoyne** [comment]
druid:tp243qs6455 has a different problem.  It is an image and it looses it's bookData node on a round trip.

**Comment by jcoyne** [comment]
druid:yy645nz4200 is a type="document" with reading order. I'm pretty sure that shouldn't be allowed.

**Comment by jcoyne** [comment]
With the PR #3583 

```
hy320vs1433 - success
rv963gj5282 - different
tp243qs6455 - success
rx931qd1265 -  different
yy645nz4200 - success
mg574qq3204 - success
zd213tg4578 - success
hb678bg7762 - success
```
