### ISSUE TITLE
Remediate collectionForRegistration roundtrip problem

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3564]
For the following:
* druid:zx033qj1365
* druid:nt592gh9590

For example:
```
Diff for administrative:
 {
   "registrationWorkflow": [
 
   ],
   "collectionsForRegistration": [
-    "druid:dg763td3416"
+
   ],
```

**Comment by justinlittman** [comment]
@andrewjbtw These two objects either need `<administrativeMetadata>/<registration>` removed or `<workflow id="[wf_id]" />` added to `<registration>`.

**Comment by andrewjbtw** [comment]
I believe I've fixed both of these now.
