### ISSUE TITLE
When updating collections, tags are not being added.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3581]
See here were it is being added on DROs: (https://github.com/sul-dlss/dor-services-app/blob/c349694b206eb51ab62e99aba8ba76b826f03b20/app/services/cocina/object_updater.rb#L131)

**Comment by justinlittman** [comment]
Please make this fix after https://github.com/sul-dlss/dor-services-app/pull/3579 is merged.

**Comment by justinlittman** [comment]
@jcoyne Can you say more about which tags should be added? Same as DRO?

**Comment by jcoyne** [comment]
The *real* problem is that updating administrative.partOfProject does not save.

**Comment by jcoyne** [comment]
This seems to have been fixed by #2579
