### ISSUE TITLE
raise error to honeybadger consistently for symphony response length mismatch

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#362]
Outgrowth of PR #358:

- should dor-services-app always alert honeybadger when it receives the wrong number of bytes from Symphony?

Current code bases (argo -> dor-services-client -> dor-services-app):

### Registration: 
  - dor-services-app handles the raise and sends 500 to client;  handles the UnexpectedResponse error from client; error not sent to Honeybadger 

### Refresh Metadata:  

got the error in Honeybadger via Argo:

![image](https://user-images.githubusercontent.com/96775/64045102-55791700-cb1d-11e9-82b6-8fdd911dc38b.png)

###  MarcxmlController:  
I think this might be unused.

Should the alerts come from the same place in our code for both registration and refresh metadata?

**Comment by jcoyne** [comment]
@ndushay dor-services-client doesn't have a honeybadger dependency. So I think the first bullet in the second list needs to be revised.

**Comment by ndushay** [comment]
@jcoyne you are right - I have corrected.
