### ISSUE TITLE
Finish setting up full QA stack for testing purposes

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#3628]
We believe we need the following environments setup to allow for full integration testing in QA:

- [ ] PURL QA
- [ ] Stacks QA
- [ ] sul-embed QA

Note, this requires coordination with access/ops, and discussion with H2 PO and Infra team about usefulness.

**Comment by jcoyne** [comment]
I believe we determined this is no longer necessary as purl-test adequately serves both our qa and stage environments.
