### ISSUE TITLE
are these API endpoints needed?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#363]
(orig from sul-dlss/dor-services-client/issues/45)

For each of the following routes, we should determine if code in our stack (anywhere in the sul-dlss org) either invokes it or uses the underlying dor-services code, else we may wind up maintaining unused code:

```
              contents_object GET  /v1/objects/:id/contents(.:format)                              content#list
          read_content_object GET  /v1/objects/:id/contents/*path                                  content#read
                       catkey GET  /v1/catalog/catkey(.:format)                                    marcxml#catkey
                      marcxml GET  /v1/catalog/marcxml(.:format)                                   marcxml#marcxml
                         mods GET  /v1/catalog/mods(.:format)                                      marcxml#mods
    update_marc_record_object POST /v1/objects/:id/update_marc_record(.:format)                    objects#update_marc_record
```

If this code is used, we should write the corresponding call in dor-services-client, and use the client.

**Comment by ndushay** [comment]
@jcoyne says, regarding catalog endpoints:

> Yeah, I remember we implemented these so we could turn off the old java services
> It could be that dor-gsb-robots (deprecated) used to use it

**Comment by jcoyne** [comment]
update_marc_record is used in common-accessioning: https://github.com/sul-dlss/common-accessioning/blob/56acc53c47df5584cd3ac3e4a97b19bbfca0d840/lib/dor/release/item.rb#L75

**Comment by jcoyne** [comment]
read_contents_object is used in Argo: https://github.com/sul-dlss/argo/blob/a7fd6f33c9739fbb4055323feeed9552c0cb251a/app/controllers/files_controller.rb#L23

**Comment by jcoyne** [comment]
I don't think marcxml is ever used.

I see one request in the logs for mods:

```
production.log-20190907.gz:I, [2019-09-06T14:35:27.682409 #92126]  INFO -- : [b0a9b21f-65eb-4340-8c87-24fda609d230] Started GET "/v1/catalog/mods?catkey=1" for 171.67.35.73 at 2019-09-06 14:35:27 -0700
[dor_services@dor-services-prod log]$ nslookup 171.67.35.73
Server:		127.0.0.1
Address:	127.0.0.1#53

73.35.67.171.IN-ADDR.ARPA	name = argo-prod-a.stanford.edu.
```

**Comment by jcoyne** [comment]
I've worked to remove that call: https://github.com/sul-dlss/argo/pull/1580

**Comment by jcoyne** [comment]
The catkey endpoint will be used by google books because it allows us to get a catkey given a barcode.
