### ISSUE TITLE
Call indexer with the cocina model when creating

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3651]
https://github.com/sul-dlss/dor-services-app/blob/bab19e95747d6584bcaded3677d81cee9e750f0c/app/services/cocina_object_store.rb#L135

This will allow the indexer to skip calling-back to DSA to get the model.

See https://github.com/sul-dlss/dor_indexing_app/pull/769

**Comment by mjgiarlo** [comment]
@jmartin-sul I put this back in Ready to work on some other stuff if you want to keep at the indexing work.
