### ISSUE TITLE
Add a unique constraint on sourceId

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3665]
Now that we've switched to a postgres data store, add a constraint for sourceId.  This will avoid the problem where two registrations at the nearly the same time are able to use the same sourceId.

**Comment by justinlittman** [comment]
@jcoyne Since DROs and Collections are stored in separate tables, they will have separate uniqueness constraints. Is that acceptable?

**Comment by jcoyne** [comment]
@justinlittman  I think that would be sufficient.
