### ISSUE TITLE
Publish::License::LegacyLicenseError

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3718]
Add additional context to this HB alert, as it does not provide enough information to troubleshoot.

## Backtrace

    line 17 of [PROJECT_ROOT]/app/services/publish/license.rb: initialize
    line 58 of [PROJECT_ROOT]/app/services/publish/access_conditions.rb: new
    line 58 of [PROJECT_ROOT]/app/services/publish/access_conditions.rb: license_description

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/84462232)

**Comment by jcoyne** [comment]
@justinlittman if you look in the arguments section of HB, it shows this druid: cq570ct3323

Loading that item in Argo triggers https://app.honeybadger.io/projects/49894/faults/84255239

**Comment by jcoyne** [comment]
This is probably created by https://github.com/sul-dlss/hydra_etd/blob/40669d5ad71652b04f60a7430ff3da7ed41757b4/app/services/cocina_dro_access_generator.rb#L66-L68
