### ISSUE TITLE
upgrade infrastructure ruby app VMs to use ruby 3.1

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dor-services-app#3723]
This could be a divide-n-conquer maintenance week task, or something that first responders chip away at.

Not specific to DSA, just filing it here for tracking since DSA tends to be our repo for general infrastructure issues like this.

TODO: list out the affected projects so that we can check them off as we go.

**Comment by ndushay** [comment]
we would want to set up the puppet techstack and perhaps get the punchlist for what is needed to convert the app.

e.g. (from the top of my head, not a real list):
- install ruby on VM with ?? rvm ??
- install rubygems and bundler
- do bundler install
- do puppet change 
- deploy after puppet change
...

**Comment by jcoyne** [comment]
I believe this is done

**Comment by mjgiarlo** [comment]
Documentation: https://docs.google.com/document/d/1ihRvAYgzFzxhBj26WWroYDLVmWpGV5HFGjgrfmwWNgA/edit#heading=h.7c4f0kmus8xw

**Comment by mjgiarlo** [comment]
This is now done. It took approximately 2.5 developer-days.
