### ISSUE TITLE
RuntimeError: runtime error: file /opt/app/dor_services/dor_services/releases/20220316190834/app/xslt/MARC21slim2MODS3-7_SDR_v2-5.xsl line 4848 element attributexsl:attribute: Cannot add attributes to an element if children have been already added to the element.runtime error: file /opt/app/dor_services/dor_services/releases/20220316190834/app/xslt/MARC21slim2MODS3-7_SDR_v2-5.xsl line 4848 element attributexsl:attribute: Cannot add attributes to an element if children have been...

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3726]
## Backtrace

    line 14 of [PROJECT_ROOT]/app/models/marcxml_resource.rb: transform
    line 14 of [PROJECT_ROOT]/app/models/marcxml_resource.rb: mods
    line 28 of [PROJECT_ROOT]/app/services/metadata_service.rb: block in fetch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/84397019)

**Comment by ndushay** [comment]
is this one for @arcadiafalcone since she maintains the stylesheets?

**Comment by arcadiafalcone** [comment]
Yes, this is on me.
