### ISSUE TITLE
releaseWF not creating 856 entries for SW release

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3745]
When the releaseWF runs on druids that are attached to a catkey, it's supposed to create an an entry in a file on dor-services-prod at the path `/sdrpurl_transfer`. I think the file is called `sdr-purl-856s` and a new one is created for each day, which Symphony picks up in its nightly updates.

I've been trying to un-release https://argo.stanford.edu/view/druid:qq706tv2805 but I'm not seeing any file created at `/sdrpurl_transfer`. I tried yesterday and again this morning. I also tried releasing - not just un-releasing - and that doesn't seem to be creating a file either.

**Comment by peetucket** [comment]
The move to load balanced dor-services-app has apparently created two separate mounts for `/sdrpurl_transfer` on `dor-services-app-prod-a.stanford.edu` and `dor-services-app-prod-a.stanford.edu`. 

This is where that mount is configured: https://github.com/sul-dlss/shared_configs/blob/dor-services-app-prod/config/settings/production.yml#L48-L49

And is where we append new rows to the `sdr-purl-856s` file, and so if we create two separate versions of those files on two separate boxes, this will lead to problems.  We have verified that each of the two dor-services-app nodes has a different file.

Basically, what is happening is that when the `releaseWF:update-marc` step is run, it is making a call to dor-services-app via the dor-services-client.  This call will now end up on either of the two load balanced boxes, which will result in two separate files being created (one per node) at random.  This is not good - we need any call to dor-services-app to always append to the same file.

This is the script where that file is appended to (in dor-services-app): https://github.com/sul-dlss/dor-services-app/blob/main/bin/write_marc_record

And where that script is called from in our code: https://github.com/sul-dlss/dor-services-app/blob/main/app/models/dor/update_marc_record_service.rb#L74-L78

We also need to be mindful that there a configured cron job in puppet that runs only one of the nodes: https://github.com/sul-dlss/puppet/commit/1be45b675c22537eb4cfdb950f1dd5b93107ce04  This is fine (and in fact required), if we have a single mount shared by both nodes.  

See sul-dlss/operations-tasks/issues/2936 for the ops task to correct this

**Comment by peetucket** [comment]
Note to future first responders: this is waiting on Ops.  Track progress here: https://github.com/sul-dlss/operations-tasks/issues/2936
