### ISSUE TITLE
add version descriptions to batch of druids opened without them so that they can close

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3746]
A batch of druids was opened without version descriptions, I think because of a bug in the bulk actions that is resulting in descriptions not being added. Since the bulk actions refactor is going to go out soon, I'm going to check on stage if this issue has been fixed already.

Meanwhile, these 105 druids should all be given a version description of "Set collection":

druid:bc050yt6152
druid:bq628rn6290
druid:bq961gm0627
druid:bt532kd0804
druid:bv566tj1180
druid:bx360ht4630
druid:cb251hh5925
druid:cc344bz5254
druid:cq578nn0713
druid:cq727sg2638
druid:cs335ty8563
druid:ct186dx4385
druid:dv899wm6448
druid:dy578sv8463
druid:fh551rn0632
druid:fh848vh3709
druid:fj139yh6401
druid:fm524jw0146
druid:fm819kg0137
druid:fn833zz4188
druid:fq389ph2975
druid:fr755qz3927
druid:fs999xc8800
druid:fx386dk4956
druid:fx646vd0209
druid:fx909jr7394
druid:gp159dp5325
druid:gq469wx9165
druid:gy353hh0234
druid:gz553zn5669
druid:hc579zz7208
druid:hh614tn4413
druid:hj040xy1528
druid:hm141md9797
druid:hm747vx3309
druid:hn537qh1925
druid:hq017dc1208
druid:hs121zy5456
druid:ht742ym4675
druid:jf529ts4883
druid:jf757fj7469
druid:jq392hd4267
druid:jr206qf7725
druid:jt038cc4545
druid:jy767pr3848
druid:kb577jc8338
druid:kd711bt0941
druid:kj614jy8767
druid:kj645mh7951
druid:kk990jr3132
druid:km228ym5758
druid:kp908kx8753
druid:kv872tt5276
druid:md204bj5829
druid:mt019kz5679
druid:mt768bp3690
druid:nh212rp7533
druid:ny555nj6684
druid:pn111hn9749
druid:pz585rp1061
druid:qf873jw4608
druid:qz806ys2431
druid:rf629qw2689
druid:rg331bb3743
druid:rp753cf8989
druid:rs732dh3654
druid:rv452kj3554
druid:sb495sn3091
druid:sm245bk0620
druid:sn897xm7464
druid:st781bv9020
druid:tk187vr7607
druid:tv125qv2174
druid:tw040tm3826
druid:tw872gr2577
druid:tx068sg6928
druid:tz246pm3805
druid:vb540mn9390
druid:vj215fp5606
druid:vn404dj4238
druid:vr845md1980
druid:vz879hp0924
druid:wc411gv7296
druid:wd351qw9336
druid:wg868xn6453
druid:wh006cp2680
druid:wn760cd1657
druid:wt737vh9490
druid:ww780gm6998
druid:wz026kt3459
druid:xb893dh7617
druid:xd213kr2527
druid:xr643cb6103
druid:xt648hb0462
druid:yk763xy9034
druid:yq089jc6334
druid:yt495cb9543
druid:yw178dw4081
druid:yw373nm2893
druid:yy653hh4346
druid:yy711qg3510
druid:zk881ds3903
druid:zr547qr7079
druid:zs541gj2654
druid:zw899xw8524

**Comment by ndushay** [comment]
![image](https://user-images.githubusercontent.com/96775/160015857-c08ea919-a953-4de2-82e2-721c30e0e0bc.png)

**Comment by ndushay** [comment]
Original: 105 druids
Updated: 105 druids

These should all be closeable now.

**Comment by ndushay** [comment]
druid:bc050yt6152,5
druid:bq628rn6290,5
druid:bq961gm0627,5
druid:bt532kd0804,5
druid:bv566tj1180,5
druid:bx360ht4630,5
druid:cb251hh5925,5
druid:cc344bz5254,5
druid:cq578nn0713,5
druid:cq727sg2638,5
druid:cs335ty8563,5
druid:ct186dx4385,5
druid:dv899wm6448,5
druid:dy578sv8463,5
druid:fh551rn0632,5
druid:fh848vh3709,6
druid:fj139yh6401,5
druid:fm524jw0146,5
druid:fm819kg0137,5
druid:fn833zz4188,5
druid:fq389ph2975,5
druid:fr755qz3927,5
druid:fs999xc8800,5
druid:fx386dk4956,5
druid:fx646vd0209,6
druid:fx909jr7394,6
druid:gp159dp5325,3
druid:gq469wx9165,5
druid:gy353hh0234,5
druid:gz553zn5669,5
druid:hc579zz7208,5
druid:hh614tn4413,5
druid:hj040xy1528,5
druid:hm141md9797,5
druid:hm747vx3309,5
druid:hn537qh1925,5
druid:hq017dc1208,5
druid:hs121zy5456,3
druid:ht742ym4675,6
druid:jf529ts4883,5
druid:jf757fj7469,6
druid:jq392hd4267,5
druid:jr206qf7725,5
druid:jt038cc4545,5
druid:jy767pr3848,6
druid:kb577jc8338,6
druid:kd711bt0941,3
druid:kj614jy8767,5
druid:kj645mh7951,5
druid:kk990jr3132,4
druid:km228ym5758,5
druid:kp908kx8753,5
druid:kv872tt5276,5
druid:md204bj5829,5
druid:mt019kz5679,5
druid:mt768bp3690,5
druid:nh212rp7533,5
druid:ny555nj6684,5
druid:pn111hn9749,6
druid:pz585rp1061,5
druid:qf873jw4608,5
druid:qz806ys2431,5
druid:rf629qw2689,5
druid:rg331bb3743,5
druid:rp753cf8989,6
druid:rs732dh3654,5
druid:rv452kj3554,5
druid:sb495sn3091,5
druid:sm245bk0620,5
druid:sn897xm7464,5
druid:st781bv9020,5
druid:tk187vr7607,6
druid:tv125qv2174,6
druid:tw040tm3826,5
druid:tw872gr2577,5
druid:tx068sg6928,5
druid:tz246pm3805,5
druid:vb540mn9390,6
druid:vj215fp5606,5
druid:vn404dj4238,5
druid:vr845md1980,5
druid:vz879hp0924,5
druid:wc411gv7296,6
druid:wd351qw9336,5
druid:wg868xn6453,5
druid:wh006cp2680,5
druid:wn760cd1657,3
druid:wt737vh9490,5
druid:ww780gm6998,5
druid:wz026kt3459,6
druid:xb893dh7617,5
druid:xd213kr2527,5
druid:xr643cb6103,5
druid:xt648hb0462,5
druid:yk763xy9034,5
druid:yq089jc6334,5
druid:yt495cb9543,5
druid:yw178dw4081,5
druid:yw373nm2893,3
druid:yy653hh4346,5
druid:yy711qg3510,5
druid:zk881ds3903,3
druid:zr547qr7079,5
druid:zs541gj2654,6
druid:zw899xw8524,5

**Comment by ndushay** [comment]
script is in branch  [add-version-desc](https://github.com/sul-dlss/dor-services-app/tree/add-version-desc)
