### ISSUE TITLE
Test cocina model db update

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3750]
In the recent cocina model update, identification and structural were required for DROs and identification and administrative were required for Collections.

This change was made after QA was migrated, meaning there are rows in the db where these fields are null. This was handled in the code by replacing a null with an empty hash when instantiating cocina, e.g., https://github.com/sul-dlss/dor-services-app/blob/main/app/models/dro.rb#L22.

For this ticket, determine the steps to manually update the database so that null fields that are now required are replaced with an empty JSON object. Please document that process in this ticket.

**Comment by justinlittman** [comment]
In QA:
```
dor_services=# select count(*) from dros where identification is null or structural is null;
 count
-------
     1
(1 row)

dor_services=# select count(*) from collections where administrative is null or identification is null;
 count
-------
   127
(1 row)
```

**Comment by justinlittman** [comment]
The fix:
```
dor_services=# update dros set structural='{}'::jsonb where structural is null;
UPDATE 1

dor_services=# update collections set identification='{}'::jsonb where identification is null;
UPDATE 127
```

**Comment by jcoyne** [comment]
I believe it also would have been possible to do this, right?
```sql
ALTER TABLE dros ALTER COLUMN structural SET DEFAULT '{}'::jsonb, ALTER COLUMN structural NOT NULL
```

**Comment by justinlittman** [comment]
I'm not sure if setting the default will apply to existing data.
