### ISSUE TITLE
when mapping from Cocina to MODS, what should happen if we encounter a semantic error?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#3751]
e.g.  cocina is syntactically valid, but the cocina name "appliesTo" property doesn't match any title.

Some options:
- sent HB alert (akin to Cocina::FromFedora::DataErrorHandler)
- ensure we never, ever have semantic errors in cocina (cough, yeah, riiiiiiiiiight)
- other?

@justinlittman @arcadiafalcone

**Comment by andrewjbtw** [comment]
Naomi will provide examples.

**Comment by justinlittman** [comment]
The approach that we selected was to add validators to cocina models which raise a ValidationError. It is up to each application to determine how to handle the error.
