### ISSUE TITLE
Publish the value of the solr field "sw_display_title_tesim" as the public XML identityMetadata objectLabel

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3760]
We have to publish the `objectLabel` field in the public XML `identityMetadata` because that value gets incorporated into some Access system displays. This value should match the "title" of the object, whether it's a collection or item. 

To make sure that this field matches the title, we should insert the value of the `sw_display_title_tesim` solr field from the Argo index into the public XML. If I understand correctly, this is the value that's generated from the Cocina descriptive metadata title.

**Why not use the Cocina "label" field?**

Cocina has a "label" field which has been mapped from either the `objectLabel` in the Fedora `identityMetadata` or from the Fedora object label stored in Fedora itself. Past practice has been to publish this value directly into the identityMetadata. Why stop doing this?

The problem is that this field has never been easily editable (only available in XML) and never gets updated automatically when the descriptive metadata title changes. This means that there are at least hundreds, probably thousands, of items where the descriptive metadata title says one thing and the objectLabel says another. 

The result is that when users update a title, the Access system displays get updated everywhere the title is used, while everywhere `objectLabel` is used remains the same. This leads to situations where SW or Spotlight may show different titles for the same collection.

**Why not remediate "label" to match the descriptive "title"?**

Two reasons:

- the data structures are not compatible: the Cocina label is a simple string, while the descriptive title can hold many different subfields
- unless the label gets updated automatically when the descriptive title is updated, things will soon go back out of sync

The advantage of using the solr field is that it should always be a structurally simpler version of the descriptive title and should be close to, if not exactly the same as, what the Access systems will generate based on the MODS descriptive title.

**Why not have the Access systems stop using `objectLabel` and use the descriptive title everywhere?**

That work has been ticketed for analysis and implementation but it's not going to be complete before the Cocina migration.

**What other advantage would this change have?**

It should make it unnecessary to make the "label" field editable and might allow us to stop using "label" at all.

**Comment by andrewjbtw** [comment]
Yes, we can use that instead of solr.

**Comment by jcoyne** [comment]
Blocked by cocina-models 0.71.0 because the implementation of TitleBuilder changed.
