### ISSUE TITLE
Publish the value of the solr field "sw_display_title_tesim" in the 856 file where the identityMetadata objectLabel has been used

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3761]
This is related to #3760 

There are circumstances where the 856 generated for a SW release includes the `objectLabel` from the `identityMetadata`. I think this happens when a collection is released with a catkey, and possibly also when an item is released that is part of a collection that has also been released. 

I'm hoping it will be clearer where this happens from looking at the code but I'm sure I can find an example.

Wherever the 856 ends up including the `objectLabel` (or the Cocina "label" in the new model), we should instead use the solr field `sw_display_title_tesim`. See #3760 for the reasoning behind this. It affects the SW display.

**Comment by jcoyne** [comment]
Rather than using the solr field, can we use the Cocina::Models::TitleBuilder for this.  We are trying to remove DSAs dependency on Solr.

**Comment by andrewjbtw** [comment]
Yes.

**Comment by jcoyne** [comment]
Blocked by cocina-models 0.71.0 because the implementation of TitleBuilder changed.
