### ISSUE TITLE
Export serials info to MARC

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3765]
The content delivered to Symphony for insertion into the MARC record should include a label attribute made of the added part name/number values joined in sequence with a comma space, and a sort attribute with the value of the added sort key. (from https://docs.google.com/document/d/1Hb37KqNwpieJabXVl4KRy8wI8LIofhX8OmEOWifTOFk/edit "digital serials form input, item 5"

**Comment by edsu** [comment]
This appears related to a corresponding change in Argo? https://github.com/sul-dlss/argo/issues/3014

**Comment by jcoyne** [comment]
@edsu related in that both cover serials metadata, but they are completely independent of one another.

**Comment by edsu** [comment]
My bad, I thought that new info being entered there needs to find its way to Symphony...

**Comment by andrewjbtw** [comment]
SDR has supported serials export to MARC (entered via MODS) for a few years. Have the details changed? I thought it was already Cocinized in the last work cycle.

**Comment by justinlittman** [comment]
This is already in the code.
