### ISSUE TITLE
Set refresh: true on first catalogLink when mapping from fedora

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3767]
See https://github.com/sul-dlss/cocina-models/pull/373

Blocked until cocina-models 0.71.0 is released

**Comment by justinlittman** [comment]
See also, https://github.com/sul-dlss/cocina-models/pull/389#issuecomment-1095313240 which indicates that objects with the "Warning : Do Not Refresh" tag should have no catalogLinks with refresh.
