### ISSUE TITLE
if Symphony request times out, does approp error get surfaced to client?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#377]
We want to surface this info to the caller, in the same way we do if the number of bytes received from Symphony doesn't match the HTTP header from Symphony.

- [x] dor-services-app (PR #392)
- [x] dor-services-client (will be surfaced the same as wrong number of bytes or other errors from Symphony)
- [x] Argo
  - [x] registration (will be surfaced the same as wrong number of bytes or other errors from Symphony)
  - [x] refresh metadata action (will be surfaced the same as wrong number of bytes or other errors from Symphony)

**Comment by jcoyne** [comment]
This assumes the timeout for the connection to dor-services-app is longer than the timeout for dor-services-app connection to Symphony.

**Comment by ndushay** [comment]
good point.
