### ISSUE TITLE
validate / roundtrip scripts:  remove excess whitespace and empty elements in cocina 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#3771]
The output of `validate-cocina-roundtrip` for failed objects includes the full cocina model and the cocina roundtrip model.  These can look like the snippet below.

Note:
- empty elements can be omitted from this output
- empty elements are output with an extra line!   If we can't eliminate them, can we at least get to `[]` or `{}` ?

@mjgiarlo did some work on this for argo display of cocina (IIRC);  @justinlittman suggested that the work could be a utility in cocina-models ... maybe "json-compact" or something.

The context of this ticket is for the particular `bin/validate-cocina-roundtrip` script, but it might handily apply to other scripts here as well as being used in Argo and elsewhere (?)

```
Diff for description:
 {
   "title": [
     {
       "structuredValue": [
 
       ],
       "parallelValue": [
 
       ],
       "groupedValue": [
 
       ],
       "value": "Bibliographie von Niedersachsen",
       "identifier": [
 
       ],
       "note": [
 
       ],
       "appliesTo": [
 
       ]
     }
   ],
   "contributor": [
 
   ],
   "event": [
     {
       "structuredValue": [
 
       ],
       "date": [
         {
           "structuredValue": [
             {
               "structuredValue": [
...
```

**Comment by ndushay** [comment]
I'm willing to take that risk.  Looking at the output now is super duper painful.  The signal to noise ratio really stiinks.

**Comment by ndushay** [comment]
method name suggestion:   "human_readable" or whatever ...

**Comment by mjgiarlo** [comment]
@ndushay Yeah, I was thinking about something like `#to_human_readable_h`

**Comment by jcoyne** [comment]
perhaps`#to_compact_h`?

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> perhaps`#to_compact_h`?

I like this even better.

**Comment by ndushay** [comment]
So we do, or do not, yet want a ticket in cocina-models to see if this code should be centralized as utility methods there?  Waiting for one more app to need it?

**Comment by mjgiarlo** [comment]
@ndushay Good question! Glad you raised it. I think the case for extraction to cocina-models will be stronger once DSA can move to Rails >= 6. Currently Argo's and DSA's implementations are pretty different. Different enough that we prolly (?) don't want to try to consolidate them in the models gem.
