### ISSUE TITLE
ETag headers are not standard.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3772]
It's `ETag` not `Etag`.  See https://datatracker.ietf.org/doc/html/rfc7232#section-2.3

https://github.com/sul-dlss/dor-services-app/blob/a2272bb71c3cdc8d20adadb13a479f8d24e65f5e/app/controllers/objects_controller.rb#L219

I'm not sure how this test is passing: https://github.com/sul-dlss/dor-services-app/blob/a2272bb71c3cdc8d20adadb13a479f8d24e65f5e/spec/requests/update_metadata_spec.rb#L153

**Comment by edsu** [comment]
HTTP headers are [case insensitive](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2). Maybe the test was passing because Rails' implementation of headers reflects this?
