### ISSUE TITLE
Report for physicalLocation type in MODS

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3778]
Desired output: a list of unique values of the type attribute for physicalLocation. Should include values regardless of nesting (ex. under relatedItem).

Example druids:

* https://argo.stanford.edu/view/druid:sc466wk6345
* https://argo.stanford.edu/view/druid:pt583pq5792

**Comment by mjgiarlo** [comment]
@arcadiafalcone the results of this report after running against the entire corpus is as follows:

```
discovery
location
misc
repository
series
```
