### ISSUE TITLE
Report on physicalDescription note type in MODS

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3782]
Desired output: a list of unique values of the type attribute for physicalDescription/note. Should include values regardless of nesting (ex. under relatedItem).

**Comment by mjgiarlo** [comment]
@arcadiafalcone I ran a report for all unique values of `//mods:physicalDescription/@type` against the entire repo and it came up empty. Closing.

**Comment by arcadiafalcone** [comment]
@mjgiarlo It should be `//mods:physicalDescription/mods:note/@type` - the type attribute on the note element as a subelement of physicalDescription.

**Comment by mjgiarlo** [comment]
@arcadiafalcone 💬 
> @mjgiarlo It should be `//mods:physicalDescription/mods:note/@type` - the type attribute on the note element as a subelement of physicalDescription.

Aha! OK, here goes.
