### ISSUE TITLE
Report on nameIdentifier type in MODS

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3784]
Desired output: a list of unique values of the type attribute for nameIdentifier. Should include values regardless of nesting (ex. under relatedItem).

**Comment by edsu** [comment]
I wrote a [report](bin/reports/report-desc-access_cond_types) for this, but when I ran it it only seemed to find one value: `orcid`. Does that sound like it could be correct @arcadiafalcone? If not I can double check with someone else to make sure the code is correct.

**Comment by edsu** [comment]
@arcadiafalcone please reopen if you suspect this report might be incorrect.
