### ISSUE TITLE
Report on part types in MODS

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3786]
Desired output: a list of unique values of the type attribute for part. Should include values regardless of nesting (ex. under relatedItem).

Example MODS:
```
        <part type="article">
          <detail>
            <title>A Section</title>
          </detail>
        </part>
```

**Comment by arcadiafalcone** [comment]
It's possible there are no values for this one, so I think it's fine to trust your logic.

**Comment by lwrubel** [comment]
Thanks for the reassurance--I don't see anything wrong with it but I'm making the PR now so that other eyes can confirm.
