### ISSUE TITLE
Report on part text types in MODS

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3788]
Desired output: a list of unique values of the type attribute for part/text. Should include values regardless of nesting (ex. under relatedItem).

Example MODS:
```
        <part type>
          <text type="summary">Here is some more info about what this article is about.</text>
        </part>
```

It is possible this report will return no data.

**Comment by peetucket** [comment]
Code in #3830

Report returned no data.
