### ISSUE TITLE
Report on invalid and complex edtf dates in MODS

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3797]
This report should identify any date value (dateCreated, dateIssued, dateCaptured, dateValid, dateModified, copyrightDate, dateOther) that has an encoding attribute with the value edtf but does not match one of the patterns below. The desired output is the druid and the date value.

Same as w3cdtf:
Year:
YYYY (eg 1997)
Year and month:
YYYY-MM (eg 1997-07)
Complete date:
YYYY-MM-DD (eg 1997-07-16)
Complete date plus hours and minutes:
YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)
Complete date plus hours, minutes and seconds:
YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
Complete date plus hours, minutes, seconds and a decimal fraction of a
second
YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)

Additional
-YYYY (eg -3999)

**Comment by edsu** [comment]
@arcadiafalcone are non four digit years valid? For example:

```xml
<dateIssued encoding="edtf" point="end">135</dateIssued>
```

in https://argo.stanford.edu/view/druid:zp396ms0570

**Comment by edsu** [comment]
I ran [these patterns](https://github.com/sul-dlss/dor-services-app/blob/45b8d86bfa80dee5335d5524c2b9cae47c677e6e/bin/reports/report-desc-edtf#L17-L24) against all the druids in `/opt/app/deploy/dor-services-app/druids.txt` and it didn't find any invalid dates.

**Comment by arcadiafalcone** [comment]
Years do need to be four digits in edtf - please rerun the report with that parameter.
