### ISSUE TITLE
Report on note type values at top level only.

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3826]
Can probably be easily adapted from existing report looking for note types at all levels. Desire output: list of unique note type values.

This is looking for instances of:
```
<mods>
  <note type="summary">A note</note>
</mods>
```
But not, e.g.:
```
<mods>
  <physicalDescription>
    <note type="media">A note</note>
  </physicalDescription>
</mods>
```

**Comment by peetucket** [comment]
Code in #3829 

Results of running report attached here: [top-level-desc-note_types.csv](https://github.com/sul-dlss/dor-services-app/files/8431664/top-level-desc-note_types.csv)
