### ISSUE TITLE
Report for ISO8601 dates in MODS

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3838]
Desired output: druids, APOs, and values for dates of any kind (dateCreated, dateIssued, dateCaptured, dateValid, dateModified, copyrightDate, dateOther) with encoding="iso8601" that do not match ISO8601 encoding patterns. It looks like Ruby includes date/time gems that parse ISO8601, so I'm not providing a complete pattern list here.

**Comment by mjgiarlo** [comment]
@arcadiafalcone here are the results of this report, 3,875 hits:

[desc-iso8601.csv](https://github.com/sul-dlss/dor-services-app/files/8455171/desc-iso8601.csv)
