### ISSUE TITLE
Report on selected note types in MODS

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3843]
Desired output: druids, APOs, catkeys, and matched values for top-level note elements with the following types:
Hydrus source id
biographical /historical note
note
statement_of_responsibility

**Comment by mjgiarlo** [comment]
@arcadiafalcone here are the report results:

[desc-invalid_note_types.csv](https://github.com/sul-dlss/dor-services-app/files/8466629/desc-invalid_note_types.csv)
