### ISSUE TITLE
Updated W3CDTF date report with additional valid patterns

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3848]
Desired output: druid, APO, catkey, and date value.

This report should return records that have any date element (dateCreated, dateIssued, dateCaptured, dateValid, dateModified, copyrightDate, dateOther) that has an encoding attribute with the value w3cdtf but does not match a valid w3cdtf pattern.

Valid patterns: sul-dlss/cocina-models#392

Previous report: #3796

**Comment by lwrubel** [comment]
@arcadiafalcone: Here's the updated report with 8016 druids.
[desc-w3cdtf-updated.csv](https://github.com/sul-dlss/dor-services-app/files/8473125/desc-w3cdtf-updated.csv)

**Comment by justinlittman** [comment]
@arcadiafalcone Here is an update report:
[desc-w3cdtf.csv](https://github.com/sul-dlss/dor-services-app/files/8476222/desc-w3cdtf.csv)
