### ISSUE TITLE
Remediate dark access

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3853]
```
Druid: druid:cv643vj6157

Error: Unable to build cocina props - #<Cocina::Models::ValidationError: Not all files have dark access and/or are unshelved when object access is dark: ["cv643vj6157-1.filelist", "cv643vj6157-1.mountstr.sha"]>
```

**Comment by andrewjbtw** [comment]
I see how I missed this: there is whitespace in some of the shelve attributes: `shelve="yes "` instead of `shelve="yes"`.

Is that something we can report on? I doubt this is the only druid with this issue. When I did the big remediation last month I never noticed the attributes with whitespace, so none of them would have been changed. I'm surprised whitespace doesn't trigger any other alert.

**Comment by andrewjbtw** [comment]
Or maybe just a report on things that still fail the validation when rights are dark, since whitespace in general will get normalized out.

**Comment by justinlittman** [comment]
Here's a few more with this problem:
* druid:bf763tf1311
* druid:cv643vj6157
* druid:jq262wc2354
* druid:mf848dg7618
* druid:nt340qb5800
* druid:ny155zd0431

I'll work on a comprehensive list.

**Comment by justinlittman** [comment]
Here it is:
* druid:bf763tf1311
* druid:jq262wc2354
* druid:mf848dg7618
* druid:nt340qb5800
* druid:ny155zd0431
* druid:yj385tx3072

**Comment by mjgiarlo** [comment]
@justinlittman I see druid:cv643vj6157 came off the list. Should we assume it's been remediated?

**Comment by andrewjbtw** [comment]
bf763tf1311 was not on the original list of 83,000+ in #3605 - which makes me wonder if there are other outliers that have escaped the comprehensive druid lists. That item hasn't changed since 2020.

**Comment by andrewjbtw** [comment]
@mjgiarlo cv643vj6157 was the first druid in this ticket, so I've already handled that one.

**Comment by andrewjbtw** [comment]
These are all remediated. Except for the one druid not on the earlier ticket, the rest had whitespace in the attributes that I hadn't flipped to "no" earlier.
