### ISSUE TITLE
Require significance and description for VersionService.open

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3908]
If not present and not-blank, raise.

This is to give a gentler, kinder message to us devs via HB when we hit the db constraint.

**Comment by justinlittman** [comment]
Depends on #3907

**Comment by ndushay** [comment]
ensure dor-services-client has a good error message as well ... See https://app.honeybadger.io/projects/50568/faults/85110247:

otherwise it's this (e.g. https://app.honeybadger.io/projects/52900/faults/78761945):

```
Dor::Services::Client::UnexpectedResponse: Internal Server Error: 500 (Response from dor-services-app did not contain a body.                         
Check honeybadger for dor-services-app for backtraces,                         
and look into adding a `rescue_from` in dor-services-app                         
to provide more details to the client in the future)
```

**Comment by ndushay** [comment]
We're calling this done:

![image](https://user-images.githubusercontent.com/96775/165369396-d9feeea2-1682-458d-b7fb-cf689779bd97.png)
