### ISSUE TITLE
Clean cache

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3926]
* Delete cache filesystem on sdr-deploy
* Reduce sdr-deploy resources (processors, memory)
* Remove cron jobs

**Comment by jcoyne** [comment]
Should we add "turn off cache-o-matic cron job"?

**Comment by justinlittman** [comment]
Yup, added above.

**Comment by justinlittman** [comment]
Cron jobs removed.

https://github.com/sul-dlss/operations-tasks/issues/2988 is for rest of clean-up.
