### ISSUE TITLE
cope with "chunked" Symphony response

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#393]
https://argo-stage.stanford.edu/view/druid:mx445pq9399  has ckey 11958694;  an attempt to refresh metadata gives this error:

![image](https://user-images.githubusercontent.com/96775/64656275-c8b73e80-d3e3-11e9-9a0c-2a600425c83f.png)

Using the rails console for dor-services-app, I was able to determine the HTTP headers in the response from Symphony had no Content-Length:

```ruby
{"date"=>"Tue, 10 Sep 2019 22:29:48 GMT", "server"=>"Apache/2.4.6 ()", "strict-transport-security"=>"max-age=31536000; includeSubDomains", "access-control-allow-origin"=>"*", "content-type"=>"application/vnd.sirsidynix.roa.resource.v1+json", "via"=>"1.1 symphony-webservices-prod.stanford.edu", "connection"=>"close", "transfer-encoding"=>"chunked"} 
```

Note especially *"transfer-encoding"=>"chunked"*

So we need a way to cope with multipart responses from Symphony.

Speaking to libsys folks, we think Symphony responses may be chunked when the record is longer than X chars.

**Comment by ndushay** [comment]
This may be a clue, but I'm not sure how to hook it up and use it:  https://github.com/particle-iot/ruby-faraday-middleware/blob/master/lib/faraday_middleware/response/chunked.rb

**Comment by ndushay** [comment]
I'm about to experiment with https://github.com/lostisland/faraday_middleware

**Comment by ndushay** [comment]
See also https://lostisland.github.io/faraday/usage/streaming.   Working in a branch "chunked"

**Comment by justinlittman** [comment]
So what I think is happening is that Faraday is correctly handling chunking. However, it passes on the last set of HTTP response headers; for a chunked response, the length of the last response is always 0.

If this is correct, then length should not be validated if the response is chunked.

Or am I misunderstanding something about the problems?

**Comment by justinlittman** [comment]
Now I'm getting a different error. Is that an improvement?

![Screen Shot 2019-09-11 at 7 06 49 AM](https://user-images.githubusercontent.com/588335/64692318-d1028e80-d462-11e9-8ca0-a1861a6ae5f4.png)

**Comment by justinlittman** [comment]
Second click is a charm:
![Screen Shot 2019-09-11 at 7 22 08 AM](https://user-images.githubusercontent.com/588335/64693280-e973a880-d464-11e9-9c54-aa17de7c3c95.png)
