### ISSUE TITLE
Use versionId, not tag, to provide the default version description

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#3946]
When providing a default version description because none existed, use the `versionId` not the `tag`.

The `versionId` is:

- a whole number
- the number that people are most likely to think of as the version number
- the number used for version in the workflow service version numbering
- the number used for version in the moab version numbering

The `tag` is:

- an attempt at semantic versioning
- nearly indecipherable
- not particularly useful

Example druid where `versionId` is preferable to `tag`: 
https://argo.stanford.edu/view/druid:sv955fw2847

In that druid, Version 6 should be called "Version 6" but instead it's called "Version 2.3.0".

**Comment by ndushay** [comment]
@justinlittman I think we might want to fix in db after migration, too, in addition to in our code.

**Comment by justinlittman** [comment]
To be considered is whether changing in DB might accidentally change some user created tags / descriptions.

**Comment by ndushay** [comment]
@andrewjbtw this implies that we don't care about "significance" which only affects the tag, right?  So more fun with all the version code in DSA and elsewhere???

**Comment by ndushay** [comment]
@justinlittman I think this is all in the VersionService and all its consumers, since we no longer need to require significance as a param.

Also, we may be able to ditch "significance" (and tag) altogether once Andrew has a chance to make sure no downstream users care.

**Comment by justinlittman** [comment]
Closed in favor of #4032
