### ISSUE TITLE
Remediate dupe source ids

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3960]
Attached are a list of druids that failed migration due to dupe source ids.

[unique_errors_druids.txt](https://github.com/sul-dlss/dor-services-app/files/8603522/unique_errors_druids.txt)

**Comment by andrewjbtw** [comment]
7628 of the 7653 are from the google books pipeline. 

Looking into the remaining 25 first because those are less expected.

**Comment by andrewjbtw** [comment]
@justinlittman These items are on the duplicate list but I can't find what they are duplicates of. When I search for the sources, I just get the same druid already on the duplicate list:

```
ht764sy5850,sulcons:5797-RB_KatalogBibliothekHildebrand_dbrock
kn165jq6998,sulcons:6167-RB_Constellations_dbrock
kr750tg2424,sulcons:5842-RB_OmniumOperumDivi_v2_dbrock
kt162vg6899,sulcons:5686-DR_ComprehensiveAtlas_dbrock
mn667kv3368,sulcons:5704-RB_VirgilWorks1575_dbrock
rj281jz8766,sulcons:5957-RB_FlaxmanIliad_dbrock
vw467hk3399,sulcons:6134-RB_CooperSermon1780_c2_dbrock
yg316hv2735,sulcons:5842-RB_OmniumOperumDivi_v1_dbrock
yx031wq2873,sulcons:5835-RB_TheBorough_dbrock
zk535bm1021,sulcons:5836-RB_ArmataFragment_dbrock
```

**Comment by andrewjbtw** [comment]
Those were not indexed, despite being migrated. Do we now have the ability to make sure everything is indexed? This whole problem of post-migration duplicates is the result of our lack of full indexing coverage.

I've done everything I can with the "visible" google items but I don't know if more duplicates are hidden outside of solr.

**Comment by jcoyne** [comment]
@andrewjbtw we can reindex everything from dor-services-app (drawing from the full list in the database).

**Comment by andrewjbtw** [comment]
For the google items, the 1605 druids on this list should get migrated:
[google-books-to-migrate.txt](https://github.com/sul-dlss/dor-services-app/files/8622007/google-books-to-migrate.txt)

I don't know if there are any duplicate source ids on druids that haven't been indexed in solr that would prevent that. But those druids are the druids recorded in the Google pipeline as the "correct" ones for deposit.

I purged the other 6023 druids on the duplicate list last night.

**Comment by andrewjbtw** [comment]
I had the wrong shell commands when piping from a larger file. This is the list:
[google-books-to-migrate.txt](https://github.com/sul-dlss/dor-services-app/files/8622206/google-books-to-migrate.txt)

**Comment by andrewjbtw** [comment]
@justinlittman Ok, after another round of indexing, evaluation, and cleanup, I think this can be tried again with the same list as above. All the duplicate source ids corresponding to that list of google druids were objects with "Unknown status" and no accessioned files. I've purged those, so I think the list will now be migrate-able.

**Comment by andrewjbtw** [comment]
Yay!
