### ISSUE TITLE
Remediate unrecognized types in description: provenience

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3962]
The following items failed migration due to an unrecognized type:
```
druid:fv513pq5632
druid:gw663gy0115
druid:hq925vd4216
druid:jc957dh9590
druid:mb707vv3140
druid:ns679gq7006
druid:pv420vx5636
druid:qb122dq4313
druid:qm662nb1071
druid:rr199bk5315
druid:vb935fy0397
druid:vg484kd1345
druid:vy595ft3039
druid:yh222fk4976
druid:yy311wt3619
druid:zf510bh5519
druid:zy004bg9872
druid:zy553gq3495
```

**Comment by jcoyne** [comment]
Should this just be a substitution of 'provenance' for 'provenience'?

**Comment by arcadiafalcone** [comment]
Would it be possible to get an export of the actual metadata for these items? I can't view them in Argo, and all the ones I've looked at don't have any invalid types in the purl MODS but are registered or opened so I'm guessing what's published to purl doesn't reflect what's in the database.

**Comment by justinlittman** [comment]
You can look directly in the fedora UI, e.g.: https://sul-dor-prod.stanford.edu/fedora/objects/druid:fv513pq5632/datastreams/descMetadata/content

**Comment by arcadiafalcone** [comment]
Yes, please replace with "provenance". Also see https://github.com/sul-dlss/cocina-models/pull/457 for adding "provenance" to event type vocabulary.

**Comment by jcoyne** [comment]
I've updated the records to have 'provenance', now awaiting a cocina-models release so they stop erroring.

**Comment by justinlittman** [comment]
With cocina-models 0.77.0 deployed to prod, I have migrated these items.
