### ISSUE TITLE
Report on date ranges in collection jw357py5564

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#3965]
Requesting a report on objects in collection jw357py5564 (Barry Ruderman map collection) that have event.date.structuredValue.value with type "start" and/or type "end".

Report should include druids and values (not necessary to indicate which is "start" or "end" - OK to just concatenate with semicolon as in date validation reports).

**Comment by peetucket** [comment]
@arcadiafalcone do you happen to have a couple examples of objects that have this date type of "start" or "end" -- trying to construct the correct xpath lookup in MODs and not exactly sure what I am looking for.  I presume the reports are still running against fedora MODs (checking in with infra team now)

**Comment by arcadiafalcone** [comment]
```
<originInfo>
  <dateIssued keyDate="yes" encoding="w3cdtf" qualifier="approximate" point="start">1652</dateIssued>
  <dateIssued encoding="w3cdtf" qualifier="approximate" point="end">19--</dateIssued>
</originInfo>
```

May be dateCreated, dateCaptured etc. instead of dateIssued.

**Comment by peetucket** [comment]
Report results attached to a comment in the PR: https://github.com/sul-dlss/dor-services-app/pull/3967#issuecomment-1115371913
