### ISSUE TITLE
Implement a new endpoint for checking the embargo status of an item

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#400]
An upcoming integration point with library systems code and Yewno for ETD metadata enhancement will require libsys being able to check if a particular item is embargoed.

**Comment by jcoyne** [comment]
@peetucket the cocina data model endpoint already returns the embargo date. Can this be closed?

**Comment by peetucket** [comment]
Closing and will revisit if the new endpoint is not sufficient for some reason.
