### ISSUE TITLE
Create log of purged druids

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4002]
As a repository manager, this is something I've wanted to be able to track for a long time. It can be hard to tell what happened to a druid if it was purged from the show page or if the the bulk action log wasn't kept.

What I'd like in a log of purged druids (if it's possible to track this):

- druid
- source id
- date removed from DOR
- sunet of user who purged it

**Comment by jcoyne** [comment]
Does purging log an event in the events service? If so, this would be a pretty simple database query.

**Comment by justinlittman** [comment]
Gone means gone: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/delete_service.rb#L54
