### ISSUE TITLE
Report on invalid EDTF dates in Cocina description

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4071]
This is to check remediation progress for invalid EDTF dates. For valid date patterns, see #3797.

Desired output: druid, collection druid, catkey, date value(s).

Check for values in description..date..value with description..date.encoding.code edtf.

**Comment by ndushay** [comment]
How one might do this:

https://www.postgresql.org/docs/current/functions-json.html

```
dor_services=# select external_identifier from dros where jsonb_path_query_first(description, 'strict $.**.parallelContributor.size() > 0') = 'true' limit 1;
 external_identifier
---------------------
(0 rows)
```

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/54882009-8917-412d-8b4b-93b55e3344af
)

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/a9cab2f2-46e5-463a-a192-9471e704cac4)

**Comment by ndushay** [comment]
See https://github.com/sul-dlss/dor-services-app/issues/4073#issuecomment-1146289667

**Comment by mjgiarlo** [comment]
@ndushay 💬 
> please include source ids; see #4072's PR

I'm seeing catkey over there, not source IDs. Should that PR have had source IDs too?

**Comment by mjgiarlo** [comment]
Chatted with Arcadia and she only needs the catkey, not source ID(s).

**Comment by mjgiarlo** [comment]
@arcadiafalcone here's the bad EDTF dates report:
[bad_edtf_dates.csv](https://github.com/sul-dlss/dor-services-app/files/8865525/bad_edtf_dates.csv)
