### ISSUE TITLE
Report on invalid ISO8601 dates in Cocina description

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4072]
This is to check remediation progress for invalid ISO 8601 dates. For valid patterns, see #3849.

Desired output: druid, collection druid, catkey, date value(s).

Check for values in description..date..value with description..date.encoding.code iso8601.

**Comment by ndushay** [comment]
How one might do this:

https://www.postgresql.org/docs/current/functions-json.html

```
dor_services=# select external_identifier from dros where jsonb_path_query_first(description, 'strict $.**.parallelContributor.size() > 0') = 'true' limit 1;
 external_identifier
---------------------
(0 rows)
```

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/54882009-8917-412d-8b4b-93b55e3344af
)

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/a9cab2f2-46e5-463a-a192-9471e704cac4)

**Comment by ndushay** [comment]
See https://github.com/sul-dlss/dor-services-app/issues/4073#issuecomment-1146289667

**Comment by jcoyne** [comment]
It looks like there are 1.4million objects that contain iso8601 dates that must be checked:
```
Dro.where("jsonb_path_exists(description, '$.**.date.encoding.code ? (@ ==  \"iso8601\")')").count
   (235522.8ms)  SELECT COUNT(*) FROM "dros" WHERE (jsonb_path_exists(description, '$.**.date.encoding.code ? (@ ==  "iso8601")'))
 => 1396795
```

**Comment by jcoyne** [comment]
@mjgiarlo still running/tuning the report

**Comment by mjgiarlo** [comment]
The report code has been written and merged to DSA. @jcoyne feel free to close the issue once you've handed the report off to @arcadiafalcone (apologies if you already did and I missed it)

**Comment by ndushay** [comment]
I'm closing this;  feel free to re-open if needed.

**Comment by ndushay** [comment]
I'm closing this;  feel free to re-open if needed.

**Comment by jcoyne** [comment]
@arcadiafalcone here is the final report:
[invalid-iso8601-v4.csv](https://github.com/sul-dlss/dor-services-app/files/8862734/invalid-iso8601-v4.csv)

**Comment by mjgiarlo** [comment]
@arcadiafalcone I re-ran the report after we changed it to find more bad data. Attached:
[bad_iso8601_dates.csv](https://github.com/sul-dlss/dor-services-app/files/8865696/bad_iso8601_dates.csv)
