### ISSUE TITLE
index records missing from Solr

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4076]
part of sul-dlss/dor_indexing_app/issues/843

Aaron - making this ticket so you can attach the DSA PR(s) to it for indexing working.

See conversation in #4079 -- this ticket is to write the code that will trigger the indexing (via rabbitMQ messages heading for dor_indexing_app) for each missing druid.

So there are pieces to this:
- [ ] code to trigger indexing for each missing druid (maybe via rabbitMQ, or some other way to do them in batches for dor_indexing_app??)
- [ ] code to determine which druids aren't in Solr (see #4079 for some hints on avoiding performance hit)
- [ ] cron job to kick off the "determine missing druids -->  index missing druids" on a regular basis (weekly?  nightly?)

**Comment by mjgiarlo** [comment]
We think reindexing via Argo bulk action may suffice given there are only two affected items.

**Comment by aaron-collier** [comment]
Reindexing of the 2 missing druids complete, these now show up in argo:

https://argo.stanford.edu/view/druid:mc728hv0556
https://argo.stanford.edu/view/druid:tk287gw2645
