### ISSUE TITLE
Report on deprecated pattern for contributor name display form

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4084]
Parameters: Records with ..contributor.name.value (not ..contributor.name.parallelValue.value) with type "display". The source field in MODS is not structured so the pattern will not include structuredValue.

Return: list of item druids and collection druids.

**Comment by justinlittman** [comment]
@arcadiafalcone Can you provide an example of what to look for?

**Comment by arcadiafalcone** [comment]
Example of desired pattern:
```
{ contributor: [ {
  name: [
    { value: "Dorothy L. Sayers", type: "display" } ] } ] }
```

**Comment by jcoyne** [comment]
@arcadiafalcone here is the report I came up with:
[deprecated_display_name.csv](https://github.com/sul-dlss/dor-services-app/files/8892046/deprecated_display_name.csv)
