### ISSUE TITLE
CDL and "Stanford, None" rights are not being included in the SW release 856 export

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4085]
When an item with a catkey is released to SW, the data in the 856 should include the rights for the item. It looks like this data is not being included when the rights are either:

- View: Stanford
- Download: None

or 

- View: Stanford
- Download: None
- ControlledDigitalLending: true

Last night's releases included items with both rights cases and the resulting 856s looked like this:

```
dor_services@dor-services-app-prod-a:~$ cat /sdrpurl/Archive/sdr-purl-856s.202206070459 
12078784	rv626jh7303	.856. 40|uhttps://purl.stanford.edu/rv626jh7303|xSDR-PURL|xitem|xrights:world
12078782	vw105tx6783	.856. 40|uhttps://purl.stanford.edu/vw105tx6783|xSDR-PURL|xitem|xrights:world
12078790	ny888pc1947	.856. 40|uhttps://purl.stanford.edu/ny888pc1947|xSDR-PURL|xitem|xrights:world
14230601	cm780kj0469	.856. 41|zAvailable to Stanford-affiliated users.|uhttps://purl.stanford.edu/cm780kj0469|xSDR-PURL|xitem|xfile:cm780kj0469%2Fcm780kj0469_Being_Thunder-screener_thumb.jp2
14233536	pk376qy9915	.856. 41|uhttps://purl.stanford.edu/pk376qy9915|xSDR-PURL|xitem|xrights:world
6917505	bp826cr2306	.856. 41|zAvailable to Stanford-affiliated users.|uhttps://purl.stanford.edu/bp826cr2306|xSDR-PURL|xitem|xbarcode:36105132211504|xfile:bp826cr2306%2Fbp826cr2306_0001.jp2
14233969	fz837ms9068	.856. 40|zAvailable to Stanford-affiliated users.|uhttps://purl.stanford.edu/fz837ms9068|xSDR-PURL|xitem|xrights:group=stanford
```

For items with world and stanford rights, the rights were included. But cm780kj0469 (Stanford, none) and bp826cr2306 (CDL) are missing the rights field.

A correct CDL book should look like this:

```
u| http://purl.stanford.edu/bt411jp0567 x| SDR-PURL x| item x| barcode:36105126885370 x| file:bt411jp0567%2Fbt411jp0567_0001.jp2 x| rights:cdl 
```

**Impact**

The Access-side code relies on rights in the 856 to enable digital borrowing. This issue is blocking a user from accessing a recent request.

**Comment by peetucket** [comment]
- Do we know what the MARC rights should be set to in that file Stanford/none (e.g. cm780kj0469) ?
- The logic for setting CDL seems odd to me in the current code, basically it is setting rights to CDL in the marc file only when view="world" and download="stanford" (see https://github.com/sul-dlss/dor-services-app/blob/main/app/services/update_marc_record_service.rb#L175-L179).  Should it just use the `controlledDigitalLending` boolean in cocina, which would fix bp826cr2306, but not sure if it is also supposed to trigger for the existing case of world/stanford?

**Comment by peetucket** [comment]
Ok, so basically I will (1) remove the setting of CDL with "view:world" and "download:stanford" (not related to these items, but may be problematic sometime) and (2) add CDL anytime `controlledDigitalLending` is set to true (which will fix items like  `bp826cr2306`.  If we discover the "view:world" and "download:stanford" case needs to be handled, we can add that later, otherwise it will remain blank for now.

**Comment by andrewjbtw** [comment]
Given that, I think including CDL in the 856 would meet the requirements of the ticket. It might be worth checking with the Access team at what bits of data are actually acted upon. I remember the CDL rights coming up during the digital borrowing implementation because the records are connected to the circulation system, which doesn't happen with other rights.
