### ISSUE TITLE
refactor reports using  DateTimeValidator to use cocina-models version instead

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4090]
cocina-models#483 is to put the DateTimeValidator code into cocina-models.

The reports for #4071, #4072, and #4073 should be changed to use the code from cocina-models gem.

PR #4052 is to remove the DateTimeValidator from this repo.

**Comment by mjgiarlo** [comment]
Hi Naomi! It turns out that I was touching similar code while working on #4071 and #4073. Let's chat?

**Comment by mjgiarlo** [comment]
Assuming we don't need bespoke datetime validation, we may want to jettison the DateTimeValidator entirely.

**Comment by justinlittman** [comment]
@mjgiarlo Once the bad data has been remediated, the thought was to use the DateTimeValidator in Cocina models as a new validator to keep the data clean.

**Comment by ndushay** [comment]
This is addressed in #4091
