### ISSUE TITLE
publish the source id and otherid in the public XML identityMetadata (again)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4095]
During the Fedora migration, we stopped publishing source id and other id to the identityMetadata block of XML. It turns out that digital borrowing needs both pieces of data in order to enable circulation. So we need to start publishing those fields again.

Example: https://argo.stanford.edu/view/druid:bp826cr2306

This item has a barcode in both the source id and in the barcode field. Neither of those fields have their data published to the public XML. To support digital borrowing, we need to publish them so the identityMetadata looks like this:

```xml
<sourceId source="sul">36105132211504</sourceId>
<otherId name="catkey">6917505</otherId>
<otherId name="barcode">36105132211504</otherId>
```

**Comment by jcoyne** [comment]
@andrewjbtw so that we can better document the consumers, can you indicate in which codebase "digital borrowing" is reading this xml?
