### ISSUE TITLE
Rake task to generate ACLJ file for pywb

### ISSUE THREAD

**Issue by edsu** [sul-dlss/dor-services-app#4114]
In order to bootstrap pywb's [ACLJ file](https://pywb.readthedocs.io/en/latest/manual/access-control.html?highlight=aclj#access-control-files-aclj) it should be possible to run a database query to identify Seed Objects which have access rights that are dark or Stanford only. These can translate into an ACLJ file that can be manually added to was-pywb-prod. It would be useful if this ACLJ generator could be run as a rake task.

**Comment by edsu** [comment]
As a preliminary step I queried the production database and only found one Web Archive Seed object that has access.view set to `dark`:

```ruby
Dro.where(content_type: Cocina::Models::ObjectType.webarchive_seed).each do |dro|
  puts dro.external_identifier if dro.access["view"] != "world"
end
```

https://argo.stanford.edu/view/druid:bf328fb5614

So unless users are expecting to be able to change rights in Argo perhaps this rake task is not necessary?

**Comment by edsu** [comment]
I generated the ACLJ file using the existing exclusion.txt file and pywb's wb-manager command:

```bash
$ wb-manager acl importtxt access.aclj exclusion.txt exclude
```

I've copied the resulting `access.aclj` file into place on qa, stage and prod.

**Comment by lwrubel** [comment]
Closing based on PO feedback.
