### ISSUE TITLE
Rerun name displayForm report

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4128]
Checking remediation status.

**Comment by ndushay** [comment]
Arcadia:  are you referring to this report?   When we cut over to postgres, we lost the ability to run reports against the fedora cache, so "rerun" is not a great description, especially without reference to a ticket or PR number for the previous report.

https://github.com/sul-dlss/dor-services-app/issues/4084

**Comment by arcadiafalcone** [comment]
Yes, that's the one - apologies for not including the direct link. All the examples in that ticket were cocina-based, so I thought it had been run against the new database.
