### ISSUE TITLE
Re-Write and run  Ruderman date report

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4129]
Original report in #3965. May need to be adapted to run on Cocina instead of MODS.

**Comment by aaron-collier** [comment]
Note: When reviewing one of the objects in the original report (https://argo.stanford.edu/view/druid:bb319jh1922) @arcadiafalcone suggests this isn't quite right yet and will investigate.

**Comment by aaron-collier** [comment]
I reran this report with a simple query:
```
Dro.where("jsonb_path_exists(structural, '$.isMemberOf ? (@ == \"druid:jw357py5564\")')").where("jsonb_path_exists(description,'$.event.date.structuredValue.type ? (@ == \"start\" || @ == \"end\")')").count
```

which found only: https://argo.stanford.edu/view/druid:hf181nf1918

According to @arcadiafalcone , this is now closable.
