### ISSUE TITLE
Report on EDTF dates containing 'x' or 'X'

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4143]
Report on all (any) dates within a cocina description with `encoding: "edtf"` and a value containing the character upper case `X` or lower case `x`. Output data should include druid, collection, catkey, and value. Concatenate multiple values for the same record with a semicolon.

Analysis for https://github.com/sul-dlss/mods/issues/54

See also #4071 for related report.

**Comment by ndushay** [comment]
@arcadiafalcone I found NO instances of dates encoded as edtf with either 'x' or 'X'.     I checked my reports by looking for '1' instead, and that got output.

**Comment by ndushay** [comment]
I'm going to close this ticket;  if it is still needed, please re-open it.
