### ISSUE TITLE
Report on invalid name URIs

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4144]
Report on values of ..name.uri that do not match the URI pattern (i.e. beginning with something other than `http://` or `https://`, or ending with `.html`.

Output should include druid, collection druid, catkey, and value. Multiple values should be concatenated with `;` separator.

**Comment by jcoyne** [comment]
I ran this query:
```ruby
Dro.where("jsonb_path_exists(description, '$.contributor.name.uri ? (@ like_regex \"^(?!https?://).*$\")
')").limit(10)
```

**Comment by jcoyne** [comment]
@arcadiafalcone the full report is here: https://gist.github.com/jcoyne/6d6cdc8e7a930e8aa7b23ac8a2cf2b1c

**Comment by arcadiafalcone** [comment]
@jcoyne This should pull the item catkey rather than the collection catkey as it currently does.

**Comment by jcoyne** [comment]
@arcadiafalcone it's not currently pulling the collection catkey, but it may have a "previous catkey" is that consistent with what you see?

**Comment by arcadiafalcone** [comment]
@jcoyne That is correct - in that case the previous version of the report is fine for now. Closing.
