### ISSUE TITLE
Report on language URIs in descriptive metadata

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4151]
Criteria: values of the following properties at any level that do not begin with `http://` or `https://`, or that end with `.html`
-language.uri
-language.script.uri
-valueLanguage.uri
-valueLanguage.valueScript.uri

Output: object druid, collection druid, object catkey, value

See #4144 for a similar query.

**Comment by jcoyne** [comment]
Report generated: https://gist.github.com/jcoyne/4cb91a08d66693eab2c725138d922b78

**Comment by arcadiafalcone** [comment]
@jcoyne I think this is pulling the collection catkey rather than the item catkey.

**Comment by arcadiafalcone** [comment]
Still needs some tweaking, see above comment

**Comment by aaron-collier** [comment]
@arcadiafalcone I believe this can be re-closed by: https://github.com/sul-dlss/dor-services-app/pull/4155 is that correct?

**Comment by arcadiafalcone** [comment]
@aaron-collier Once I have the link to the updated report, yes.

**Comment by aaron-collier** [comment]
ah, apologies for missing that :-)

**Comment by jcoyne** [comment]
@arcadiafalcone no, this isn't the collection catkey, it's from the object.  What lead you to say this?

**Comment by jcoyne** [comment]
I think the problem is that it's matching on previous catkeys too:
```json
"catalogLinks": [
           {
                "catalog": "previous symphony",
                "refresh": false,
                "catalogRecordId": "13236277"
            }
        ],
```

**Comment by arcadiafalcone** [comment]
@jcoyne In that case this is fine for now. Closing.
