### ISSUE TITLE
Report on location URIs in descriptive metadata

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4152]
Criteria: values of `event.location.uri` that do not begin with `http://` or `https://` or which end with `.html`.

Output: object druid, object catkey, collection druid, value of `uri`, value of sibling `code`, value of sibling `value`

**Comment by jcoyne** [comment]
report is here https://gist.github.com/jcoyne/c671e5223885cd9fcb702be7ff313cf2

**Comment by arcadiafalcone** [comment]
@jcoyne Is it possible to include the additional requested output fields as well?

**Comment by arcadiafalcone** [comment]
Also please confirm that this is checking for the item catkey rather than the collection catkey.

**Comment by arcadiafalcone** [comment]
Still needs some tweaking, see above comments

**Comment by jcoyne** [comment]
@arcadiafalcone how's this: https://gist.github.com/jcoyne/7c5d36990abdf98ae1a40deac160880e

**Comment by arcadiafalcone** [comment]
@jcoyne Great, thanks!
