### ISSUE TITLE
Report on invalid form URIs

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4178]
Report on values of `..form.uri` that do not match the URI pattern (i.e. beginning with something other than `http://` or `https://`, or ending with `.html`.

Output should include druid, collection druid, catkey, and value. Multiple values should be concatenated with ; separator.

**Comment by arcadiafalcone** [comment]
Example druid: vg425tv5042

**Comment by ndushay** [comment]
[invalid-form-uris-report.csv](https://github.com/sul-dlss/dor-services-app/files/9338949/invalid-form-uris-report.csv)

**Comment by ndushay** [comment]
@arcadiafalcone closing this as the report should now be attached;  it is also merged into the app so it can be rerun.
