### ISSUE TITLE
Report on invalid role URIs

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4180]
Report on descriptive metadata where contributor.role.uri does not begin with `http://` or `https://`, or does end with `.html`.

Report should return object druid, collection druid, catkey, and value, with multiple values concatenated with a ;.

**Comment by arcadiafalcone** [comment]
Please also include contributor.role.source.uri.

**Comment by arcadiafalcone** [comment]
Example druid: vg425tv5042

**Comment by ndushay** [comment]
@arcadiafalcone closing this as the report should now be attached;  it is also merged into the app so it can be rerun.
