### ISSUE TITLE
Report on unexpected name URIs

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4185]
Report is for values of contributor..name..uri (excluding source.uri) anywhere in the descriptive metadata that do not begin with any of the following (for http or https) and have at least two characters after the matched pattern:
```
http(s)://id.loc.gov/authorities/names/
http(s)://id.loc.gov/vocabulary/organizations/
http(s)://vocab.getty.edu/ulan/
http(s)://viaf.org/viaf/
```
Report output should include object druid, catkey, collection druid, collection name, and the value. If a record returns multiple matches, the values should be concatenated on one line with a semicolon.

Test object vz332dg7306 has 3 incorrect role URIs.

**Comment by jcoyne** [comment]
@arcadiafalcone I'm having trouble understanding these two clauses:
> do not begin with any of the following (for http or https) and have at least two characters after the matched pattern

What is the "matched pattern" in this case?

**Comment by arcadiafalcone** [comment]
@jcoyne The pattern is the matched URL, for example https://id.loc.gov/authorities/names/. https://id.loc.gov/authorities/names/12 would not be in the report, but https://id.loc.gov/authorities/names/1 would. I've clarified the language above.

**Comment by ndushay** [comment]
Report is here:  https://gist.github.com/ndushay/1a354f424a1295828515fb7d1c8c7bc9

**Comment by ndushay** [comment]
looks like lots of 
- `http://id.loc.gov/vocabulary/organizations` without additional chars
- `http://viaf.org/viaf/xxx`
- `https://lccn.loc.gov/nxxx` though perhaps too many of them end `n88638669` to be correct ...

**Comment by ndushay** [comment]
report without viaf:

https://gist.github.com/ndushay/442ddf6df15c89fde40e4cf2b4cefb8f

1373 of 'em now.

**Comment by ndushay** [comment]
[invalid-name-uris-report3.csv](https://github.com/sul-dlss/dor-services-app/files/9397937/invalid-name-uris-report3.csv)
