### ISSUE TITLE
Report on unexpected location URIs

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4188]
Report is for values of event..location..uri (excluding source.uri) anywhere in the descriptive metadata that do not begin with any of the following (for http or https) or do not have at least two characters after the matched URL pattern (i.e., after the final slash):

```
http(s)://id.loc.gov/authorities/names/
http(s)://id.loc.gov/vocabulary/geographicAreas/
http(s)://id.loc.gov/vocabulary/countries/
http(s)://www.geonames.org/
http(s)://www.wikidata.org/wiki/
```

Report output should include object druid, catkey, collection druid, collection name, and the value. If a record returns multiple matches, the values should be concatenated on one line with a semicolon.

Test object vz332dg7306 has 2 incorrect location URIs.

**Comment by jcoyne** [comment]
@arcadiafalcone I don't see any matches for this on vz332dg7306. Is it supposed to match?

I'm running this code:

```ruby
url_patterns = [
    'id\.loc\.gov/authorities/names/',
    'id\.loc\.gov/vocabulary/geographicAreas/',
    'id\.loc\.gov/vocabulary/countries/',
    'www\.geonames\.org/',
    'www\.wikidata\.org/wiki/']
sql = "SELECT external_identifier, jsonb_path_query_array(description, " \
"'$.**.event.location.uri ? (@ like_regex \"^https?://(?!#{url_patterns.join('|')}).*$\")') " \
"FROM dros " \
"WHERE jsonb_path_exists(description, " \
"'$.**.event.location.uri ? (@ like_regex \"^https?://(?!#{url_patterns.join('|')}).*$\")') AND external_identifier = 'druid:vz332dg7306'"
```

which results in this sql:
```sql
SELECT external_identifier, jsonb_path_query_array(description, '$.**.event.location.uri ? (@ like_regex "^https?://(?!id\.loc\.gov/authorities/names/|id\.loc\.gov/vocabulary/geographicAreas/|id\.loc\.gov/vocabulary/countries/|www\.geonames\.org/|www\.wikidata\.org/wiki/).*$")') FROM dros WHERE jsonb_path_exists(description, '$.**.event.location.uri ? (@ like_regex "^https?://(?!id\.loc\.gov/authorities/names/|id\.loc\.gov/vocabulary/geographicAreas/|id\.loc\.gov/vocabulary/countries/|www\.geonames\.org/|www\.wikidata\.org/wiki/).*$")') AND external_identifier = 'druid:vz332dg7306'
```

**Comment by arcadiafalcone** [comment]
My mistake, it should match now.

**Comment by ndushay** [comment]
report here:  https://gist.github.com/ndushay/a07ca1800016e040ebd7f3fe72dea83b

Lots of getty location uris like this:
- druid:vk383mh4657,,druid:cr247kt0623,http://vocab.getty.edu/tgn/1112357,cau,“California, Gulf of”- 
- druid:vg592dw2602,,druid:xd695sf9329,http://vocab.getty.edu/page/tgn/7430399,,“Oaxaca”

And some like this:
- druid:vg755gm3310,,druid:xt708rr0510,http://id.loc.gov/authorities/subjects/sh85117096,,“San Francisco Bay Area (Calif.)”

Care for any more exclusions?

**Comment by ndushay** [comment]
[invalid-location-uris-report2.csv](https://github.com/sul-dlss/dor-services-app/files/9397935/invalid-location-uris-report2.csv)
