### ISSUE TITLE
Change content diff endpoint so that current content doesn't need to be passed in

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#419]
Dor-service-app could load the current content instead.
https://github.com/sul-dlss/common-accessioning/blob/71facfec09d08cdfda30a703b73088fb67b71a97/lib/technical_metadata_service.rb#L52

**Comment by aaron-collier** [comment]
@jcoyne doing a quick search through our repos, I think this issue is no longer valid. Can you confirm? Thanks.

**Comment by jcoyne** [comment]
yes, no longer valid.
