### ISSUE TITLE
Republish all objects in a collection when a collection is changed 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#4195]
When a collection is published,
then republish all of the published items that are not "opened" in that collection.

Ref sul-dlss/happy-heron#2354

> updating the collection name on the Purl requires updating the public XML, which mean republishing the XML for each item in a collection after its collection’s name has been updated. There’s no way to avoid having to do this because the Purls are static and there’s no rolling process to pull in new data. So what we’d need to do every time a collection name is updated would be to republish (but not necessarily re-release) every item in the collection (except for Registered items and dark items since they have no Purl). This is generally safe to do for items that already have Purls except in the case of items that are “Opened” – these might be in the process of being edited and could contain metadata not ready to be published.

**Comment by jcoyne** [comment]
@andrewjbtw can you help define this a little clearer?  Do we want to republish items that are opened or not?  Do we want to restrict this just to a collection name change or for any change to a collection?  If restricted to a name change, where do we want to look to know if the name has changed?  One possibility here is to look at the published version of the cocina (e.g.: https://purl.stanford.edu/md919gh6774.json)  and see if the title in that version has changed.

**Comment by andrewjbtw** [comment]
I suppose there's no way to republish only the description change? The reason I think we should not automatically publish Opened objects is there are too many ways the public xml/cocina can get out of sync:

- rights changes that shouldn't be applied yet
- differences in what files have been shelved vs. the files listed in the public Cocina (accessionWF brings these in sync)
- changes to content/resource type that shouldn't be applied yet

The description alone won't affect user-facing functionality but changes to other data could result in broken links, etc. Opened items will get published when they're closed, so they should still end up with the new collection title on the purl.

To detect a change in title, I can think of two ways:

- check against the public cocina
- compare the most recent internal cocina with the last cocina to have been saved in the previous object version

**Comment by jcoyne** [comment]
> I suppose there's no way to republish only the description change? The reason I think we should not automatically publish Opened objects is there are too many ways the public xml/cocina can get out of sync:

Ideally, the PURL server would have an  API and we could send it a "Change collection name" message and it could do this, but in the current architecture and given the current originazational boundaries, this doesn't seem feasable.

**Comment by cbeer** [comment]
PURL is stateless (by design) and has no link between a collection and its members (by design?), but adding an API method to purl-fetcher that touches all the known collection members seems pretty trivial.

**Comment by andrewjbtw** [comment]
I'm not sure where we are on this PR. I think exclude "Opened" objects from an automatic republish is the safest course of action if we're making no other changes to how Purl publishing works.

**Comment by mjgiarlo** [comment]
@andrewjbtw I have a PR ready for testing. Happy to work with you on that when you're available. (I.e., I would heartily welcome your help testing this!)

**Comment by andrewjbtw** [comment]
@mjgiarlo if argo-stage isn't needed for anything else, you could deploy there and I'll test today or tomorrow.

**Comment by andrewjbtw** [comment]
Oh, I guess this isn't Argo, but same considerations apply. Just a higher chance that DSA might be needed for something else on stage.

**Comment by mjgiarlo** [comment]
@andrewjbtw Sounds good. I have deployed the changes to (DSA) stage now. 🍻
