### ISSUE TITLE
Rerun date validation reports

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4209]
~~HOLD till date validation is turned back on https://github.com/sul-dlss/cocina-models/issues/518~~

1. Update the edtf report: #4218
2. Rerun three existing reports for invalid dates in w3cdtf, edtf, and iso8601 encodings.
3. Remediate bad dates found in report.
4. Revert the date exceptions in cocina-models in sul-dlss/cocina-models#521, release cocina-models, deploy everything.
5. Rerun the three reports again to make sure no bad dates slip through.

**Comment by peetucket** [comment]
Are these the three reports?

- https://github.com/sul-dlss/dor-services-app/blob/main/app/reports/bad_w3cdtf_dates.rb
- https://github.com/sul-dlss/dor-services-app/blob/main/app/reports/bad_edtf_dates.rb
- https://github.com/sul-dlss/dor-services-app/blob/main/app/reports/bad_iso8601_dates.rb

**Comment by arcadiafalcone** [comment]
Yes.

**Comment by peetucket** [comment]
Running reports now before validation is changed.

BadW3CDTF:

```
item_druid,collection_druid,catkey,invalid_values
druid:nt378cz3315,druid:kp887kn2294,,4/6/19
druid:rq763ns6811,druid:kp887kn2294,,4/6/19
druid:vk107pm8726,druid:xs048zp7815,,8/1/22
druid:cz210jv4565,druid:xs048zp7815,,8/1/22
```

**Comment by peetucket** [comment]
BadEdtf:

```
item_druid,collection_druid,catkey,invalid_values
druid:by052zc6748,druid:br508kk5736,,250
druid:py523gk3381,druid:br508kk5736,,-148
druid:pz335jq2154,druid:br508kk5736,,-245
druid:qw379nm1681,druid:br508kk5736,,197
druid:xh603zr5591,druid:br508kk5736,,150
druid:yr135dr4419,druid:br508kk5736,,-170
```

**Comment by peetucket** [comment]
BadIso6081:

```
item_druid,collection_druid,catkey,invalid_values
druid:jz235fc6523,druid:wk956yb8565,,8/3/22
```

**Comment by arcadiafalcone** [comment]
I can't access the ISO 8601 record to fix it - did date validation get turned on? I remember now it's not possible to access records that don't pass cocina validation via Argo (which makes it difficult to fix them).

**Comment by peetucket** [comment]
Hmm, I didn't turn on any validation. Will check in channel.

**Comment by peetucket** [comment]
Reports rerun after druids above remediated and no druids returned.

**Comment by peetucket** [comment]
Re-run after new cocina-models changes in https://github.com/sul-dlss/cocina-models/issues/518 have been released and deployed.

**Comment by jcoyne** [comment]
Blocked by https://github.com/sul-dlss/dor-services-app/pull/4213

**Comment by ndushay** [comment]
So we know about remaining problem edtf dates from #4226.   For iso8601 dates, we're in the clear.

For w3cdtf dates, I have to tweak the report, which I am doing now.

**Comment by ndushay** [comment]
I have rerun all three updated reports (updated to catch more dates -- see PR #4231) and we are currently showing NO invalid dates.

Next steps:
- [ ] update cocina-models to be stricter about the edtf dates (removing the relaxation https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/validators/date_time_validator.rb#L80 )
- [ ] deploy updated apps
- [ ] run the 3 validation reports one more time (InvalidXXXDates.rb where XXX is w3cdtf, edtf and iso8601)
