### ISSUE TITLE
Retry on Symphony error

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#421]
When doing a refresh metadata, sometimes Symphony has locked the records and we get a response like this:

Status: 500
```
{"messageList":[{"code":"hatErrorResponse.116","message":"The records are currently in use.  Please try again later."}]}
```
## Request

POST https://dor-services-prod.stanford.edu/v1/objects/druid:mj644hc4989/refresh_metadata 

## Backtrace

    line 55 of [PROJECT_ROOT]/app/models/symphony_reader.rb: symphony_response
    line 80 of [PROJECT_ROOT]/app/models/symphony_reader.rb: json
    line 84 of [PROJECT_ROOT]/app/models/symphony_reader.rb: bib_record

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/54913406)

**Comment by ndushay** [comment]
This is probably the same as #433.
