### ISSUE TITLE
Report on subjects containing "--"

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4228]
Report on subject.value, subject.structuredValue.value, and subject.parallelValue.value (with any number of structuredValue and/or parallelValue as intermediaries between subject and value) containing the string "--".

Report should return druid, catkey, collection druid, collection name, and value.

Test druid vz332dg7306 should return four results.

**Comment by jcoyne** [comment]
[double_dash.csv](https://github.com/sul-dlss/dor-services-app/files/9567495/double_dash.csv)
Here's the report @arcadiafalcone
