### ISSUE TITLE
Report on events with multiple date types

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4229]
Report should include records with multiple dates within the same event that have different types.

Returned data should include druid, catkey, collection druid, collection name, and a list of the date types contained within the event.

Results should include sample druid bh845qb8447.

**Comment by ndushay** [comment]
@arcadiafalcone I'm confused.  Is this:

- events with multiple types
- dates of multiple types within a single event
- multiple dates in a single event when the dates have different encodings

**Comment by arcadiafalcone** [comment]
The second one.

**Comment by ndushay** [comment]
This was tricky for me to implement.  I believe I got there in the end.
[EventsMultipleDateTypes.csv](https://github.com/sul-dlss/dor-services-app/files/9586804/EventsMultipleDateTypes.csv)
