### ISSUE TITLE
Modify existing subject report to exclude some records

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4237]
Modify the report created for https://exhibits.stanford.edu/parker/catalog/wz026zp2442 to exclude subjects where source.code is not `lcsh` or `naf`.

**Comment by ndushay** [comment]
Do you have a ticket number or a report name for this?   Was it run after we were off fedora?  Was it #4214 ?

**Comment by arcadiafalcone** [comment]
Sorry, wrong link from the clipboard. The report is https://github.com/sul-dlss/dor-services-app/issues/4228.

**Comment by ndushay** [comment]
[SubjectsWithDoubleDash.csv](https://github.com/sul-dlss/dor-services-app/files/9619748/SubjectsWithDoubleDash.csv)

9387 of 'em.
