### ISSUE TITLE
Publication date mismatch

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#4253]
These druids have a publication date that has an edtf encoded value and a structured value that are not in agreement:
```
"druid:ct503zg9433",
 "druid:mx151nn9365",
 "druid:nw987sj3048",
 "druid:sg156yw7438",
 "druid:vh225xq6457",
 "druid:vp123jj3577"
```

The edtf was updated in https://github.com/sul-dlss/happy-heron/issues/2086, but the structured value was not changed.

@arcadiafalcone how would you like us to fix these?

**Comment by arcadiafalcone** [comment]
Having the date range represented using EDTF format breaks MODS display:
https://app.honeybadger.io/projects/49894/faults/88773221
https://app.honeybadger.io/projects/49629/faults/85138665

The date.value should be removed and the "-01" should be dropped from the date.structuredValue in the Cocina.

**Comment by jcoyne** [comment]
These items have been remediated.
