### ISSUE TITLE
Globus integration discussion

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#4269]
Idea:
- single shared folder for all H2 deposits is created in globus
- a new folder is created per work and per version as needed by the API, with permissions set ti the depositor's sunet (folder for work ID, sub-folder for version)
- depositor is directed to place content in this folder and indicate when done (by clicking a special link, or returning to the work and checking a box, or some other mechanism TBD)
- this starts to the process of accessioning, which may involve moving files from the globus folder, at which point the that folder is set to read only (or files are deleted?) to prevent changes by the API
- if a new version is needed, the API will create a new version sub-folder in the same work ID folder
- a new work will create a new work ID folder

Changes needed to H2:
- new globus client to perform API actions (see #4272)
- a new email to user when globus folder is ready with endpoint
- a new email to user when folder is set to read only and/or files deleted
- changes to the globus checkbox and instructions to user on the work deposit page
- a mechanism for the user to indicate their files have been moved to globus
- new background job to take care of moving files from globus to the correct location and making changes to the globos folder

Changes needed to other apps:
- TBD based on #4270 and on if the content is moved from Globus to /dor/workspace or is accessioned directly from globus

**Comment by peetucket** [comment]
@rsmith11 what are the next steps to getting access to the globus API so we can begin testing it out?  and I am remembering correctly that we will be using production services (but can work in a separate folder area?)

**Comment by peetucket** [comment]
See https://docs.google.com/document/d/1kB3dZdlPn9znH85c12H0qDbK4oRfQAkSg_rmEFk4k-c/edit for where H2 files move

**Comment by lwrubel** [comment]
Questions:

1. Process for getting files to preservation? Any further work to document?
2. What is the upper limit for file size support? 
- Explore through testing and talking to POs
- If we were ever to need it, the [Globus Transfer API](https://docs.globus.org/api/transfer/file_operations/#dir_listing_response) can provide file info (including filesize)
3. What is the update use case? Question for Amy and Andrew.
- Are updates a full replacement or just new stuff? 
- Full replacement is easier requirement to satisfy. What is user need?
4. Do we need to be concerned about the amount of space that these files are taking up on Globus?
- Would we delete content at some point?
- How does the mount work? (Where are the files living?)

**Comment by rsmith11** [comment]
Globus API client is setup.  `client_id` and `client_secret` are stored in vault at `puppet/application/h2/globus/`.  The Globus endpoint UUID is `34ea3e65-6831-479a-8da3-87f118e3fc2b`.  The friendly name is `H2 test endpoint`.  Currently only the Globus admins and that token have access to the endpoint, but we can change that later.  

The Globus SDK and API info can be found at https://globus-sdk-python.readthedocs.io/en/stable/index.html.

**Comment by peetucket** [comment]
> Globus API client is setup. `client_id` and `client_secret` are stored in vault at `puppet/application/h2/globus/`. The Globus endpoint UUID is `34ea3e65-6831-479a-8da3-87f118e3fc2b`. The friendly name is `H2 test endpoint`. Currently only the Globus admins and that token have access to the endpoint, but we can change that later.
> 
> The Globus SDK and API info can be found at https://globus-sdk-python.readthedocs.io/en/stable/index.html.

Thanks Rob.  I can see the client_id and client_secret in vault.  Haven't tried doing anything though.  So since only the globus admins and the token have access, we won't see that endpoint in our personal connect (just verifying)

Also, a couple other questions... we talked about reading from globus via an NFS mount, but are curious how that works.  Are files in globus copied onto that mount or do they live on globus and we just get a sort of symlink over to them, i.e. where does the content actually live?  This has some implications for if we need to care about how/when users clean off that mount or how we accession from it (or not).

also,

**Comment by peetucket** [comment]
Thanks, just tested uploading a file via the UI and it worked.

So if I am understanding correctly, if/when we setup an NFS mount, we will need to be mindful of file storage limits on our volume, as anything uploaded to that globus endpoint will take up space on our mount?

**Comment by lwrubel** [comment]
@peetucket @rsmith11 could you provide me access to the endpoint? Also @justinlittman and @aaron-collier.

**Comment by lwrubel** [comment]
@rsmith11 to clarify, this request is to be able to access the endpoint via Personal Connect as lwrubel@stanford.edu. (It's helpful for testing.)

**Comment by lwrubel** [comment]
I see that `/globus/h2/` [is now mounted](https://github.com/sul-dlss/puppet/pull/8791) to `dor-services-app-qa` and `-stage` etc. Thanks, @rsmith11! 

I confirmed that from dor-services-app-qa I could see a file that I had previously uploaded via Personal Connect to `lwrubel/work1234/`

**Comment by mjgiarlo** [comment]
I'm not sure we have anything else to do here, so I'm closing this issue for now.
