### ISSUE TITLE
Analysis: what needs to change to integrate a globus endpoint/mount into accessioning/preservation pipeline

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#4270]
There are two possible paths that we may take with Globus integration:

1. content from globus is moved into an existing location (e.g. /dor/workspace) prior to accessioning, in which case we may not need to change any workflows/processes
2. content from globus stays there and is accessed by the rest of our accessioning workflows directly, which thus need to recognize that content may from an alternate location

So this ticket is to verify that if 1 is true, we do not need to make any changes, and if 2 is true, some understanding of what may need to change.  In other words, which apps would need to be updated/changed in order to allow content coming from an globus endpoint (possibly seen as an NFS mount) into the accessioning pipeline.

We are currently leaning towards 1, but would like to have a better understanding of common use cases and file limitations, so it would be nice to understand the implications of both scenarios.

- [x] investigate how files are processed by H2 and move into the accessioning pipeline
see https://docs.google.com/document/d/1kB3dZdlPn9znH85c12H0qDbK4oRfQAkSg_rmEFk4k-c/edit
- [ ] investigate how large content works with pre-assembly (e.g. video files, maps) and then symlinks are made
- [x] investigate how warcs and google books use the accessioning pipeline (these also have large content)
- [ ] what changes would be needed for preservation if content is accessioned from a globus endpoint directly as opposed to being in /dor/workspace

**Comment by justinlittman** [comment]
H2 and GB are deposited via the SDR API. In both cases, the files are transferred via HTTP to the SDR API. The SDR API then writes them to the DOR workspace.

**Comment by justinlittman** [comment]
For web archives, a WAS robot copies the files to the DOR workspace: https://github.com/sul-dlss/was_robot_suite/blob/main/lib/robots/dor_repo/was_crawl_preassembly/build_was_crawl_druid_tree.rb

**Comment by peetucket** [comment]
Presumably files coming from globus are large enough that we do not want to transfer via HTTP to SDR API, so the WAS approach may make more sense, so it does introduce another job or robot into the mix.  

Another (potentially less desirable) possibility is having the globus folder mounted on our various services (robots, techMD, etc.) and have each of these services check both the dor mount and the globus mount for files.  This saves copying content onto the dor mount and the potential space issues this may introduce, but introduces complexity in other apps.  I know we had done this in the past, though I think we removed it at some point.  Rob has mentioned that globus can be mounted on our services so we can read files from it directly (for either copying or directly working with).

**Comment by lwrubel** [comment]
During the analysis workcycle, Rob mounted the h2 Globus endpoint folder to DSA QA. It's still there if useful for trying out any approaches.

**Comment by justinlittman** [comment]
I'd propose that copying files from globus endpoint to DOR workspace be a responsibility of SDR API (just as it is currently responsible for copying files from ActiveStorage to DOR workspace).

**Comment by peetucket** [comment]
Would this be a new endpoint on SDR API ?  Basically: 

- params: globus input folder path, dor output path
- action: copy files from globus folder to dor folder

And H2 makes the SDR API call with the appropriate params upon deposit?

**Comment by justinlittman** [comment]
I'd suggest that this would just a new parameter passed to the existing object create/update endpoints. Or it might be provided as an external identifier for the file in the cocina. It depends on the globus flow.

**Comment by lwrubel** [comment]
If SDR API is doing the copying would the globus files still get saved temporarily on sdr-api (e.g. `/opt/app/sdr/sdr-api/shared/storage`)? I remember one thing we talked about in the analysis workcycle is how to reduce the number of times large files had to have copies made. 

Or would SDR-API know that the globus endpoint is mounted to DSA and not make an intermediate copy?

**Comment by justinlittman** [comment]
I'd suggest that Globus be mounted on SDR API and nowhere else. Once SDR API copied the files from Globus to the DOR Workspace, all other accessioning operations would be performed on the DOR workspace.
