### ISSUE TITLE
Create prototype Globus API client

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#4272]
Rob Smith to help with pre-reqs, see https://github.com/sul-dlss/dor-services-app/issues/4269#issuecomment-1284647647

Tested so far via the globus SDK (python via jupiter notebook):
- [x] Authentication
- [x] List contents of endpoint
- [x] Create a folder
- [x] Fetch a file (determined we did not need this because Globus will be mounted on DSA)
- [x] Set permissions --- get a 403 now
- [x] Delete a folder

Client should:
- [x] Setup a globus folder that we can use for testing the Globus API
- [x] Get a globus API key/credentials, `client_id` and `client_secret` are stored in vault at `puppet/application/h2/globus/`. The Globus endpoint UUID is `34ea3e65-6831-479a-8da3-87f118e3fc2b`. The friendly name is `H2 test endpoint`.   See https://consul.stanford.edu/display/systeam/Vault+for+Developers
-- `vault login -method oidc mount=oidc-dev`  (select Stanford SAML in browser, go through webauth)
-- `vault kv get puppet/application/h2/globus/client_id`
-- `vault kv get puppet/application/h2/globus/client_secret`
- [x] Figure out how to read files from globus on our VMs (is it a NFS mount?)

Create ruby globus client (i.e. could be gem or just a new project for prototyping)  

Features:
- [x] authenticate to Globus
- [x] create folders in the root globus test folder
- [x] set permissions on this new folder by sunetid to write access
- [x] test that the user who is granted permission can write files into that endpoint using the globus desktop client (personal connect)
- [x] test that we can read files from that endpoint from our servers (e.g. common-accessioning, DSA, technical-metadata, etc.) ... could be seen as an NFS mount, so may not need the API to read these files (this will be a new sdr-api ticket)
- [x] set permissions on that folder to read-only so that the user cannot add/change files once accessioning has started (part of new sdr-api ticket)
- [x] test that whatever solution we have integrates if needed with HFS work upstream 
- [x] delete files from folder (icebox this ticket, needing more PO + team discussion)
- [x] include the magic link in the email sent to user (that pops up globus connect pointing at the right endpoint) (this is already an H2 issue)

Globus API documentation: https://docs.globus.org/api/
Globus SDK: https://globus-sdk-python.readthedocs.io/en/stable/index.html

Questions:
* Where is the right place (or right places) to mount the globus endpoint? (Analysis question for the team post-stand-up)
  * we decided we don't want to mount anything. we'll use the gem/API instead.
* Work with Rob/Ops to figure out how to operationalize this (env-specific endpoints? etc.) once ☝🏻 is settled
  * Mike will set this up soon

**Comment by lwrubel** [comment]
Here are the Globus CLI docs: https://docs.globus.org/cli/examples/

**Comment by lwrubel** [comment]
Question for @rsmith11: what role does our CLIENT_ID have? We've been able to create and delete directories, but we get a 403 error when trying to set permissions on a directory. We're wondering if there may be any restrictions on what it can do.

**Comment by lwrubel** [comment]
For those of us looking at how to use our `CLIENT_ID` and `CLIENT_SECRET ` with the globus CLI yesterday, turns out you can [set them as environment variables, and then NOT use the `globus login` command](https://github.com/globus/globus-cli/blob/main/src/globus_cli/commands/login.py#L41). 

I was able to list files in the h2 endpoint after doing so. I still get a 403 error when trying to change permissions on a directory.

**Comment by lwrubel** [comment]
Another clarification: our "endpoint" is what Globus calls a "Guest Collection". I determined this by doing: 

```
! globus collection show 34ea3e65-6831-479a-8da3-87f118e3fc2b -v

Display Name:                H2 test endpoint
Owner:                       rsmith11@stanford.edu
ID:                          34ea3e65-6831-479a-8da3-87f118e3fc2b
Collection Type:             guest
Storage Gateway ID:          869b76b6-3e12-4f31-8049-463c9860fb16
Connector:                   POSIX
High Assurance:              False
Authentication Timeout:      43200
Multi-factor Authentication: False
...
Force Encryption:            True
Public:                      True
Keywords:                    []
```

Also, it appears we are not an administrator of it. These two factors are probably the reason that we can't successfully use some commands that don't work on endpoints. See [Handling Collections vs Endpoints](https://docs.globus.org/cli/collections_vs_endpoints/) for some more detail on this.

**Comment by lwrubel** [comment]
@aaron-collier The sample code at https://github.com/sul-dlss-labs/globus_client/blob/sample-code/api_test.rb does the following using the Globus APIs:
1) Requests an access token
2) Lists files at our endpoint
3) Makes a directory
4) Looks up a user's identity ID
5) Gives the user read/write permissions on the directory
6) Changes the user's permissions to read-only
7) Deletes the directory

**Comment by lwrubel** [comment]
Note that while Globus can provide a list of files in a directory, the response does not include whether that upload is still in progress or completed. The file size will increase while it's being uploaded.

**Comment by mjgiarlo** [comment]
I believe this issue is now done enough and broken out into new tickets, so I'm closing it. Feel free to re-open if I was too hasty!
