### ISSUE TITLE
Analysis: SUL-Embed Codebase Overview

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#4285]
Do a short deep-dive for the team into the sul-embed codebase after reviewing it.

**Comment by mjgiarlo** [comment]
# High-level characterization

sul-embed is a Rails-based MVC web application with a significant amount of JavaScript code as well.

# Viewers

Beyond MVC, the app uses type-specific "viewer" classes in `app/viewers/embed/viewer/` which all inherit from the `CommonViewer` class. These classes are used to:
* Figure out which Rails view to render
* Assert which types the viewer supports
* Control whether a download UI widget will be rendered
* Set a default height for the viewer
* Control whether a full-screen experience is allowed
* Interact with the purl object (from the request) to list Stacks URLs of the files that can be rendered
* Control whether to show an attribution panel
* Control whether to show a file search widget
* Answer rights-related questions about rendered objects (getting this information from the purl object)
* Control whether to show the header

Viewers are registered for one or more supported types, and only one viewer may be registered for a given type. This happens in `config/initializers/register_viewers.rb`. Currently there are seven viewers registered:
* File
* Geo
* M3 (Mirador 3, a viewer for images)
* PDF
* 3D
* Media
* WasSeed

# TBD

* Models
* Controllers
* Views
* Helpers
* `lib/`
* JavaScript

**Comment by mjgiarlo** [comment]
This is done ☝🏻 

If you find you need more info to get started on sul-embed, let's chat.

**Comment by justinlittman** [comment]
Thanks @mjgiarlo. That was helpful.
