### ISSUE TITLE
EPIC: release to SW (via Folio)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4304]
dor-services-app writes an 856 to a text file on a shared mount “/sdrpurl_transfer/” which gets it discoverable by SW (?)

from shared_configs:

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/a655a518-3fa3-4e4f-82e0-165e13b90389)

from dor-services-app:

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/e6c1e13c-ed34-40d6-ae09-817be056a802)

**Comment by arcadiafalcone** [comment]
Is this needed for end-to-end testing to work?

**Comment by ndushay** [comment]
closing this in favor of #4454, which is the ticket being worked on.
