### ISSUE TITLE
Report: items that use "previous symphony" to record a previous catkey

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4309]
In response to a query by @arcadiafalcone, I'm looking for items that use the "previous symphony" field to record a catkey that was later changed. The system used to record this information in the identityMetadata datastream but I'm having trouble finding examples that have the previous catkey in the Cocina.

Examples where I know a catkey was changed are not showing the previous catkey, e.g. https://argo.stanford.edu/view/druid:qn269jk7253

**Comment by ndushay** [comment]
I think the cocina *might* have multiple catkeys with the current one possibly marked "refresh" ?  Looking at the item in question ... I wonder if that cocina code was written AFTER you made the change to this particular record?  Perhaps @arcadiafalcone know?

**Comment by ndushay** [comment]
@andrewjbtw attaching report.  7976 items found.  (I ran it for items only based on your use of that word).

[CatalogLinksPreviousSymphony.csv](https://github.com/sul-dlss/dor-services-app/files/10463269/CatalogLinksPreviousSymphony.csv)

**Comment by ndushay** [comment]
In the DSA code, 

https://github.com/sul-dlss/dor-services-app/blob/main/app/services/update_marc_record_service.rb#L218  gets the data, but I don't see them changed anywhere.

Searching in sul-dlss github organization, I found https://github.com/sul-dlss/argo/blob/main/app/services/catkey.rb but am not at all clear where it is used.

**Comment by ndushay** [comment]
tagging @arcadiafalcone so she can look at records with "previous symphony" also.
