### ISSUE TITLE
Add FOLIO HRIDs and refresh status to SDR Cocina for records with Symphony catkey

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4326]
The FOLIO HRID may be generated from the catkey by adding a prefix based on the source ILS. All catkeys currently in the SDR refer to Symphony and (except Lane, see #4335) will become FOLIO instances, so the prefix will be `a`.

The Symphony catkey is in the `identification` section of the Cocina (example from tw211pt6154):
```
"identification": {
        "catalogLinks": [
           {
                "catalog": "symphony",
                "refresh": true,
                "catalogRecordId": "10172564"
            }
        ],
        "sourceId": "renaissanceatlas:14"
    }
]
```

The FOLIO HRID should be added (with the catkey's refresh status) to the `catalogLinks` section, and the refresh status of the catkey changed to `false`:
```
"identification": {
        "catalogLinks": [
           {
                "catalog": "symphony",
                "refresh": false,
                "catalogRecordId": "10172564"
            },
           {
                "catalog": "folio",
                "refresh": true,
                "catalogRecordId": "a10172564"
            }
        ],
        "sourceId": "renaissanceatlas:14"
    }
]
```
If the Cocina has multiple active (not previous) catkeys, all should be added as FOLIO HRIDs (example from fd109zd9961):
```
"identification": {
        "catalogLinks": [
           {
                "catalog": "symphony",
                "refresh": false,
                "catalogRecordId": "10762220"
            },
           {
                "catalog": "symphony",
                "refresh": false,
                "catalogRecordId": "10762249"
            },
           {
                "catalog": "folio",
                "refresh": true,
                "catalogRecordId": "a10762220"
            },
           {
                "catalog": "folio",
                "refresh": false,
                "catalogRecordId": "a10762249"
            }
        ],
        "sourceId": "sul:MLM_217"
    }
```

**Comment by ndushay** [comment]
what will Folio record id prefixes be?  Good question:

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/479c7375-bb02-4e95-98fe-927bf915ab40)

**Comment by arcadiafalcone** [comment]
Depends on #4327

**Comment by ndushay** [comment]
![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/611a3aee-1de6-4e17-85d5-63a581a156d7)

**Comment by arcadiafalcone** [comment]
The following catkeys are valid but are from Lane Medical Library records that will not be migrated. They should remain in the record for now but no HRIDs should be generated based on them.

Catkeys to skip when generating Symphony-based HRIDs:
10872078
10906003
11574734
11718696
12208745
12307427
12718359
12811199
13638174
11827181
12311317

**Comment by ndushay** [comment]
tagging @justinlittman on this ticket

**Comment by ndushay** [comment]
assigning this ticket to @justinlittman as I think he is working on it

**Comment by lwrubel** [comment]
To be done still: determine plan to run in production and run.

**Comment by lwrubel** [comment]
Migration is in progress on prod. Will be complete when that process is done successfully.

**Comment by lwrubel** [comment]
Migration completed successfully with no errors. When running the verify step, the following items reported ERROR:
```
5215367,druid:bb223rf9165,ERROR
5215338,druid:bf777tz7987,ERROR
5215375,druid:cw635hq4276,ERROR
5215381,druid:dj085sn4672,ERROR
5215365,druid:gc596rm2073,ERROR
5215371,druid:gd133jt2816,ERROR
5215342,druid:hn467gc8080,ERROR
5215337,druid:ht274fq6242,ERROR
5215368,druid:kk764vg7407,ERROR
5215373,druid:mj328vc1209,ERROR
5215366,druid:nb516bv0000,ERROR
5215379,druid:pg977ym8022,ERROR
5215372,druid:pp915tm9599,ERROR
5215383,druid:pq966ss8527,ERROR
5215370,druid:pt575ms6579,ERROR
5215361,druid:qb241kf5082,ERROR
5215378,druid:qd280hf9629,ERROR
5215374,druid:qx721yv5939,ERROR
5215377,druid:rc798gw7445,ERROR
5215280,druid:rd780mt4706,ERROR
5215339,druid:rf597kz4712,ERROR
5215276,druid:sh574zq3673,ERROR
5215376,druid:sv002jd3150,ERROR
5215382,druid:td074gz2682,ERROR
5215360,druid:th362df0512,ERROR
5215384,druid:tn594dg8610,ERROR
5215369,druid:tq132pr8713,ERROR
5215336,druid:vv376cn0627,ERROR
5215283,druid:xq523gt2972,ERROR
5215282,druid:xt297nr3318,ERROR
5215340,druid:yj566sh7400,ERROR
5215343,druid:yv777hw7947,ERROR
5215341,druid:zn585gn4646,ERROR
```

Spot-checking, these look to be all Google Books. @andrewjbtw reported that Google started depositing again last week, for reasons that remain unknown. (Andrew says they sometimes show as "available" books that our app had not recorded as available previously.)

**Comment by ndushay** [comment]
@justinlittman when this ticket is closed, please close the EPIC as well (#4322)

**Comment by justinlittman** [comment]
Uggh, I just discovered that `sync_cataloglinks` was not enabled in prod. (The good news is that the verify step uncovered the problem.) I need to re-migrate.

**Comment by justinlittman** [comment]
Re-migrated, done, and verified.
