### ISSUE TITLE
Report on Lane Symphony catkeys in Cocina

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4334]
Currently Lane records have the Symphony catkey in their metadata. However, Lane records will be migrated from Voyager rather than Symphony, and the FOLIO HRID will be based on the Voyager identifier. A report is needed to identify SDR records for Lane resources with catkeys so that the correct FOLIO identifier can be used.

The actions for this ticket:  
1.  (part one) take the list supplied below and determine which of those objects have catkeys in the cocina.  Note:  it may be easiest to use json_path and the report approach to find whether or not a list of objects has cocina;  the difference is you'll be starting with a known list of druids, rather than using json_path to find the set of druids.

2.  (part two) work with Andrew to get the list of objects from Lane based on APO or Collection.  Check the resulting list for records with ckeys.

3.   End up with one or more lists of Lane objects in SDR with and without ckeys.

**Comment by arcadiafalcone** [comment]
Note this will only identify managed purls.

**Comment by arcadiafalcone** [comment]
I also asked Vitus to run a report in Symphony for Lane items with purls,:
[Lane_SDR_list.xlsx](https://github.com/sul-dlss/dor-services-app/files/10562872/Lane_SDR_list.xlsx)

**Comment by justinlittman** [comment]
Can you provide more details on what is required for this ticket?

**Comment by ndushay** [comment]
@andrewjbtw nudgee-ing here -- are there APOs or collections that will have only Lane records, or another way to get Lane items in DSA beyond the list from Vitus?  We can code and run the report if you tell us what is needed.

**Comment by andrewjbtw** [comment]
Sorry, I thought the reporting from the Symphony side would take care of identifying Lane items. There are two Lane APOs for historical digitization projects:

[Lane Medical Library (Attribution-Noncommercial-Share Alike 3.0)](https://argo.stanford.edu/view/druid:pp928km2258)

[Lane Medical Library](https://argo.stanford.edu/view/druid:mf043wz1042)

Both of them have a mix of items with and without Symphony records. I don't have any background on these APOs in terms of whether more items will be added to either one, or if there will be changes in cataloging.

**Comment by arcadiafalcone** [comment]
I looked at those two APOs in Argo and there are 8 collection records with catkeys (not all of which are valid catkeys).

The Symphony report includes only objects that are released to SearchWorks where the catkeys are correct in Argo.

This may need to morph into an ETD-specific report - I will investigate further.

**Comment by arcadiafalcone** [comment]
Replaced by #4373
