### ISSUE TITLE
Research ruby-marc fidelity in converting FOLIO marc json to marcxml

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/dor-services-app#4342]
This ticket needs to be rewritten to focus on marc data accuracy in conversion, not ruby-marc. 

We can get MARC records in JSON format from FOLIO's source records via the [source-record-storage-records/{id} API](https://s3.amazonaws.com/foliodocs/api/mod-source-record-storage/p/source-record-storage-records.html#source_storage_records__id__formatted_get). We currently use the [ruby-marc gem](https://github.com/ruby-marc/ruby-marc) for working with MARC records from Symphony. 

Does the ruby-marc gem convert FOLIO's marc json into marcxml that is accurate for conversion into Cocina? 

One way to approach this is to run the refresh process by hand using marc json from FOLIO and checking whether the Cocina matches what's in SDR.

Ways to get source record storage records for analysis:
- Use the [source-record-storage id endpoint](https://s3.amazonaws.com/foliodocs/api/mod-source-record-storage/p/source-record-storage-records.html#source_storage_records__id__formatted_get)
- View Source on an instance in FOLIO (may need to request permissions for this option to be visible, or log in with an admin account). 
![image (4)](https://user-images.githubusercontent.com/1619369/216720598-df1f9af1-2325-42f1-b3b1-2defed2b76d2.png)

@arcadiafalcone: would you provide some example records that demonstrate local practices we need to test?

**Comment by ndushay** [comment]
Closing in favor of #4348
