### ISSUE TITLE
Research API call for getting MARC JSON from FOLIO, given an HRID

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/dor-services-app#4344]
We will need to replace the `SymphonyReader.to_marc` method, which retrieves a MARC record from the ILS using a catkey. This supports the workflows to update Cocina descriptive metadata with what's in the ILS MARC record. 

The MARC data lives in FOLIO's source record. Once way to do this lookup is to:
1. Look up the instance identifier by querying by HRID (which we will have in the Cocina) using the [`/instance-storage/instances`](https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/instance-storage.html#instance_storage_instances_get) endpoint with a query string such as `query=(hrid==ah123456)`

2. Get the source record from the [`/source-storage/{id}/formatted`](https://s3.amazonaws.com/foliodocs/api/mod-source-record-storage/p/source-record-storage-records.html#source_storage_records__id__formatted_get) endpoint, with the instance UUID as the id param. 

This ticket is to determine 1) whether there a single API call possible to get MARC JSON from Folio given HRID (or identifiers in the Cocina) and 2) if not, confirm this sequence of calls is an appropriate approach for getting the metadata.

**Comment by lwrubel** [comment]
According to @shelleydoljack  we can use something like {base_url}/source-storage/source-records?instanceHrid={hrid}. However, currently getting a 403 with this query.

**Comment by shelleydoljack** [comment]
Are you using the app_sdr user?

**Comment by lwrubel** [comment]
Sorry, yes. I can use that user for other endpoints with no problem.

**Comment by shelleydoljack** [comment]
Yea, after looking at the FOLIO api doc you put together, I'll have to add some permissions to the app_sdr permission set to allow the user to hit those endpoints.

**Comment by shelleydoljack** [comment]
Ok, I added the app_discovery pset to the app_sdr pset. I'll list the permissions in the google doc.

**Comment by lwrubel** [comment]
I have confirmed this works. Thanks, @shelleydoljack!

**Comment by lwrubel** [comment]
Confirming here that we can use mod-source-storage's /GET /source-storage/source-records endpoint for looking up a source record by instanceHRID.

Documented here: https://s3.amazonaws.com/foliodocs/api/mod-source-record-storage/p/source-record-storage-source-records.html

Given a JSON response, the MARC record is in `JSON.parse(response)["sourceRecords"].first(["parsedRecord"]["content"]["fields"]))`

A response with no records returns a 200 with the following JSON:
`{'sourceRecords': [], 'totalRecords': 0}`

**Comment by jmartin-sul** [comment]
> @jmartin-sul This is the endpoint we discussed yesterday for getting MARC data.

thanks!
