### ISSUE TITLE
Create gem for FOLIO API interactions

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/dor-services-app#4345]
DSA and (likely) the ETD app will need to be able to make calls to FOLIO's Okapi API gateway for reading and writing data. This ticket is to set up a gem for these API calls and include the initial method(s) to get and manage authentication tokens. (folio-client doesn't yet exist on RubyGems) 

We can draw on what is being used in the [FolioRequests class](https://github.com/sul-dlss/folio-tasks/blob/d5737049ce9f082419ff3b5784a59511f0dd9023/lib/folio_request.rb#L54) in the `folio-tasks` repo. (That repo is for running command-line utilities.) See also the example API calls in this [FOLIO Infra Jupyter notebook](https://github.com/sul-dlss-labs/sdr-notebooks/blob/folio-notebook/FOLIOAPIsInfraExploration.ipynb). 

The [`authn/login`](https://s3.amazonaws.com/foliodocs/api/mod-login/p/login.html#authn_login_post) is used for the POST request for a token, given a username and password. This ticket includes adding those to shared_configs, noting that the app user will be changed with https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/301

The `okapiToken` will be configured to expire and @shelleydoljack recommends requesting a new token with each request, at least for now. If the configuration of these tokens changes, and/or expiration becomes available, we can adjust.

**Comment by peetucket** [comment]
folio_client gem created and released 

https://github.com/sul-dlss/folio_client/
https://rubygems.org/gems/folio_client/
