### ISSUE TITLE
Add feature switch(es) for turning on Folio HRID and turning off ckey

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4353]
The ETD app needs a feature switch in settings.yml and in shared_configs for all 3 environments, to  switch between Symphony and Folio for back end ILS related processing.

The switch should be "catalog_record_id" and the values should be "folio" or "symphony" and should default to "symphony"

This will allow us to develop what is needed to use Folio instead of Symphony for the ETD workflow.

**Comment by justinlittman** [comment]
I've added this as a requirement of relevant tickets, so no need to implement this separately.
