### ISSUE TITLE
Investigate different pathways to MARC exported from FOLIO

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4355]
See https://docs.google.com/document/d/1lfFBqqkNqX4JKiF6gBspnsQnTC9oWuooJjrJF0pDiig/edit?disco=AAAAqAnK0fQ

**Comment by ndushay** [comment]
can you remind me what this ticket is about?

**Comment by arcadiafalcone** [comment]
It's about the process of going from the MARC JSON stored in the SRS (or converted from Inventory) to the MARC XML consumed by the MARC2MODS transformation, and how that might differ for different kinds of records, especially order records with minimal description and records (if any) created in FOLIO.

**Comment by arcadiafalcone** [comment]
Per Alissa, order records may be created in FOLIO Inventory if copy cataloging is not available, and not stored as MARC in the SRS. MARC can be exported for these records based on the Inventory data, but it's a different process/API from retrieving stored MARC.  I think this will be an edge case so far as the SDR is concerned, but something to be aware of.

**Comment by ndushay** [comment]
ugh.   Guess we'll cross that bridge later.

**Comment by arcadiafalcone** [comment]
Course reserves also surfaced as a case where a record might be created in FOLIO inventory without underlying MARC.
