### ISSUE TITLE
[SPIKE] Perform content metadata diffing as part of shelving

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor-services-app#4359]
CONTEXT: work is mostly done with an approach detailed in #4492, which has been reviewed by John.  What's next is to respond/review his comments, which is likely involving improved test coverage.

# Background

Currently, DSA uses the prescat HTTP API in order to [generate content diffs when shelving](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/shelving_service.rb#L40-L64). These diffs are used by:

* [`ShelvableFilesStager`](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/shelvable_files_stager.rb) to figure out which files need staging and which ones need to be copied over from preservation.
* [`DigitalStacksService`](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/digital_stacks_service.rb) to shelve files needing shelving, to remove files from the stacks that are no longer present or shelvable, and to rename files on the stacks that have had their filenames changed.

# Problem Statement

For items with very many files (~5K-10K+), this operation on the prescat side is extremely slow: it can take over ten minutes, possibly up to thirty minutes or more, to complete the content diffing[^1]. On top of that:

* There is nothing about this content diffing that is really about the Moab file format or versioning. The only Moab versioning piece is figuring out which content metadata to compare against.
* Content diffing is only needed in one place across all of SDR and it's right here in DSA for shelving.

# Spike Proposal

Given that, we propose a spike cutting out the middle person. For content diffing, DSA should:

1. Ask prescat for the most recent content metadata XML[^2]: `Preservation::Client.objects.metadata(druid: 'bc123df4567', filepath: 'contentMetadata.xml')`
2. Convert the content metadata XML to a Cocina structural JSON[^3]
3. Produce a diff between the two Cocina structural JSON objects sufficient for what `ShelvableFilesStager` and `DigitalStacksService` need

[^1]: And this is **after** a greater than 2x performance boost was added to the code responsible for the diffing in the `moab-versioning` gem.
[^2]: Even though we'd rather compare Cocina JSON structures to figure out the diff, not all items in SDR have Cocina JSON in preservation, so instead of handling both items with Cocina JSON and items without request and work with the content metadata XML.
[^3]: You can probably unearth some [old XML-to-JSON code in DSA](https://github.com/sul-dlss/dor-services-app/blob/dd56a3f6e41b870fb327af0212ae05f320952c64/app/services/cocina/from_fedora/dro_structural.rb) and adapt it to do what we need.

**Comment by jmartin-sul** [comment]
closed by #4492
