### ISSUE TITLE
Generate report of SDR items that use a file hierarchy but do not have content type of file

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4360]
Analysis for a different issue (https://github.com/sul-dlss/dor-services-app/issues/4327#issuecomment-1424865636) revealed that there are items in SDR that:

- use a folder hierarchy
- do not have content type=file

These items were likely deposited with subfolders by accident. I know of cases where that happened in the past. My understanding has been that a decision was made not to remediate them at the time but that they were meant to have been accessioned as a flat list.

However, some druids look more complicated and I'd like to investigate before deciding whether to remediate. For example: https://argo.stanford.edu/view/druid:hc083jx5634 has a subfolder within each resource grouping. That may have been unintentional, but it's different than other cases I've seen where everything is in just one subfolder.

**Comment by ndushay** [comment]
This is needed to allow records with barcodes only (no catkeys) to be cocina valid.

**Comment by ndushay** [comment]
@peetucket leaving this open until the report is run -- assuming you'll be doing that and posting results here for Andrew ...

**Comment by peetucket** [comment]
Report here:  There were a lot of invalid objects found... 28,685   so not sure what we want to do about that.

[https://app.zenhub.com/files/16625188/005b6869-5d5f-4353-aa77-5e005b5ce7bc/download](https://app.zenhub.com/files/16625188/005b6869-5d5f-4353-aa77-5e005b5ce7bc/download)
