### ISSUE TITLE
Turn on skipped specs

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4366]
See PR #4365 and https://github.com/sul-dlss/dor-services-app/commit/c43e0dc5481f9932e2111393581995143bbc3d1b

@andrewjbtw CAN preassembly make valid dark objects?

We think the answer to this is now yes.

**Comment by ndushay** [comment]
@andrewjbtw just that https://github.com/sul-dlss/dor-services-app/pull/4365/files shows we have 2 specs skipped, and they were turned off because "turned off until preassembly can make valid dark objects" 

I'm gonna turn on the specs;  perhaps they will "just work" and problem solved.

**Comment by ndushay** [comment]
Hrmm.  Not that simple:  https://app.circleci.com/pipelines/github/sul-dlss/dor-services-app/8413/workflows/7fe3d24f-4e5a-4713-ad92-27090042fefd/jobs/17736

maybe the data in the tests isn't correct?   

![image](https://user-images.githubusercontent.com/96775/218855030-5dd407cc-2455-4f7e-af72-3521343d9041.png)

@andrewjbtw there is no urgency here, but if it's fast to get appropriate fixes to that metadata, I'll proceed.   This is, effectively, random but tractible tech debt I put in the ready column so it wasn't empty.

**Comment by andrewjbtw** [comment]
I see I never replied to this but also I don't know what the question is.

**Comment by justinlittman** [comment]
Cocina Model's DarkValidator now validates that files are set correctly when item is dark, so there is no reason for PublishingJob to do so. I'm going to delete the specs.
