### ISSUE TITLE
Review/remediate barcode-only records with errors

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4371]
Review failed barcodes in #4327

**Comment by arcadiafalcone** [comment]
rd204pt4752 - Barcode does not appear to match any MARC record in SearchWorks. Will follow up with Branner.

**Comment by arcadiafalcone** [comment]
These three had an error to do with file hierarchy and do have catkeys. Will follow up with EAL.

hc083jx5634/9207724 - MARC parent bound-with record
ts082qm3256/9214347 - child record
yn655rb4901/9214418 - child record

The remaining druids were not accessioned and therefore not versioned, which is fine.

**Comment by andrewjbtw** [comment]
I think the hierarchy in those three objects was unintentional. Each druid contains a subfolder named "Result" that appears to duplicate the files in the content folder. None of the files in the subfolders are presented for public view so I was going to submit new versions of each of these druids that contain only the unique files in a flat folder arrangement. There should be no effect on display.

The catch is that we have to turn off file hierarchy validation temporarily to fix these.

**Comment by ndushay** [comment]
is this something we can do with the cocina migration infrastructure, @justinlittman

**Comment by ndushay** [comment]
Andrew has 2x,xxx objects that also need file hierarchy validation turned off to be remediated.

**Comment by lwrubel** [comment]
Need to comment out validator in a branch, deploy that branch and reaccession, and then uncomment.

**Comment by lwrubel** [comment]
@andrewjbtw will add catkeys to the three mentioned above.

**Comment by andrewjbtw** [comment]
I've added the three catkeys. If that's the last thing to be done for this ticket, I think can be closed.
