### ISSUE TITLE
Report on catkeys for ETDs in Argo

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4373]
In order to identify catkeys for Lane ETDs and catkeys that are no longer valid, we need a report of all current (not previous) catkeys for ETDs.

Selection criteria:
- has APO bx911tp9024

Data to return:
- druid
- all catkeys for that druid with type `symphony`, and the refresh status of each

The results should be structured as `druid,catkey,refresh,catkey,refresh` etc. for as many catkeys as are present.

**Comment by peetucket** [comment]
Report attached here:

[etd_catkey_report.csv](https://github.com/sul-dlss/dor-services-app/files/10748957/etd_catkey_report.csv)

PR with code that ran the report: #4379

**Comment by mjgiarlo** [comment]
@arcadiafalcone I'm touching the class that drives this report, and I'm wondering if it should be looking only at items or at both items and collections?

**Comment by arcadiafalcone** [comment]
Items only.
