### ISSUE TITLE
Handle Lane objects with managed purls

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4375]
So far qn269jk7253 is the only one identified.,

If the only catkey for the object is from Lane, it will need the Voyager-based Lane FOLIO instance ID, because the Lane Symphony record will not be migrated.

**Comment by ndushay** [comment]
@arcadiafalcone:  qn269jk7253 shows as a collection in argo https://argo.stanford.edu/view/qn269jk7253 -- This seems like bad data somewhere that needs fixing, rather than a case for coding.   Would you please investigate further, or perhaps we shoud pair on spelunking this one.

**Comment by arcadiafalcone** [comment]
It is a collection - the managed purl is on the MARC collection record.

**Comment by arcadiafalcone** [comment]
And "handle" in this case may mean "manually add the Lane identifier to the identification metadata" - I'm waiting on the report to be sure, but I suspect the number of Lane items requiring special handling will be small enough that they will in general be accommodated by data edits rather than by code.

**Comment by ndushay** [comment]
oh - sorry - I was in ETD headspace and thought I was looking at an ETD. Doh.

I'm going to leave this ticket assigned to you as it seems likely you will be shepherding info through.  If you need us to do rails console stuff to update cocina in the DSA database, holla.

**Comment by arcadiafalcone** [comment]
See #4385
