### ISSUE TITLE
Change invalid Lane ETD catkeys to "previous symphony" (cocina change and versioning)

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4387]
For this set of ETDs from the Med School, the catkeys associated with these records were changed at some point and no longer appear in Symphony.  In other words, the Lane catkeys in these SDR records are invalid now.

As the Lane records do not have managed purls, it's not necessary at this time to look up and add the valid Folio instance HRID (based on the Lane Voyager ID) to the cocina for these specific SDR records (this subset of Medical School ETDs).  All these objects currently have a valid catkey for the Special Collections copy of the ETD -- this should be left alone. 

The action for this ticket is to, for each object (roughly 600 of them):
1. open a version
2. change the cocina for these objects - in identification, the value of `catalog` for these catkeys should be changed from `symphony` to `previous symphony`  for ONLY the Lane catkey - the value of interest is indicated in the attached file.
3. close the version and accession

[invalid_catkeys_to_delete.csv](https://github.com/sul-dlss/dor-services-app/files/10761572/invalid_catkeys_to_delete.csv)

(there may be a separate ticket for dealing with the ETD database values;  "dinna fash yerself")

**Comment by ndushay** [comment]
"add the valid Lane HRID" - did you mean Folio instance HRID?

If so:  the action for this ticket is to change the cocina for these object to be "previous symphony" ... and make a new version?

**Comment by arcadiafalcone** [comment]
As these objects have multiple catkeys and the non-Lane one should remain, they can't be fixed in the Argo user interface.

**Comment by ndushay** [comment]
leaving this ticket for @arcadiafalcone or @justinlittman  to close - perhaps the code is ready but the migration hasn't happened yet??

**Comment by justinlittman** [comment]
That's correct. I'm waiting until after dep updates.

**Comment by justinlittman** [comment]
Remediation complete.
