### ISSUE TITLE
Add HRIDs for selected Lane objects with catkeys

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4388]
[lane_hrids.csv](https://github.com/sul-dlss/dor-services-app/files/10771847/lane_hrids.csv)

These are the Lane objects now in Symphony with a Symphony assigned catkey that will need to have the Folio instance HRID based on the Voyager ID for the Lane record, prefixed with "L".

These SDR objects all have a single catkey that is currently for the Lane record as represented in Symphony, but in production, these records will have a new instance HRID in Folio based on the Voyager ID (not this catkey). 

The action for this ticket is to, for each object

1.  open a version
2. change the cocina for these objects - in identification, a new `catalogLink` for these objects should be created with a Folio instance HRID and the value based on the Voyager id with "L" (capital L) as a prefix. Refresh should be set to false.
3. close the version and accession

CatalogLink example
```
"identification": {
        "catalogLinks": [
              {
                    "catalog": "folio",
                    "refresh": true,
                    "catalogRecordId": "L235413"
               }
        ],
        "sourceId": "lane:H154H_F61"
    }
```

Background:

Once upon a time, Voyager records were imported into Symphony and assigned catkeys in Symphony, with the Voyager identifier being preserved in the marc bib as the 001 field with a value starting "LL" and there is a 596 field with LANE-MED.

When we switch to Folio, the Lane Voyager data will be loaded into Folio separately from the Symphony data, and the Folio instance ids for this load into Folio will insert an "L" prefix in front of the native Voyager identifier as the new Folio instance HRID for the existing Voyager record (e.g. L34532542).

**Comment by ndushay** [comment]
So is the action for this ticket to take the Lane objects with druids, and ensure that we assign the Folio instance HRID (corresponding to the ckey) to the cocina?

How is this different from assigning Folio instance HRIDs to other SDR objects with ckeys?

Are there Lane objects with ckeys we should NOT assign Folio instance HRIDs to?   We will likely need a way to know how to skip those (and not skip these)

- lines 40-48 don't have druids, so we ain't gonna have cocina for 'em.

**Comment by justinlittman** [comment]
Remediation complete.
