### ISSUE TITLE
MARC XML needs to have HRID in 001 and FOLIO in 003 before using marc-to-mods XSLT

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4395]
1. This intervenes in the workflow between a SRS record exported from FOLIO being transformed into MARC XML and the MARC XML going to the modsulator.
2. Delete the existing 001 and 003 (each tag should appear in the record only once).
3. Add a 001 tag with the HRID at the top of the record.
4. Add a 003 tag with the value `FOLIO` under the 001.
5. Send the record to be processed by the marc-to-mods XSLT.

Both fields are control fields, so there are no indicators or subfields.

This process applies to records created both pre- and post-migration.

Background
Migrated records will continue to have an 001 with the catkey and an 003 with `SIRSI`. in SRS. New records may have a variety of values in these fields. This data is inserted into the adminMetadata of the MODS record to indicate its source record, so it needs to correspond to the local HRID and system in use.

**Comment by lwrubel** [comment]
Completed with FolioReader work.
