### ISSUE TITLE
Write Folio equivalent to SymphonyReader

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4398]
FolioReader should have the same public interface as SymphonyReader, except it should use "folio_instance_hrid" instead of "catkey". It should use the FolioClient gem for reading from Folio.

It should perform the following transformations on the retrieved MARC record:
* Delete the existing 001 and 003 (each tag should appear in the record only once).
* Add a 001 tag with the HRID at the top of the record.
* Add a 003 tag with the value FOLIO under the 001.
See https://github.com/sul-dlss/dor-services-app/issues/4395. Also, see the existing code in SymphonyReader for mutating 001 and 003. And check with @arcadiafalcone to verify that implementation is correct.

**Comment by peetucket** [comment]
Are there some example equivalent records that can be pulled from both symphony and folio to see if the marc format lines up?  Looks like the JSON formatting is different in the couple examples I have looked at so far, but this could be due to the random record I found in okapi-test
