### ISSUE TITLE
Cleanup SymphonyReader exceptions

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4399]
SymphonyReader defines some exceptions. References to those exceptions are in various parts of the DSA codebase. At this point, all handling of these exceptions should be performed by MarcService.

For this ticket, remove all SymphonyReader exceptions error handling that is sprinkled erroneously through DSA (except in MarcService).

**Comment by ndushay** [comment]
"remove" exception  handling, or "MOVE" it to MarcService?   We presumably want to keep handling the exceptions somewhere ...

**Comment by justinlittman** [comment]
All necessary SymphonyReader exception handling is already performed by the MarcService. All SymphonyReader exceptions error handling outside of MarcService is probably cruft. (The developer should verify this assessment.)
