### ISSUE TITLE
After migration, flip refresh flag on selected Lane items

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4438]
See #4437 and #4435 

A developer has to do this, and presumably redeploy?

**Comment by ndushay** [comment]
@arcadiafalcone is this something that should be done more or less as soon as Folio is available/stable?  Or something that can happen a few weeks later?

And is it something you will do, or something a developer will do?

**Comment by arcadiafalcone** [comment]
It can wait a few weeks, but it does require developer attention.

**Comment by peetucket** [comment]
I read through the linked tickets, but am not 100% clear what should happen here.  Are there specific druids for which we need to change the refresh state for the lane catalog IDs?  So the action is to get a list of druids and for each druid, find the catalog ID that is prefixed with an "L" in the cocina and toggle the refresh status to the opposite state of what it currently is?

**Comment by arcadiafalcone** [comment]
The FOLIO refresh toggle appears to be set correctly (to "true"), so I'm closing.
