### ISSUE TITLE
Something ... something ... holding records

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4444]
Requirements for when and what holding records should be written when updating the 856 field of MARC records goes right here -->

(waiting for decison from committee from constituent libraries that wanted separate holdings ...)

**Comment by lwrubel** [comment]
Closing since creating holdings with the appropriate permanent location will be handled manually by catalogers, per decision communicated by @ahafele 3/17/2023

**Comment by arcadiafalcone** [comment]
Holdings records will be created manually along with the bib record.
