### ISSUE TITLE
856/Folio: do not duplicate 856 entries for the same druid

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4452]
When an item that has been released is released again, do not create additional 856 records referring to the same druid.

For example, I released https://argo-qa.stanford.edu/view/druid:qq019rq5469 multiple times:

- initial release
- second release with no change (resulting in identical 856)
- third release after changing the rights (different 856)

Each release should have left only one 856 on the MARC record. But the MARC ([folio-test link](https://folio-test.stanford.edu/inventory/view/1e5890fc-f7f5-518f-a8ea-9256b43c9007?qindex=hrid&query=a111)) looks like this:

```
856 | 4 1 | ‡u https://sul-purl-stage.stanford.edu/qq019rq5469 ‡x SDR-PURL ‡x item ‡x rights:world
856 | 4 1 | ‡u https://sul-purl-stage.stanford.edu/qq019rq5469 ‡x SDR-PURL ‡x item ‡x rights:world
856 | 4 1 | ‡u https://sul-purl-stage.stanford.edu/qq019rq5469 ‡x SDR-PURL ‡x item
```

**Comment by mjgiarlo** [comment]
@andrewjbtw I can no longer reproduce this with the test object in QA. Can you?

**Comment by andrewjbtw** [comment]
This is now working in QA.

**Comment by mjgiarlo** [comment]
Thank you! Closing.
