### ISSUE TITLE
856/Folio: Un-release should remove 856 from MARC record

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4453]
When un-releasing a druid, the 856 corresponding to that druid should be removed from the MARC record. I tested with https://argo-qa.stanford.edu/view/yj417jr1159 by

- release to SW 
- unrelease to SW

The workflows report success but the 856 remains in the record ([folio link](https://folio-test.stanford.edu/inventory/view/9afe9b02-1e4b-5ba8-9842-0214ca9d63d1?qindex=hrid&query=a999)):
```
‡z Available to Stanford-affiliated users. ‡u https://sul-purl-stage.stanford.edu/yj417jr1159 ‡x SDR-PURL ‡x item ‡x file:yj417jr1159%2Fpage_0001.jp2 ‡x rights:group=stanford 
```

To reproduce:

- Go to Argo item page for item with an HRID
- Release first
  - Click "manage release" button
  - Choose "release this object"
  - Wait for process to complete and verify 856 is in the MARC
- Then unrelease
  - Go back to Argo page
  - Click "manage release" button
  - Choose "Do not release this object"
  - Wait for process to finish and check the MARC again

**Comment by edsu** [comment]
I happened to notice that releasing again (after un-release) adds a duplicate 856?

**Comment by andrewjbtw** [comment]
That is, multiple 856s are fine as long as they refer to different druids.

**Comment by edsu** [comment]
If I'm reading [this test](https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/catalog/folio_writer_spec.rb#L148-L167) correctly it looks like a MARC record will not get a duplicate 856 field if the release tags are set up correctly? So I guess they are not being set correctly when something is Unreleased?

**Comment by edsu** [comment]
Unless I'm reading it wrong I think this test ensures that FolioWriter will remove any 856 fields for the same DRUID, assuming that the correct ReleaseTags are used? 

This seems to imply to me, that perhaps the Cocina object hasn't been updated such that the ReleaseTags are correct? Still digging...

**Comment by edsu** [comment]
Maybe I'm not understanding the DSA API correctly. When I watch the DSA Apache logs during the `release` action I can see DSA gets a POST to `/v1/objects/{id}/publish`. But when I `un-release` I don't see a POST to `/v1/objects/{id}/unpublish` and see a POST to `/v1/objects/{id}/publish` instead?

DSA HTTP traffic when releasing to SearchWorks:

```
172.20.21.210 - "" [24/Mar/2023:08:01:10 -0700] "PATCH /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1097 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:01:10 -0700] "GET /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1097 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:01:10 -0700] "GET /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1097 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:01:10 -0700] "GET /v1/objects/druid:yj417jr1159/administrative_tags HTTP/1.1" 200 44 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:01:10 -0700] "GET /v1/objects/druid:yj417jr1159/administrative_tags HTTP/1.1" 200 44 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:01:10 -0700] "POST /v1/objects/druid:yj417jr1159/publish?workflow=releaseWF HTTP/1.1" 201 - "-" "dor-services-   client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:01:10 -0700] "GET /v1/objects/druid:yj417jr1159/administrative_tags HTTP/1.1" 200 44 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:05:34 -0700] "GET /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1097 "-" "dor-services-client 12.13.1"
```

DSA HTTP traffic when un-releasing to SearchWorks:

```
172.20.21.210 - "" [24/Mar/2023:08:12:16 -0700] "PATCH /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1106 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:16 -0700] "GET /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1106 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:16 -0700] "GET /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1106 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:16 -0700] "GET /v1/objects/druid:yj417jr1159/administrative_tags HTTP/1.1" 200 44 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:16 -0700] "GET /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1106 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:16 -0700] "GET /v1/objects/druid:yj417jr1159/administrative_tags HTTP/1.1" 200 44 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:16 -0700] "POST /v1/objects/druid:yj417jr1159/publish?workflow=releaseWF HTTP/1.1" 201 - "-" "dor-services-   client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:17 -0700] "GET /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1106 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:17 -0700] "GET /v1/objects/druid:yj417jr1159/versions HTTP/1.1" 200 119 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:18 -0700] "GET /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1106 "-" "dor-services-client 12.13.1"
172.20.21.210 - "" [24/Mar/2023:08:12:18 -0700] "GET /v1/objects/druid:yj417jr1159 HTTP/1.1" 200 1106 "-" "dor-services-client 12.13.1"
```

Is this correct?

**Comment by andrewjbtw** [comment]
I'm not too familiar with the DSA API, but generally "publish" should mean create or update a purl and "unpublish" means remove a purl. 

When something is unreleased from SearchWorks, it is not unpublished. The purl remains after the unrelease. Instead what happens is that the purl is re-published with updated information that says "do not release."

**Comment by edsu** [comment]
After testing with @mjgiarlo's work on [folio_writer retries](https://github.com/sul-dlss/dor-services-app/pull/4474) I'm not able to replicate this anymore.

@andrewjbtw do you want to give a try and see if that's the case for you too?

**Comment by andrewjbtw** [comment]
This is now working in QA.

**Comment by mjgiarlo** [comment]
Thanks! Closing.
