### ISSUE TITLE
Review public MODS augmentation code

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor-services-app#4486]
As part of our [cross-team work to "Cocinize" the Access stack](https://docs.google.com/document/d/1xeU8JcMOKwgfu2xoOZRNijdngShA2x895h6LRGCpwSU/edit#), we are moving logic about mapping Cocina to "public XML" out of dor-services-app and into purl-fetcher. That logic includes code in DSA that augments the public MODS with information such as collection titles and virtual object memberships. We should review that code, which will be copied into purl-fetcher, to determine how "keepable" it is.

This was @justinlittman's idea, so I'm tagging him here to add detail or correct what I've written. I'll pre-emptively assign him, too.

**Comment by justinlittman** [comment]
Basically, it is this code here: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_desc_metadata_service.rb

Having a local copy within DSA seems fine. We probably also want to de-solr the code as well.

**Comment by justinlittman** [comment]
I think it OK to close.
