### ISSUE TITLE
report: all version descriptions for all versions of all druids

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4509]
Not sure if this is possible or possible but very difficult, but I would like a report of all version descriptions for all versions of all druids. I think these four fields in a CSV or TSV would be sufficient:

- druid
- version number (as a whole number)
- tag (or whatever the pseudo-semantic version number is called, e.g. 2.1.0
- version description

For various threads of SDR planning, especially around versioning, I would like to do some analysis on existing data. I'm especially interested in how many versions are:

- clearly system-described (usually via bulk action)
- are metadata bulk updates, which usually get a system-made description
- were obvious fixes to errors ("fix version mismatch")
- show some indication of user attempts to signify that some versions are more significant than others (i.e. "release 2.0")

**Comment by peetucket** [comment]
I have a PR for this now: #4510 and have run the report on SDR-infra.  There are 11 million rows however, making the CSV file very large: 559 MB.  What's the best way of getting this to you (it's currently in `/opt/app/deploy/dor-services-app/tmp` on the sdr-infra server.

**Comment by andrewjbtw** [comment]
Thanks! I have access to sdr-infra and got the report from there.
