### ISSUE TITLE
Only publish the latest "release tag" to the public XML/Cocina

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4515]
**Describe the bug**

At some point in the last year, SDR has started publishing more than one SearchWorks "release" tag to the public XML. This is causing some releases to Searchworks to fail because the Access systems expect to see only one tag.

Example: https://purl.stanford.edu/xh235dd9059.xml

In this object's public XML, there are multiple release tags:
```xml
<releaseData>
    <release to="Searchworks">false</release>
    <release to="Searchworks">true</release>
    <release to="Searchworks">true</release>
    <release to="Searchworks">true</release>
    <release to="Searchworks">true</release>
    <release to="Searchworks">true</release>
    <release to="Searchworks">true</release>
  </releaseData>
```
This object should appear in SW but it does not because one of those release tags is set to "false". In the [object history in Argo](https://argo.stanford.edu/view/xh235dd9059), you can see that the object has been sent through the release process multiple times. 

<img width="1134" alt="Screenshot 2023-05-23 at 9 41 21 AM" src="https://github.com/sul-dlss/dor-services-app/assets/8975583/07d76a14-7a9e-48c7-b2e3-dc86a92d1cf6">

The Cocina also includes multiple release tags. The earliest release tag is the tag that was set to false, indicating that many years ago the object was withdrawn from SW. However, all of the later tags are set to "true", showing that the object should have been released.

The problem seems to be that SDR should be publishing only the most recent release tag, not the full set of historical release tags. According to Chris Beer, as long as purl-fetcher receives a "false" release tag somewhere in the list, whether or not it's the last value, it will interpret that as an instruction to keep the object out of SW.

**Expected behavior**

When an item or collection is released to or withdrawn from SearchWorks or EarthWorks, a `<release>` tag is inserted into its public XML:

The tag should look like this when an item is released:
```xml
<releaseData>
    <release to="Searchworks">true</release>
</releaseData>
```
When an item has been un-released (withdrawn) from SW, the tag looks like this:
```xml
<releaseData>
    <release to="Searchworks">true</release>
</releaseData>
```
There should never be more than one release tag in the public XML for SearchWorks and one release tag for EarthWorks. So an item or collection public XML can have:

- no release tag
- one SW release tag
- one EW release tag
- both one SW release tag and one EW release tag

**Additional context**

I happen to have a copy of the public XML for this object from April 2022, just before the Fedora migration. In that copy, there is only a single release tag for SW, which confirms that the publishing behavior changed at some point in the last year.

**Comment by peetucket** [comment]
Context: this is working OK *except* for collection objects.  So the bug is here: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_cocina_service.rb#L18

Basically, for anything other than a DRO, it short circuits the logic in the `ReleaseTags` class (called here: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_cocina_service.rb#L30-L34) that only selects the last release tag when building the administrative part of public cocina.  We need to run this logic for release tags even for collection objects.

**Comment by peetucket** [comment]
@andrewjbtw I have a potential fix for this here: #4516, but it would be good to test with a collection on stage to be sure there isn't some stuff in the public XML that is being published for collections that will get removed with this change.

**Comment by andrewjbtw** [comment]
I've tested with a few collections and it looks good. Given the variety of XML we could have, I'm not sure how to check for other possible changes this could have introduced to public XML. In the collections I tested, the only difference I saw was in the release tags.

**Comment by peetucket** [comment]
Ok, that's good.  I'll call it done.  The only change is in what get's published, so there is no data loss (and in the remote case where we do find an issue, re-publishing after fix).
