### ISSUE TITLE
Bad ORCID create work request

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4545]
## Backtrace

    line 64 of [PROJECT_ROOT]/app/jobs/update_orcid_work_job.rb: create
    line 15 of [PROJECT_ROOT]/app/jobs/update_orcid_work_job.rb: block in perform
    line 12 of [PROJECT_ROOT]/app/jobs/update_orcid_work_job.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/99383416)

**Comment by justinlittman** [comment]
This is because the publication date is "1000" which is not permitted by ORCID.

<img width="962" alt="image" src="https://github.com/sul-dlss/dor-services-app/assets/588335/2fd88c55-f1e0-4652-9651-041d0b704769">

@amyehodge You can ignore this or change the publication date.

**Comment by amyehodge** [comment]
I've contacted the depositor about updating or removing this date. Stay tuned.

**Comment by amyehodge** [comment]
Depositor has removed the erroneous date.
