### ISSUE TITLE
No longer update marc 856 from ConstituentService

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/dor-services-app#4548]
After migration to FOLIO, remove guard clause concerning Symphony catalogLinks and the call to `Catalog::UpdateMarc856Service`. Rely on releaseWF for updating FOLIO in the unusual case that there is a catalog link in a constituent.

https://github.com/sul-dlss/dor-services-app/blob/5a0f5671a6b59e1ce07256dfb7910627ea307a7a/app/services/constituent_service.rb#L76

For background, see: https://github.com/sul-dlss/dor-services-app/issues/4445

**Comment by ndushay** [comment]
@lwrubel - I'm not clear if this is something we should do when Folio is "ready", or if it's something we should do after we configure and turn on Folio.

**Comment by ndushay** [comment]
If we need to do this as part of turning on features when Folio is ready - is the Draft PR ready to go and approved?  Should it become a "real" PR with a HOLD on it?

**Comment by lwrubel** [comment]
This is part of extracting Symphony-related code from SDR after we're live on FOLIO. So it is not needed for go-live, just something to merge post go-live.
