### ISSUE TITLE
catch up with 856s written to  /sdrpurl_transfer during cutover period

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4569]
Any "release to SW" that happened after Symphony became read only, and before #4568 is done will need to be addressed.

The data for this will be in the /sdrpurl_transfer directory;  not sure if we can just re-run the releaseWF once Folio is hooked up and ready.

**Comment by andrewjbtw** [comment]
This is done. Only a small number of items were in the sdrpurl file. I released them on Monday and checked SW to see that the MARC was updated properly.
