### ISSUE TITLE
 update openapi.yml to remove references to symphony

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4572]
After sul-dlss/cocina-models/issues/614, 
- [ ] update openapi.yml 
- [ ] search on, case insensitive, e.g.:
    - [ ] `catalogRecordId`
    - [ ] `catalog_record_id`
    - [ ] `ckey`
    - [ ] `catkey`
    - [ ] `symphony`
    - [ ] `ils`
    - [ ] `folio`
    - [ ] ...

**Comment by edsu** [comment]
From planning: This is redundant with our normal release process that will be performed as part of #614.
