### ISSUE TITLE
Excise Catalog::MarcComparisonService

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dor-services-app#4585]
This was useful for building understanding when we were working on the Symphony to FOLIO migration, but has probably now outlived its usefulness.  See e.g.

* https://github.com/sul-dlss/dor-services-app/blob/1de80f173f867efff1679fddb058f4259bf1ebd7/app/services/catalog/marc_comparison_service.rb
* https://github.com/sul-dlss/dor-services-app/blob/1de80f173f867efff1679fddb058f4259bf1ebd7/Gemfile#L32 (we can probably get rid of the dependency on the hashdiff gem, as i believe this is the app's only use of it)

**Comment by ndushay** [comment]
@justinlittman can you think of a reason not to do this?

**Comment by ndushay** [comment]
@andrewjbtw @arcadiafalcone  can you think of a reason we should keep the MarcComparisonService in DSA?

**Comment by justinlittman** [comment]
No.

**Comment by arcadiafalcone** [comment]
@ndushay I think it's OK to remove.

**Comment by andrewjbtw** [comment]
Ok with me too.
