### ISSUE TITLE
Some SDR objects with catkeys do NOT have current folio_instance_hrid, only "previous folio"

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4586]
We stumbled onto this bug when looking for SDR objects that were not ETDs that were recently released to SW.  

We do not know how many SDR objects are affected.  Here are 2 of them:

For https://argo.stanford.edu/items/druid:gw145sz1930.json

![image](https://github.com/sul-dlss/dor-services-app/assets/96775/64f5949d-ddf2-42a0-8772-ba5f959cacc1)

For https://argo.stanford.edu/items/druid:bq617py5227.json

![image](https://github.com/sul-dlss/dor-services-app/assets/96775/f51851b0-1cc0-4950-8f7a-f313a81fb5b6)

Here is one that was released to SearchWorks recently that was NOT affected:

In https://argo.stanford.edu/items/druid:gw739nt6189.json

![image](https://github.com/sul-dlss/dor-services-app/assets/96775/c69b9801-e1d6-42c0-97ea-f66079d2c36e)

**Comment by peetucket** [comment]
An attempt to write a report to find the problems: https://github.com/sul-dlss/dor-services-app/pull/4588

**Comment by justinlittman** [comment]
Are we sure that the folio HRIDs weren't just deleted by a user?

**Comment by justinlittman** [comment]
Looks like Jessica made changes about 3 days ago.

**Comment by peetucket** [comment]
Seeing that from version history?  It says "Remove collection catkey" which seems like maybe we have some process that isn't working as expected.  Seems odd to remove the single folio ID.

I'm still twiddling with a report to see what items may have this ... not sure I have the queries quite right yet.

**Comment by justinlittman** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0dCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e166433b88ed0f3ddef84ebd21516d61330ada80/image.png)

**Comment by peetucket** [comment]
Interesting.  I got the report running and found these with previous folios, all except one has no current folio, so presumably we can verify these are the ones that were deliberately removed:

And druid:wx466ty0174 is the one from yesterday that Geoff fixed!

````
item_druid,folios,previous_folios
druid:xq195jn0278,,a4085058
druid:wx466ty0174,in00000002962,in00000002965
druid:kc972mz7533,,a4085693
druid:vw498zg1201,,a4085058
druid:gw145sz1930,,a4085058
druid:sq559dg5711,,a4085773
druid:yv285wk4152,,a4085963
druid:xg968xb6452,,a7779562
druid:sx744kc1471,,a7779569
druid:bq617py5227,,a12833415
```

**Comment by peetucket** [comment]
These all appear to have been modified in the same way by Jessica.  So yes, i think this is mystery solved.  Closing.
