### ISSUE TITLE
DSA Post Folio cutover cleanup

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4595]
This issue is to create PR(s) for removing ILS cutover code.

Please do NOT do this in one giant PR. I recommend making multiple small PRs. This ticket can also be broken up into multiple tickets -- there is a lot here.

- [ ] remove code such as `if Settings.catalog_record_id == 'symphony'`  
- [x] remove SymphonyChecker and such classes
- [x] remove MarcComparisonService and such classes
- [ ] PublicXmlService can stop exposing catkeys?
- [x] specs involving "symphony" or "catkey" should be changed to Folio
- [ ] update the README
- [ ] search on, case insensitive, e.g.:
    - [ ] `catalogRecordId`
    - [ ] `catalog_record_id`
    - [ ] `ckey`
    - [ ] `catkey`
    - [ ] `symphony`
    - [ ] `ils`
    - [ ] ...
- [x] no longer use `/sdrpurl_transfer' - take it out of settings.yml in repo and in all shared configs, and tell ops they can remove the mount from DSA apps?

**Comment by andrewjbtw** [comment]
This item should be verified with the Access team. I think they're still applying logic where they read catkey or FOLIO hrid and I don't know that catkey can be removed without an issue.

>PublicXmlService can stop exposing catkeys?
