### ISSUE TITLE
Manually set the version number on 4 stage druids so they sync with preservation

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4614]
I can't update these 4 druids and the error messages suggest the problem is that the version in Cocina does not match the version in preservation. I think if the Cocina is updated to match the current preservation version, then I will be able to update the items to make them dark.

```
druid,version to assign
bf444sk5509,23
bf481jf9879,23
bf498wc3325,23
bq653yd1233,31
```

All of these items date back to 2019 when version mismatch errors were still a problem that required manual editing of versionMetadata datastreams.

**Comment by justinlittman** [comment]
Done.

**Comment by justinlittman** [comment]
```
 > Dro.where(external_identifier: ['druid:bf444sk5509','druid:bf481jf9879','druid:bf498wc3325','druid:bq653yd1233']).pluck(:external_identifier, :version)
 => [["druid:bf444sk5509", 23], ["druid:bf481jf9879", 23], ["druid:bf498wc3325", 23], ["druid:bq653yd1233", 31]]
```
