### ISSUE TITLE
determine where we test that variants of shelve / publish / preserve do the right thing

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4617]
an outgrowth from sul-dlss/infrastructure-integration-test/42.

"we should have tests ensuring that

   -  preserve = yes puts a file in preservation
   -  preserve = no does NOT put a file in preservation
    -  shelve = yes puts the file in stacks (or clearly does the right trigger for getting the file in stacks)
    -  shelve = no does NOT put the file in stacks
    -  publish = yes puts the file in purl (or clearly does the right trigger for getting the file in purl)
    -  publish = no does NOT put the file in purl"

@justinlittman commented:
> ... I went looking for where we could point to in the DSA codebase that these things were tested and I wasn't coming up with anything clear. (I was only looking at preserve.)

> Maybe a first step is to determine where these are currently tested? We might convince ourselves that the testing is adequate or perhaps that additional testing within DSA is necessary or perhaps more integration testing is warranted.

**Comment by justinlittman** [comment]
After further consideration, I've concluded that these functions depend on a complicated interplay of DSA services, libraries (e.g., Moab), and SDR systems. While each of these are tested individually with extensive stubbing, there is not anything currently approximating an integration test.

**Comment by ndushay** [comment]
Implying that the ticket in integration-testing repo is a go ... I'll put it back in ready.

**Comment by justinlittman** [comment]
Integration testing added.
