### ISSUE TITLE
Report on multiple events in descriptive metadata

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4618]
Criteria:
- record contains more than one top-level instance of the Cocina `event` property
- object does not have a FOLIO HRID

Return: purl, title, collection name, APO

**Comment by mjgiarlo** [comment]
@aaron-collier GH may have mistakenly closed this issue automatically, but I assume we also need a report from a prod run before we close this? Re-opening for now.

**Comment by aaron-collier** [comment]
This has been sent, so closing.
