### ISSUE TITLE
Internal server error on the shelving step

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dor-services-app#463]
Message in argo:
```
Internal Server Error: 500 (Response from dor-services-app did not contain a body. 
Check honeybadger for dor-services-app for backtraces, and look into adding a
`rescue_from` in dor-services-app to provide more details to the client in the future)
```

tracing in honeybadger shows the shelving robot uses dor-services-app `app/services/sdr_client` file and it can't do it's stuff:  

```
NoMethodError: undefined method `group_difference' for #<Faraday::Response:0x...>
```

https://app.honeybadger.io/projects/50568/faults/55941181

![image](https://user-images.githubusercontent.com/96775/66784995-d05d7d80-ee90-11e9-8cdb-4dcfbc5eeab8.png)

It's possible that this faraday response object should get ".body" called on it to get the info.

**Comment by jcoyne** [comment]
Here's the old version:
https://github.com/sul-dlss/common-accessioning/commit/0b53a3bb51b736b54eec51c815a445ccd6da5eac#diff-2c9f4fd1a8aa4b12bf0aefd1841e02a0L41

So I think it's expecting a `Moab::FileInventoryDifference` there. See https://github.com/sul-dlss/dor-services-client/blob/master/lib/dor/services/client/sdr.rb#L51

**Comment by ndushay** [comment]
@jcoyne agree.  Was honing in on that at the same time.  

Odd that we haven't noticed this sooner.
