### ISSUE TITLE
Publish "file language" attribute to public XML (and JSON)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4641]
To support captioning, we're adding a "file language" attribute to Cocina. We need to publish the attribute so that sul-embed can use it.

I think this item has the correct codes "en" for English and "ru" for Russian and can be used for testing: https://argo-stage.stanford.edu/view/druid:wm783fb6812

I think we could go with adding a "language" attribute and publish it only if it has a value in Cocina:

```xml
      <file id="nf738cz3269.zip" mimetype="application/zip" size="452160" publish="yes" shelve="yes" preserve="yes" language="en">
```

For the public JSON, I think we are currently publishing file metadata in the form that it's stored in the cocina JSON, for files where "publish" is set to "yes". Note that we aren't currently consuming the public JSON.

**Comment by aaron-collier** [comment]
@andrewjbtw is the a document or spec defining how this should be published to public xml?

**Comment by andrewjbtw** [comment]
Good question. I've never added a new field to public XML before. Based on what the current file XML looks like

```xml
      <file id="nf738cz3269.zip" mimetype="application/zip" size="452160" publish="yes" shelve="yes" preserve="yes">
```

I think we could go with adding a "language" attribute and publish it only if it has a value in Cocina:

```xml
      <file id="nf738cz3269.zip" mimetype="application/zip" size="452160" publish="yes" shelve="yes" preserve="yes" language="en">
```

Someone with more experience working on a public XML consuming app might want to weigh in.

For the public JSON, I think we are currently publishing file metadata in the form that it's stored in the cocina JSON, for files where "publish" is set to "yes".

**Comment by andrewjbtw** [comment]
I updated the main ticket description with my suggested XML.
