### ISSUE TITLE
Report request: event with displayLabel

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4649]
Select for report: digital objects that have a value in cocina event.displayLabel (top-level event only).

Include in output: object purl, object title, displayLabel value, catalog ID if present, collection name

If multiple instances of event have a value in displayLabel, either include all on separate lines or concatenate - whichever is easier.

Output should be in CSV format.

**Comment by justinlittman** [comment]
@arcadiafalcone report attached:
[displaylabel.zip](https://github.com/sul-dlss/dor-services-app/files/13561722/displaylabel.zip)

**Comment by arcadiafalcone** [comment]
@justinlittman Could you rerun this and put the values in quotes? Some of them have internal commas.

**Comment by justinlittman** [comment]
Try this @arcadiafalcone:
[displaylabel.zip](https://github.com/sul-dlss/dor-services-app/files/13572846/displaylabel.zip)

**Comment by arcadiafalcone** [comment]
I'm seeing quotation marks in the label field but not in title or collection name.

**Comment by justinlittman** [comment]
3rd time is a charm:
[displaylabel.zip](https://github.com/sul-dlss/dor-services-app/files/13620796/displaylabel.zip)

**Comment by arcadiafalcone** [comment]
@justinlittman Almost! I'm still having trouble parsing the columns correctly with command line tools. Could you run it one more time as a tab-delimited file instead of a CSV? Thanks.

**Comment by arcadiafalcone** [comment]
@justinlittman Hurrah, that works!
