### ISSUE TITLE
Report on files that lack a mimetype in the structural metadata

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4651]
During the 3D migration, @edsu and I discovered that files that lack a mimetype in the structural metadata run into a problem when using Preassembly's targeted updates feature. This happens because the system expects all files already accessioned into the SDR to have a mimetype.

I would like to know how many files lack a mimetype to see if it would be feasible for me to remediate all of them via Argo. I would like the report output to be:

```druid, name of file lacking a mimetype```

For each file that lacks a mimetype. If a druid has more than one file without a mimetype, list each file and the associated druid on its own line.
 
**Additional information**

When migrating from Fedora, we noticed that some files lacked mimetypes but because they were not causing errors, we decided not to remediate at that time. Now that we are off of Fedora, it turns out that we need that data. Fortunately, it is also much easier to remediate than it was before.

**Comment by edsu** [comment]
See #4653 for the report. I've attached the CSV here:

[empty-mediatypes.csv](https://github.com/sul-dlss/dor-services-app/files/13575038/empty-mediatypes.csv)

**Comment by andrewjbtw** [comment]
Thank you! 22,000 files. I guess it could be worse.
