### ISSUE TITLE
Report request: event.displayLabel when child of relatedResource

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/dor-services-app#4658]
Request for the same kind of report as the final version of #4649, except instead of displayLabel for top-level event only, this is only for displayLabel for event as the direct child of relatedResource.

Select for report: digital objects that have a value in cocina event.displayLabel where event is child of relatedResource.

Include in output: object purl, object title, displayLabel value, catalog ID if present, collection name

If multiple instances of event have a value in displayLabel, concatenate with semicolon.

Output (*including header row*) should be tab-delimited (header is change from final version of previous report).

**Comment by justinlittman** [comment]
@arcadiafalcone Do you have any example druids that should match?

**Comment by arcadiafalcone** [comment]
@justinlittman vs810rq0531

**Comment by justinlittman** [comment]
Here you go:
[relateddisplaylevel.zip](https://github.com/sul-dlss/dor-services-app/files/13652292/relateddisplaylevel.zip)
