### ISSUE TITLE
Audit: Verify that ObjectVersion for each item and version.

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4712]
Currently ObjectVersion references a Dro, Collection, or AdminPolicy by druid, without db referential integrity.

For this ticket, verify that for every version for every Dro, Collection, and AdminPolicy there is an ObjectVersion.

**Comment by jcoyne** [comment]
Every ObjectVersion has a DRO, Collection or AdminPolicy:
```sql
SELECT count(*) from (
 (
    SELECT external_identifier as id FROM dros UNION
    SELECT external_identifier as id from collections UNION
    SELECT external_identifier as id from admin_policies)
  EXCEPT SELECT distinct(druid) as id from object_versions 
) as derived;
```
```
 count
-------
     0
(1 row)
```

**Comment by jcoyne** [comment]
For each version:
```sql
SELECT count(*) from (
  (SELECT external_identifier, a.expected_version FROM dros,
       generate_series(1,dros.version) as a(expected_version)
   UNION SELECT external_identifier, a.expected_version FROM collections,
       generate_series(1,collections.version) as a(expected_version)
   UNION SELECT external_identifier, a.expected_version FROM admin_policies,
       generate_series(1,admin_policies.version) as a(expected_version)
  )
  EXCEPT SELECT druid, version FROM object_versions
) as derived;
```

```
 count
-------
     0
(1 row)
```

**Comment by jcoyne** [comment]
It looks like those versions were within milliseconds of one another:
```
dor_services=# select * from object_versions where druid = 'druid:gp730qp5664';
   id   |       druid       | version |  tag  |   description   |         created_at         |         updated_at
--------+-------------------+---------+-------+-----------------+----------------------------+----------------------------
 340023 | druid:gp730qp5664 |       1 | 1.0.0 | Initial Version | 2022-04-14 17:58:02.966403 | 2022-04-14 17:58:02.966403
 340024 | druid:gp730qp5664 |       2 | 2.0.0 | Version 2       | 2022-04-14 17:58:03.041556 | 2022-04-14 17:58:03.041556
(2 rows)
```

**Comment by andrewjbtw** [comment]
What does "version" mean here? That item has only one "Moab" version: https://argo.stanford.edu/view/gp730qp5664

But it no doubt has a bunch of Cocina versions.

**Comment by jcoyne** [comment]
April 2022, was just as we were rolling this out.  This must be a migration error.  None of those have a version 2 in the workflow database.  I think those extra 5 rows are garbage and we should delete them.

**Comment by justinlittman** [comment]
"Moab" version and Cocina versions should all be the same.

**Comment by justinlittman** [comment]
@jcoyne Can you please (1) perform the audits (both directions) in QA, stage, and prod and (2) delete any extraneous ObjectVersions?

**Comment by jcoyne** [comment]
@justinlittman Unfortunately, I don't seem to have access to those machines.

**Comment by jcoyne** [comment]
There are no extraneous versions on QA or Stage.  I deleted the 5 from prod.

**Comment by justinlittman** [comment]
Thanks!
