### ISSUE TITLE
OpenAPI badge showing as invalid

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor-services-app#472]
And our CI is not catching this because we are merely checking that the output of the validation contains `Document is valid`. And the output does include that string, but it also includes a bunch of warnings:

```
$ openapi-enforcer validate openapi.json

Document is valid but has one or more warnings.

One or more warnings exist in the OpenApi definition
  at: components > schemas
    at: Access > properties > embargoReleaseDate > example
      Unable to deserialize value
        Expected a date-time string of the format YYYY-MM-DDTmm:hh:ss.sssZ
    at: AdminPolicy > properties > type > example
      Invalid value
        Value "item" did not meet enum requirements
    at: Collection > properties > type > example
      Invalid value
        Value "item" did not meet enum requirements
    at: DRO > properties > type > example
      Invalid value
        Value "item" did not meet enum requirements
  at: paths
    at: /virtual_objects > post > responses > 201
      at: headers > Location > schema > format
        Non standard format "uri" used for type "string"
      A 201 response for a POST request should return a location header (https://tools.ietf.org/html/rfc7231#section-4.3.3) and this is not documented in your OpenAPI document.
    at: /objects/{id}/publish > post > responses > 201
      at: headers > Location > schema > format
        Non standard format "uri" used for type "string"
      A 201 response for a POST request should return a location header (https://tools.ietf.org/html/rfc7231#section-4.3.3) and this is not documented in your OpenAPI document.
```

@sul-dlss/infrastructure-team should we fix this up?

**Comment by jcoyne** [comment]
> Non standard format "uri" used for type "string"

This seems odd.  https://swagger.io/docs/specification/data-models/data-types/#format says:

>  format is an open value, so you can use any formats, even not those defined by the OpenAPI Specification, such as:  ...uri

**Comment by jcoyne** [comment]
See https://github.com/byu-oit/openapi-enforcer/issues/36#issuecomment-540234408

**Comment by Gi60s** [comment]
These warnings generated by the OpenAPI Enforcer can be hidden in their entirety or hidden on a case by case basis (newly added feature). Check out the documentation at https://byu-oit.github.io/openapi-enforcer/guide/exceptions.

**Comment by mjgiarlo** [comment]
Thanks for letting us know, @Gi60s! Good to have this flexibility. Now my team (@sul-dlss/infrastructure-team) has to decide whether we want to act on the warnings or hide them. :smile:

**Comment by Gi60s** [comment]
LOL. I know what you mean. I was thinking those same things for my APIs as I was adding this functionality.

**Comment by jcoyne** [comment]
This is now fixed.
