### ISSUE TITLE
Run release tags and object version tag migration

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4749]
1. Tag all the repos. 
2.  In stage, deploy all apps. 
3. In stage, run migration: app/services/migrate_release_tags
4. In stage, run audit: reports/audit_release_tag_migration
5. In stage, run integration tests.
6. In QA, deploy all apps. 
7. In QA, run migration.
8. In QA, run audit.
9. Coordinate migration with @andrewjbtw 
10. In prod, deploy latest DSA.
11. In prod, run migration.
12. In prod, run audit.

**Comment by lwrubel** [comment]
Tagged with `rel-2024-03-28-release-tags`. No items were found invalid by the audit script after migration.
