### ISSUE TITLE
Remove all uses of significance and object version tags

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4758]
Including from openapi.yml and creating a database migration to remove from database.

**Comment by justinlittman** [comment]
Blocked by needing to deploy all applications to production.

**Comment by lwrubel** [comment]
@justinlittman I didn't see an issue for removing this reference to object version tags in Dor Services Client but may have missed it: https://github.com/sul-dlss/dor-services-client/blob/ae14f4116c2e70a050c1fc2844df0988ccd066d4/lib/dor/services/client/object_version.rb#L8. What's the best order for doing this work?

**Comment by justinlittman** [comment]
Ticketed as https://github.com/sul-dlss/dor-services-client/issues/415
