### ISSUE TITLE
Consider remediation of public XML that has incorrect release tags

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4768]
For the past year, the logic for determining release tags added to public XML have been incorrect when there is both item and collection release tags. For context, see https://github.com/sul-dlss/dor-services-app/issues/4765

For this ticket, determine what remediation, if any, is necessary.

This ticket should either be done by or in coordination with @andrewjbtw.

**Comment by lwrubel** [comment]
Comparing druids released in Argo and released in SearchWorks would help us determine what may be wrong with the rolling indexer/releasing and inform the work in this ticket. @andrewjbtw will look at running a solr query in SW.

**Comment by lwrubel** [comment]
Closing as completed / reviewed.
