### ISSUE TITLE
Consider reports

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4771]
Currently, most of our reports query Dro, Collection, and/or AdminPolicy active record models. In the new data model, the existing active record models will be removed.

We can: (1) delete reports that use the legacy active record models; (2) update all reports to use the new active record models; or (3) update some reports to use the new active record models.

The goal of this ticket is for @andrewjbtw and @arcadiafalcone to determine which approach we should take.

**Comment by arcadiafalcone** [comment]
@justinlittman @lwrubel Where can I find (a description of) the reports that have been created? The third option (update selected reports) is the most likely.

Will the change in record models affect validation as well?

**Comment by jcoyne** [comment]
There are a list of reports in https://github.com/sul-dlss/dor-services-app/tree/main/app/reports. I don't think there is one document that describes all of them, but each is individually documented.

**Comment by justinlittman** [comment]
@arcadiafalcone Cocina model validation will remain unchanged.

**Comment by lwrubel** [comment]
@arcadiafalcone will provide a list of the subset of reports she'd like to have updated to the new models and will request them to be run again before the changes to the models are in place.

**Comment by arcadiafalcone** [comment]
Please update these reports:
contributors_identifiers
descendant_source_code_no_uri
descriptive_shape
events_multiple_date_types
export_cocina_from_druid_list
invalid_edtf_dates
invalid_edtf_structured_dates
invalid_form_source_codes
invalid_form_uris
invalid_iso8601_dates
invalid_language_uris
invalid_location_uris
invalid_name_uris
invalid_role_uris
invalid_subject_non_source_uris
invalid_subject_source_codes
invalid_w3cdtf_dates
property_contains_property_collections
property_contains_property_dros
property_events_with_display_label
property_existence_collections
property_existence_dros
property_multiple_events
property_nesting_level_collections
property_nesting_level_dros
unusual_language_source_uris

These reports don't need to be updated but should be run before decommissioning:
edtf_lower_x_dates
edtf_upper_x_dates
subject_map_coordinates
subjects_with_double_dash
unstructured_display_names

**Comment by andrewjbtw** [comment]
There's aren't many DSA reports that I've used. These I'd like updated:
export_cocina_from_druid_list
file_counts

This can be decommissioned if it's run again and everything passes:
invalid_cocina (despite the generic name, it's about file hierarchy/content type validation)

This should be run again and could be decommissioned if we can remediate the remaining problem items (which I think are all H2 items I can't update myself because of sync issues):
empty_mediatypes

**Comment by justinlittman** [comment]
Considered and ticketed.
