### ISSUE TITLE
Add dro?, admin_policy?, collection? convenience methods to RepositoryObject

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4775]

**Comment by justinlittman** [comment]
Blocked by #4760.

**Comment by jcoyne** [comment]
Should we use STI here?

**Comment by mjgiarlo** [comment]
@jcoyne STI is compelling here and but a small tweak to what we have currently.

**Comment by jcoyne** [comment]
These already exist by virtue of using AR::Enum: https://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html


```
irb(main):001> RepositoryObject.new.collection?
=> false
irb(main):002> RepositoryObject.new.admin_policy?
=> false
irb(main):003> RepositoryObject.new.dro?
=> false
```

**Comment by mjgiarlo** [comment]
You might think I would remember that, having added that myself, buuuuut
