### ISSUE TITLE
Add to_cocina, to_h methods to RepositoryObjectVersion

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4788]
Also, add to_cocina to RepositoryObject that delegates to current's to_cocina.

See https://github.com/sul-dlss/dor-services-app/blob/main/app/models/dro.rb#L17-L37

Note that will need to handle DROs, Collections, and AdminPolicies.

**Comment by jcoyne** [comment]
@justinlittman can you say why these need to be moved?  Why don't we continue to use the existing `to_model_hash` methods on Dro, Collection and AdminPolicy?

**Comment by justinlittman** [comment]
We are getting rid of Dro, Collection, and AdminPolicies active record models and replacing with a single RepositoryObject.

`to_h` converts to a hash that can be used to build a Cocina Model. `to_model_hash` converts to a hash that can be used to update a RepositoryObjectVersion.

**Comment by jcoyne** [comment]
I believe we also need `to_cocina_with_metadata` as well.
