### ISSUE TITLE
Add from_cocina, to_model_hash, update_cocina methods to RepositoryObjectVersion

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4789]
See https://github.com/sul-dlss/dor-services-app/blob/main/app/models/dro.rb#L39-L64

Note that will need to handle DROs, Collections, and AdminPolicies.

Also note that `update_cocina` will always be an update so the existing upsert logic isn't necessary.

**Comment by jcoyne** [comment]
@justinlittman can you say why we need to do this?  Can we just use the existing `to_model_hash` methos on Dro, Collection and AdminPolicies?

**Comment by justinlittman** [comment]
We are getting rid of Dro, Collection, and AdminPolicies active record models and replacing with a single RepositoryObject.

**Comment by mjgiarlo** [comment]
After some analysis and team discussion, we decided that `from_cocina` was dead code (since removed) and focused this work on `update_cocina`.
