### ISSUE TITLE
Find RepositoryObjects in CocinaObjectStore find methods

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4794]
For each of the CocinaObjectStore find methods (find, find_by_source_id), implement such that:
* When enabled_features.repository_object_test is enabled and a RepositoryObject exists, the cocina from the RepositoryObject and the Dro / AdminPolicy / Collection active record models will be compared. If there is a discrepancy, Honeybadger will be alerted and the Dro / AdminPolicy / Collection will be returned.
* When a RepositoryObject exists, the cocina model from the RepositoryObject will be returned; otherwise, the cocina model from the Dro / AdminPolicy / Collection will be returned

**Comment by justinlittman** [comment]
Blocked by #4788

**Comment by jcoyne** [comment]
I'm not a fan of this idea because now CocinaObjectStore is going to return two different types of objects from `find()` depending on settings.  This breaks Liskov substitution. I think it's better to call RepositoryObject.find directly in this case.

**Comment by justinlittman** [comment]
I think this was clarified in discussions: find methods return cocina models, not active record models. Thus, the underlying active record model has no impact on the interface.
