### ISSUE TITLE
Implement CocinaObjectStore destroy

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4796]
In addition to deleting Dro / AdminPolicy / Collection, also delete RepositoryObject (and associated RepositoryObjectVersions).

Please test that a RepositoryObject with RepositoryObjectVersions can be deleted, as there are foreign keys in both directions.

**Comment by mjgiarlo** [comment]
@justinlittman 💬 
> Please test that a RepositoryObject with RepositoryObjectVersions can be deleted, as there are foreign keys in both directions.

I believe I added a test case for this when we polished up the related PR last week. Destroying a `RepositoryObject` should do the right thing (destroying all versions, even if they are current/head/open, and then destroying the object).
