### ISSUE TITLE
Query RepositoryObject in CocinaObjectStore version method

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4797]
For the CocinaObjectStore version method, implement such that:
* When enabled_features.repository_object_test is enabled, the version will be retrieved from both Dro / AdminPolicy / Collection and RepositoryObject (when present) and compared. If there is a discrepancy, Honeybadger will be alerted.
* When enabled_features.repository_object_find is enabled, the version will be returned from RepositoryObject (when present); otherwise it will be returned from Dro / AdminPolicy / Collection.

See also #4794 for similar for find methods.

**Comment by jcoyne** [comment]
@justinlittman is this returning a version number or some other objct?
