### ISSUE TITLE
Write migrator to remove release tags field from cocina

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4811]
This should use the existing migration framework: https://github.com/sul-dlss/dor-services-app/blob/main/bin/migrate-cocina

This will be executed before releaseTags is removed from cocina model.

**Comment by justinlittman** [comment]
Good point, but the work in this ticket still needs to happen (viz., remove from the persisted cocina). The PublicCocinaService already gets and replaces the release tags from the ReleaseTagsService: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_cocina_service.rb#L36

**Comment by jcoyne** [comment]
@justinlittman why do we need to do this migration? Can't we just let it fall out of use? This migration will take some work and has a non-zero risk.
