### ISSUE TITLE
Close RepositoryObject in VersionService.close

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4813]
If a RepositoryObject exists, it should be closed (opened_version is moved to last_closed_version and closed_at set on new last_closed_version). If a description is provided, the description in the RepositoryObjectVersion should be updated. This should be in addition to existing work done in VersionService.close.

~~Mutating the RepositoryObject should be encapsulated in the CocinaObjectStore. (That is, RepositoryObjects should not be manipulated in VersionService code.)~~

Please leave a note indicating that the "if a RepositoryObject exists" should be removed. See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina_object_store.rb#L140-L141

**Comment by justinlittman** [comment]
#4815 didn't encapulate RepositoryObject in CocinaObjectStore. (So a close method should be added to CocinaObjectStore.)

**Comment by jcoyne** [comment]
@jcoyne the `close_version!` is encapsulated in the `RepositoryObject`?  Do we need another layer of indirection here?  Why?

**Comment by justinlittman** [comment]
Based on discussion, RepositoryObject will be closed directly in VersionService instead of CocinaObjectStore.
