### ISSUE TITLE
Write RepositoryObject migration service

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4817]
For a DRO, Collection, or AdminPolicy:
* Create an RepositoryObject, keeping created and updated dates.
* For each ObjectVersion, create a RepositoryObjectVersion, keeping created and updated dates.
* For the RepositoryObjectVersion that corresponds with the Dro, Collection, AdminPolicy’s version set the RepositoryObjectVersion's cocina properties.
* If item is open (based on VersionService.open?), set last RepositoryObjectVersion to RepositoryObject's opened_version and head_version associations. Otherwise, set it to RepositoryObject's last_closed_version and head_version associations and set closed_at to the date of last accessioning.

**Comment by jcoyne** [comment]
> For the RepositoryObjectVersion that corresponds with the Dro, Collection, AdminPolicy’s version set the RepositoryObjectVersion's cocina properties.

Are we saying we're only recording he cocina properties on the head version?

**Comment by justinlittman** [comment]
That's correct, as we don't have the cocina properties for earlier versions.

**Comment by jcoyne** [comment]
@justinlittman does it make sense to even make those version records then?  Should we just say create a RepositoryObject with one RepositoryObjectVersion and make that one have version 5?

**Comment by justinlittman** [comment]
We need the earlier versions to record the data that is currently in ObjectVersions (e.g., the version description).
