### ISSUE TITLE
Report request: all druids that will be indexed as "Released" by the rolling indexer

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4824]
As discussed in standup, we can get a report of everything that the rolling indexer will eventually index as "Released" in SDR. I've decided that there's too much variation in trying to analyze the release situation based on lists exported from Argo because things are changing too quickly. It would be better to get a stable list.

**Comment by lwrubel** [comment]
Where does the Releasable Indexer code live?

**Comment by jcoyne** [comment]
@lwrubel the ReleasableIndexer is https://github.com/sul-dlss/dor_indexing/blob/main/lib/dor_indexing/indexers/releasable_indexer.rb

**Comment by lwrubel** [comment]
Thanks, @jcoyne. Apparently I can't spell Releasable correctly when searching (`releaseableindexer` gets you nothing).

**Comment by andrewjbtw** [comment]
The rolling indexer has apparently caught up in the time since I requested this report so I'm closing this.
