### ISSUE TITLE
Report request: all druids that have a release tag in the internal DB

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#4825]
Data needed:

- druid
- object type (item or collection)
- most recent released status (true or false)
- "what" value (self or collection)

**Comment by jcoyne** [comment]
@andrewjbtw can you say more about why you need this?  We've moved away from the release tags in cocina, so I'm wondering if this is for historical reasons or if we just want all released tags.

**Comment by andrewjbtw** [comment]
It's related to https://github.com/sul-dlss/dor-services-app/issues/4768 The tags are still in the Cocina but since that should match what's in the DB it doesn't really matter to me which source the tags come from. I want to separate this list from druids that have only public XML/public Cocina release tags.

**Comment by andrewjbtw** [comment]
I switched the title because I've signed off on removing the tags from the Cocina.
