### ISSUE TITLE
Update accessioning endpoint for versioning

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4830]
The existing versioning logic in accessioning endpoint should be replaced with: If a version is not already opened, then open a new version (rescuing and handling VersionService::VersioningError).

**Comment by jcoyne** [comment]
@justinlittman why are we making this change?

**Comment by justinlittman** [comment]
Otherwise objects are not in the correct versioning state that is expected by the workflows -- they are closed, whereas the assembly workflows expect them to be open. This is revealed by current integration tests.
