### ISSUE TITLE
Create UserVersion active record model

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4840]
Fields:
* version: integer, not null
* withdrawn: boolean, not null, default false
* belongs to a **closed** RepositoryObjectVersion. (That the RepositoryObjectVersion is closed should be validated.)

Unique index on version, repository_object_version_id.

**Comment by jcoyne** [comment]
Why do we need dark user versions?  

Completely aside from that, how about a "public" column with a boolean value?

**Comment by justinlittman** [comment]
There is a business requirement to allow users to suppress a user version. When suppressed, the PURL page will indicate that there was a user version, but it is no longer available.

The use of an "access" enum field was to make it similar to other access rights and allow for other flavors of suppressing. However, this is arguably premature generalization; I don't feel strongly about it.

**Comment by jcoyne** [comment]
In standup today, @andrewjbtw states that "withdrawn" (as a boolean), should replace "access" as a field name.

**Comment by justinlittman** [comment]
Decision in standup today to call the attribute "withdrawn".
