### ISSUE TITLE
Determine if RepositoryObject lock column necessary

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4857]
This was transitioned over from Dro / Collection / AdminPolicy. However, it seems like it might not be used.

If it is not used, get rid of it.

**Comment by jcoyne** [comment]
@justinlittman it is not used right now. I was expecting a ticket that would add that functionality though. As i think we want to accidentially prevent overwrite with out of date functionality once we stop writing to the legacy models.

**Comment by justinlittman** [comment]
Is there a reason we wouldn't want to continue our current approach of rolling our own lock? https://github.com/sul-dlss/dor-services-app/blob/main/app/models/repository_object_version.rb#L35

**Comment by jcoyne** [comment]
I don't understand what you're getting at. It looks to me like RepositoryObjectVersion#external_lock is using the lock column.

**Comment by justinlittman** [comment]
You're right. I was under the mistaken assumption that lock was always null. It's just mostly null.
