### ISSUE TITLE
Index after AdministrativeTags create/update/destroy

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#4885]
In here:
https://github.com/sul-dlss/dor-services-app/blob/e4b9d96d64ee0981745a5614f0dffc8cac45f49f/app/controllers/administrative_tags_controller.rb#L21-L66

Rather than sending `Notifications::ObjectUpdated`, call the indexer in DSA, but in a Synchronous manner.

This will allow Argo to stop calling the indexer:
https://github.com/sul-dlss/argo/blob/84743b4ceb85a55356f7f2323faa72983f06ae66/app/controllers/tags_controller.rb#L64
https://github.com/sul-dlss/argo/blob/84743b4ceb85a55356f7f2323faa72983f06ae66/app/jobs/import_tags_job.rb#L38

**Comment by justinlittman** [comment]
Do you think this should be done synchronously or kick off a job?

**Comment by jcoyne** [comment]
For parity with what is currenty done in argo, we need to index synchronously.
