### ISSUE TITLE
Run, remediate, and retire empty_mediatypes report

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4918]
Per @andrewjbtw:
> This should be run again and could be decommissioned if we can remediate the remaining problem items (which I think are all H2 items I can't update myself because of sync issues):
empty_mediatypes

Please check with @andrewjbtw to determine whether remediation is possible / how to proceed.

**Comment by jcoyne** [comment]
Here is the report: [empty-type.csv](https://github.com/sul-dlss/dor-services-app/files/15135145/empty-type.csv)

**Comment by justinlittman** [comment]
@andrewjbtw Can we proceed with deleting this report?

**Comment by andrewjbtw** [comment]
Yes.
