### ISSUE TITLE
File exists @ dir_s_mkdir - ShelvingService

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4952]
## Backtrace

    line 30 of [PROJECT_ROOT]/app/services/shelving_service.rb: shelve
    line 9 of [PROJECT_ROOT]/app/services/shelving_service.rb: shelve
    line 15 of [PROJECT_ROOT]/app/jobs/shelve_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/94972560)

**Comment by jcoyne** [comment]
I believe this is a long standing race condition
