### ISSUE TITLE
Write DSA-to-Stacks audit

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#4960]
To determine which files does DSA expect to be on stacks but are not there.

Please have this audit optionally check the checksums of the files as well.

Please coordinate with #4961

**Comment by jcoyne** [comment]
I am creating a data file that contains the list of all files on stacks (`find /stacks/ -type f > stacks_files.csv`). I will put this on our google drive.

**Comment by lwrubel** [comment]
Closed since report has been delivered.
