### ISSUE TITLE
Test publishing with large file

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#4972]
Up to 1 TB

Validate the approach implemented in #4965.

**Comment by lwrubel** [comment]
@andrewjbtw is testing with a large object currently.

**Comment by andrewjbtw** [comment]
I've created a [test object in stage](https://argo-stage.stanford.edu/view/druid:fb146xw8568) with a 1TB file plus a few smaller files, using data from a real deposit.

To test shelving, it should be sufficient to 

1. Take the files off stacks
(assumes the starting point is "publish=yes,shelve=yes" and files are already on stacks)
- Open a new version
- Change "publish" and "shelve" to "no" to unshelve the files
- Close the version
- Make sure the files are unshelved during accessionWF

2. Put the files on stacks
(assumes the starting point is "publish=no,shelve=no" and files are not on stacks)
- Open a new version
- Change "publish" and "shelve" to "yes" to shelve the files
- Close the version
- Make sure the files are shelved during accessionWF

**Comment by jcoyne** [comment]
It looks like https://argo-stage.stanford.edu/view/druid:fb146xw8568 was published, so I think we can say this worked, right?

**Comment by andrewjbtw** [comment]
I don't think this went through the new API yet. I was just making sure it got into the stage systems for future use.

**Comment by jcoyne** [comment]
Blocked by https://github.com/sul-dlss/purl-fetcher/pull/751

**Comment by jcoyne** [comment]
Looks good:
```
 #<ActiveStorage::Blob:0x00007f2a2e4e0de0
  id: 246,
  key: "ay4ojwqoehp9n9smt5fof1qwoaxy",
  filename: "DTU_DMS.tar.gz",
  content_type: "application/octet-stream",
  metadata: {},
  service_name: "local",
  byte_size: 1196585612576,
  checksum: "6o51iYPNe6/dloBheVB75A==",
  created_at: Fri, 17 May 2024 13:42:04.495049000 UTC +00:00>
```
