### ISSUE TITLE
Create a report for shelve: yes, publish: no

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#5045]
record the APO to identify an ETDs, which are expected to have this state
and the content-type to identify webarchive-binary which also have this state.

**Comment by aaron-collier** [comment]
@andrewjbtw here is a report of objects that have at least one file with shelve: true and publish: false

Let me know if there are any issues

[shelve_report_prod.csv](https://github.com/sul-dlss/dor-services-app/files/15491574/shelve_report_prod.csv)

**Comment by jcoyne** [comment]
I see 845 items that are not webarchive-binary or ETDs in that report. 

A lot of them are in the APOs:
druid:sr199zw3981 https://argo.stanford.edu/view/druid:sr199zw3981
druid:fv454nq4574 https://argo.stanford.edu/view/druid:fv454nq4574
druid:yf767bj4831 https://argo.stanford.edu/view/druid:yf767bj4831
druid:nc748zf7708 https://argo.stanford.edu/view/druid:nc748zf7708
druid:wr005wn5739 https://argo.stanford.edu/view/druid:wr005wn5739

There are a handful of druids that seem to be outliers:
druid:yq024wn9035
druid:km968br2393
druid:jr074fv4770
druid:bm870xs2710
druid:wh006xp6502
druid:bg026kj3984
druid:kp533js8274
druid:mt103cj8868
druid:tp004wn4309
druid:sw929qw1534
druid:ym138xd1285
druid:fh546wt8551

**Comment by jcoyne** [comment]
@aaron-collier how did you run this query. It would be nice to record it so we can re-run after remediating.

**Comment by aaron-collier** [comment]
@jcoyne I was going to ask if we wanted to keep the report, I'll put up a PR.
