### ISSUE TITLE
Add a basic check that the "shelve" step ran correctly

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#5117]
**Background**

When we shelve files during accessionWF, the result should be that the /stacks filesystem ends up with exactly the files listed as "publish=yes, shelve=yes" in the public Cocina. If there are no shelved files, the filesystem for that druid (or that druid version) should be empty.

We do not currently have a check that shelving has succeeded. Over the years, we've found numerous cases where the filesystem does not match the Cocina. In testing new features, we've also missed cases where shelving did not do what it was supposed to do. The shelve step rarely reports anything other than success - even if files did not get shelved (or unshelved) as expected.

**The request**

We should add a basic check in accessioning to verify that the Stacks filesystem is in sync with the Cocina. As a sanity check, this could be as basic as checking that the filenames and paths line up properly between Stacks and Cocina. To be thorough, we could check checksums, but this could cause significant slowdowns for large deposits.

In the coming versioned world, the check should verify that the correct files are present for each version of the druid. The "withdraw" use case means that there can be changes to the files of a previous version. Withdrawal means that a version will be taken down, so files unique to that version should be removed.  

**How this will help**
Having this basic check will likely save us a lot of time in the long run. For testing and feature development, it would lessen the burden on testers to watch the Stacks filesystem closely. Currently, a person has to be in the Stacks directory for a specific druid and eyeball the before and after states in order to verify shelving success.

This check should also prevent situations like the one we had where we found over 1 million files on Stacks that should not have been there.

**Comment by justinlittman** [comment]
Here's what I propose: As an additional step in publish-shelve, DSA will call purl-fetcher's "files by md5" endpoint to get the current list of shelved files. It will then check that list against the current cocina to make sure every shelvable file has been shelved.

Currently, the files by md5 endpoint gets the shelved files from the cocina it has stored. This would require that it also check that those files exist on disk. (Once we move to the new file storage layout we can just read the md5s directly from the file system directory listing.)

**Comment by justinlittman** [comment]
Punting until we've switched to the new file storage layout.

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/purl-fetcher/issues/876 will change how purl-fetcher determines which files are actually shelved. However, this does not preclude working on the DSA side.
