### ISSUE TITLE
Bring 16 items back to cocina validity (descriptive metadata issues)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#5179]
16 items are caught in accessioning because of problems with descriptive metadata. The metadata issue prevents reindexing, so the items look "Opened" but they are repeatedly retrying the "publish" and "reindex" jobs, visible on the DSA sidekiq dashboard.

Since there's no clear way to fix the metadata in place, the best course of action is to stop the accession and set the items back to "Opened" so they can be updated again via metadata spreadsheet. There's a "cleanup" rake task in DSA that should be able to accomplish this. It should:

- stop the workflows (actually delete the rows for the in-accessioning version)
- set the item back to Opened (in the cocina DB)
- discard the in-accessioning version of Cocina (in this case, the invalid one) and restore the Cocina for the previously accessioned version

I'm not 100% certain it will revert the Cocina version properly, but if it does, that should be sufficient to allow updates to the item again.

The 16 druids that are stuck are:

```
druid:bt138zb1591
druid:bv559ft4642
druid:hx222dm6304
druid:mk292tp3606
druid:mn014gd6082
druid:nv119cw6090
druid:px761kq4896
druid:rm943nd3817
druid:sc698sv3558
druid:st839wj7268
druid:tc646sf6384
druid:vm955zv7342
druid:ww437bz6619
druid:wy269sz7448
druid:xm084qn2992
druid:xv845zv9436
```

**Comment by mjgiarlo** [comment]
Ran the DSA cleanup task twice for each druid and we think they're in a better state now.

**Comment by andrewjbtw** [comment]
All signs are that this was successful, and it looks like the items have since been updated via Argo, so I'm closing the issue.
