### ISSUE TITLE
Deactivate the lock icon and open/close during the speechToTextWF

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/dor-services-app#5228]
In testing on QA, I noticed that the object-level "lock" icon remains active during the speechToTextWF, which would potentially allow someone to make an unrelated update and close the item while Whisper is still running.

> <img width="727" alt="Screenshot 2024-11-12 at 1 36 26 PM" src="https://github.com/user-attachments/assets/522e98ce-6885-4301-bef5-7162c1e7a2b0">

I'm pretty sure we prevent this from happening during the ocrWF but I don't remember how we addressed that.

**Comment by peetucket** [comment]
Argo determines how to draw the lock icon by using the `StateService`: https://github.com/sul-dlss/argo/blob/main/app/services/state_service.rb

In particular, we want the process of speechToTextWF running to be the same as ocrWF running, which is under `assembling?` in this class.

If you follow the logic down, you will find it goes to dor-services-client, which makes a call to DSA, which ultimately ends up here:  https://github.com/sul-dlss/dor-services-app/blob/main/app/services/workflow_state_service.rb#L25

We just need a new line to this method accounting for `speechToTextWF'
