### ISSUE TITLE
default return type is no longer text? maybe only for registration?

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor-services-app#53]
In the old framework, we had a default response format of text:

  https://github.com/sul-dlss/dor-services-app/blob/v1.20.0/lib/dor_services_app.rb#L6

But on `master` now, the default response to registration is now a JSON response not a text response.

In the old framework that was here:

  https://github.com/sul-dlss/dor-services-app/blob/v1.20.0/lib/dor_services_app.rb#L125-L143

Not sure how to fix it offhand, but here's the code which support both JSON and text for the registration:

  https://github.com/sul-dlss/dor-services-app/blob/master/app/controllers/objects_controller.rb#L23-L26

**Comment by ndushay** [comment]
It does seem as if the new service should have the same defaults as the old one.  If we are not going that way, there should be a code search to ensure downstream consuming apps are prepared for a non-backwards compatible change.

**Comment by LynnMcRae** [comment]
The primary goal is the relocation of these services off of lyberservices-prod, transparently I assume. Otherwise we'd  have a lot more testing/validation to do along with code changes.

**Comment by blalbrit** [comment]
Agreed - if there's a change in response payload, etc. then we would be looking at significant testing across the environments before rolling to prod.
