### ISSUE TITLE
Cocina::Mapper should set image type

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#536]
https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/mapper.rb#L34

If the object type is an image (`object.identityMetadata.objectType.first == :image`)

https://github.com/sul-dlss/common-accessioning/blob/b09b0e8f204d8202490239f9ad2d8c3a18bbaade/lib/dor/assembly/item.rb#L22

Then the mapper should use the value `http://cocina.sul.stanford.edu/models/image.jsonld`

This will allow https://github.com/sul-dlss/common-accessioning/blob/9d9076a96b24cedd0295bd92598c2fbc0a37f827/lib/robots/dor_repo/assembly/exif_collect.rb#L31 to not need to use fedora.

**Comment by mjgiarlo** [comment]
Chatted with @jcoyne and he suggested closing this issue with the following rationale:

> [the image] type was meant to be on the file node (https://github.com/sul-dlss/common-accessioning/blob/9d9076a96b24cedd0295bd92598c2fbc0a37f827/lib/robots/dor_repo/assembly/exif_collect.rb#L29) not the object.
> It isn't actually hitting fedora there.
> it's hitting a `Assembly::ObjectFile` or something
> I made that a little clearer in https://github.com/sul-dlss/common-accessioning/commit/396d2f57fb368f246c1059b08821ef8eb3fa1c2c
