### ISSUE TITLE
Cocina::Mapper should set content_type_tag

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#537]
So that pre-assembly does not need to hit Fedora.

https://github.com/sul-dlss/pre-assembly/blob/e5091a1fbb4e385f69c49d25a531a63c118c401f/app/lib/pre_assembly/digital_object.rb#L93

content_type_tag is here: https://github.com/sul-dlss/dor-services/blob/b9b4768eac560ef99b4a8d03475ea31fe4ae2367/lib/dor/datastreams/identity_metadata_ds.rb#L77-L80

**Comment by mjgiarlo** [comment]
Needs research (@jcoyne ?)
