### ISSUE TITLE
trap for preservation-client gem errors in dor-services-app and handle accordingly

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#545]
dor-services-app uses preservation-client in the following ways:
- shelving API service:
   - uses preservation-client to get content diff for shelved files
- versioning service:
   - uses preservation-client to get current_version
- other?

dor-services-app code should trap for any errors from preservation-client (e.g. can't connect, not found, generic error, response status other than expected (i.e. not a 200) ) and:
- pass along appropriate error code to dor-services-client (which needs to handle it properly)
- notify honeybadger as appropriate

See https://github.com/sul-dlss/preservation-client/blob/master/lib/preservation/client.rb#L30-L39

**Comment by justinlittman** [comment]
- [ ] Verify that Pres Cat client checks response code.
- [ ] When an error occurs, return 500 with useful info

**Comment by justinlittman** [comment]
Here is where Pres Cat client checks response code:
* https://github.com/sul-dlss/preservation-client/blob/master/lib/preservation/client/versioned_api_service.rb#L60
* https://github.com/sul-dlss/preservation-client/blob/master/lib/preservation/client/versioned_api_service.rb#L24
