### ISSUE TITLE
Use dor-workflow-client errors_for method

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#553]
To replace: https://github.com/sul-dlss/dor-services-app/blob/7fb98f10efb7b14c34077da0160489f87acd3a72/app/services/workflow_error_checking_service.rb#L23-L25

See https://github.com/sul-dlss/dor-workflow-client/pull/140

**Comment by ndushay** [comment]
@jcoyne I don't even see the class in dor-services-app -- perhaps this has already been done?

**Comment by jcoyne** [comment]
Yes, fixed in https://github.com/sul-dlss/dor-services-app/pull/570
