### ISSUE TITLE
PreserveJob reports workflow errors after workflow step has been completed

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#563]
The SDR Ingest Transfer robot invokes dor-services-app to preserve an object and then marks the `sdr-ingest-transfer` step as complete. The workflow proceeds.

When dor-services-app is invoked to preserve an object, it queues a preserve job. If there is an error in the preserve job, the `sdr-ingest-transfer` step is updated with the error: https://github.com/sul-dlss/dor-services-app/blob/master/app/jobs/preserve_job.rb#L18

This creates a situation in which a workflow proceeds, even though a step has failed, which creates the problem of (1) the improper processing of an object and (2) user confusion.

This is reflected in the workflow below:
![image](https://user-images.githubusercontent.com/588335/72291410-4c489c80-361d-11ea-8dd2-855daca7187f.png)

**Comment by justinlittman** [comment]
Three possible approaches:
1. Allow a robot perform to complete without updating the workflow (from the current default of marking a workflow step as complete after a robot perform). Dor Services App would be responsible for updating the workflow step when complete or there is an error.

The problem with the current implementation and approach 1 is that the Dor Services App preserve method is tightly bound to the workflow system; that is, it can only be called in the context of a workflow.

2. Since only the robot invokes / can invoke preserve, return the preserve code from Dor Services App to the robot. This definitely puts the code where it is called and removes the complexity of an async job invoking a remote async job.

3. Decouple Dor Services App preserve from the workflow so that it follows the remote method invocation pattern (i.e., there is a standard way of invoking preserve and receiving the response such as a HTTP callback or an async message). This would allow other services to potentially call preserve.

I personally would suggest 2 as the simplest solution.

**Comment by justinlittman** [comment]
Also, for 3 the listener does not need to be the robot (as an async job blocking for an async job has proven problematic for virtual merge). The robot could complete without updating the workflow step and then Dor Services App could invoke a callback on, say, the Workflow System that would update the workflow step.

**Comment by jcoyne** [comment]
I'm strongly against #2 as it devolves how we are trying to decouple robots from `/dor/workspace`.   We've been trying to move away from using NFS mounts as a shared state and move to using APIs. 

#3 is not possible with our current architecture as there is no HTTP server to call back to nor do w have infrastructure to pass asynchronous messages.  In fact, we have been using the workflow service as this "passer of asynchronous messages"

**Comment by jcoyne** [comment]
I propose that an event based architecture might offer a solution here.   We can have a process that reads the event stream and can update workflow steps as appropriate.

**Comment by justinlittman** [comment]
Per discussion with @jcoyne, will resolve this ticket by having error be reported to the correct workflow step. This should be the same step to which completion is reported. Currently, it is usually the previous step.

This fix should be applied to all of the async jobs in dor-services-app that report errors to workflow.
