### ISSUE TITLE
Stop logging to the event datastream on version open/close

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#585]
Now that we have an event service that does this. See https://github.com/sul-dlss/dor-services-app/pull/584

Looking for approval from @andrewjbtw before we can start on this.  This will help us migrate away from Fedora 3.

Then update `DatastreamExtractor#datastream_content` to pull version_open and version_close events from the events service.

**Comment by andrewjbtw** [comment]
@jcoyne How do I access the events service to get this information?

**Comment by jcoyne** [comment]
@andrewjbtw presently, it's in the database.  There is this argo ticket to expose it: https://github.com/sul-dlss/argo/issues/1773

**Comment by mjgiarlo** [comment]
@andrewjbtw will review the events we're currently collecting in the events database. Changes: 

- [ ] when we push to preservation, export events data to events.xml in lieu of a datastream.
- [ ] remove events datastream and the code that writes to it

**Comment by jcoyne** [comment]
This is complete.
