### ISSUE TITLE
Expose an API to get the catalog record

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#594]
So that we can use the catalog record to get the place and date of publication

I believe this used to exist in dor-services-app, but it was removed because we didn't use it.

**Comment by mjgiarlo** [comment]
May be irrelevant. Depends on sul-dlss/google-books#1.

**Comment by justinlittman** [comment]
Unless I'm misunderstanding, all of the proposals under consideration require metadata from the MARC record. See the _Information used_ section of https://www.hathitrust.org/bib_rights_determination
