### ISSUE TITLE
CocinaMapper should map special_dissemination_wf for APOs

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#598]
This can be used by https://github.com/sul-dlss/common-accessioning/blob/master/lib/robots/dor_repo/accession/end_accession.rb#L31-L34

This will allow us to remove that call to Fedora.

wasDisseminationWF is a common value for that field to have

**Comment by mjgiarlo** [comment]
Closed by https://github.com/sul-dlss/dor-services-app/pull/605 ?
