### ISSUE TITLE
Remove workflows datastream from Fedora

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor-services-app#601]
We do not believe it is being used. Instead, services and apps are hitting workflow-server-rails and getting workflow XML exported from the database.

- [x] Remove from `dor-services` gem.  https://github.com/sul-dlss/dor-services/pull/683
- [x] Cut a version 9 of `dor-services`
- [x] Use new version of `dor-services` in Argo
- [x] Remove workflow datastream from item show page in Argo https://github.com/sul-dlss/argo/pull/1785
- [x] Test in staging environment

Spun off from #554.

**Comment by jcoyne** [comment]
Done.
