### ISSUE TITLE
stop checking purl for release tags

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#630]
Currently the release process is checking for release tags in identityMetadata and also in the PURL service.

https://github.com/sul-dlss/dor-services-app/blob/eb58b2e9016783b786dbb08b2b0dabd3a6eca3bf/app/models/dor/update_marc_record_service.rb#L179

This behavior was added 5 years ago: https://github.com/sul-dlss/dor-services/commit/439b8084f5f36567bbefeb954f40ebee82268ff1

There's no reason that I'm aware of that we need to look to PURL for release tags that would not be in the identityMetadata.  In fact, 4 years ago we changed the indexer so it wouldn't look in PURL for the release tags.:
https://github.com/sul-dlss/dor-services/commit/ecda58f75d17611daa6ca41f81bbae8be8d8f9f1

@andrewjbtw can we remove this check to PURL in the update marc process?

**Comment by andrewjbtw** [comment]
Looking up previous discussions of how releases works, it's possible that items that are released as part of a collection release do not get release tags in the identityMetadata. If that's the case, then the PURL might be the only place where the release tag exists. We'll need to find examples. 

Ben suggested that @peetucket might know some of the background here.

**Comment by peetucket** [comment]
I think that may be correct.  If we could find an example of a collection that is released, we could look at some of the item's identityMetadata.  Its possible only exceptions have a tag (e.g. the collection is released as a whole, but one item was specifically excluded, so that particular item would have a "false" release tag, and the rest would have none).

**Comment by jcoyne** [comment]
I want to add that the release robot itself, does  not look  into PURL. It looks at all the members of  the collection that is being released.  It is only looking to PURL when it updats the MARC record to determine if an item has been released to Searchworks.  

It is already searching the tags for the collections it is a member of without going to PURL:
https://github.com/sul-dlss/dor-services/blob/master/lib/dor/release_tags/identity_metadata.rb#L48

so  the check to purl seems unnecessary.

**Comment by peetucket** [comment]
I cannot think of a specific reason and it seems you've done the code archaeology well.
