### ISSUE TITLE
Draw conclusions about rightsMetadata experiment: setting rights in reg. service

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor-services-app#652]
[This experiment](https://github.com/sul-dlss/dor-services-app/pull/600/files) has been running a while. We should see what have learned for SDR evolution. Is this a valid code path or not? Can we draw any conclusions?

**Comment by jcoyne** [comment]
The experiment was added 12 days ago and we haven't seen one instance of it yet.

**Comment by ndushay** [comment]
This should have been closed by PR sul-dlss/common-accessioning#571
