### ISSUE TITLE
[ÜBER] Create a data store for user tags

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#679]
Because user tags should not end up in MOABs or be on PURL.

- [x] [Write tags into this data store (vs. identityMetadata)](https://github.com/sul-dlss/dor-services-app/pull/709)
- [x] [Support endpoint in dor-services-client](https://github.com/sul-dlss/dor-services-client/pull/154)
- [x] [Index the tags from the new data store](https://github.com/sul-dlss/dor_indexing_app/pull/358)
- [x] [Create/update/destroy/list tags via dor-services API in Argo](https://github.com/sul-dlss/argo/pull/1857)
- [x] [Write integration test testing interaction between Argo, DSA, and DIA](https://github.com/sul-dlss/infrastructure-integration-test/pull/34)
- [x] [Point Hydrus at the new API](https://github.com/sul-dlss/hydrus/pull/410)
- [x] [Point gis-robot-suite at the new API](https://github.com/sul-dlss/gis-robot-suite/pull/261)
- [x] [Remove dead related code from dor-services gem](https://github.com/sul-dlss/dor-services/pull/696)
- [x] Migrate tags from Fedora 3 to the new store (see [question below in the comments](https://github.com/sul-dlss/dor-services-app/issues/679#issuecomment-594098784))

**Comment by mjgiarlo** [comment]
@jcoyne Given the gradual/backwards-compatible reading and writing strategies in https://github.com/sul-dlss/dor-services-app/pull/709/files#diff-89dd5a4d668b498bad0357a62bf4e862R27-R52, what else needs to be done re: migration? Do you think we need to schedule a mass migration job, or will the strategy above suffice?

**Comment by jcoyne** [comment]
@mjgiarlo gradual migration would be fine, but how will we know when the migration is complete?
Perhaps if we migrate on read, we know the dor-indexing-app will iterate over everything every week or so.

**Comment by mjgiarlo** [comment]
@jcoyne I pondered also migrating on read but was reluctant to commingle read and write operations. I'm open to it, though, if that'd check a box and get this moving more quickly.

**Comment by jcoyne** [comment]
@mjgiarlo I think it's up to you to pick how you want to do it, either the rolling migration on read or a more deliberate migration process.  In either case, I would like to know when it's done, so some work needs to be done so we can achieve that goal.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> @mjgiarlo I think it's up to you to pick how you want to do it, either the rolling migration on read or a more deliberate migration process. In either case, I would like to know when it's done, so some work needs to be done so we can achieve that goal.

The four API endpoints (create, update, destroy, list) now all read in legacy tags: https://github.com/sul-dlss/dor-services-app/pull/709/files

I'm not yet sure how to answer the question of "is this done yet?" Count of unique druids in the DSA admin tags table?

**Comment by jcoyne** [comment]
> I'm not yet sure how to answer the question of "is this done yet?" Count of unique druids in the DSA admin tags table?

Sounds good to me.

**Comment by jmartin-sul** [comment]
> > I'm not yet sure how to answer the question of "is this done yet?" Count of unique druids in the DSA admin tags table?
> 
> Sounds good to me.

if it's useful for comparing, there's a script for dumping the list of all druids in fedora on fedora's VM.  if you log into that box as `lyberadmin`, you should be able to run `ruby dump_fedora_pids.rb`, and it should print the location of a temp file with all the druids.  when i ran it recently, it resulted in about 35 MB of output.  this is the only way i found to get fedora to reliably list all its contents, but it's been a while and i've never been an expert on fedora, so maybe there's a better approach.

script is in version control here, because that was the most logical home at the time it was written (it was used to aid full-reindexing during the last huge argo UI overhaul):  https://github.com/sul-dlss/argo/blob/master/bin/dump_fedora_pids.rb.

**Comment by mjgiarlo** [comment]
I believe this is now finished.
