### ISSUE TITLE
Handle 500 from Symphony in Object#create

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#694]
This happens consistently and causes the error to ripple down to google-books.

At the very least, should not HB alert.

See:
* https://app.honeybadger.io/projects/50568/faults/59538379
* https://app.honeybadger.io/projects/67990/faults/60731529

**Comment by jcoyne** [comment]
@justinlittman I think this is doing the right thing already. If it can't connect to symphony, then it can't build the descMetadata, which is required per our data model validations.

**Comment by justinlittman** [comment]
That's fine, but we don't need a HB alert from dor-services-app and google-books every time it occurs, which is often.
