### ISSUE TITLE
Dry::Struct::Error in objects # show - missing sourceIDs

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#695]
Dry::Struct::Error: [Cocina::Models::DRO::Identification.new] nil (NilClass) has invalid type for :sourceId violates constraints (type?(String, nil) failed)

https://app.honeybadger.io/projects/50568/faults/61092422

The exception should better indicate the source of the error (that results from invalid data in an object that will need to be remediated later) so that we can make it clearer.

Explore if dry::validation or dry::schema allows us to improve error messaging for these scenarios

**Comment by jcoyne** [comment]
@justinlittman this is triggered by objects that have invalid data (non-etd objects missing sourceId in identityMetadata datastream)

**Comment by mjgiarlo** [comment]
@jcoyne Do you think this is a `#wontfix` or should we put some code in place to deal with bad data like this more gracefullly?

**Comment by jcoyne** [comment]
This is the only mechanism we have of identifying bad data right now. Andrew has indicated he will fix these as they show up.
