### ISSUE TITLE
Restore MODS parm on new /catalog/mods service call 

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/dor-services-app#70]
The lyberservices-based catalog service was set up to have old, current and new XSLT versions installed and addressable via a query parm:

http://lyberservices-prod.stanford.edu/catalog/mods?catkey=3195754&mods=3.3
http://lyberservices-prod.stanford.edu/catalog/mods?catkey=3195754&mods=3.4

That way we could test a new stylesheet before cutting over the default. Just as important, we could continue to compare current with old behaviors when questions arose any time after the cutover. The new dor-services-app version does not implement this option.

https://dor-services-prod.stanford.edu/v1/catalog/mods?catkey=319575
https://dor-services-prod.stanford.edu/v1/catalog/mods?catkey=319575&mods=3.3
https://dor-services-prod.stanford.edu/v1/catalog/mods?catkey=319575&mods=3.6

all deliver 3.4. The ability to invoke specific versions needs to be retained, both for testing now and for later use if questions arise about particular forms of data.

**Comment by cmh2166** [comment]
@cbeer have you scoped this work already?

**Comment by cbeer** [comment]
No; it seems straightforward enough, but we should make sure it's something we actually need and will use. In my log analysis way back when, it was clear it had never been used (at least as far back as we had logs).

**Comment by cmh2166** [comment]
kk, thanks.
