### ISSUE TITLE
Stop sending technicalMetadata into preservation

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#720]
This can happen once we get the new techMd server/robot into production.

Just need to remove this line:
https://github.com/sul-dlss/dor-services-app/blob/7e94da22e7fa9e09af6fe88bd76085d7471f3548/app/services/datastream_extractor.rb#L52

**Comment by ndushay** [comment]
Note:  new tech-md-service must be running in production first.  unless we don't care.

**Comment by jcoyne** [comment]
@ndushay Yes, it must be or the existing techMd will fail on reaccession.
