### ISSUE TITLE
Add ok computer check  for workers

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#741]
- [x] dor-services-app
- [x] google books
- [x] techMetadata service
- [x] sdr-api
- [x] was-registrar-app

Double check infra team playbook to see if there are others.

Akin to the check in pre-assembly or preservation_catalog.

**Comment by jermnelson** [comment]
@ndushay, I'm not sure what `okcomputer` is supposed to check for in these projects that are using Sidekiq beyond the already existing `OkComputer::SidekiqLatencyCheck`. Looking over the documentation for the [Sidekiq API](https://github.com/mperham/sidekiq/wiki/API), the Sidekiq notion of workers is different from a Resque worker that is being monitored in `pre-assembly` or `preservation_catalog`. In Sidekiq a worker is the thread currently processing a job. If no jobs are running, all we get from the `Sidekiq::Workers` are the available `Sidekiq::Process` and not much else. 

If the intention is to monitor Sidekiq's connections to Redis, we could iterate through the `Sidekiq::ProcessSet` to check  each `Sidekiq::Process`. Further clarification would be great. Thanks!

**Comment by ndushay** [comment]
i think the spirit of this is essentially:  
- we expect to be able to handle new requests - are we green light on that?
- we expect to be able to handle up to N simultaneously ... is that true?
- are there any clogged processes?

I don't know enough about Sidekiq::ProcessSet and Sidekiq::Process to be able to translate -- but I suspect you do.  :-)

If there's no progress to be made towards those objectives, let's close this.

**Comment by jermnelson** [comment]
Created the following PRs to add the Sidekiq latency checks:
- https://github.com/sul-dlss/sdr-api/pull/177
- https://github.com/sul-dlss/google-books/pull/494
- https://github.com/sul-dlss/was-registrar-app/pull/215

`dor-services-app` and techMetadata service already had the check.

**Comment by jermnelson** [comment]
All PRs merged; closing this ticket.
