### ISSUE TITLE
Map file access and administrative to File cocina model

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#749]
in `DROStructuralBuilder.build_files`.

**Comment by jcoyne** [comment]
@justinlittman can you add more detail to this ticket please?

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/dro_structural_builder.rb#L56

The access and administrative models should be populated from the DOR Item. (I don't know where that data comes from in the Item.)
