### ISSUE TITLE
Allow single quotes in Collection titles and elsewhere in update_marc_service

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/dor-services-app#76]
Per https://app.honeybadger.io/projects/50568/faults/33388400#notice-summary , the update_marc step of the releaseWF returns a 500 when collection titles contain a single quote or apostrophe.

Per @jkeck "Looks like the the command sent to `bin/write_marc_record` is an unescaped string wrapped in single quotes (which will break if single-quotes are in the data anywhere)."

I'm not sure if this belongs in the dor-services-app where the update-marc-service sits, or somewhere else in either dor-services or the release robots. Please feel free to let me know and I'll move it.

**Comment by blalbrit** [comment]
@LynnMcRae - tagging you for tracking.

**Comment by peetucket** [comment]
agree with @jkeck  -- i'll look into this, seems straightforward
