### ISSUE TITLE
SDR-managed MARC 856 PURL - Collection title built from incorrect field

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/dor-services-app#78]
https://github.com/sul-dlss/dor-services-app/blob/56ebef441ba4b96e04008933c6490dff7db00eba/app/models/dor/update_marc_record_service.rb#L124

is using .label to build the collection title. However, this is the Fedora label produced at registration and not the final title. It appears that this .label call might be hitting the Fedora DC metadata stream. We should opt for information derived from the MODS title from the descMetadata datastream.

@LynnMcRae - do you have other suggestions for fixing this problem?

**Comment by ndushay** [comment]
Is this related to the info in sul-dlss/argo#910?

**Comment by ndushay** [comment]
@blalbrit can you provide an end-user view of this, with one or more druids and a screen shot of where you see this?   I want to be certain we fix the right thing(s) in the right codebase(s) ...

**Comment by blalbrit** [comment]
@ndushay - yes, this is identical to sul-dlss/argo#910 . The work done on that ticket was comprehensive. This ticket can be closed.
