### ISSUE TITLE
Cocina registration should accept an abstract in the descriptive metadata

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#782]
Argo passes an abstract when registering a collection.
https://github.com/sul-dlss/dor-services-app/pull/761 might offer a clue for how to do this.

**Comment by justinlittman** [comment]
See https://github.com/sul-dlss/cocina-models/blob/master/spec/fixtures/description/etd.json#L420

**Comment by ndushay** [comment]
Is this how this work is envisioned?

- change to cocina-models to allow abstract as an attribute of description
- dor-services-app will set the abstract attribute of description in the cocina-model when creating a new object
- argo will pass in the abstract attribute to dor-services-app when a collection is registered (already being done)

**Comment by jcoyne** [comment]
@ndushay I don't believe any change will be required to cocina-models.  @justinlittman has pointed out we can add it as a `note` (see https://github.com/sul-dlss/cocina-models/blob/master/lib/cocina/models/description.rb#L11)  I believe the other parts are correct.

**Comment by ndushay** [comment]
I would think we would want to separate it from note - I'll check w arcadia.

**Comment by ndushay** [comment]
slack'ed with Arcadia;  she says go with note of type 'summary', as in https://github.com/sul-dlss/cocina-models/blob/master/spec/fixtures/description/etd.json#L420 as was indicated above.

>this is how it currently stands in the modeling work i've been doing:
```
{
  "note": [
    {
      "value": "This is an abstract.",
      "type": "summary"
    }
  ]
}
```

**Comment by ndushay** [comment]
PRs merged;  dor-services-app fix deployed;  argo fix will be deploy with next week dep updates.
