### ISSUE TITLE
Fix Hydrus testing suite 

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#796]
See https://github.com/sul-dlss/hydrus/pull/413

The issue? Spec tests non-deterministically fail (between 2 and 9 different failures each run) due to the DSC registration call timing out. Note that this is using the "legacy" registration method in DSA, so recentish changes to Cocina registrations should not be at fault.

Funnily enough, if I run the whole suite a couple times locally, the second run succeeds. smth smth caching smth? I think we could use another set of :eyes: on this one.

@jcoyne asks if it could be related to not having messaging in the docker-compose service cluster

**Comment by justinlittman** [comment]
Here's what I've found. The following locks up dor-services-app:
1. Hydrus makes call to dor-services-app to create an object.
2. Dor-services-app calls dor-indexing-app to index the object.
3. Dor-indexing-app calls dor-services-app to get the administrative tags.
Dor-indexing-app locks up and dor-indexing-app's call times out.

What do I mean by lock up?
* Even a call to `/status` hangs.
* Calls to `/status` and to get administrative tags outside of the above scenario work fine.

I've tried increasing the number of threads in dor-services-app.

**Comment by jcoyne** [comment]
Could one of those servers be using sqlite?  I believe that is restricted to a single connection.

**Comment by justinlittman** [comment]
Most of the the problems are resolved by running dor-services-app in `RAILS_ENV=production`. There is one remaining test problem that occurs because it depends on an administrative tag being present; previously, this was set in Foxml fixture; it needs to be switched to being added to dor-services-app tag db.

**Comment by justinlittman** [comment]
So I tried adding the necessary tags on fixture load. However, the fixtures don't use valid druids, so dor-services-app openapi is unhappy.

**Comment by ndushay** [comment]
@justinlittman are you actively working on this ticket?  it is unassigned and in the ready column

**Comment by justinlittman** [comment]
I left it unassigned since my work is incomplete and I'm not sure how much time I will have this week to work on it.

**Comment by ndushay** [comment]
but now, you've done it!!!!  I am closing this.  Please reopen if I am wrong.
