### ISSUE TITLE
Update file location currently on /afs for CentOS migration for marc record writing

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#830]
Aas part of ops upgrading servers to the new CentOS, they are removing /afs mounts.  Infra team currently have a touchpoint with libsys via an /afs mount, where we write out updated marc records during the searchworks release.  This file is currently /afs/ir/dept/SUL/dsg/libsys/LoadToSymph/SDR-PURL and needs to be changed to some other writable location that can be picked up.   We are coordinating with Ops in a google doc and we need someone from libsys to be coordinate on this. 

Share config update needed to change file location: https://github.com/sul-dlss/shared_configs/blob/dor-services-app-prod/config/settings/production.yml#L36

Google doc for coordination with Ops: https://docs.google.com/document/d/14nXehbar-OsrXKtuF8xodZJ2rR4ricfiMqmlZk97zmw/edit?disco=AAAAJUxvJ1s

New location for -stage and -qa is `/sdrpurl`

**Comment by peetucket** [comment]
Shared configs PR for changing path in -stage (no shared configs for new -qa box, so noop for now): https://github.com/sul-dlss/shared_configs/pull/1329

**Comment by peetucket** [comment]
Updated dor-services-stage shared_configs and wrote one line of the new file to:

`/sdrpurl/sdr-purl-856s`

**Comment by peetucket** [comment]
To create a marc record from rails console:

```
2.5.0 :001 > @item = Dor.find('druid:bb181jh4180')
 => #<Dor::Item pid: "druid:bb181jh4180", admin_policy_object_id: "druid:xs835jp8197">
2.5.0 :002 > Dor::UpdateMarcRecordService.new(@item).update
```

And then check the `/sdrpurl/sdr-purl-856s` file.

**Comment by peetucket** [comment]
From shelley:

"The /sdrpurl mount writes files with user thine as the owner and group. i think it should be sirsi since thine is a sponsored sunetid of a SirsiDynix:"

```
consultant.sirsi@symphony-app-dev-1 /s/SUL> LL sdrpurl/total 12drwxrwxr-x 3 sirsi sirsi 4096 Apr 27 10:10 ./drwxr-xr-x 22 sirsi sirsi 4096 Feb 20 11:21 ../drwxrwxr-x 2 sirsi sirsi 4096 Feb 20 11:21 Archive/rw-rw-r- 1 thine thine 5 Apr 27 09:47 hello.txtrw-rw-r- 1 thine thine 18 Apr 27 10:10 sdr-purl-856s
```

**Comment by tallenaz** [comment]
We did a similar afs to nfs migration last year for etds. The steps were:

1. making sure we had a location to replace afs set up on the symphony nfs volume. In this case it was (sf6-webapp:/sirsi_prod/symphony-app-prod-1/SUL/etd).
2. make sure that location was mounted from common-accessioning with the correct uid:gid (214:214 had to be set from common-accessioning).

**Comment by peetucket** [comment]
So what's the next step, are they operations tasks?

**Comment by tallenaz** [comment]
I see the `/sdrpurl` mount on `dor-services-stage` has files written to it that are dor_services user/group from dor-services, and thine from symphony. That makes sense, since dor_services and thine are both id 503. @shelleydoljack notes the files need to be owned by sirsi, id 214. The next step should be to make sure the files have the right permissions. @peetucket how often does the write take place? The way this happened with ETD is that a cron transferred files to symphony every so often, and part of the cron job was `chown`ing the files to the sirsi user 214 upon transfer. If this case is similar, something like this might work: https://github.com/sul-dlss/puppet/blob/production/hieradata/node/common-accessioning-prod-b.stanford.edu.eyaml#L105-L109

**Comment by peetucket** [comment]
Do we need to do anything else with operations to move this forward and allow this migration to proceed?  @rsmith11 @tallenaz ?

**Comment by rsmith11** [comment]
Thanks @tallenaz .  So using the etd example, dor-services-app would right to a directory on the local filesystem that it has rights to, with proper uid and gid settings.  Then a daily cron job would run to reset uid/gid to 214 and then copy the contents to the /sdrpurl mount so that symphony-app-{env} can read them.  Does that sound right to you?

**Comment by tallenaz** [comment]
Yes, that's exactly it.

**Comment by peetucket** [comment]
NOTE: new folder to write too and confirm if working is `/sdrpurl_transfer`

**Comment by peetucket** [comment]
Stage is working ok writing to `/sdrpurl_transfer` but production is throwing an error:

```
RuntimeError (Error in writing marc_record file using the command bin/write_marc_record 9370404\	bb018zb8894\	.856.\ 41\|uhttp://purl.stanford.edu/bb018zb8894\|xSDR-PURL\|xitem\|xfile:bb018zb8894\%2Fbb018zb8894_00_0001.jp2\|xcollection:jt466yc7169::Jarndyce\ Single-Volume\ Nineteenth-Century\ Novel\ Collection,\ 1823-1914 /sdrpurl_transfer/sdr-purl-856s)

k5start: error reading /opt/app/dor_services/sulair-lyberservices: Key table file '/opt/app/dor_services/sulair-lyberservices' not found
```

**Comment by peetucket** [comment]
It looks like the `bin/write_marc_record` script on prod is looking for a file that is missing: 

```
export KRB5CCNAME=/tmp/kerb5.tkt
KINIT_PROG=/usr/bin/aklog \
/usr/bin/k5start  -t -k /tmp/kerb5.tkt -H 60 -U -f \
/opt/app/dor_services/sulair-lyberservices

echo "${1}" >> $2

unlog 2> /dev/null
kdestroy 2> /dev/null
```

**Comment by tallenaz** [comment]
I believe that's a keytab that was necessary to get afs access, and is no longer necessary now that we're on nfs.

**Comment by peetucket** [comment]
so all the k5 stuff, do we just need `echo "${1}" >> $2` now?

looks like we had specific shared config files for that bin script and there is a simple version checked into github, which perhaps could just be the actual one and we can ditch from shared_configs?

its weird that it seems to work on -stage even with that missing k5 file

**Comment by tallenaz** [comment]
That's my sense, you should just need the `echo`. You shouldn't need the `unlog`, or `kdestroy`, as they're afs related.

**Comment by peetucket** [comment]
yeah, ok --- quick test in -prod suggests you are correct...changes incoming

**Comment by peetucket** [comment]
done and deployed everywhere
