### ISSUE TITLE
Allow creating a tag that already exists

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#841]
ETDs does this and then fails when it tries to create the same tag the second time.

**Comment by peetucket** [comment]
For reference, the associated HB alert: https://app.honeybadger.io/projects/55164/faults/63353532#notice-summary
and ETD issue for object manually remediated: https://github.com/sul-dlss/hydra_etd/issues/426

**Comment by peetucket** [comment]
The uniqueness is enforced at the model level: https://github.com/sul-dlss/dor-services-app/blob/master/app/models/administrative_tag.rb

so I think the controller can perhaps just skip the create if the tag already exists?

https://github.com/sul-dlss/dor-services-app/blob/master/app/controllers/administrative_tags_controller.rb#L16-L24

**Comment by peetucket** [comment]
I also presume we aren't actually allowing duplicate tags, but rather not erroring out if one tries to create a dupe (basically a NOOP).

**Comment by peetucket** [comment]
Actual creation occurs here: https://github.com/sul-dlss/dor-services-app/blob/master/app/services/administrative_tags.rb#L98-L100

**Comment by mjgiarlo** [comment]
@peetucket correct. another option: to change https://github.com/sul-dlss/dor-services-app/blob/master/app/services/administrative_tags.rb#L99 to use `#find_or_create_by` instead of `#create!`.

**Comment by peetucket** [comment]
Oh, that's a good idea.
