### ISSUE TITLE
xpath query may fail to return results for constitutent object titles

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dor-services-app#87]
https://argo.stanford.edu/view/druid:bq150fx9908
https://app.honeybadger.io/projects/50568/faults/36675240

the above honeybadger link points to this exception:
```
NoMethodError: undefined method `content' for nil:NilClass
app/models/dor/update_marc_record_service.rb:136:in `block in get_x2_constituent_info' 
app/models/dor/update_marc_record_service.rb:134:in `map'
app/models/dor/update_marc_record_service.rb:134:in `get_x2_constituent_info'
app/models/dor/update_marc_record_service.rb:73:in `new_856_record'
app/models/dor/update_marc_record_service.rb:45:in `generate_symphony_records' 
app/models/dor/update_marc_record_service.rb:17:in `push_symphony_records'
app/models/dor/update_marc_record_service.rb:9:in `update'
app/controllers/objects_controller.rb:45:in `update_marc_record'
```

first triggered by a request to:  https://sul-lyberservices-prod.stanford.edu/v1/objects/druid:zn774gv3919/update_marc_record  (though this was most recently observed with the druid linked at the top of the issue, which was also the druid used for further investigation).

the code at issue:
https://github.com/sul-dlss/dor-services-app/blob/17c2503fe01b5e0de052dd03e45c0ac962914bd9/lib/update_marc_record_service.rb#L158-L166

in particular, this line is blowing up:
```ruby
cons_obj_title = cons_obj.datastreams['descMetadata'].ng_xml.xpath('//mods/titleInfo/title').first.content
```

...because the xpath expression returns no results.  thus `.first` is called on an empty array, and `.content` fails with `NoMethodError: undefined method 'content' for nil:NilClass`.

if the xpath call is changed to define and use the default mods namespace:
```ruby
cons_obj_title = cons_obj.datastreams['descMetadata'].ng_xml.xpath('//mods:mods/mods:titleInfo/mods:title', 'mods' => 'http://www.loc.gov/mods/v3').first.content
```

things work as expected, a one result array is returned, and `.first.content` returns a title from the xml.

i don't have much context here, as i'm not particularly familiar with mods xml (and what it should look like), nor am i particularly familiar with the dor-services-app codebase.  there seemed to be general surprise that this would have ever worked, based on the slack chatter this afternoon (e.g. from @cbeer, @ndushay, and @mjgiarlo).  other similar xpath queries (e.g. in dor-services) do similar namespacing to the working modified version of the xpath query that this bug is about (see e.g. https://github.com/sul-dlss/dor-services/blob/9b93538aa0a258ebf97c02874a703cb201988045/lib/dor/services/metadata_handlers/catalog_handler.rb#L12).

the most recently deployed dor-services-app commit (deployed 2016-10-19):
https://github.com/sul-dlss/dor-services-app/commit/17c2503

as per @vivnwong's instructions, i'm filing what we discovered this afternoon, and she'll confer w/ @blalbrit to determine severity of the issue and resource allocation.

paired w/ @tingulfsen on the investigation.

**Comment by blalbrit** [comment]
Turns out this was a data error. All 27 errors were virtual objects that also claimed to be constituent members of other virtual objects. Fixing the virtual circularity unblocked them - clearing the rest now.

**Comment by jmartin-sul** [comment]
@blalbrit: nice!

**Comment by cbeer** [comment]
Even though the immediate issue is addressed, isn't there still an issue with any object with a constituent relation?

**Comment by jcoyne** [comment]
There no longer is XML, so closing.
