### ISSUE TITLE
Remove /v1/objects/{id}/contents and /v1/objects/{id}/contents/{path}

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#877]
See https://github.com/sul-dlss/dor-services-client/issues/174

**Comment by jcoyne** [comment]
This is blocked until https://github.com/sul-dlss/argo/pull/2066 is reviewed, merged and deployed.

**Comment by ndushay** [comment]
is this ready to go now?

**Comment by peetucket** [comment]
Yes, ready to go.  We can then undraft and do https://github.com/sul-dlss/dor-services-client/pull/176

**Comment by peetucket** [comment]
PR for this work is here: https://github.com/sul-dlss/dor-services-app/pull/916
