### ISSUE TITLE
[PROXY] Add a way to distinguish ARC and WARC files in cocina

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#885]
See https://github.com/sul-dlss/was_robot_suite/blob/master/lib/was_crawl_dissemination/utilities.rb#L13

We need to add this attribute to cocina-models (Possibly a subtype of File) and then need to map to and from files that have the `dataType` attribute set.

It doesn't look like we are able to use mime-type for this because we are using `application/octet-stream` for ARC files (see https://argo.stanford.edu/view/druid:bb077hj4590).  It's possible that we could look at filename suffixes (e.g. `.arc.gz`) to determine this.

**Comment by jcoyne** [comment]
@andrewjbtw I'm curious to know your thoughts on this.

**Comment by jcoyne** [comment]
@aaron-collier I don't believe this is actionable until we get a direction from @andrewjbtw

**Comment by andrewjbtw** [comment]
It looks like going by suffix is the best option. I thought Siegfried might be able to distinguish them, but it must not look inside the gzip.

**Comment by justinlittman** [comment]
I would suggest that the mime type is the correct way to handle this in Cocina models, rather than enshrine ARC vs. WARC is some other way in the model.

The correct mime type should now be set for new WARC files. For existing WARC files, perhaps the mime type could be set correctly in the cocina mapper (using the file extension)?

**Comment by justinlittman** [comment]
Oh wait, is there a reason why this needs to be done with the cocina model, and can't just be done in the WAS code by looking at the filenames?

**Comment by jcoyne** [comment]
Since we decided on using suffixes, there is no model changes necessary.
