### ISSUE TITLE
[marc maint] validate SymphonyReader retrieved data from Symphony is same across web services versions

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/dor-services-app#90]
for symphony right now, there are 2 web services versions. libwebdev1 (symphony web service dev) uses the most recent version; libwebprod1 uses an older version.

for the catkeys of resources we care about for this app (from argo-prod https://sul-solr.stanford.edu/solr/argo3_prod), perform a diff / analysis of the two web services versions to ensure retrieved MARC data is the same. If there are diffs, involve @arcadiafalcone to check if harmful for moving from using Symphony Oracle. 

URL for sirsi here: https://github.com/sul-dlss/shared_configs/blob/dor-services-app-prod/config/settings/production.yml

write up steps for sharing with @jgreben

**Comment by jcoyne** [comment]
getting keys by doing: view-source:https://sul-solr.stanford.edu/solr/argo3_prod/select?facet.field=catkey_id_ssim&facet.limit=300000&facet=on&fl=catkey_id_ssim&rows=0&fq=catkey_id_ssim:*&indent=on&q=*:*&wt=json
which gave me 125798 unique keys.  Perhaps we have to filter out those derived from MARC.

**Comment by cmh2166** [comment]
@arcadiafalcone is reviewing the diff now. @aaron-collier also will put here the simple write up for sharing out with others.

**Comment by cmh2166** [comment]
@aaron-collier where is the write up + can you share the list of catkeys / druids you retrieved? thanks.

**Comment by aaron-collier** [comment]
Write up with link to the ruby script that can be used: https://consul.stanford.edu/display/DSG/Compare+Symphony+web+services+output+between+production+and+development
