### ISSUE TITLE
[marc maint] Process Arcadia's feedback re: correct ID in 001 when retrieving data from Symphony web services

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/dor-services-app#91]
See the feedback here: 

> The marc2xml stored process removes any existing 001 fields from the MARC record, and then adds a single 001 field containing the catkey with the “a” prefix. That process’s output also includes an 003 field with value “SIRSI”. The MARC2MODS XSLT expects a single instance of each of these fields, which it uses to generate the recordIdentifier value for the metadata source in the MODS output. The web services MARCXML output may include zero or multiple 001s containing non-catkey identifiers, and lacks the 003 when the catkey 001 is not already present in the MARC, so this needs to be normalized before the data goes to the XSLT for transformation.

what should be in the recordIdentifier in the generated MODs, does that require the XSLT to work from the 001 field, and if so, then what should be (but isn't) in the 001 field.

larger question: do we care about having recordIdentifier in the generated MODS, or can we use that identifier / catkey field from the Identification metadata? If needed, add data injection on the symphony reader (with @arcadiafalcone reviewing that output).

**Comment by cmh2166** [comment]
From @arcadiafalcone : 

> so long as it's [the correct, single catkey in the `001` field] there by the time the record gets to the xslt, that should be fine

> `recordIdentifier` should stay in the MODS for ease of reference

So, we need to: 
- inject (overwrite) the catkey into a singular 001 field in the MARC before it is sent to XSLT
- inject `SIRSI` into the 003 field in the MARC before it is sent to XSLT is that field value isn't already there

The XSLT covers everything else.

@arcadiafalcone please confirm.

**Comment by arcadiafalcone** [comment]
@cmh2166 That is correct.
