### ISSUE TITLE
[marc maint] analysis on who calls catalog-service, xml-service, or xslt-service

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/dor-services-app#93]
who calls catalog-service, xml-service, xslt-service. can we pin down to common-accessioning (and within that, dor-services describable concern) only? can we even tell this?

**Comment by aaron-collier** [comment]
I will verify this, but I'm not seeing any logging of the /catalog/mods route aside from nagios on lyberservices-prod

**Comment by blalbrit** [comment]
I would expect sul-robots3-prod and sul-robots5-prod as well.

**Comment by aaron-collier** [comment]
@blalbrit Since mid-february the logs here have been shipped to AFS on rotation, so this is only a review of today (so far). Looking into reviewing the older logs.

**Comment by aaron-collier** [comment]
@cmh2166 see my comment above about usage for 2018 so far. Let me know if you have any questions.
