### ISSUE TITLE
[marc maint] testing environment for switching dor-services (and anything else) to using dor-services-app /catalog/mods route

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss/dor-services-app#94]
How, when + who will test changes in which environments for switching to calling the dor-services-app /catalog (+ related) routes instead of the java apps (catalog-service, xml-service, xslt-service)?

Dependent on #93

**Comment by aaron-collier** [comment]
In progress:
- [ ] Update dor-services (gem) & release
- [ ] Update configuration options in Argo (and other services -stage)
- [ ] Close version of a "good" object in Argo to go through workflow (specifically descMetadata)
- [ ] Review metadata returned
