### ISSUE TITLE
[marc maint] Change calls in dor-services from using lyberservices /catalog (java app) to using /catalog handler in dor-services-app

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/dor-services-app#95]
Devs review code of replacement, code of existing, and where the calls need to change that call these

- https://github.com/sul-dlss/dor-services/blob/master/lib/dor/services/metadata_service.rb
- https://github.com/sul-dlss/dor-services/blob/master/lib/dor/services/metadata_handlers/catalog_handler.rb
- https://github.com/sul-dlss/catalog-service

Dependent on #93 #94 (who calls this catalog route so needs to change, then how to put into a test environment with adequate testing first)

**Comment by aaron-collier** [comment]
One piece of this: https://github.com/sul-dlss/dor-services/pull/361

**Comment by aaron-collier** [comment]
This has been deployed to production in argo and common-assessioning, so closing :-)
