### ISSUE TITLE
need mapping from Cocina Model of descMetadata to MODS for Fedora descMd datastream xml

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#953]
This is the reverse of #952.   In order to store a cocina-model with descriptive metadata fully populated, there needs to be a mapping of descriptiveMetadata to MODS, which will be stored as xml in Fedora as the descriptive metadata datastream.

Arcadia has created all the appropriate attributes in cocina models, and the mappings are here https://github.com/sul-dlss-labs/cocina-descriptive-metadata ( https://github.com/sul-dlss-labs/cocina-descriptive-metadata/pull/2 unless it's already merged - examples provided)

For mapping completeness/correctness, we may want @arcadiafalcone to sign off on the PR for this.

**Comment by ndushay** [comment]
this is in the in progress column with no one assigned;  moving back to ready.

**Comment by jcoyne** [comment]
Closing this as done in #1052 even though it is known to not be complete.  Follow on tickets will be added to make it complete.
