### ISSUE TITLE
[marc maint] Who uses the barcode to catkey service currently in catalog-service > xml-service

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss/dor-services-app#96]
Get metrics on barcode -> catkey useage on current service. Do we still use this? is there an easier way to do this?

**Comment by arcadiafalcone** [comment]
@blalbrit ?

**Comment by blalbrit** [comment]
Registration in Argo uses it.

**Comment by blalbrit** [comment]
Release to SW was meant to use it, but I think never implemented. Highly desired.

**Comment by jcoyne** [comment]
@blalbrit can you point out in the code or in the UI where this is?

**Comment by blalbrit** [comment]
@jcoyne - if I understand what you're asking for in this ticket, then the place in the UI where this is used is the left-hand Metadata ID column in the Argo registration form (https://argo.stanford.edu/items/register)

You can put either a barcode OR a catkey into this column, and retrieve the metadata for the catkey.

<img width="1589" alt="screenshot 2018-04-30 21 33 08" src="https://user-images.githubusercontent.com/796990/39461223-1ab86348-4cbe-11e8-9a22-ccdd4c06d125.png">

Release to SW was supposed to allow the same process in the opposite direction (release an object with a barcode and have it aggregate to the correct catkey in SearchWorks). I don't believe that code was ever written.

**Comment by cmh2166** [comment]
thanks for this. we are trying to figure out specifically which barcode to catkey service is used - there are 2 options in the existing code. We can start with this function in Argo and build backwards, then update our docs.
