### ISSUE TITLE
MARC2MODS XSLT - genre conversion terminal-punctuation

### ISSUE THREAD

**Issue by kevkishi** [sul-dlss/dor-services-app#962]
Please change the XSLT so that the terminal punctuation for genre is the same for both 655 and 650|v. The 655 retains terminal periods, but the 650|v removes them. This causes issues of splits in Spotlight faceting. I only noticed this happening with genres, but there may be other types of headings that have a similar issue.
I would prefer stripping the terminal periods from all headings, but as long as the behavior matches it should be fine.

I'm pasting the body text of my original email to argo-feedback below:
-----
Please take a look at:
https://argo.stanford.edu/view/druid:hb523vs3190
and
https://argo.stanford.edu/view/druid:tn412mq0486
 
Both of these appear in Spotlight with a Genre "Excerpts", but one is faceted there as "Excerpts" (no terminal period) and the other as "Excerpts." (with period). Therefore they are separated in the faceting. See https://exhibits.stanford.edu/garcia-sampedro_rolls
 
Looking at the source of metadata in Symphony, the first comes the 650 |v.
The second comes from the 655.
 
I haven't done a thorough investigation, but when converting Symphony MARC to Argo MODS, the terminal periods in the 650 fields are stripped, but they are not stripped from the 655 field.
 
Here's a fun one! See:
https://argo.stanford.edu/view/druid:wj624rv1393
https://searchworks.stanford.edu/view/13289327
There are multiple 'genres' found in this MARC record.
•         There are several 650s with "|v Music."
•         There is also a 655 "|a Music."
•         Notice that the MODS converted from the MARC has several occurrences of genre, but only one of them has a terminal period. This is the <genre> converted from the 655 field. The 650 |v has had the period stripped during conversion
 
If this object were in a Spotlight exhibit, two separate "Music" genre headings are shown in the facet, one with a period and one without, but both point to the same object.
Is there a way to change the indexing so that the periods are stripped off the 655s during conversion from MARC?

**Comment by arcadiafalcone** [comment]
Closed by #1008
